### ISSUE TITLE
ec2 example code not working

### ISSUE THREAD

**Issue by ruivapps** [spulec/moto#1022]
environment: 
    python 2.7.13 (fresh virtualenv)
pip install boto moto: 
    boto (2.48.0) 
    moto (1.0.1)

I am using example from README as:
#!/usr/bin/env python
import boto
from moto import mock_ec2

def add_servers(ami_id, count):
    conn = boto.connect_ec2('the_key', 'the_secret')
    for index in range(count):
        conn.run_instances(ami_id)

@mock_ec2
def test_add_servers():
    add_servers('ami-1234abcd', 2)
    conn = boto.connect_ec2('the_key', 'the_secret')
    reservations = conn.get_all_instances()

test_add_servers()

when running the script, I see error 
Traceback (most recent call last):
  File "moto_test.py", line 16, in <module>
    test_add_servers()
  File "/tmp/moto_test/lib/python2.7/site-packages/moto/core/models.py", line 70, in wrapper
    result = func(*args, **kwargs)
  File "moto_test.py", line 12, in test_add_servers
    add_servers('ami-1234abcd', 2)
  File "moto_test.py", line 8, in add_servers
    conn.run_instances(ami_id)
  File "/tmp/moto_test/lib/python2.7/site-packages/boto/ec2/connection.py", line 977, in run_instances
    verb='POST')
  File "/tmp/moto_test/lib/python2.7/site-packages/boto/connection.py", line 1208, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 401 Unauthorized

if using @mock_ec2_deprecated instead @mock_ec2, then everything works fine.

**Comment by JackDanger** [comment]
Thanks for this @ruivapps , I've updated the README to use the more recent versions of both Moto and Boto3. Thanks for pointing this out, it's a big help!
