### ISSUE TITLE
Connection Refused error when running in an AWS Codebuild environment

### ISSUE THREAD

**Issue by ndpete** [spulec/moto#1036]
I have python code as part of an AWS codepipeline with a codebuild phase responsible for running tests. When tests are run the following error is produced:

```requests.exceptions.ConnectionError: Connection refused: GET http://169.254.170.2/v2/credentials/5b20b383-ddb7-4e80-b5e7-358afc51e4c2```

Full Traceback:
```
Traceback (most recent call last):
File "moto-test.py", line 31, in <module>
moto_test_describe_parameters()
File "/usr/local/lib/python3.6/site-packages/moto/core/models.py", line 70, in wrapper
result = func(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/moto/core/models.py", line 70, in wrapper
result = func(*args, **kwargs)
File "moto-test.py", line 9, in moto_test_describe_parameters
client = boto3.client('ssm', region_name='us-east-1')
File "/usr/local/lib/python3.6/site-packages/boto3/__init__.py", line 83, in client
return _get_default_session().client(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/boto3/session.py", line 263, in client
aws_session_token=aws_session_token, config=config)
File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 825, in create_client
credentials = self.get_credentials()
File "/usr/local/lib/python3.6/site-packages/botocore/session.py", line 449, in get_credentials
'credential_provider').load_credentials()
File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1146, in load_credentials
creds = provider.load()
File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1009, in load
return self._retrieve_or_fail()
File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1018, in _retrieve_or_fail
creds = fetcher()
File "/usr/local/lib/python3.6/site-packages/botocore/credentials.py", line 1040, in fetch_creds
full_uri, headers=headers)
File "/usr/local/lib/python3.6/site-packages/botocore/utils.py", line 1025, in retrieve_full_uri
return self._retrieve_credentials(full_url, headers)
File "/usr/local/lib/python3.6/site-packages/botocore/utils.py", line 1061, in _retrieve_credentials
return self._get_response(full_url, headers, self.TIMEOUT_SECONDS)
File "/usr/local/lib/python3.6/site-packages/botocore/utils.py", line 1073, in _get_response
timeout=timeout)
File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 477, in get
return self.request('GET', url, **kwargs)
File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 465, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.6/site-packages/moto/packages/responses/responses.py", line 308, in unbound_on_send
return self._on_request(adapter, request, *a, **kwargs)
File "/usr/local/lib/python3.6/site-packages/moto/packages/responses/responses.py", line 250, in _on_request
raise response
requests.exceptions.ConnectionError: Connection refused: GET http://169.254.170.2/v2/credentials/5b20b383-ddb7-4e80-b5e7-358afc51e4c2
```

A simple script to test with:
```python
import boto3
import sure
from moto import mock_ssm

@mock_ssm
def moto_test_describe_parameters():
    client = boto3.client('ssm', region_name='us-east-1')

    client.put_parameter(
        Name='test',
        Description='A test parameter',
        Value='value',
        Type='String')

    response = client.describe_parameters()

    len(response['Parameters']).should.equal(1)
    response['Parameters'][0]['Name'].should.equal('test')
    response['Parameters'][0]['Type'].should.equal('String')

def main():
    print('Starting test')
    moto_test_describe_parameters()
    print('finished')

if __name__ == '__main__':
    moto_test_describe_parameters()
```

Sample Buildspec.yml
```yaml
version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements-dev.txt
  build:
    commands:
      - python moto-test.py
  post_build:
    commands:
artifacts:
  files:
    - '**/*'
```

requirements-dev.txt
```
boto3==1.4.5
sure==1.4.6
git+https://github.com/spulec/moto.git
```
Note I use `git+https://github.com/spulec/moto.git` because describe_parameters isn't supported in the current pypi published version.

I've tried with the following codebuild images `aws/codebuild/python:3.5.2` and `python:3.6`

Any ideas on what I'm doing wrong?

Thanks

**Comment by JackDanger** [comment]
Can you print the environment that exists when this test runs?
```
import os
print(os.environment)
```
I'm wondering if there's some kind of endpoint overriding that's going on.

**Comment by ndpete** [comment]
I notice that the regions were different with my test script and environment variables so I re-ran with that removed and here is the output of os.environ (I think thats what you wanted as os.environment doesn't exist)

```
{
  'CODEBUILD_AGENT_ENV_CODEBUILD_CTS_ENDPOINT': 'https://codebuild-builds.us-west-2.amazonaws.com',
  'CODEBUILD_BMR_URL': 'https://CODEBUILD_AGENT:3000',
  'CODEBUILD_AGENT_ENV_BUNDLE_APP_CONFIG': '/usr/local/bundle',
  'CODEBUILD_SOURCE_VERSION': '{REMOVED}',
  'HOSTNAME': '80b0cd72fc81',
  'CODEBUILD_AGENT_ENV_MYSQL_DATA_DIR': '/var/lib/mysql',
  'CODEBUILD_BUILD_ID': 'mototest-prd-Build:{CODEBUILD-ID}',
  'CODEBUILD_KMS_KEY_ID': '{REMOVED}',
  'HANDEL_PIPELINE_NAME': 'mototest',
  'PYTHON_PIP_VERSION': '9.0.1',
  'CODEBUILD_AGENT_ENV_CODEBUILD_LOG_STREAM_INFO': '{Cleaned}',
  'CODEBUILD_AGENT_ENV_MYSQL_RUN_DIR': '/run/mysqld',
  'CODEBUILD_AGENT_ENV_DB_NAME': 'build-agent-sql',
  'HOME': '/root',
  'OLDPWD': '/codebuild/output/src974707887/src',
  'CODEBUILD_GOPATH': '/codebuild/output/src974707887',
  'CODEBUILD_RESOLVED_SOURCE_VERSION': '{source version}',
  'CODEBUILD_BUILD_SUCCEEDING': '1',
  'CODEBUILD_AGENT_ENV_RUBY_MAJOR': '2.2',
  'GPG_KEY': '{REMOVED}',
  'AWS_CONTAINER_CREDENTIALS_RELATIVE_URI': '/v2/credentials/f08ae970-b65c-40b9-9b0b-c90d115c877c',
  'CODEBUILD_BUILD_ARN': '{REMOVED}',
  'CODEBUILD_AGENT_PORT_3000_TCP_ADDR': '172.17.0.2',
  'CODEBUILD_INITIATOR': 'codepipeline/mototest-prd',
  'CODEBUILD_AGENT_PORT_3000_TCP_PORT': '3000',
  'CODEBUILD_AGENT_PORT_3000_TCP_PROTO': 'tcp',
  'CODEBUILD_AGENT_ENV_CODEBUILD_LOG_GROUP': 'CodeBuild/BuildStreams',
  'AWS_DEFAULT_REGION': 'us-west-2',
  'CODEBUILD_AGENT_ENV_CODEBUILD_CONTAINER_INFO': '{CLEANED}',
  'CODEBUILD_AGENT_ENV_AWS_CONTAINER_CREDENTIALS_RELATIVE_URI': '/v2/credentials/f08ae970-b65c-40b9-9b0b-c90d115c877c',
  'CODEBUILD_AGENT_ENV_CODEBUILD_BUILD_ID': '{REMOVED}',
  'CODEBUILD_AGENT_ENV_CODEBUILD_DEPRECATED': 'false',
  'CODEBUILD_AGENT_ENV_CODEBUILD_KMS_KEY_ID': '{REMOVED}',
  'CODEBUILD_AGENT_ENV_GEM_HOME': '/usr/local/bundle',
  'PATH': '/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
  'CODEBUILD_LOG_PATH': '{CODEBUILD-ID}',
  'CODEBUILD_AGENT_PORT_3000_TCP': 'tcp://172.17.0.2:3000',
  'CODEBUILD_AGENT_ENV_CODEBUILD_REGION': 'us-west-2',
  'CODEBUILD_BUILD_IMAGE': 'python:3.6',
  'LANG': 'C.UTF-8',
  'CODEBUILD_AGENT_ENV_CODEBUILD_BUILD_ARN': '{REMOVED}',
  'AWS_ACCOUNT_ID': '{REMOVED}',
  'CODEBUILD_AGENT_ENV_RUBY_VERSION': '2.2.0',
  'CODEBUILD_AGENT_ENV_MYSQL_LOG_DIR': '/var/log/mysql',
  'GOPATH': '/codebuild/output/src974707887',
  'AWS_REGION': 'us-west-2',
  'PYTHON_VERSION': '3.6.2',
  'CODEBUILD_SRC_DIR': '/codebuild/output/src974707887/src',
  'CODEBUILD_AGENT_ENV_CODEBUILD_CONTAINER_TOKENS': '{REMOVED}',
  'CODEBUILD_AGENT_ENV_CODEBUILD_SECRET_KEY_BASE': '{REMOVED}',
  'CODEBUILD_AUTH_TOKEN': '{REMOVED}',
  'CODEBUILD_AGENT_PORT': 'tcp://172.17.0.2:3000',
  'PWD': '/codebuild/output/src974707887/src',
  'CODEBUILD_AGENT_NAME': '/{long address}/CODEBUILD_AGENT',
  'CODEBUILD_AGENT_ENV_MYSQL_USER': '{cleaned}',
  'CODEBUILD_AGENT_ENV_DB_USER': '{cleaned}'
}
```

**Comment by ndpete** [comment]
I haven't been able to solve this yet but I'm pretty sure it is related to the Task Roles for IAM, I wonder if moto is mocking too much or if I need to find a way to force it to not use Task Roles for IAM.
[http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html)

**Comment by ndpete** [comment]
Well I think I've got a workaround for this issue.

When creating a client in Boto3 if you don't specify credentials or you don't have a file in `~/.aws/credentials` and you are running in AWS it will automatically attempt to load the temporary Task Roles IAM credentials. Apparently when using moto it mocks(? or just interferes with) the endpoint to get the Task Roles IAM which causes connection refused error.

The two different workarounds I've tested that seem to be working are the following:

If your code structure allows explicitly define your client with fake credentials:
```python
client = boto3.client('ssm', aws_access_key_id="FakeKey", aws_secret_access_key='FakeSecretKey', aws_session_token='FakeSessionToken')
```

If your code is like mine and the above wasn't an option you can create a fake credential file for boto3 to use in your buildspec.yml file:
```yaml
version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements-dev.txt
      # create the aws dir
      - mkdir -p ~/.aws/
      # create fake credential file
      - echo "[default]\naws_access_key_id = FakeKey\naws_secret_access_key = FakeKey\naws_session_token = FakeKey" > ~/.aws/credentials
  build:
    commands:
      - python moto-test.py
  post_build:
    commands:
artifacts:
  files:
    - '**/*'
```

**Comment by oharaandrew314** [comment]
@ndpete 's first method worked for me.

**Comment by spulec** [comment]
Going to close this in favor of https://github.com/spulec/moto/issues/1567
