### ISSUE TITLE
RDS2 is unusable if hostname is an IP address instead of an domain name

### ISSUE THREAD

**Issue by 2mf** [spulec/moto#1068]
We are using moto in a dockerized environment __without__ any domains just bare IP's for local development and testing.
We won't do anything hackisch regarding boto or /etc/hosts file as this causes other problems.

The IP address is in my case "172.17.0.1" for the server, port doesn't matter.

Moto is mocking AWS that is right, but we can not relay in every situation on the **HTTP "Host" header** to be specific for a region.
Please keep in mind that boto connectors support "port" and "host" which can be a domain __or__ a raw IP. This must be considered for every service nor only RDS.

```
aws-moto-rds_1       | 172.18.0.1 - - [19/Aug/2017 12:52:53] "POST / HTTP/1.1" 500 -
aws-moto-rds_1       | Error on request:
aws-moto-rds_1       | Traceback (most recent call last):
aws-moto-rds_1       |   File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 209, in run_wsgi
aws-moto-rds_1       |     execute(self.server.app)
aws-moto-rds_1       |   File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 197, in execute
aws-moto-rds_1       |     application_iter = app(environ, start_response)
aws-moto-rds_1       |   File "/usr/local/lib/python2.7/dist-packages/moto/server.py", line 84, in __call__
aws-moto-rds_1       |     return backend_app(environ, start_response)
aws-moto-rds_1       |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
aws-moto-rds_1       |     return self.wsgi_app(environ, start_response)
aws-moto-rds_1       |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
aws-moto-rds_1       |     response = self.handle_exception(e)
aws-moto-rds_1       |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
aws-moto-rds_1       |     reraise(exc_type, exc_value, tb)
aws-moto-rds_1       |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
aws-moto-rds_1       |     response = self.full_dispatch_request()
aws-moto-rds_1       |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
aws-moto-rds_1       |     rv = self.handle_user_exception(e)
aws-moto-rds_1       |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
aws-moto-rds_1       |     reraise(exc_type, exc_value, tb)
aws-moto-rds_1       |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
aws-moto-rds_1       |     rv = self.dispatch_request()
aws-moto-rds_1       |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
aws-moto-rds_1       |     return self.view_functions[rule.endpoint](**req.view_args)
aws-moto-rds_1       |   File "/usr/local/lib/python2.7/dist-packages/moto/core/utils.py", line 131, in __call__
aws-moto-rds_1       |     result = self.callback(request, request.url, {})
aws-moto-rds_1       |   File "/usr/local/lib/python2.7/dist-packages/moto/core/responses.py", line 111, in dispatch
aws-moto-rds_1       |     return cls()._dispatch(*args, **kwargs)
aws-moto-rds_1       |   File "/usr/local/lib/python2.7/dist-packages/moto/core/responses.py", line 179, in _dispatch
aws-moto-rds_1       |     return self.call_action()
aws-moto-rds_1       |   File "/usr/local/lib/python2.7/dist-packages/moto/core/responses.py", line 196, in call_action
aws-moto-rds_1       |     response = method()
aws-moto-rds_1       |   File "/usr/local/lib/python2.7/dist-packages/moto/rds2/responses.py", line 117, in describe_db_instances
aws-moto-rds_1       |     all_instances = list(self.backend.describe_databases(db_instance_identifier))
aws-moto-rds_1       |   File "/usr/local/lib/python2.7/dist-packages/moto/rds2/responses.py", line 14, in backend
aws-moto-rds_1       |     return rds2_backends[self.region]
aws-moto-rds_1       | KeyError: u'17'
```

**Comment by spulec** [comment]
Can you confirm this is still an issue with the latest version and give some code/steps to reproduce?

**Comment by 2mf** [comment]
@spulec I'll try it again with the latest version and if I run into a similar issues I'll add some code snippets to reproduce the problem.

**Comment by bblommers** [comment]
With the lack of action here, I'm going to assume this is (no longer) an issue. Let us know if it is, though.
