### ISSUE TITLE
Moto allowing CloudFormation service requests to go thru boto

### ISSUE THREAD

**Issue by luispollo** [spulec/moto#1098]
I'm new to using moto so please let me know if I'm doing something wrong, but I could not find any guidance in the docs or similar previously opened issues.

The issue I'm having is that I'm trying to mock CloudFormation calls using the boto3 service interface, but apparently moto is letting those calls through:

```
Traceback (most recent call last):
  File "C:\tools\Python27\lib\unittest\case.py", line 329, in run
    testMethod()
  File "C:\tools\Python27\lib\site-packages\moto\core\models.py", line 70, in wrapper
    result = func(*args, **kwargs)
  File "C:\<obfuscated>\_modules\tests\unit\test_ecs_service_deployment_strategy.py", line 57, in test_create_ecs_task_definition
    EcsServiceDeploymentStrategy.deploy(self.app, self.version_tag, self.site, self.vpc)
  File "C:\<obfuscated>\_modules\model\deployment\ecs_service_deployment_strategy.py", line 19, in deploy
    task_template = _create_ecs_task_definition(app, version_tag, site, vpc)
  File "C:\<obfuscated>\_modules\model\deployment\ecs_service_deployment_strategy.py", line 28, in _create_ecs_task_definition
    _create_or_update_cloudformation_stack(cf_stack_name, cf_stack_template)
  File "C:\<obfuscated>\_modules\model\deployment\ecs_service_deployment_strategy.py", line 69, in _create_or_update_cloudformation_stack
    Capabilities=['CAPABILITY_NAMED_IAM']
  File "C:\tools\Python27\lib\site-packages\boto3\resources\factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "C:\tools\Python27\lib\site-packages\boto3\resources\action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "C:\tools\Python27\lib\site-packages\botocore\client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\tools\Python27\lib\site-packages\botocore\client.py", line 588, in _make_api_call
    operation_model, request_dict)
  File "C:\tools\Python27\lib\site-packages\botocore\endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "C:\tools\Python27\lib\site-packages\botocore\endpoint.py", line 170, in _send_request
    success_response, exception):
  File "C:\tools\Python27\lib\site-packages\botocore\endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "C:\tools\Python27\lib\site-packages\botocore\hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "C:\tools\Python27\lib\site-packages\botocore\hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "C:\tools\Python27\lib\site-packages\botocore\retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "C:\tools\Python27\lib\site-packages\botocore\retryhandler.py", line 251, in __call__
    caught_exception)
  File "C:\tools\Python27\lib\site-packages\botocore\retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "C:\tools\Python27\lib\site-packages\botocore\retryhandler.py", line 317, in __call__
    caught_exception)
  File "C:\tools\Python27\lib\site-packages\botocore\retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "C:\tools\Python27\lib\site-packages\botocore\retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
KeyError: u'Volumes'
```

My test code:
```
    @mock_cloudformation
    def test_create_ecs_task_definition(self):
        EcsServiceDeploymentStrategy.deploy(self.app, self.version_tag, self.site, self.vpc)
```

And an excerpt of the applicable method definition:
```
def _create_or_update_cloudformation_stack(cf_stack_name, cf_stack_template,
                                           create_timeout=DEFAULT_CLOUDFORMATION_TIMEOUT,
                                           update_timeout=DEFAULT_CLOUDFORMATION_TIMEOUT):
    cf_service = boto3.resource('cloudformation')
    cf_template_body = cf_stack_template.render()
    cf_stack = cf_service.create_stack(
        StackName=cf_stack_name,
        TemplateBody=cf_template_body,
        Capabilities=['CAPABILITY_NAMED_IAM']
    )
```

Versions:
```
Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win32
boto3.__version__
'1.4.6'
botocore.__version__
'1.6.8'
moto.__version__
u'1.0.1'
```

Any thoughts? Thanks in advance for your help!

**Comment by luispollo** [comment]
P.S. If it helps, I can see that both my instance of the boto3 client for cloudformation, as well as the resource service, are actual boto objects. Not sure if that's expected. There must be something obvious I'm missing...

```
cf_client = <botocore.client.CloudFormation object at 0x000000000567FB00>
cf_service = ServiceResource: cloudformation.ServiceResource()
```

**Comment by luispollo** [comment]
Additional info: I've tested with python 2.7 and 3.6 on both Windows and Debian Jessie with the same package versions, same results. Tried several variations of starting the mocks (decorator, raw, etc.). Tried just a simple test calling an arbitrary API on the boto3 client for both cloudformation and ecs. All calls resulted in actual HTTP requests to AWS.

Is there any known "gotcha" with library versions or python versions that could be causing this?

Thanks!

**Comment by luispollo** [comment]
Never mind. My fault misinterpreting the results. Moto is doing its job, but I should have payed attention to the error and the stack trace. The problem is that it's looking for keys in the CloudFormation template that were missing in my case, but that are not mandatory per the AWS spec (or boto3 API). I'll submit a separate issue for that, and a PR to fix it if I have a chance.
