### ISSUE TITLE
/moto-api/ not working correctly.

### ISSUE THREAD

**Issue by chrisLeeTW** [spulec/moto#1102]
### situation 1 : /moto-api/ return 500
**moto[server] version : lastest master branch
startup command : moto_server -H 0.0.0.0 -p 3000**

**here is error traceback**
```
moto-server    | 10.1.0.1 - - [16/Sep/2017 12:21:18] "GET /moto-api/ HTTP/1.1" 500 -
moto-server    | Error on request:
moto-server    | Traceback (most recent call last):
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 209, in run_wsgi
moto-server    |     execute(self.server.app)
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 197, in execute
moto-server    |     application_iter = app(environ, start_response)
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/moto/server.py", line 92, in __call__
moto-server    |     return backend_app(environ, start_response)
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
moto-server    |     return self.wsgi_app(environ, start_response)
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
moto-server    |     response = self.handle_exception(e)
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
moto-server    |     reraise(exc_type, exc_value, tb)
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
moto-server    |     response = self.full_dispatch_request()
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
moto-server    |     rv = self.handle_user_exception(e)
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
moto-server    |     reraise(exc_type, exc_value, tb)
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
moto-server    |     rv = self.dispatch_request()
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
moto-server    |     return self.view_functions[rule.endpoint](**req.view_args)
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/moto/core/utils.py", line 131, in __call__
moto-server    |     result = self.callback(request, request.url, {})
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/moto/core/responses.py", line 401, in dashboard
moto-server    |     return render_template('dashboard.html')
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 133, in render_template
moto-server    |     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
moto-server    |     return self.get_template(template_name_or_list, parent, globals)
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
moto-server    |     return self._load_template(name, self.make_globals(globals))
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
moto-server    |     template = self.loader.load(self, name, globals)
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
moto-server    |     source, filename, uptodate = self.get_source(environment, name)
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 57, in get_source
moto-server    |     return self._get_source_fast(environment, template)
moto-server    |   File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 85, in _get_source_fast
moto-server    |     raise TemplateNotFound(template)
moto-server    | TemplateNotFound: dashboard.html
```

### situation 2 : /moto-api/ return 404
**moto[server] version : lastest master branch
startup command : moto_server -H 0.0.0.0 -p 3000 ec2**

there is no error traceback.

**Comment by spulec** [comment]
Should be fixed with https://github.com/spulec/moto/pull/1279
