### ISSUE TITLE
Mock SQS: incorrect handling of bad queue URLs

### ISSUE THREAD

**Issue by MarSoft** [spulec/moto#1251]
On real SQS, when I try to access a queue with invalid URL (e.g. `sqs.Queue('http://some-unknown-name').load()`), I get `QueueDoesNotExist` error.
When using Moto mock, the error I get is different: `UndefinedError: 'None' has no attribute 'attributes'`.
Will attach full trace below but it is not very helpful because BotoCore hides original stack trace.
I tracked this down and found that the exception happens in `moto/sqs/responses.py`, in `SQSResponse.get_queue_attributes`, when trying to render template `GET_QUEUE_ATTRIBUTES_RESPONSE`. This happens because `self.sqs_backend.get_queue(queue_name)` returns None.
The code is in `moto/sqs/models.py`, in `SQSBackend.get_queue`. It just uses `self.queues.get(name, None)` thus falling back to None if there is no such queue. I think that it should raise an exception instead.
Also it should probably make some better validation in `SQSResponse._get_queue_url` than just fetch last slash-delimited part. Or validate URL somewherre else.. 

How to reproduce:
```
import moto
import boto3

with moto.mock_sqs():
    sqs = boto3.resource('sqs')
	sqs.Queue('http://whatever-incorrect-queue-address').load()
```
Expected result (the one that happens without using `mock_sqs`):
```
QueueDoesNotExist: An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the GetQueueAttributes operation: The specified queue does not exist for this wsdl version.
```
Actual result:
```
Traceback (most recent call last):
  File "/tmp/test.py", line 9, in <module>
    sqs.Queue('http://abc/whatever').load()
  File "/tmp/env/lib/python2.7/site-packages/boto3/resources/factory.py", line 505, in do_action
    response = action(self, *args, **kwargs)
  File "/tmp/env/lib/python2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/tmp/env/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/tmp/env/lib/python2.7/site-packages/botocore/client.py", line 586, in _make_api_call
    operation_model, request_dict)
  File "/tmp/env/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/tmp/env/lib/python2.7/site-packages/botocore/endpoint.py", line 170, in _send_request
    success_response, exception):
  File "/tmp/env/lib/python2.7/site-packages/botocore/endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/tmp/env/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/tmp/env/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/tmp/env/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/tmp/env/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/tmp/env/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/tmp/env/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/tmp/env/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/tmp/env/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
jinja2.exceptions.UndefinedError: 'None' has no attribute 'attributes'
```

Moto version: `moto-ext==1.0.1.7`, installed with `pip`.

**Comment by JackDanger** [comment]
@MarSoft Thanks for reporting this! I've fixed it in #1252, would you be so kind as to review that PR?
