### ISSUE TITLE
Not able to use mocked s3 if script is executed with subprocess (from cli)

### ISSUE THREAD

**Issue by zelima** [spulec/moto#1256]
Hi, Trying to write test case where I need to execute the simple script with cli. Script simply puts the file on S3. To execute it I'm using `subprocess.call(['python', 'my_script.py'])`.  For some reasons, this way it is not run under Moto's "virtual AWS server" and `botocore` complains about credentials  - saying so cause if I import the same script and execute that way, everything works fine.

To clear things out here is an example:
```python
## my_script.py
import boto3

def main():
    s3 = boto3.resource('s3')
    s3.create_bucket(Bucket="testing")
    s3.Object('testing', 'hello.txt').put(Body="some text")

if __name__ == '__main__':
    main()
```
and script for test
```python
## my_test.py
import subprocess
from moto import mock_s3
import my_script

@mock_s3
def my_test_1():
    my_script.main()
    assert (...)
    print('with import worked fine')

@mock_s3
def my_test_2():
   subprocess.call(['python', 'my_script.py'])  # this fails
   assert (...)
   print('with subprocess worked fine\n')

my_test_1() # this works fine
my_test_2() # this fails
```
_Note:_ Tried this with a decorator, context manager and in a raw form - same results.
Is there an easy (or hard) way to accomplish what I'm trying to do above?

Not sure Traceback is useful here but here it is 
```
with import worked fine

Traceback (most recent call last):
  File "my_script.py", line 9, in <module>
    main()
  File "my_script.py", line 5, in main
    s3.create_bucket(Bucket="testing")
  File "/home/local/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/local/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/home/local/lib/python3.6/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/lib/python3.6/site-packages/botocore/client.py", line 588, in _make_api_call
    operation_model, request_dict)
  File "/home/local/lib/python3.6/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/local/lib/python3.6/site-packages/botocore/endpoint.py", line 166, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/lib/python3.6/site-packages/botocore/endpoint.py", line 150, in create_request
    operation_name=operation_model.name)
  File "/home/local/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/home/local/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/home/local/lib/python3.6/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/home/local/lib/python3.6/site-packages/botocore/signers.py", line 154, in sign
    auth.add_auth(request)
  File "/home/local/lib/python3.6/site-packages/botocore/auth.py", line 408, in add_auth
    super(S3SigV4Auth, self).add_auth(request)
  File "/home/local/lib/python3.6/site-packages/botocore/auth.py", line 340, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

**Comment by JackDanger** [comment]
@zelima If you use Moto the default, in-memory way then `@mock_s3` stubs out the AWS client libraries for you. If you call out via subprocess then you're going around that stub and Moto doesn't know how to intercept that call.
However, you can run Moto in server mode! Try running `moto_server` before you run your test and follow the instructions here: https://github.com/spulec/moto#stand-alone-server-mode

**Comment by zelima** [comment]
@JackDanger Thanks for such quick response. This looks promising for me, but I guess it means I should connect to S3 form `my_script` and `my_tests` in the same way, (with `endpoint_url`) If I want to create fake bucket in tests. So, for example, this won't work:
```python
## my_script.py
## assume the mock_server is running
def main():
    s3 = boto3.resource('s3')
    s3.Object('testing', 'hello.txt').put(Body="some text")

if __name__ == '__main__':
    main()
```
and script for test
```python
## my_test.py
import my_script

def my_test():
    boto3.resource(
        service_name='s3',
        region_name='us-west-1',
        endpoint_url='http://localhost:5000', 
    )
    s3.create_bucket(Bucket="testing")
    subprocess.call(['python', 'my_script.py'])
    
my_test()
```

Since in `my_script.py` I'm connecting to S3 without `endpoint_url='http://localhost:5000'` it will still complain for credentials.
