### ISSUE TITLE
Decorator doesn't capture test classMethods

### ISSUE THREAD

**Issue by adamgilman** [spulec/moto#1327]
**Expected behaviour**: Decorating a test class should make all calls to boto3 mocked by moto

**Resulting behaviour**: ConnectionError raised

```
import boto3, os, logging, moto
from unittest import TestCase

@moto.mock_sns
class MockDoesntCapturesClassMethod(TestCase):
    @classmethod
    def setUpClass(cls):
        cls.sns_client = boto3.client("sns")
        sns_topic_arn = cls.sns_client.create_topic(Name="SNSTopic")['TopicArn']
        super(MockDoesntCapturesClassMethod, cls).setUpClass()

    def test_run(self):
        pass
```

Traceback
```
Traceback (most recent call last):
  File "/Users/dev4/Developer/xxx.co/webapp/xxx/xxx/services/tests/tests_usermanagement/test_moto_bug.py", line 9, in setUpClass
    sns_topic_arn = cls.sns_client.create_topic(Name="SNSTopic")['TopicArn']
  File "/Users/dev4/Developer/xxx.co/lib/python2.7/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/dev4/Developer/xxx.co/lib/python2.7/site-packages/botocore/client.py", line 592, in _make_api_call
    operation_model, request_dict)
  File "/Users/dev4/Developer/xxx.co/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/dev4/Developer/xxx.co/lib/python2.7/site-packages/botocore/endpoint.py", line 170, in _send_request
    success_response, exception):
  File "/Users/dev4/Developer/xxx.co/lib/python2.7/site-packages/botocore/endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/dev4/Developer/xxx.co/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/dev4/Developer/xxx.co/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/dev4/Developer/xxx.co/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/dev4/Developer/xxx.co/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/dev4/Developer/xxx.co/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/dev4/Developer/xxx.co/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/dev4/Developer/xxx.co/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/dev4/Developer/xxx.co/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
ConnectionError: Connection refused: POST https://sns.us-east-2.amazonaws.com/
```

**Comment by terrycain** [comment]
The mock when used on a class skips class methods, am not sure if we can safely undo that without breaking an untold number of peoples code.

https://github.com/spulec/moto/blob/master/moto/core/models.py#L88-L90

@JackDanger Opinions?
