### ISSUE TITLE
NotImplementedError: Called get_bucket_versions with some of delimiter, encoding_type, key_marker, version_id_marker

### ISSUE THREAD

**Issue by linkyndy** [spulec/moto#1330]
My application is issuing S3 requests like:

```
127.0.0.1 - - [08/Nov/2017 13:45:44] "GET /bucket?versions&encoding-type=url HTTP/1.1" 500 -
```

Using debug mode, I get this error:

```
Error on request:
Traceback (most recent call last):
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
execute(self.server.app)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/werkzeug/serving.py", line 197, in execute
application_iter = app(environ, start_response)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/moto/server.py", line 93, in __call__
return backend_app(environ, start_response)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/moto/core/utils.py", line 137, in __call__
result = self.callback(request, request.url, {})
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/moto/s3/responses.py", line 106, in ambiguous_response
return self.bucket_response(request, full_url, headers)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/moto/s3/responses.py", line 110, in bucket_response
response = self._bucket_response(request, full_url, headers)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/moto/s3/responses.py", line 148, in _bucket_response
return self._bucket_response_get(bucket_name, querystring, headers)
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/moto/s3/responses.py", line 250, in _bucket_response_get
prefix=prefix
File "/Users/andrei/.pyenv/versions/2.7.13/envs/localstack/lib/python2.7/site-packages/moto/s3/models.py", line 517, in get_bucket_versions
"Called get_bucket_versions with some of delimiter, encoding_type, key_marker, version_id_marker")
NotImplementedError: Called get_bucket_versions with some of delimiter, encoding_type, key_marker, version_id_marker
```

I use localstack that in turn uses moto. Are you planning on addressing this issue somewhere in the near future? It is very important for us, since the whole local setup relies on this.

**Comment by terrycain** [comment]
Can you give me a simple testcase with boto3 that will cause this, then I'll go and look at it.

**Comment by linkyndy** [comment]
Unfortunately, our client is implemented in Ruby and communicates locally with localstack's S3 (which I guess uses moto underneath). So I'm not sure what I can provide in order to help you. Isn't the URL/stacktrace from localstack insightful enough?

**Comment by terrycain** [comment]
It would of been quicker if I had a test case but I can make do.

**Comment by linkyndy** [comment]
Do you happen to have any updates on this? Thanks!
