### ISSUE TITLE
[SES]: send_raw_emal fails to parse a POST request

### ISSUE THREAD

**Issue by tiago-loureiro** [spulec/moto#1421]
# What happens:

Currently moto (using the standalone server, version 1.1.25) errors when clients try to `send_raw_email` as a `POST` request (which is what is used by the [aws cli](https://docs.aws.amazon.com/cli/latest/reference/ses/send-raw-email.html)) with the following stacktrace:

```
moto_server ses -p3000
 * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
127.0.0.1 - - [06/Jan/2018 18:19:22] "POST / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
File "code/python-envs/moto-2.7/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "code/python-envs/moto-2.7/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "code/python-envs/moto-2.7/lib/python2.7/site-packages/moto/server.py", line 93, in __call__
    return backend_app(environ, start_response)
  File "code/python-envs/moto-2.7/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "code/python-envs/moto-2.7/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "code/python-envs/moto-2.7/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "code/python-envs/moto-2.7/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "code/python-envs/moto-2.7/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "code/python-envs/moto-2.7/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "code/python-envs/moto-2.7/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "code/python-envs/moto-2.7/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "code/python-envs/moto-2.7/lib/python2.7/site-packages/moto/core/utils.py", line 137, in __call__
    result = self.callback(request, request.url, {})
  File "code/python-envs/moto-2.7/lib/python2.7/site-packages/moto/core/responses.py", line 114, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "code/python-envs/moto-2.7/lib/python2.7/site-packages/moto/core/responses.py", line 182, in _dispatch
    return self.call_action()
  File "code/python-envs/moto-2.7/lib/python2.7/site-packages/moto/core/responses.py", line 256, in call_action
    response = method()
  File "code/python-envs/moto-2.7/lib/python2.7/site-packages/moto/ses/responses.py", line 78, in send_raw_email
    source = self.querystring.get('Source')[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

The client used to trigger this (the raw.json was taken from amazon's [documentation](https://docs.aws.amazon.com/cli/latest/reference/ses/send-raw-email.html) and is also attached at the end of the issue description 
```
aws --no-verify-ssl --endpoint=http://0.0.0.0:3000 ses send-raw-email --raw-message file://raw.json
```

raw.json
```
{
   "Data": "From: sender@example.com\nTo: recipient@example.com\nSubject: Test email sent using the AWS CLI (contains an attachment)\nMIME-Version: 1.0\nContent-type: Multipart/Mixed; boundary=\"NextPart\"\n\n--NextPart\nContent-Type: text/plain\n\nThis is the message body.\n\n--NextPart\nContent-Type: text/plain;\nContent-Disposition: attachment; filename=\"attachment.txt\"\n\nThis is the text in the attachment.\n\n--NextPart--"
}
```

# What I expected to happen:

That this request would return a [successful response](https://github.com/spulec/moto/blob/master/moto/ses/responses.py#L181-L188)

**Comment by fenrisf** [comment]
I have the same problem. Sending plain mails is going ok, but not when send a raw mail.

**Comment by bblommers** [comment]
If I'm not mistaken, this was fixed by https://github.com/spulec/moto/pull/1622

Feel free to open a new issue if something is still not working
