### ISSUE TITLE
"from moto import mock_ses" raises : "KeyError: 'us-east-1'" error 

### ISSUE THREAD

**Issue by Gosev** [spulec/moto#1440]
My default AWS region is 'eu-west-1' (as are the other regions in ~/aws/config and ~/aws/credentials) 

Doing the following :

```
import boto3
from moto import mock_ses

@mock_ses
def test_send_admin_report():
    pass 
```

Results in the following traceback stack : 

```
File "/Users/yannbonafons/REPOS/gamecore-srv/scripts/tests/test_emails.py", line 2, in <module>
    from moto import mock_ses
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/moto/__init__.py", line 12, in <module>
    from .cloudformation import mock_cloudformation, mock_cloudformation_deprecated  # flake8: noqa
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/moto/cloudformation/__init__.py", line 2, in <module>
    from .models import cloudformation_backends
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/moto/cloudformation/models.py", line 11, in <module>
    from .parsing import ResourceMap, OutputMap
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/moto/cloudformation/parsing.py", line 11, in <module>
    from moto.batch import models as batch_models
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/moto/batch/__init__.py", line 5, in <module>
    batch_backend = batch_backends['us-east-1']
KeyError: 'us-east-1'

```

Update : it looks like batch_backends is an empty object ({}) when batch/__init__.py is called

Update 2: I got around it by (monkey)patching `/batch/__init__.py` (+ equivalent patches in `polly` and `resourcegroupstaggingapi`, and fixing `moto/__init__.py` accordingly) like this :  
```
if 'us-east-1' in batch_backends:
    batch_backend = batch_backends['us-east-1']
    mock_batch = base_decorator(batch_backends)

```

**Comment by bpandola** [comment]
Updating the version of `boto3` and/or `botocore` that you're using will obviate the need to make those patches.  The available regions for a particular service are determined at runtime by calling `boto3.session.Session().get_available_regions()`.  Newer services, like `batch`, are not supported by older versions of `boto3`/`botocore`.

**Comment by earlbread** [comment]
I got the same error and solved it by updating `botocore` from 1.4.93 to 1.8.33.

**Comment by Gosev** [comment]
yep that solved it, thanks.

**Comment by ssudake21** [comment]
Facing same issue with following requirements.
```
(py27) ➜  ✗ pip freeze | grep boto
boto==2.42.0
boto3==1.7.4
botocore==1.4.50
(py27) ➜ ✗ pip freeze | grep moto
moto==1.3.3
(py27) ✗ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import moto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sanket/pf9/pf9-omni/pf9/pf9-neutron/.tox/py27/local/lib/python2.7/site-packages/moto/__init__.py", line 12, in <module>
    from .cloudformation import mock_cloudformation, mock_cloudformation_deprecated  # flake8: noqa
  File "/home/sanket/pf9/pf9-omni/pf9/pf9-neutron/.tox/py27/local/lib/python2.7/site-packages/moto/cloudformation/__init__.py", line 2, in <module>
    from .models import cloudformation_backends
  File "/home/sanket/pf9/pf9-omni/pf9/pf9-neutron/.tox/py27/local/lib/python2.7/site-packages/moto/cloudformation/models.py", line 11, in <module>
    from .parsing import ResourceMap, OutputMap
  File "/home/sanket/pf9/pf9-omni/pf9/pf9-neutron/.tox/py27/local/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 11, in <module>
    from moto.batch import models as batch_models
  File "/home/sanket/pf9/pf9-omni/pf9/pf9-neutron/.tox/py27/local/lib/python2.7/site-packages/moto/batch/__init__.py", line 5, in <module>
    batch_backend = batch_backends['us-east-1']
KeyError: u'us-east-1'
>>> 
```
