### ISSUE TITLE
AttributeError: 'Session' object has no attribute 'get_available_regions'

### ISSUE THREAD

**Issue by boldandbusted** [spulec/moto#1444]
```
vagrant@ubuntu-xenial:~$ moto_server ec2
Traceback (most recent call last):
  File "/home/vagrant/.local/bin/moto_server", line 7, in <module>
    from moto.server import main
  File "/home/vagrant/.local/lib/python2.7/site-packages/moto/__init__.py", line 12, in <module>
    from .cloudformation import mock_cloudformation, mock_cloudformation_deprecated  # flake8: noqa
  File "/home/vagrant/.local/lib/python2.7/site-packages/moto/cloudformation/__init__.py", line 2, in <module>
    from .models import cloudformation_backends
  File "/home/vagrant/.local/lib/python2.7/site-packages/moto/cloudformation/models.py", line 11, in <module>
    from .parsing import ResourceMap, OutputMap
  File "/home/vagrant/.local/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 11, in <module>
    from moto.batch import models as batch_models
  File "/home/vagrant/.local/lib/python2.7/site-packages/moto/batch/__init__.py", line 2, in <module>
    from .models import batch_backends
  File "/home/vagrant/.local/lib/python2.7/site-packages/moto/batch/models.py", line 18, in <module>
    from moto.ecs import ecs_backends
  File "/home/vagrant/.local/lib/python2.7/site-packages/moto/ecs/__init__.py", line 2, in <module>
    from .models import ecs_backends
  File "/home/vagrant/.local/lib/python2.7/site-packages/moto/ecs/models.py", line 892, in <module>
    available_regions = boto3.session.Session().get_available_regions("ecs")
AttributeError: 'Session' object has no attribute 'get_available_regions'
vagrant@ubuntu-xenial:~$ 
```

I have installed via:

```
$ sudo apt-get install libcurl4-openssl-dev libssl-dev
$ pip install --user moto[server]
```

I'm using the Vagrant box for Ubuntu Xenial (16.4), with all current package upgrades (as of this writing). I'm happy to provide further info, and iterative testing. I'm hoping there's some implied setup preliminaries that I just missed that aren't in the README.md. :) Thanks!

**Comment by bpandola** [comment]
What versions of `boto3`/`botocore` do you have installed?

**Comment by spulec** [comment]
I agree that this is likely a boto3/botocore version issue. Feel free to reopen if you are seeing this with the latest version of those.
