### ISSUE TITLE
Autoscaling describe_policies fails if at least one policy of type TargetTrackingScaling is present

### ISSUE THREAD

**Issue by sterago** [spulec/moto#1458]
Here a test to reproduce the issue:
```
    @mock_ec2
    @mock_autoscaling
    def test_can_create_autoscaling_policy(self):
        client = boto3.client("autoscaling")
        configuration_name = 'test'

        client.create_launch_configuration(
            LaunchConfigurationName=configuration_name
        )
        client.create_auto_scaling_group(
            LaunchConfigurationName=configuration_name,
            AutoScalingGroupName=configuration_name,
            MinSize=1,
            MaxSize=2
        )

        assert len(client.describe_policies(
            AutoScalingGroupName=configuration_name
        )['ScalingPolicies']) == 0

        client.put_scaling_policy(
            AutoScalingGroupName=configuration_name,
            PolicyName=configuration_name,
            PolicyType='TargetTrackingScaling',
            EstimatedInstanceWarmup=100,
            TargetTrackingConfiguration={
                'PredefinedMetricSpecification': {
                    'PredefinedMetricType': 'ASGAverageNetworkIn',
                },
                'TargetValue': 1000000.0
            }
        )

        assert len(client.describe_policies(
            AutoScalingGroupName=configuration_name
        )['ScalingPolicies']) == 1
```

The last assertion fails with the following traceback:

```
Error
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "[...]/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "[...]/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "[...]/test/units/library/test_autoscaling.py", line 333, in test_can_create_autoscaling_policy
    AutoScalingGroupName=configuration_name
  File "[...]/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "[...]/python2.7/site-packages/botocore/client.py", line 586, in _make_api_call
    operation_model, request_dict)
  File "[...]/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "[...]/python2.7/site-packages/botocore/endpoint.py", line 168, in _send_request
    request, operation_model, attempts)
  File "[...]/python2.7/site-packages/botocore/endpoint.py", line 233, in _get_response
    response_dict, operation_model.output_shape)
  File "[...]/python2.7/site-packages/botocore/parsers.py", line 212, in parse
    parsed = self._do_parse(response, shape)
  File "[...]/python2.7/site-packages/botocore/parsers.py", line 462, in _do_parse
    parsed = self._parse_shape(shape, start)
  File "[...]/python2.7/site-packages/botocore/parsers.py", line 261, in _parse_shape
    return handler(shape, node)
  File "[...]/python2.7/site-packages/botocore/parsers.py", line 330, in _handle_structure
    member_shape, member_node)
  File "[...]/python2.7/site-packages/botocore/parsers.py", line 261, in _parse_shape
    return handler(shape, node)
  File "[...]/python2.7/site-packages/botocore/parsers.py", line 314, in _handle_list
    return super(BaseXMLResponseParser, self)._handle_list(shape, node)
  File "[...]/python2.7/site-packages/botocore/parsers.py", line 269, in _handle_list
    parsed.append(self._parse_shape(member_shape, item))
  File "[...]/python2.7/site-packages/botocore/parsers.py", line 261, in _parse_shape
    return handler(shape, node)
  File "[...]/python2.7/site-packages/botocore/parsers.py", line 330, in _handle_structure
    member_shape, member_node)
  File "[...]/python2.7/site-packages/botocore/parsers.py", line 261, in _parse_shape
    return handler(shape, node)
  File "[...]/python2.7/site-packages/botocore/parsers.py", line 150, in _get_text_content
    return func(self, shape, text)
  File "[...]/python2.7/site-packages/botocore/parsers.py", line 419, in _handle_integer
    return int(text)
ValueError: invalid literal for int() with base 10: 'None'
```

I guess the expected behavior is that the last assertion passes and the call to `describe_policies` returns `1`

the following libraries are all installed via `pip`
```
boto==2.48.0
boto3==1.4.4
botocore==1.5.95
moto==1.2.0
```

From my understanding the reason for this might be that the `DESCRIBE_SCALING_POLICIES_TEMPLATE ` (https://github.com/spulec/moto/blob/master/moto/autoscaling/responses.py#L576) does not take into account policies of type `TargetTrackingScaling`

**Comment by vascokk** [comment]
Same for PolicyType='StepScaling'
`    # response = client.describe_policies(AutoScalingGroupName=asg_name)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 135, in _send_request
    request, operation_model, context)
  File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 167, in _get_response
    request, operation_model)
  File "/usr/local/lib/python3.6/site-packages/botocore/endpoint.py", line 218, in _do_get_response
    response_dict, operation_model.output_shape)
  File "/usr/local/lib/python3.6/site-packages/botocore/parsers.py", line 242, in parse
    parsed = self._do_parse(response, shape)
  File "/usr/local/lib/python3.6/site-packages/botocore/parsers.py", line 509, in _do_parse
    parsed = self._parse_shape(shape, start)
  File "/usr/local/lib/python3.6/site-packages/botocore/parsers.py", line 302, in _parse_shape
    return handler(shape, node)
  File "/usr/local/lib/python3.6/site-packages/botocore/parsers.py", line 377, in _handle_structure
    member_shape, member_node)
  File "/usr/local/lib/python3.6/site-packages/botocore/parsers.py", line 302, in _parse_shape
    return handler(shape, node)
  File "/usr/local/lib/python3.6/site-packages/botocore/parsers.py", line 360, in _handle_list
    return super(BaseXMLResponseParser, self)._handle_list(shape, node)
  File "/usr/local/lib/python3.6/site-packages/botocore/parsers.py", line 310, in _handle_list
    parsed.append(self._parse_shape(member_shape, item))
  File "/usr/local/lib/python3.6/site-packages/botocore/parsers.py", line 302, in _parse_shape
    return handler(shape, node)
  File "/usr/local/lib/python3.6/site-packages/botocore/parsers.py", line 377, in _handle_structure
    member_shape, member_node)
  File "/usr/local/lib/python3.6/site-packages/botocore/parsers.py", line 302, in _parse_shape
    return handler(shape, node)
  File "/usr/local/lib/python3.6/site-packages/botocore/parsers.py", line 175, in _get_text_content
    return func(self, shape, text)
  File "/usr/local/lib/python3.6/site-packages/botocore/parsers.py", line 466, in _handle_integer
    return int(text)
ValueError: invalid literal for int() with base 10: 'None'`

**Comment by spulec** [comment]
Thanks for opening. I'm going to set this to a feature request for us to implement the other policy types.
