### ISSUE TITLE
dynamodb2 mock incorrectly fails on attribute name of \"

### ISSUE THREAD

**Issue by mattsb42-aws** [spulec/moto#1505]
Props to hypothesis for finding this.

When using the `moto.mock_dynamodb2` mock, `Table.put_item` fails when the attribute name is the string `"`, incorrectly interpreting it as an empty value.

## Example of actual boto3 client behavior
```
>>> t = b3.resource('dynamodb').Table('data_test')
>>> t.put_item(Item={'key': 'asdf', 'range': 'another', '"': '???'})
{'ResponseMetadata': {'RequestId': '1OVEN5O6S2BT2N2NKQOCLGQM2NVV4KQNSO5AEMVJF66Q9ASUAAJG', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'Server', 'date': 'Thu, 08 Mar 2018 22:44:00 GMT', 'content-type': 'application/x-amz-json-1.0', 'content-length': '2', 'connection': 'keep-alive', 'x-amzn-requestid': '1OVEN5O6S2BT2N2NKQOCLGQM2NVV4KQNSO5AEMVJF66Q9ASUAAJG', 'x-amz-crc32': '2745614147'}, 'RetryAttempts': 0}}
>>> t.get_item(Key={'key': 'asdf', 'range': 'another'})
{'Item': {'key': 'asdf', '"': '???', 'range': 'another'}, 'ResponseMetadata': {'RequestId': 'H62VA5MBGL7GC00CSFPMMKFAG7VV4KQNSO5AEMVJF66Q9ASUAAJG', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'Server', 'date': 'Thu, 08 Mar 2018 22:44:20 GMT', 'content-type': 'application/x-amz-json-1.0', 'content-length': '70', 'connection': 'keep-alive', 'x-amzn-requestid': 'H62VA5MBGL7GC00CSFPMMKFAG7VV4KQNSO5AEMVJF66Q9ASUAAJG', 'x-amz-crc32': '2541731839'}, 'RetryAttempts': 0}}
```

## Moto error
```
Python 3.6.4 (default, Feb 20 2018, 14:38:13)
>>> import moto
>>> moto.__version__
('1.2.0',)
>>> from moto import mock_dynamodb2
>>> import boto3
>>> from decimal import Decimal
>>> mock_dynamodb2().start()
>>> ddb = boto3.resource('dynamodb', region_name='us-west-2').Table('my_table')
>>> _TABLE_NAME = 'my_table'
>>> _INDEX = {
...     'partition_attribute': {
...         'type': 'S',
...         'value': 'test_value'
...     },
...     'sort_attribute': {
...         'type': 'N',
...         'value':  Decimal('99.233')
...     }
... }
>>> _KEY = {name: value['value'] for name, value in _INDEX.items()
>>> ddb = boto3.resource('dynamodb', region_name='us-west-2')
>>> ddb.create_table(
...         TableName=_TABLE_NAME,
...         KeySchema=[
...             {
...                 'AttributeName': 'partition_attribute',
...                 'KeyType': 'HASH'
...             },
...             {
...                 'AttributeName': 'sort_attribute',
...                 'KeyType': 'RANGE'
...             }
...         ],
...         AttributeDefinitions=[
...             {
...                 'AttributeName': name,
...                 'AttributeType': value['type']
...             }
...             for name, value in _INDEX.items()
...         ],
...         ProvisionedThroughput={
...             'ReadCapacityUnits': 100,
...             'WriteCapacityUnits': 100
...         }
...     )
dynamodb.Table(name='my_table')
>>> t = ddb.Table('my_table')
>>> t.put_item(Item={'partition_attribute': 'asdf', 'sort_attribute': 33, '"': 'df'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bullocm/git/aws-dynamodb-encryption-python/.tox/py36-local-fast/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/bullocm/git/aws-dynamodb-encryption-python/.tox/py36-local-fast/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Users/bullocm/git/aws-dynamodb-encryption-python/.tox/py36-local-fast/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/bullocm/git/aws-dynamodb-encryption-python/.tox/py36-local-fast/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the PutItem operation: One or more parameter values were invalid: An AttributeValue may not contain an empty string
```

**Comment by mattsb42-aws** [comment]
In further testing, it looks like having this string as a String value or Map key also throws an error.

**Comment by spulec** [comment]
Thanks for reporting! This should be fixed now.

**Comment by mattsb42-aws** [comment]
It looks like this fix went a bit over too far in the opposite direction. There should be an error raised if the attribute name or map key is empty, just not if it happens to just be quote characters.

I put together this test suite to demonstrate what I mean, and show it working against the actual service.

https://gist.github.com/mattsb42-aws/a6fa25bed15079fc99ac1ed0f6c81066

**Comment by mattsb42-aws** [comment]
Looks good!
