### ISSUE TITLE
CloudWatch metrics: Support statistic-values in put-metric-data

### ISSUE THREAD

**Issue by barryoneill** [spulec/moto#1615]
When putting statistic data (and not single values), moto returns a 500 error.  

*Version: 1.3.3*

- when `--value` is being supplied, everything is fine.  
- when `--value` is not present (e.g. when using `--statistic-values` instead - see the example in [Amazon's Docs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/PublishMetrics.html)), a 500 error occurs.

### to reproduce

In one terminal, leave moto running cloudwatch:

```
$ moto_server cloudwatch
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

In another, issue the following commands to see the difference (again, following the example in [Amazon's Docs])(https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/PublishMetrics.html):

- Success Case

```
$ aws --endpoint=http://localhost:5000 cloudwatch put-metric-data --metric-name RequestLatency --namespace GetStarted --timestamp 2016-10-14T20:30:00Z --value 235 --unit Milliseconds

// server logs:
127.0.0.1 - - [03/May/2018 19:22:10] "POST / HTTP/1.1" 200 -
```

- failure case

```
$ aws --endpoint=http://localhost:5000 cloudwatch put-metric-data --metric-name RequestLatency --namespace GetStarted --timestamp 2016-10-14T21:30:00Z --statistic-values Sum=577,Minimum=65,Maximum=189,SampleCount=5 --unit Milliseconds

Unable to parse response (syntax error: line 1, column 54), invalid XML received:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>\n'

// server logs:
127.0.0.1 - - [03/May/2018 19:22:13] "POST / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/vm/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/media/sf_external/moto/moto/server.py", line 93, in __call__
    return backend_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/sf_external/moto/moto/core/utils.py", line 139, in __call__
    result = self.callback(request, request.url, {})
  File "/media/sf_external/moto/moto/core/responses.py", line 116, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/media/sf_external/moto/moto/core/responses.py", line 199, in _dispatch
    return self.call_action()
  File "/media/sf_external/moto/moto/core/responses.py", line 273, in call_action
    response = method()
  File "/media/sf_external/moto/moto/core/utils.py", line 263, in _wrapper
    response = f(*args, **kwargs)
  File "/media/sf_external/moto/moto/cloudwatch/responses.py", line 81, in put_metric_data
    self.cloudwatch_backend.put_metric_data(namespace, metric_data)
  File "/media/sf_external/moto/moto/cloudwatch/models.py", line 233, in put_metric_data
    namespace, metric_member['MetricName'], float(metric_member['Value']), metric_member.get('Dimensions.member', _EMPTY_LIST), metric_member.get('Timestamp')))
KeyError: 'Value'
```

I understand from comments [such as this](https://github.com/spulec/moto/blob/master/moto/cloudwatch/models.py#L169) that statistics support is on the roadmap.  An intermediate fix would just be to default calls without `Value` to 0 as an interim, if not desireable alternative to crashing.

**Comment by barryoneill** [comment]
Just opened a PR to deal with the KeyError, but would love to see statistic support in the next release.  Thank you!

**Comment by spulec** [comment]
Fixed with https://github.com/spulec/moto/pull/1616
