### ISSUE TITLE
Mocking SQS `get_queue_by_name` gives error The specified queue does not exist for this wsdl version

### ISSUE THREAD

**Issue by vishsangale** [spulec/moto#1683]
```   
def test_break_sqs_send(self):
    with moto.mock_sqs():
        sqs = boto3.resource('sqs')
        sqs.get_queue_by_name(QueueName='http://whatever-incorrect-queue-address')
```

Error log
```
Traceback (most recent call last):
  File "C:\repos\simple-test-framework\stf\tests\test_sqs.py", line 116, in test_break_sqs_send
    sqs.get_queue_by_name(QueueName='http://whatever-incorrect-queue-address')
  File "c:\repos\simple-test-framework\venv\lib\site-packages\boto3\resources\factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "c:\repos\simple-test-framework\venv\lib\site-packages\boto3\resources\action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "c:\repos\simple-test-framework\venv\lib\site-packages\botocore\client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\repos\simple-test-framework\venv\lib\site-packages\botocore\client.py", line 544, in _make_api_call
    raise error_class(parsed_response, operation_name)
QueueDoesNotExist: An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the GetQueueUrl operation: The specified queue does not exist for this wsdl version.
-------------------- >> begin captured logging << --------------------
botocore.loaders: DEBUG: Loading JSON file: c:\repos\simple-test-framework\venv\lib\site-packages\boto3\data\sqs\2012-11-05\resources-1.json
botocore.loaders: DEBUG: Loading JSON file: c:\repos\simple-test-framework\venv\lib\site-packages\botocore\data\sqs\2012-11-05\service-2.json
botocore.client: DEBUG: Registering retry handlers for service: sqs
botocore.hooks: DEBUG: Event creating-client-class.sqs: calling handler <function add_generate_presigned_url at 0x000000000381AF98>
botocore.args: DEBUG: The s3 config key is not a dictionary type, ignoring its value of: None
botocore.endpoint: DEBUG: Setting sqs timeout as (60, 60)
boto3.resources.factory: DEBUG: Loading sqs:sqs
boto3.resources.action: INFO: Calling sqs:get_queue_url with {'QueueName': 'http://whatever-incorrect-queue-address'}
botocore.hooks: DEBUG: Event before-parameter-build.sqs.GetQueueUrl: calling handler <function generate_idempotent_uuid at 0x000000000384AB38>
botocore.endpoint: DEBUG: Making request for OperationModel(name=GetQueueUrl) (verify_ssl=True) with params: {'body': {'Action': u'GetQueueUrl', 'Version': u'2012-11-05', 'QueueName': 'http://whatever-incorrect-queue-address'}, 'url': u'https://queue.amazonaws.com/', 'headers': {'User-Agent': 'Boto3/1.4.4 Python/2.7.13 Windows/7 Botocore/1.5.35 Resource'}, 'context': {'auth_type': None, 'client_region': 'us-east-1', 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x00000000068E5390>}, 'query_string': '', 'url_path': '/', 'method': u'POST'}
botocore.hooks: DEBUG: Event request-created.sqs.GetQueueUrl: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x00000000068E5198>>
botocore.hooks: DEBUG: Event choose-signer.sqs.GetQueueUrl: calling handler <function set_operation_specific_signer at 0x000000000384AA58>
botocore.auth: DEBUG: Calculating signature using v4 auth.
botocore.auth: DEBUG: CanonicalRequest:
POST
/

host:queue.amazonaws.com
x-amz-date:20180612T164118Z

host;x-amz-date
1b40b7f5999260f67653d51eebef3e2fb68ae4d914873cd15ec1cc3a08f78971
botocore.auth: DEBUG: StringToSign:
AWS4-HMAC-SHA256
20180612T164118Z
20180612/us-east-1/sqs/aws4_request
bd2c56c6c0860bdc9f69cc3e27d653f2009cd5a93d1ee5d69750c7278d5fd62c
botocore.auth: DEBUG: Signature:
89fc02715fcd772b47f672749a2e6346397dd8821b5c54513cc1f58f093831eb
botocore.endpoint: DEBUG: Sending http request: <PreparedRequest [POST]>
botocore.vendored.requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): queue.amazonaws.com
botocore.vendored.requests.packages.urllib3.connectionpool: DEBUG: "POST / HTTP/1.1" 404 364
botocore.parsers: DEBUG: Response headers: {'status': '404', 'content-length': '364', 'server': 'Python/HTTPretty', 'connection': 'close', 'date': 'Tue, 12 Jun 2018 16:41:18 GMT', 'content-type': 'text/plain; charset=utf-8'}
botocore.parsers: DEBUG: Response body:
<ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">
    <Error>
        <Type>Sender</Type>
        <Code>AWS.SimpleQueueService.NonExistentQueue</Code>
        <Message>The specified queue does not exist for this wsdl version.</Message>
        <Detail/>
    </Error>
    <RequestId>b8bc806b-fa6b-53b5-8be8-cfa2f9836bc3</RequestId>
</ErrorResponse>
botocore.hooks: DEBUG: Event needs-retry.sqs.GetQueueUrl: calling handler <botocore.retryhandler.RetryHandler object at 0x000000000691D550>
botocore.retryhandler: DEBUG: No retry needed.
```
Packages
```
boto3==1.4.4
botocore==1.5.35
moto==0.4.31
```

**Comment by iainb** [comment]
I believe that this is working as expected, moto mocks the entire SQS service, it aims to be as close to AWS production environment as possible. As you have not created a queue and [`get_queue_by_name` only fetches queues that exist](https://boto3.readthedocs.io/en/latest/reference/services/sqs.html#SQS.ServiceResource.get_queue_by_name) an error is to be expected.

You must first create a queue within the `with` statement if you want to then fetch it using `get_queue_by_name`.

**Comment by spulec** [comment]
Yes, @iainb is correct. Going to close this, but feel free to reopen if you have more questions.

**Comment by Naveen-Regulus** [comment]
Is there a way to handle this exception ?

**Comment by nsjcorps** [comment]
Try this
```
try:
        queue = sqs.get_queue_by_name(QueueName=queue_name)
    except botocore.exceptions.ClientError as ex:
        if (
            ex.response["Error"]["Code"]
            != "AWS.SimpleQueueService.NonExistentQueue"
        ):
            logger.exception("Cannot get queue: {}".format(queue_name))
        queue = sqs.create_queue(QueueName=queue_name)
    return queue
```
