### ISSUE TITLE
Cannot download 'application/x-empty' files

### ISSUE THREAD

**Issue by NyanKiyoshi** [spulec/moto#1775]
Hello, when trying to download a file having for mime-type `application/x-empty`, the following error occurs: `ValueError: I/O operation on closed file`.

I tried to reproduce the issue on `boto3` without using `moto`, and it doesn't occur.

## How to reproduce
```python
from io import BytesIO
import boto3
import moto

BUCKET_NAME = 'bucket'
KEY_NAME = 'emptyFile'

KEY_MIME_TYPE = 'application/x-empty'

mocked_s3 = moto.mock_s3()
mocked_s3.start()

s3 = boto3.resource(service_name='s3')
s3.create_bucket(Bucket=BUCKET_NAME)

bucket = s3.Bucket(BUCKET_NAME)

with BytesIO() as fp:
    bucket.upload_fileobj(
        Fileobj=fp, Key=KEY_NAME, ExtraArgs={'ContentType': KEY_MIME_TYPE})


# should raise 'ValueError: I/O operation on closed file.'
with BytesIO() as fp:
    bucket.download_fileobj(Fileobj=fp, Key=KEY_NAME)
```

## Error Stack
```
Traceback (most recent call last):
  File "<input>", line 25, in <module>
  File "/home/sayuri/development/sailing-venv/lib/python3.6/site-packages/boto3/s3/inject.py", line 720, in bucket_download_fileobj
    Callback=Callback, Config=Config)
  File "/home/sayuri/development/sailing-venv/lib/python3.6/site-packages/boto3/s3/inject.py", line 678, in download_fileobj
    return future.result()
  File "/home/sayuri/development/sailing-venv/lib/python3.6/site-packages/s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/home/sayuri/development/sailing-venv/lib/python3.6/site-packages/s3transfer/futures.py", line 233, in result
    raise self._exception
  File "/home/sayuri/development/sailing-venv/lib/python3.6/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/home/sayuri/development/sailing-venv/lib/python3.6/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/sayuri/development/sailing-venv/lib/python3.6/site-packages/s3transfer/download.py", line 532, in _main
    for chunk in chunks:
  File "/home/sayuri/development/sailing-venv/lib/python3.6/site-packages/s3transfer/download.py", line 660, in __next__
    chunk = self._body.read(self._chunksize)
  File "/home/sayuri/development/sailing-venv/lib/python3.6/site-packages/s3transfer/utils.py", line 519, in read
    value = self._stream.read(*args, **kwargs)
  File "/home/sayuri/development/sailing-venv/lib/python3.6/site-packages/botocore/response.py", line 76, in read
    chunk = self._raw_stream.read(amt)
  File "/home/sayuri/development/sailing-venv/lib/python3.6/site-packages/urllib3/response.py", line 413, in read
    data = self._fp.read(amt)
ValueError: I/O operation on closed file.
```

## Versions
```
python==3.6.6
moto==1.3.4
boto==2.49.0
boto3==1.7.70
botocore==1.10.72
s3transfer==0.1.13
urllib3==1.23
```

**Comment by spulec** [comment]
Thanks for opening. Confirmed as a bug.

**Comment by Bennyelg** [comment]
I can't re produce this.. looks like it was solved.

**Comment by spulec** [comment]
Okay. I am going to close. If anyone is still experiencing this, please comment.
