### ISSUE TITLE
moto raises PicklingError when testing multiprocessing using Pool class

### ISSUE THREAD

**Issue by chunyong-lin** [spulec/moto#1798]
## Reporting Bugs
I am using `Pool` class from python multiprocessing module. The code is working well. But the unit test is failed with following errors.
```
Traceback (most recent call last):
  File "moto_kinesis_test.py", line 43, in <module>
    test_main()
  File "/Users/chunyong_lin/Work/virtual_environments/testing-3/lib/python3.7/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "moto_kinesis_test.py", line 41, in test_main
    main()
  File "moto_kinesis_test.py", line 37, in main
    run()
  File "moto_kinesis_test.py", line 34, in run
    pool.map(send_to_kinesis, message_batches)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x104c4c518>'. Reason: 'PicklingError("Can't pickle <class 'botocore.errorfactory.ResourceNotFoundException'>: attribute lookup ResourceNotFoundException on botocore.errorfactory failed")'
```

Here is the testing code I have
```
from multiprocessing import Pool
import uuid

import boto3
from moto import mock_kinesis

KINESIS_STREAM_NAME = 'cl_test_stream'
KINESIS_REGION = 'us-west-1'

def send_to_kinesis(message_batch):
    kinesis_client = boto3.client('kinesis', region_name=KINESIS_REGION)
    response = kinesis_client.put_records(
        Records=[{
            'Data': data,
            'PartitionKey': str(uuid.uuid4())
        } for data in list(message_batch)],
        StreamName=KINESIS_STREAM_NAME
    )

    return response

def run():
    count = 10000
    batch_count = 500
    messages = [str(index) for index in range(count)]

    message_batches = []
    for index in range(0, count, batch_count):
        message_batches.append(messages[index:batch_count + index])

    with Pool(4) as pool:
        pool.map(send_to_kinesis, message_batches)

def main():
    run()

@mock_kinesis
def test_main():
    main()

test_main()
```

My `moto` version is 1.3.4
```
 pip show moto
Name: moto
Version: 1.3.4
Summary: A library that allows your python tests to easily mock out the boto library
Home-page: https://github.com/spulec/moto
Author: Steve Pulec
Author-email: spulec@gmail.com
License: Apache
Location: /Users/chunyong_lin/Work/virtual_environments/testing-3/lib/python3.7/site-packages
Requires: boto3, mock, pyaml, six, cookies, pytz, docker, werkzeug, requests, python-dateutil, boto, Jinja2, jsondiff, responses, python-jose, aws-xray-sdk, cryptography, xmltodict, botocore
Required-by:
```
My tried python version 3.6.5 and 3.7.0, they experience same issue.

**Comment by spulec** [comment]
Does this work without using Moto? At first glance it seems to be related to botocore errors not being pickleable.

**Comment by grapemix** [comment]
We got the same problem too. The test is fine when the testcase is not being run in --parallel. We are using this lib with Django testcase and of course boto3.
