### ISSUE TITLE
Moto should raise an error when SQS send_message_batch pass an empty entries

### ISSUE THREAD

**Issue by ozooxo** [spulec/moto#1799]
When doing `client.send_message_batch(QueueUrl=queue_url, Entries=[])`, boto will raise an error.

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.EmptyBatchRequest: An error occurred (AWS.SimpleQueueService.EmptyBatchRequest) when calling the SendMessageBatch operation: There should be at least one SendMessageBatchRequestEntry in the request.
```

moto should raise the same error, rather than to be silent on that.

Environment:

```
$ python --version
Python 2.7.11
$ python -c "import boto3; print(boto3.__version__)"
1.4.7
$ python -c "import moto; print(moto.__version__)"
1.3.1
```

**Comment by spulec** [comment]
Thanks; setting as a feature request.
