### ISSUE TITLE
mock_kinesis fails to mock create_stream call when using boto3 1.8.6

### ISSUE THREAD

**Issue by FrederikP** [spulec/moto#1805]
When using boto3 1.7.x the following call was mocked and everything was well. I removed my aws credentials for this test, but the following script runs without error. This is a small example that reproduced the issue we had in a bigger test case.

```
from moto import mock_kinesis
import boto3

@mock_kinesis
def test():
    kinesis_client = boto3.client('kinesis', region_name='eu-central-1')
    kinesis_client.create_stream(StreamName='teststream', ShardCount=1)

test()
```

Now, after upgrading to boto3 1.8.6 (and leaving the script as is), it complains about missing credentials. (With credentials and all permissions it goes ahead and creates a stream in the cloud).

```
Traceback (most recent call last):
  File "scripts/kinesis_mock.py", line 9, in <module>
    test()
  File "/home/project/venv/lib/python3.6/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "scripts/kinesis_mock.py", line 7, in test
    kinesis_client.create_stream(StreamName='teststream', ShardCount=1)
  File "/home/project/venv/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/project/venv/lib/python3.6/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/home/project/venv/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/project/venv/lib/python3.6/site-packages/botocore/endpoint.py", line 131, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/project/venv/lib/python3.6/site-packages/botocore/endpoint.py", line 115, in create_request
    operation_name=operation_model.name)
  File "/home/project/venv/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/home/project/venv/lib/python3.6/site-packages/botocore/hooks.py", line 360, in _emit
    aliased_event_name, kwargs, stop_on_response
  File "/home/project/venv/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/home/project/venv/lib/python3.6/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/home/project/venv/lib/python3.6/site-packages/botocore/signers.py", line 156, in sign
    auth.add_auth(request)
  File "/home/project/venv/lib/python3.6/site-packages/botocore/auth.py", line 356, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials

```

This happens using moto 1.3.5 (as well as earlier versions, probably).

**Comment by FrederikP** [comment]
Just noticed, this is basically due to https://github.com/spulec/moto/issues/1793 .
Will close this
