### ISSUE TITLE
@mock_dynamodb2 update_item with UpdateExpression doesn't work for list items

### ISSUE THREAD

**Issue by zero-you** [spulec/moto#1823]
I tried to use something like `UpdateExpression='SET testList[1]  = 10'` to update the elements of a list, which works if I use Boto3 to interact directly with an actual dynamoDB table on AWS. However, with mock_dynamodb2, I got a new item in the table named "testList[1]". An example code is attached below: 
```python
from __future__ import unicode_literals

import boto3
from moto import mock_dynamodb2
from boto3.dynamodb.conditions import Key
from botocore.exceptions import ClientError
import sure


def _create_table_with_range_key():
    dynamodb = boto3.resource('dynamodb', region_name='us-east-1')

    # Create the DynamoDB table.
    table = dynamodb.create_table(
        TableName='users',
        KeySchema=[
            {
                'AttributeName': 'forum_name',
                'KeyType': 'HASH'
            },
            {
                'AttributeName': 'subject',
                'KeyType': 'RANGE'
            },
        ],
        AttributeDefinitions=[
            {
                'AttributeName': 'forum_name',
                'AttributeType': 'S'
            },
            {
                'AttributeName': 'subject',
                'AttributeType': 'S'
            }
        ],
        ProvisionedThroughput={
            'ReadCapacityUnits': 5,
            'WriteCapacityUnits': 5
        }
    )
    return dynamodb.Table('users')


@mock_dynamodb2
def test_update_item_with_expression():
    table = _create_table_with_range_key()

    table.put_item(Item={
        'forum_name': 'the-key',
        'subject': '123',
        'field': '1',
        'testList': [1, 2, 3]
    })

    item_key = {'forum_name': 'the-key', 'subject': '123'}

    table.update_item(
        Key=item_key,
        UpdateExpression='SET testList[1]  = 10',
    )
    dict(table.get_item(Key=item_key)['Item']).should.equal({
        'field': '1',
        'forum_name': 'the-key',
        'subject': '123',
        'testList': [1, 10, 3]
    })

if __name__ == '__main__':
    test_update_item_with_expression()
```

Here is the Traceback:
```
Traceback (most recent call last):
  File "/Users/admin/anaconda3/lib/python3.6/site-packages/sure/__init__.py", line 385, in wrapper
    value = func(self, *args, **kw)
  File "/Users/admin/anaconda3/lib/python3.6/site-packages/sure/__init__.py", line 673, in equal
    raise error
AssertionError: given
X = {'field': '1', 'forum_name': 'the-key', 'subject': '123', 'testList': [Decimal('1'), Decimal('2'), Decimal('3')], 'testList[1]': '10'}
    and
Y = {'field': '1', 'forum_name': 'the-key', 'subject': '123', 'testList': [1, 10, 3]}
X has the key "'testList[1]'" whereas Y does not

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests.py", line 69, in <module>
    test_update_item_with_expression()
  File "/Users/admin/anaconda3/lib/python3.6/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "tests.py", line 65, in test_update_item_with_expression
    'testList': [1, 10, 3]
  File "/Users/admin/anaconda3/lib/python3.6/site-packages/sure/__init__.py", line 387, in wrapper
    raise AssertionError(e)
AssertionError: given
X = {'field': '1', 'forum_name': 'the-key', 'subject': '123', 'testList': [Decimal('1'), Decimal('2'), Decimal('3')], 'testList[1]': '10'}
    and
Y = {'field': '1', 'forum_name': 'the-key', 'subject': '123', 'testList': [1, 10, 3]}
X has the key "'testList[1]'" whereas Y does not
```

**Comment by spulec** [comment]
Thanks; setting as a feature request.
