### ISSUE TITLE
cognito-idp admin_get_user should raise a UserNotFoundException, when user not in pool

### ISSUE THREAD

**Issue by georgealton** [spulec/moto#1831]
Hi,

when using cognito-idp and searching for a non existing user, the Exception raised is `ResourceNotFoundException`, the Exception i'm expecting to be raised is a `UserNotFoundException`

This is how to reproduce in moto 
```python
import moto
import boto3
with moto.mock_cognitoidp():
    cognito = boto3.client('cognito-idp')
    create_pool_kwargs = {
        "PoolName": "test_pool",
        "Schema": [
            {
                "Name": "email",
                "AttributeDataType": "String",
                "Required": True,
                "Mutable": True,
            }
        ],
        "AdminCreateUserConfig": {
            "AllowAdminCreateUserOnly": True, "UnusedAccountValidityDays": 1
        },
    }
    pool = cognito.create_user_pool(**create_pool_kwargs)['UserPool']
    cognito.admin_get_user(Username='missing', UserPoolId=pool['Id'])
```

This is the Traceback generated 
```
Traceback (most recent call last):
  File "<stdin>", line 18, in <module>
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the AdminGetUser operation: missing
```

Here's the same command run against a user pool in aws, where boto raises a `UserNotFoundException`

```python
import boto3
cognito = boto3.client('cognito-idp')
cognito.admin_get_user(Username='missing', UserPoolId='eu-west-1_zsFiodetm')
```
And the Traceback from that call
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.UserNotFoundException: An error occurred (UserNotFoundException) when calling the AdminGetUser operation: User does not exist.
```

This is also the same for admin_delete_user

```
>>> cognito.admin_delete_user(Username='missing', UserPoolId='eu-west-1_zsFiodetm')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.UserNotFoundException: An error occurred (UserNotFoundException) when calling the AdminDeleteUser operation: User does not exist.
```

I'm using the package installed via pip and python mocks. 
```
moto==1.3.4
botocore==1.10.52
boto3==1.7.3
```

**Comment by spulec** [comment]
Thanks; setting as a feature request.
