### ISSUE TITLE
Getting: "Unable to locate credentials" on latest core/boto3

### ISSUE THREAD

**Issue by kingbuzzman** [spulec/moto#1833]
My pristine machine that has nothing installed. (I'm seeing this exact behavior in my main app, i'm just trying to illustrate the issue here)

```
$ docker run --rm -it python:3.7 bash
root@8ced02d5d4c8:/# pip install boto==2.49.0 boto3==1.9.7 botocore==1.12.7 moto==1.3.5
..... SNIPPED.......
Successfully installed Jinja2-2.10 MarkupSafe-1.0 PyYAML-3.13 asn1crypto-0.24.0 aws-xray-sdk-0.95 boto-2.49.0 boto3-1.9.7 botocore-1.12.7 certifi-2018.8.24 cffi-1.11.5 chardet-3.0.4 cookies-2.2.1 cryptography-2.3.1 docker-3.5.0 docker-pycreds-0.3.0 docutils-0.14 ecdsa-0.13 future-0.16.0 idna-2.7 jmespath-0.9.3 jsondiff-1.1.1 jsonpickle-1.0 mock-2.0.0 moto-1.3.5 pbr-4.2.0 pyaml-17.12.1 pycparser-2.19 pycryptodome-3.6.6 python-dateutil-2.7.3 python-jose-2.0.2 pytz-2018.5 requests-2.19.1 responses-0.9.0 s3transfer-0.1.13 six-1.11.0 urllib3-1.23 websocket-client-0.53.0 werkzeug-0.14.1 wrapt-1.10.11 xmltodict-0.11.0
root@8ced02d5d4c8:/# python
Python 3.7.0 (default, Jul 17 2018, 11:04:33) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import moto
>>> moto.mock_s3().start()
>>> import boto3
>>> client = boto3.client('s3')
>>> client.create_bucket(Bucket='testing')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 610, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/usr/local/lib/python3.7/site-packages/botocore/signers.py", line 157, in sign
    auth.add_auth(request)
  File "/usr/local/lib/python3.7/site-packages/botocore/auth.py", line 424, in add_auth
    super(S3SigV4Auth, self).add_auth(request)
  File "/usr/local/lib/python3.7/site-packages/botocore/auth.py", line 356, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

Any ideas whats causing it?

**Comment by kingbuzzman** [comment]
Looks like i was using versions that are explicitly stated to not work.

`botocore==1.10.84 boto3==1.7.84` i get the expected result.
