### ISSUE TITLE
DynamoDB: FilterExpression does not work on numerical nested fields

### ISSUE THREAD

**Issue by davidshay** [spulec/moto#1934]
I am using moto 1.3.7, and I run the following code:

```python
import boto3
from moto import mock_dynamodb2
from boto3.dynamodb.conditions import Key, Attr

@mock_dynamodb2
def test():
    boto3.client("dynamodb").create_table(
        AttributeDefinitions=[
            {"AttributeName": "key", "AttributeType": "S"},
            {"AttributeName": "sort", "AttributeType": "S"},
        ],
        TableName="table",
        KeySchema=[
            {"AttributeName": "key", "KeyType": "HASH"},
            {"AttributeName": "sort", "KeyType": "RANGE"},
        ],
        ProvisionedThroughput={"ReadCapacityUnits": 5, "WriteCapacityUnits": 5},
    )

    dynamodb = boto3.resource("dynamodb")
    dynamodb.Table("table").put_item(Item={"key": "x", "sort": "a", "sub": {"value": 5}})
    dynamodb.Table("table").put_item(Item={"key": "x", "sort": "b", "sub": {"value": 6}})
    dynamodb.Table("table").put_item(Item={"key": "x", "sort": "c", "sub": {"value": 7}})

    result = dynamodb.Table("table").query(
        KeyConditionExpression=Key("key").eq("x"),
        FilterExpression=Attr("sub.value").gt(5),
    )
    
    print (result["Count"])

test()
```

As you can see, I create a table and insert some items with a nested numeric field, then I run a query with a FilterExpression. I expect this code to print 2. However, I get the following error:

```
Traceback (most recent call last):
  File "/home/g179879/workspace/smartwifi/python/pure_lambdas/update_disconnect/tests/snippet.py", line 32, in <module>
    test()
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/moto/core/models.py", line 74, in wrapper
    result = func(*args, **kwargs)
  File "/home/g179879/workspace/smartwifi/python/pure_lambdas/update_disconnect/tests/snippet.py", line 27, in test
    FilterExpression=Attr("sub.value").gt(5),
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/botocore/client.py", line 610, in _make_api_call
    operation_model, request_dict)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/botocore/endpoint.py", line 136, in _send_request
    success_response, exception):
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/botocore/endpoint.py", line 210, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/botocore/endpoint.py", line 176, in _get_response
    responses = self._event_emitter.emit(event_name, request=request)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/moto/core/models.py", line 292, in __call__
    status, headers, body = response_callback(request, request.url, request.headers)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/moto/core/responses.py", line 117, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/moto/core/responses.py", line 200, in _dispatch
    return self.call_action()
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/moto/core/utils.py", line 264, in _wrapper
    response = f(*args, **kwargs)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/moto/dynamodb2/responses.py", line 64, in call_action
    response = getattr(self, endpoint)()
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/moto/dynamodb2/responses.py", line 437, in query
    filter_expression=filter_expression, **filter_kwargs
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/moto/dynamodb2/models.py", line 784, in query
    exclusive_start_key, scan_index_forward, projection_expression, index_name, filter_expression, **filter_kwargs)
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/moto/dynamodb2/models.py", line 550, in query
    results = [item for item in results if filter_expression.expr(item)]
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/moto/dynamodb2/models.py", line 550, in <listcomp>
    results = [item for item in results if filter_expression.expr(item)]
  File "/home/g179879/workspace/venv/lib/python3.6/site-packages/moto/dynamodb2/comparisons.py", line 368, in expr
    return lhs > rhs
TypeError: '>' not supported between instances of 'str' and 'float'
```

However it works fine with non-nested fields.

**Comment by spulec** [comment]
Thanks for opening. Setting this as a feature request for us to implement.

**Comment by bblommers** [comment]
@davidshay Can you verify whether this has been fixed already? I can't reproduce it anymore for moto >= 1.3.10

**Comment by davidshay** [comment]
@bblommers I checked with version 1.3.13 and it works fine.
