### ISSUE TITLE
Multiple ApiGateway endpoints not supported and breaking serverless deploy

### ISSUE THREAD

**Issue by acoulson2000** [spulec/moto#1962]
I am attempting to do a relatively simple deployment of a lamda into Localstack using Serverless and believe I have narrowed the problem down to endpoints that aren't implemented by moto.

My serverless.yml defines just one simple function:
```functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: GET
```
This results in an error in localstack:
```2018-11-20T14:13:33:ERROR:localstack.services.generic_proxy: Error forwarding request: list index out of range Traceback (most recent call last):
  File "/home/acoulson/.local/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 215, in forward
    updated_response = self.proxy.update_listener.return_response(**kwargs)
  File "/home/acoulson/.local/lib/python2.7/site-packages/localstack/services/cloudformation/cloudformation_listener.py", line 216, in return_response
    template_deployer.deploy_template(template, req_data.get('StackName')[0])
  File "/home/acoulson/.local/lib/python2.7/site-packages/localstack/utils/cloudformation/template_deployer.py", line 513, in deploy_template
    resource['__details__'] = stack_resources[0]
IndexError: list index out of range
```
but turning on debugging, I see the following during the initial deployment of the generated stack:
```127.0.0.1 - - [20/Nov/2018 14:09:49] "GET /timeseries-service-dev-ServerlessDeploymentBucket-827A-Z6A-Z976390/serverless/timeseries-service/dev/1542744572309-2018-11-20T20:09:32.309Z/compiled-cloudformation-template.json HTTP/1.1" 200 -
No handlers could be found for logger "moto"
/home/acoulson/.local/lib/python2.7/site-packages/moto/cloudformation/parsing.py:269: UserWarning: Tried to parse AWS::ApiGateway::Resource but it's not supported by moto's CloudFormation implementation
"Tried to parse {0} but it's not supported by moto's CloudFormation implementation".format(resource_type))
/home/acoulson/.local/lib/python2.7/site-packages/moto/cloudformation/parsing.py:269: UserWarning: Tried to parse AWS::ApiGateway::Method but it's not supported by moto's CloudFormation implementation
"Tried to parse {0} but it's not supported by moto's CloudFormation implementation".format(resource_type))
/home/acoulson/.local/lib/python2.7/site-packages/moto/cloudformation/parsing.py:269: UserWarning: Tried to parse AWS::ApiGateway::Deployment but it's not supported by moto's CloudFormation implementation
"Tried to parse {0} but it's not supported by moto's CloudFormation implementation".format(resource_type))
/home/acoulson/.local/lib/python2.7/site-packages/moto/cloudformation/parsing.py:269: UserWarning: Tried to parse AWS::Lambda::Permission but it's not supported by moto's CloudFormation implementation
"Tried to parse {0} but it's not supported by moto's CloudFormation implementation".format(resource_type))
/home/acoulson/.local/lib/python2.7/site-packages/moto/cloudformation/parsing.py:269: UserWarning: Tried to parse AWS::ApiGateway::RestApi but it's not supported by moto's CloudFormation implementation
"Tried to parse {0} but it's not supported by moto's CloudFormation implementation".format(resource_type))
```
Stepping through localstack code execution (which I am not very adept at), I believe I am seeing evidence that lcocalstack is throwing the errors because these resources do not exist in the results returned by the mocked CloudFormation decribe-stack-resources, basically because they were not supported during creation.

For reference, my cloudformation-template-update-stack.json, which I think represents what serverless is trying to create within the CloudFormation implementation:
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket"
    },
    "HelloLogGroup": {
      "Type": "AWS::Logs::LogGroup",
      "Properties": {
        "LogGroupName": "/aws/lambda/timeseries-service-dev-hello"
      }
    },
    "IamRoleLambdaExecution": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              },
              "Action": [
                "sts:AssumeRole"
              ]
            }
          ]
        },
        "Policies": [
          {
            "PolicyName": {
              "Fn::Join": [
                "-",
                [
                  "dev",
                  "timeseries-service",
                  "lambda"
                ]
              ]
            },
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:CreateLogStream"
                  ],
                  "Resource": [
                    {
                      "Fn::Sub": "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/timeseries-service-dev-hello:*"
                    }
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:PutLogEvents"
                  ],
                  "Resource": [
                    {
                      "Fn::Sub": "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/timeseries-service-dev-hello:*:*"
                    }
                  ]
                }
              ]
            }
          }
        ],
        "Path": "/",
        "RoleName": {
          "Fn::Join": [
            "-",
            [
              "timeseries-service",
              "dev",
              "us-east-1",
              "lambdaRole"
            ]
          ]
        }
      }
    },
    "HelloLambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": {
            "Ref": "ServerlessDeploymentBucket"
          },
          "S3Key": "serverless/timeseries-service/dev/1542744572309-2018-11-20T20:09:32.309Z/timeseries-service.zip"
        },
        "FunctionName": "timeseries-service-dev-hello",
        "Handler": "handler.hello",
        "MemorySize": 1024,
        "Role": {
          "Fn::GetAtt": [
            "IamRoleLambdaExecution",
            "Arn"
          ]
        },
        "Runtime": "python2.7",
        "Timeout": 6
      },
      "DependsOn": [
        "HelloLogGroup",
        "IamRoleLambdaExecution"
      ]
    },
    "HelloLambdaVersionU88Ag36tX5K6Yuze3R8jedH2g7q2TTGuafWQxEnUmo": {
      "Type": "AWS::Lambda::Version",
      "DeletionPolicy": "Retain",
      "Properties": {
        "FunctionName": {
          "Ref": "HelloLambdaFunction"
        },
        "CodeSha256": "+pq+8RveA979z1DNF8UKnFGZfgE07blNyJGust5VJnU="
      }
    },
    "ApiGatewayRestApi": {
      "Type": "AWS::ApiGateway::RestApi",
      "Properties": {
        "Name": "dev-timeseries-service",
        "EndpointConfiguration": {
          "Types": [
            "EDGE"
          ]
        }
      }
    },
    "ApiGatewayResourceHello": {
      "Type": "AWS::ApiGateway::Resource",
      "Properties": {
        "ParentId": {
          "Fn::GetAtt": [
            "ApiGatewayRestApi",
            "RootResourceId"
          ]
        },
        "PathPart": "hello",
        "RestApiId": {
          "Ref": "ApiGatewayRestApi"
        }
      }
    },
    "ApiGatewayMethodHelloGet": {
      "Type": "AWS::ApiGateway::Method",
      "Properties": {
        "HttpMethod": "GET",
        "RequestParameters": {},
        "ResourceId": {
          "Ref": "ApiGatewayResourceHello"
        },
        "RestApiId": {
          "Ref": "ApiGatewayRestApi"
        },
        "ApiKeyRequired": false,
        "AuthorizationType": "NONE",
        "Integration": {
          "IntegrationHttpMethod": "POST",
          "Type": "AWS_PROXY",
          "Uri": {
            "Fn::Join": [
              "",
              [
                "arn:",
                {
                  "Ref": "AWS::Partition"
                },
                ":apigateway:",
                {
                  "Ref": "AWS::Region"
                },
                ":lambda:path/2015-03-31/functions/",
                {
                  "Fn::GetAtt": [
                    "HelloLambdaFunction",
                    "Arn"
                  ]
                },
                "/invocations"
              ]
            ]
          }
        },
        "MethodResponses": []
      }
    },
    "ApiGatewayDeployment1542744572805": {
      "Type": "AWS::ApiGateway::Deployment",
      "Properties": {
        "RestApiId": {
          "Ref": "ApiGatewayRestApi"
        },
        "StageName": "dev"
      },
      "DependsOn": [
        "ApiGatewayMethodHelloGet"
      ]
    },
    "HelloLambdaPermissionApiGateway": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "FunctionName": {
          "Fn::GetAtt": [
            "HelloLambdaFunction",
            "Arn"
          ]
        },
        "Action": "lambda:InvokeFunction",
        "Principal": {
          "Fn::Join": [
            "",
            [
              "apigateway.",
              {
                "Ref": "AWS::URLSuffix"
              }
            ]
          ]
        },
        "SourceArn": {
          "Fn::Join": [
            "",
            [
              "arn:",
              {
                "Ref": "AWS::Partition"
              },
              ":execute-api:",
              {
                "Ref": "AWS::Region"
              },
              ":",
              {
                "Ref": "AWS::AccountId"
              },
              ":",
              {
                "Ref": "ApiGatewayRestApi"
              },
              "/*/*"
            ]
          ]
        }
      }
    }
  },
  "Outputs": {
    "ServerlessDeploymentBucketName": {
      "Value": {
        "Ref": "ServerlessDeploymentBucket"
      }
    },
    "HelloLambdaFunctionQualifiedArn": {
      "Description": "Current Lambda function version",
      "Value": {
        "Ref": "HelloLambdaVersionU88Ag36tX5K6Yuze3R8jedH2g7q2TTGuafWQxEnUmo"
      }
    },
    "ServiceEndpoint": {
      "Description": "URL of the service endpoint",
      "Value": {
        "Fn::Join": [
          "",
          [
            "https://",
            {
              "Ref": "ApiGatewayRestApi"
            },
            ".execute-api.us-east-1.",
            {
              "Ref": "AWS::URLSuffix"
            },
            "/dev"
          ]
        ]
      }
    }
  }
}
```

**Comment by bblommers** [comment]
Creation of this templates is now supported against moto >= 1.3.17.dev266.
Feel free to open a new issue if there are other resources still unsupported/you need updates/deletes for any of these as well.
