### ISSUE TITLE
Error when listing objects with page size 0

### ISSUE THREAD

**Issue by dvh312** [spulec/moto#2020]
Error when running this command with Localstack. Empty bucket works fine.
`aws s3api list-objects --bucket=mybucket --endpoint-url http://localhost:4572 --page-size 0`

Ref:
https://github.com/spulec/moto/blob/850496f29a66b109b87f9d26d4c5b8456b3b195f/moto/s3/responses.py#L382

Error logs:
```
localstack                       | 127.0.0.1 - - [16/Jan/2019 00:50:16] "GET /mybucket?max-keys=0&encoding-type=url HTTP/1.1" 500 -
localstack                       | Error on request:
localstack                       | Traceback (most recent call last):
localstack                       | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
localstack                       | execute(self.server.app)
localstack                       | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
localstack                       | application_iter = app(environ, start_response)
localstack                       | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/server.py", line 101, in __call__
localstack                       | return backend_app(environ, start_response)
localstack                       | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
localstack                       | return self.wsgi_app(environ, start_response)
localstack                       | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
localstack                       | response = self.handle_exception(e)
localstack                       | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
localstack                       | reraise(exc_type, exc_value, tb)
localstack                       | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
localstack                       | response = self.full_dispatch_request()
localstack                       | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
localstack                       | rv = self.handle_user_exception(e)
localstack                       | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
localstack                       | reraise(exc_type, exc_value, tb)
localstack                       | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
localstack                       | rv = self.dispatch_request()
localstack                       | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
localstack                       | return self.view_functions[rule.endpoint](**req.view_args)
localstack                       | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/core/utils.py", line 140, in __call__
localstack                       | result = self.callback(request, request.url, {})
localstack                       | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 112, in ambiguous_response
localstack                       | return self.bucket_response(request, full_url, headers)
localstack                       | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 116, in bucket_response
localstack                       | response = self._bucket_response(request, full_url, headers)
localstack                       | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 155, in _bucket_response
localstack                       | return self._bucket_response_get(bucket_name, querystring, headers)
localstack                       | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 310, in _bucket_response_get
localstack                       | result_keys, is_truncated, _ = self._truncate_result(result_keys, max_keys)
localstack                       | File "/opt/code/localstack/.venv/lib/python2.7/site-packages/moto/s3/responses.py", line 370, in _truncate_result
localstack                       | next_continuation_token = result_keys[-1].name
localstack                       | IndexError: list index out of range
```

**Comment by dvh312** [comment]
Any update?

**Comment by spulec** [comment]
Thanks for opening. I'm setting this as a feature request for us to implement the logic to handle this.
