### ISSUE TITLE
Include "How to Run Tests Locally" as a part of the contributing documentation

### ISSUE THREAD

**Issue by drmorr0** [spulec/moto#2031]
I've been doing some development on moto and I don't really understand how to run the tests locally.  I've done the following:

`> virtualenv venv`
`> venv/bin/pip install -r requirements.txt`
`> venv/bin/pip install -r requirements-dev.txt`
`> venv/bin/nosetests` 

But when I run this, invariably there are a handful of tests that fail locally but pass on Travis.  Is there something else I need to do to reproduce the Travis environment?  Could we include that in the CONTRIBUTING.md documentation?

**Comment by triat** [comment]
Hey @drmorr0, 
I just pulled the master branch, installed everything from scratch and run the tests with `nosetests` as you did and got very few errors (3 to be exact) which look like timezone issue.

Maybe you can be more specific with the errors you have to help other people find the errors or guide you for the installation

**Comment by sahilkoladiya** [comment]
I get following error by running nosetests on master branch.

ERROR: Failure: MissingServiceIdError (The model being used for the service iot is missing the serviceId metadata property, which is required.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/skoladiy/moto/venv_moto/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/skoladiy/moto/venv_moto/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/skoladiy/moto/venv_moto/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/skoladiy/moto/tests/test_xray/test_xray_client.py", line 2, in <module>
    from moto import mock_xray_client, XRaySegment, mock_dynamodb2
  File "/Users/skoladiy/moto/moto/__init__.py", line 51, in <module>
    from .iot import mock_iot  # flake8: noqa
  File "/Users/skoladiy/moto/moto/iot/__init__.py", line 2, in <module>
    from .models import iot_backends
  File "/Users/skoladiy/moto/moto/iot/models.py", line 659, in <module>
    available_regions = boto3.session.Session().get_available_regions("iot")
  File "/Users/skoladiy/moto/venv_moto/lib/python2.7/site-packages/boto3/session.py", line 173, in get_available_regions
    allow_non_regional=allow_non_regional)
  File "/Users/skoladiy/moto/venv_moto/lib/python2.7/site-packages/botocore/session.py", line 883, in get_available_regions
    service_data = self.get_service_data(service_name)
  File "/Users/skoladiy/moto/venv_moto/lib/python2.7/site-packages/botocore/session.py", line 514, in get_service_data
    service_name=service_name, session=self)
  File "/Users/skoladiy/moto/venv_moto/lib/python2.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Users/skoladiy/moto/venv_moto/lib/python2.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/Users/skoladiy/moto/venv_moto/lib/python2.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/Users/skoladiy/moto/venv_moto/lib/python2.7/site-packages/botocore/handlers.py", line 285, in register_retries_for_service
    raise MissingServiceIdError(service_name=service_name)
MissingServiceIdError: The model being used for the service iot is missing the serviceId metadata property, which is required.

TOTAL                                       18709  12941    31%
----------------------------------------------------------------------
Ran 170 tests in 39.305s

FAILED (errors=170)


Can someone please help?

Thanks

**Comment by spulec** [comment]
Thanks; added with https://github.com/spulec/moto/commit/e77c4e3d09f39e6415fbbc86cfb98709480eb1a9

Let me know if there are still issues.
