### ISSUE TITLE
elbv2 : Can't Register "Lambda"-Type TargetGroups

### ISSUE THREAD

**Issue by tewner** [spulec/moto#2057]
Hi All!
I'm trying to mock TargetGroups with TargetType='lambda'
The create_target_group() API fails with:

ValueError: invalid literal for int() with base 10: 'None'

I see that it's trying to parse the "port" for the target group which isn't applicable to Lambda targets ( in addition to other parameters).

Is there any plan to add this support soon? Is there _already_ support and I'm doing something wrong?

Thank you!!!

Traceback (most recent call last):
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/moto/core/models.py", line 74, in wrapper
    result = func(*args, **kwargs)
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/moto/core/models.py", line 74, in wrapper
    result = func(*args, **kwargs)
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/moto/core/models.py", line 74, in wrapper
    result = func(*args, **kwargs)
  File "/Users/mike/Projects/LUA-Runtime/LS-Deploy/lsclient/tests/test_unittest.py", line 64, in test_deployLambdaListener
    TargetType='lambda'
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/endpoint.py", line 135, in _send_request
    request, operation_model, context)
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/endpoint.py", line 167, in _get_response
    request, operation_model)
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/endpoint.py", line 218, in _do_get_response
    response_dict, operation_model.output_shape)
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/parsers.py", line 242, in parse
    parsed = self._do_parse(response, shape)
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/parsers.py", line 509, in _do_parse
    parsed = self._parse_shape(shape, start)
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/parsers.py", line 302, in _parse_shape
    return handler(shape, node)
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/parsers.py", line 377, in _handle_structure
    member_shape, member_node)
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/parsers.py", line 302, in _parse_shape
    return handler(shape, node)
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/parsers.py", line 360, in _handle_list
    return super(BaseXMLResponseParser, self)._handle_list(shape, node)
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/parsers.py", line 310, in _handle_list
    parsed.append(self._parse_shape(member_shape, item))
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/parsers.py", line 302, in _parse_shape
    return handler(shape, node)
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/parsers.py", line 377, in _handle_structure
    member_shape, member_node)
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/parsers.py", line 302, in _parse_shape
    return handler(shape, node)
  File "/Users/localmikemike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/parsers.py", line 175, in _get_text_content
    return func(self, shape, text)
  File "/Users/mike/.virtualenvs/LS-Deploy/lib/python2.7/site-packages/botocore/parsers.py", line 466, in _handle_integer
    return int(text)
ValueError: invalid literal for int() with base 10: 'None'

**Comment by spulec** [comment]
I don't believe we support this today so I'm going to change this to a feature request.

Thanks for opening!

**Comment by tewner** [comment]
Thank you, @spulec !
