### ISSUE TITLE
Moto 1.3.7 ISSUE: Mock_iam: EntityAlreadyExistsException when running tests, unclosed socket warning

### ISSUE THREAD

**Issue by SalasSanchez** [spulec/moto#2115]
**This is an issue with moto==1.3.7, downgrading to 1.3.6 fixed the issue for me.**

I am running a test suite using mock_iam and the test I have testing a role creation throws this error when running the whole test suite:

botocore.errorfactory.EntityAlreadyExistsException: An error occurred (EntityAlreadyExists) when calling the CreateRole operation: Role with name testRole already exists.

The interesting thing is that I do NOT get any errors when I run each class separately, I only get these errors when I run the whole test suite (in /test/), which tests role creation on 3 different classes in separate files. The error is also followed by an 'unclosed socket' warning. 

Testing started at 10:19 ...
/Users/vdsdgfsdgsfgsf/bin/python3 "/Applications/PyCharm CE.app/Contents/helpers/pycharm/_jb_unittest_runner.py" --path /Users/dsfhgsfhr/test
Launching unittests with arguments python -m unittest discover -s /Users/shgfrwtwrthwrt/test -t /Users/ethgwrbrwt/test in /Users/tsrhbrtbrw/test
/Users/rthwrtrtr/miniconda3/lib/python3.7/unittest/case.py:643: ResourceWarning: unclosed <ssl.SSLSocket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.101.218.95', 62505), raddr=('54.239.22.207', 443)>
  outcome.errors.clear()

Error
Traceback (most recent call last):
  File "/Users/htrwbgtrtwh/miniconda3/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/hbrwrtwrt/miniconda3/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Users/trhrttbrgtwh/test/test_build_stage.py", line 77, in test_attach_build_stage_policies_to_role
    MaxSessionDuration=3600
  File "/Users/gbrsthrwt/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/sfgnbsghrnrwty/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.EntityAlreadyExistsException: An error occurred (EntityAlreadyExists) when calling the CreateRole operation: Role with name testRole already exists.

/Users/hbrstrw/miniconda3/lib/python3.7/unittest/case.py:643: ResourceWarning: unclosed <ssl.SSLSocket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.101.218.95', 62507), raddr=('54.239.22.207', 443)>
  outcome.errors.clear()

If I run each test class separately, it does NOT give me any errors. If I put all three test classes in on file and run that, it does NOT give me errors. It only fails if I try to run the three test classes in separate files in one run.

The tests that are failing are like this, one for each class. I am using the explicit mock.start() and mock.stop() 

    def test_attach_pipeline_policies_to_role(self):
        mock = mock_iam()
        mock.start()

        iam_client = boto3.client('iam')

        # create test role
        test_role_name = 'testRole'
        assume_role_doc = self.test_json.pipeline_assume_role_doc

# THIS IS THE CALL THAT THROWS THE ERROR       
 role = iam_client.create_role(
            RoleName=test_role_name,
            Path='/',
            AssumeRolePolicyDocument=json.dumps(assume_role_doc),
            MaxSessionDuration=3600
        )

        # set values
        self.pipeline.pipeline_role_name = test_role_name
        self.pipeline.role_arn = role['Role']['Arn']

        policies_in_role = iam_client.list_attached_role_policies(RoleName=test_role_name)['AttachedPolicies']

        policies_in_role_names = [item['PolicyName'] for item in policies_in_role]

        self.assertEqual(policies_in_role_names, [])

        # run attach_policies method
        self.pipeline._attach_pipeline_policy_to_role()

        new_policies_in_role = iam_client.list_attached_role_policies(RoleName=test_role_name)['AttachedPolicies']

        new_policies_in_role_names = [item['PolicyName'] for item in new_policies_in_role]

        self.assertNotEqual(policies_in_role_names, new_policies_in_role_names)

        mock.stop()

**Comment by mikegrima** [comment]
What happens if you make use of the decorator or the context manager: https://github.com/spulec/moto#context-manager ?

**Comment by SalasSanchez** [comment]
Same thing. :(

**Comment by spulec** [comment]
Is there a chance you are calling `.start()` twice accidentally or using other moto decorators? It looks like something isn't being reset properly between tests.

If you can trim down the tests + code to a minimal reproducible case, we can try to dig in more, but it will be challenging without the code to reproduce.

**Comment by eugenetaranov** [comment]
hello @spulec , I have hit the similar issue, hopefully the code below would help to reproduce:
`import unittest
import boto3
# from env_restart import ASG
from moto import mock_autoscaling

class AWSBase(object):
    def __init__(self, service, region_name):
        self.client = boto3.client(service, region_name=region_name)

class ASG(AWSBase):
    def __init__(self, region_name, name):
        service = 'autoscaling'
        super().__init__(service, region_name)
        self.name = name

@mock_autoscaling
class TestASG(unittest.TestCase):
    @classmethod
    @mock_autoscaling
    def setUpClass(cls):
        cls.region = 'us-east-1'
        cls.asg_name = 'test_asg'
        a = ASG('us-east-1', cls.region)
        a.client.create_launch_configuration(LaunchConfigurationName='test_launch_config')
        a.client.create_auto_scaling_group(AutoScalingGroupName=cls.asg_name, MinSize=1, MaxSize=1, AvailabilityZones=[
                                        'us-east-1'], LaunchConfigurationName='test_launch_config')

    def test_get_instances(self):
        a = ASG('us-east-1', self.asg_name)
        self.assertEqual(a.name, self.asg_name)
`

**Comment by mikegrima** [comment]
Remove this decorator:
```
---> @mock_autoscaling # Remove me
class TestASG(unittest.TestCase):
```

**Comment by eugenetaranov** [comment]
Thank you, just tried to remove @mock_autoscaling from the TestASG(), did not help:
`sys:1: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 0)>`

**Comment by mikegrima** [comment]
Please read: https://github.com/spulec/moto/blob/f4964f5f975db063d4f2df1d73f1384794f05666/README.md#very-important----recommended-usage (this will soon be merged in)

Also, pop a breakpoint in to verify if the mock is being established. (PyCharm is great for this)
