### ISSUE TITLE
ECR mock passing through commands to boto3

### ISSUE THREAD

**Issue by piercefreeman** [spulec/moto#2117]
I'm using `moto 1.3.7` and trying to mock out a simple command to create a repository in ECR.

```
from moto import mock_ecr
from boto3 import client, setup_default_session

@mock_ecr
def test_sync_ecr(self):
    setup_default_session()

    ecr = client("ecr", region_name="us-east-1")
    ecr.create_repository(repositoryName="Testing")
```

This code raises the following error, though, which seems to signify that the request is reaching `boto` and trying to actually execute that command remotely.  I shouldn't need credentials to mock the endpoints, plus a S3 mock works fine.

```
Traceback (most recent call last):
  File "/Users/pierce/.virtualenvs/project/lib/python3.7/site-packages/moto/core/models.py", line 74, in wrapper
    result = func(*args, **kwargs)
  File "/Users/pierce/globality/project/globality_ml_scripts/tests/test_sync.py", line 23, in test_sync_ecr
    ecr.create_repository(repositoryName="Testing")
  File "/Users/pierce/.virtualenvs/project/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/pierce/.virtualenvs/project/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ExpiredTokenException) when calling the CreateRepository operation: The security token included in the request is expired
```

I tried the workaround proposed in #1926 to reset the session via `setup_default_session` - but the same error occurs.

**Comment by piercefreeman** [comment]
Fixed by #2036.  Closing this ticket.
