### ISSUE TITLE
Filter dicts have not been implemented in Moto for 'Tag:Name' yet.

### ISSUE THREAD

**Issue by ghost** [spulec/moto#2122]
## issue description
 - I am using moto to mock a call to AWS ( ec2 client describe_instances) and am trying to filter results based on the "Name" tag. 

Code Example, this can be run as is with the error reproduced.
```
import boto3
from moto import mock_ec2

mock_ec2 = mock_ec2()
mock_ec2.start()

ec2 = boto3.resource('ec2')
ec2_client = boto3.client('ec2')

#Create an instance - looks like moto does not support multiple DeviceNames
ec2.create_instances(
    ImageId='ami-9b32e8e2',
    InstanceType='t2.small',
    MinCount=1,
    MaxCount=1,
    BlockDeviceMappings=[
        {
            'DeviceName': '/dev/xda1',
            'Ebs': {
                'VolumeSize': 50,
            }
        },
        {
            'DeviceName': '/dev/xda2',
            'Ebs': {
                'VolumeSize': 50,
            }
        }

    ])

# get instance id
instance_info = ec2_client.describe_instances()
for r in instance_info['Reservations']:
    for i in r['Instances']:
        instance_id = i['InstanceId']

# let's put in a tag in the instance, let's call it Name: stuffed chicken:
ec2.create_tags(
    Resources=[
        '{0}'.format(instance_id),
    ],
    Tags=[
        {
            'Key': 'Name',
            'Value': 'stuffed-chicken'
        },
    ],
)


#get the instance with the tag "Name:Stuffed-Chicken"
instance = ec2_client.describe_instances(
    Filters=[
    {
    'Name': 'Tag:Name',
    'Values':['stuffed-chicken']

}]
)

mock_ec2.stop()
```

Running this code produces the following error:
```
Traceback (most recent call last):
  File "boto3-list-instances.py", line 55, in <module>
    'Values':['stuffed-chicken']
  File "/home/dcoty/py27/local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/dcoty/py27/local/lib/python2.7/site-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/home/dcoty/py27/local/lib/python2.7/site-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/dcoty/py27/local/lib/python2.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/dcoty/py27/local/lib/python2.7/site-packages/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/home/dcoty/py27/local/lib/python2.7/site-packages/botocore/endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/home/dcoty/py27/local/lib/python2.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/dcoty/py27/local/lib/python2.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/home/dcoty/py27/local/lib/python2.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/home/dcoty/py27/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/home/dcoty/py27/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/home/dcoty/py27/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/dcoty/py27/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/home/dcoty/py27/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/home/dcoty/py27/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
NotImplementedError: Filter dicts have not been implemented in Moto for 'Tag:Name' yet. Feel free to open an issue at https://github.com/spulec/moto/issues
```

## Environment
- using python 2.7.12
- using moto 1.3.7
- using boto 2.49
- using boto3 1.9.87
- using botocore 1.12.87
- moto was installed using pip
-  using the moto raw mock, but the same issue happens using decorators and moto server as well.

## Expected result:
 - Expect to return the instance that has the key value pair specified, as it usually does with boto3(unmocked)

## What happens:
 - The error above in the traceback:
```
NotImplementedError: Filter dicts have not been implemented in Moto for 'Tag:Name' yet. Feel free to open an issue at https://github.com/spulec/moto/issues
```

## is this a duplicate issue?
 - i wasn't able to find anything on this exact error, but i found some related issues  above. 

## need more information?
 - let me know here, and i will do my best to give you any more info you need. 

Thanks!

**Comment by spulec** [comment]
Thanks; setting as a feature request.

**Comment by bblommers** [comment]
Hi @dacoty, your test case passes for me in the [latest version](https://pypi.org/project/moto/#history), as long as I use a lower-case ```tag:Name```. 
All examples in official documentation seem to use the lower case ```tag``` as well: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#ec2

Does that solve your problem?

**Comment by bblommers** [comment]
Going to close this due to a lack of response - let me know if it is still an issue though.
