### ISSUE TITLE
Autoscaling: describe_auto_scaling_instances() fails after attaching a moto instance with attach_instances() when using moto_server

### ISSUE THREAD

**Issue by jmeichle** [spulec/moto#2123]
## Issue Description

When using moto_server (and possibly the decorators), calls to autoscaling describe_auto_scaling_instances() fail with a 500 after calling attach_instances() for a moto EC2 instance into a moto ASG.

## Steps to reproduce

Running moto server this way:

```
moto_server -H 0.0.0.0 -p 3000
```

And then using the following:

```
import boto3
session = boto3.Session()
asg_client = session.client(service_name='autoscaling', region_name='us-east-1', endpoint_url='http://localhost:3000/')
ec2_client = session.client(service_name='ec2', region_name='us-east-1', endpoint_url='http://localhost:3000/')

kwargs = {
    'KeyName': 'foobar',
    'ImageId': 'ami-pytest',
    'MinCount': 1,
    'MaxCount': 1,
    'InstanceType': 'c4.2xlarge',
    'TagSpecifications': [
        {
            'ResourceType': 'instance',
            'Tags': [
                {
                    'Key': 'key',
                    'Value': 'val'
                }
            ]
        },
    ]
}
fake_instance = ec2_client.run_instances(**kwargs)['Instances'][0]
fake_lc = asg_client.create_launch_configuration(
    LaunchConfigurationName='foobar',
    ImageId='ami-pytest',
    KeyName='foobar',
)
fake_asg = asg_client.create_auto_scaling_group(
    AutoScalingGroupName='test-cluster',
    LaunchConfigurationName='foobar',
    MinSize=0,
    MaxSize=1,
    AvailabilityZones=[fake_instance['Placement']['AvailabilityZone']]
)
```

This works great and I can call `asg_client.describe_auto_scaling_groups()` and `asg_client.describe_auto_scaling_instances()` without any problems.

If I attach the fake instance to the ASG via:

```
In [4]: asg_client.attach_instances(
   ...:     InstanceIds=[
   ...:         fake_instance['InstanceId'],
   ...:     ],
   ...:     AutoScalingGroupName='test-cluster'
   ...: )
Out[4]: 
{'ResponseMetadata': {'HTTPHeaders': {'content-length': '221',
   'content-type': 'text/html; charset=utf-8',
   'date': 'Thu, 21 Mar 2019 17:59:56 GMT',
   'server': 'amazon.com',
   'x-amz-crc32': '1138981672',
   'x-amzn-requestid': 'FYD91BZH2BETNY0UFB7D9HNKXG7PVFE1JFEYW4J0USJKS410AWGA'},
  'HTTPStatusCode': 200,
  'RequestId': None,
  'RetryAttempts': 0}}
```

I get a valid response, but any future calls for `asg_client.describe_auto_scaling_instances()` raise with the moto server logging: 

```
Error on request:
Traceback (most recent call last):
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/moto/server.py", line 101, in __call__
    return backend_app(environ, start_response)
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/moto/core/utils.py", line 140, in __call__
    result = self.callback(request, request.url, {})
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/moto/core/responses.py", line 117, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/moto/core/responses.py", line 200, in _dispatch
    return self.call_action()
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/moto/core/responses.py", line 274, in call_action
    response = method()
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/moto/autoscaling/responses.py", line 224, in describe_auto_scaling_instances
    return template.render(instance_states=instance_states)
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 7, in top-level template code
    
  File "/home/jmeichle/.pyenv/versions/2.7.10/envs/venv/lib/python2.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'moto.ec2.models.Instance object' has no attribute 'autoscaling_group'
```

with boto3 client receving a HTTP 500 with an html payload.

## Expected Result

Future calls to describe_auto_scaling_instances() would return the instances associated with the auto scaling groups and not a 500

## Environment

```
jmeichle@jmeichle-XPS-15-9570:~$ pip freeze 2>/dev/null | egrep 'moto|boto'
boto==2.49.0
boto3==1.9.73
botocore==1.12.90
moto==1.3.7
jmeichle@jmeichle-XPS-15-9570:~$ python --version
Python 2.7.10
```

## Is this Duplicate?

I searched for describe_auto_scaling_instances as well as the error specifics and nothing came up

## Extra information

Let me know how I can help here. I might be able to look into this myself but am new to the moto codebase.

**Comment by jmeichle** [comment]
Same for usage with the decorator, via this test script:


```
import boto3
from moto import mock_autoscaling, mock_ec2

@mock_ec2
@mock_autoscaling
def test_bug():
    session = boto3.Session()
    print "Creating clients"
    asg_client = session.client(service_name='autoscaling', region_name='us-east-1')
    ec2_client = session.client(service_name='ec2', region_name='us-east-1')

    kwargs = {
        'KeyName': 'foobar',
        'ImageId': 'ami-pytest',
        'MinCount': 1,
        'MaxCount': 1,
        'InstanceType': 'c4.2xlarge',
        'TagSpecifications': [
            {
                'ResourceType': 'instance',
                'Tags': [
                    {
                        'Key': 'key',
                        'Value': 'val'
                    }
                ]
            },
        ]
    }
    print "Creating an instance"
    fake_instance = ec2_client.run_instances(**kwargs)['Instances'][0]
    print "Creating a launch config"
    fake_lc = asg_client.create_launch_configuration(
        LaunchConfigurationName='foobar',
        ImageId='ami-pytest',
        KeyName='foobar',
    )
    print "Creating an ASG"
    fake_asg = asg_client.create_auto_scaling_group(
        AutoScalingGroupName='test-cluster',
        LaunchConfigurationName='foobar',
        MinSize=0,
        MaxSize=1,
        AvailabilityZones=[fake_instance['Placement']['AvailabilityZone']]
    )
    print "Attaching the instance"
    asg_client.attach_instances(
        InstanceIds=[
            fake_instance['InstanceId'],
        ],
         AutoScalingGroupName='test-cluster'
    )
    print "Describing ASG instances"
    print asg_client.describe_auto_scaling_instances()
```

having this output:

```
jmeichle@jmeichle-XPS-15-9570:~$ pytest -vs moto_bug.py 
============================================================================================================= test session starts =============================================================================================================
platform linux2 -- Python 2.7.10, pytest-3.2.3, py-1.7.0, pluggy-0.4.0 -- /home/jmeichle/.pyenv/versions/2.7.10/bin/python2.7
cachedir: .cache
rootdir: /home/jmeichle, inifile:
plugins: testinfra-1.10.0, cov-2.5.1
collected 1 item                                                                                                                                                                                                                               

moto_bug.py::test_bug Creating clients
Creating an instance
Creating a launch config
Creating an ASG
Attaching the instance
Describing ASG instances
FAILED

================================================================================================================== FAILURES ===================================================================================================================
__________________________________________________________________________________________________________________ test_bug ___________________________________________________________________________________________________________________

    @mock_ec2
    @mock_autoscaling
    def test_bug():
        session = boto3.Session()
        print "Creating clients"
        asg_client = session.client(service_name='autoscaling', region_name='us-east-1')
        ec2_client = session.client(service_name='ec2', region_name='us-east-1')
    
        kwargs = {
            'KeyName': 'foobar',
            'ImageId': 'ami-pytest',
            'MinCount': 1,
            'MaxCount': 1,
            'InstanceType': 'c4.2xlarge',
            'TagSpecifications': [
                {
                    'ResourceType': 'instance',
                    'Tags': [
                        {
                            'Key': 'key',
                            'Value': 'val'
                        }
                    ]
                },
            ]
        }
        print "Creating an instance"
        fake_instance = ec2_client.run_instances(**kwargs)['Instances'][0]
        print "Creating a launch config"
        fake_lc = asg_client.create_launch_configuration(
            LaunchConfigurationName='foobar',
            ImageId='ami-pytest',
            KeyName='foobar',
        )
        print "Creating an ASG"
        fake_asg = asg_client.create_auto_scaling_group(
            AutoScalingGroupName='test-cluster',
            LaunchConfigurationName='foobar',
            MinSize=0,
            MaxSize=1,
            AvailabilityZones=[fake_instance['Placement']['AvailabilityZone']]
        )
        print "Attaching the instance"
        asg_client.attach_instances(
            InstanceIds=[
                fake_instance['InstanceId'],
            ],
             AutoScalingGroupName='test-cluster'
        )
        print "Describing ASG instances"
>       print asg_client.describe_auto_scaling_instances()

moto_bug.py:54: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/client.py:357: in _api_call
    return self._make_api_call(operation_name, kwargs)
.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/client.py:648: in _make_api_call
    operation_model, request_dict, request_context)
.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/client.py:667: in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/endpoint.py:102: in make_request
    return self._send_request(request_dict, operation_model)
.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/endpoint.py:137: in _send_request
    success_response, exception):
.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/endpoint.py:231: in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/hooks.py:356: in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/hooks.py:228: in emit
    return self._emit(event_name, kwargs)
.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/hooks.py:211: in _emit
    response = handler(**kwargs)
.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/retryhandler.py:183: in __call__
    if self._checker(attempts, response, caught_exception):
.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/retryhandler.py:251: in __call__
    caught_exception)
.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/retryhandler.py:269: in _should_retry
    return self._checker(attempt_number, response, caught_exception)
.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/retryhandler.py:317: in __call__
    caught_exception)
.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/retryhandler.py:223: in __call__
    attempt_number, caught_exception)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <botocore.retryhandler.ExceptionRaiser object at 0x7f09ed1c8290>, attempt_number = 1, caught_exception = UndefinedError("'moto.ec2.models.Instance object' has no attribute 'autoscaling_group'",)

    def _check_caught_exception(self, attempt_number, caught_exception):
        # This is implementation specific, but this class is useful by
        # coordinating with the MaxAttemptsDecorator.
        # The MaxAttemptsDecorator has a list of exceptions it should catch
        # and retry, but something needs to come along and actually raise the
        # caught_exception.  That's what this class is being used for.  If
        # the MaxAttemptsDecorator is not interested in retrying the exception
        # then this exception just propogates out past the retry code.
>       raise caught_exception
E       UndefinedError: 'moto.ec2.models.Instance object' has no attribute 'autoscaling_group'

.pyenv/versions/2.7.10/lib/python2.7/site-packages/botocore/retryhandler.py:359: UndefinedError
========================================================================================================== 1 failed in 1.29 seconds ===========================================================================================================
```

**Comment by spulec** [comment]
Thanks for opening. It looks like we haven't implemented all of the code yet so that attaching instances will work. I'm setting this as a feature request.
