### ISSUE TITLE
UnicodeDecodeError on presigned post url's with non-unicode data

### ISSUE THREAD

**Issue by ignaloidas** [spulec/moto#2175]
```import unittest

import boto3
import requests
from moto import mock_s3


@mock_s3
class BuggyTest(unittest.TestCase):
    def test_buggy(self):
        client = boto3.client('s3', aws_access_key_id="ACCESS_KEY", aws_secret_access_key="SECRET_KEY")

        obj = client.generate_presigned_post(
            Bucket="testing-bucket", Key="key", Conditions=[['eq', '$Content-Type', "application/zip"]], ExpiresIn=100
        )

        form_data = obj["fields"]
        form_data['Content-Type'] = 'application/zip'

        requests.post(obj["url"], data=form_data, files={'file': ('test-file', b"\x90\x12\x34\x89")})
```
When this code is run, this error occurs:
```
Traceback (most recent call last):
  File "test_bug.py", line 23, in <module>
    BuggyTest().test_buggy()
  File "/<python-path>/site-packages/moto/core/models.py", line 74, in wrapper
    result = func(*args, **kwargs)
  File "test_bug.py", line 20, in test_buggy
    requests.post(obj["url"], data=form_data, files={'file': ('test-file', b"\x90\x12\x34\x89")})
  File "/<python-path>/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/<python-path>/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/<python-path>/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/<python-path>/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/<python-path>/site-packages/responses.py", line 626, in unbound_on_send
    return self._on_request(adapter, request, *a, **kwargs)
  File "/<python-path>/site-packages/responses.py", line 604, in _on_request
    response = adapter.build_response(request, match.get_response(request))
  File "/<python-path>/site-packages/moto/core/models.py", line 151, in get_response
    result = self.callback(request)
  File "/<python-path>/site-packages/moto/core/utils.py", line 173, in __call__
    result = self.callback(request, request.url, request.headers)
  File "/<python-path>/site-packages/moto/s3/responses.py", line 116, in bucket_response
    response = self._bucket_response(request, full_url, headers)
  File "/<python-path>/site-packages/moto/s3/responses.py", line 149, in _bucket_response
    body = body.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 802: invalid start byte
```
Seems like body is decoded where it is not needed to be decoded.

I'm using moto 1.3.8 boto3 1.9.138 botocore 1.12.138

**Comment by ignaloidas** [comment]
Note: this is not the only place that the decoding is done. It is also done here https://github.com/spulec/moto/blob/master/moto/s3/responses.py#L526 where it incorrectly assumes it is from HTTPretty and tries to decode it. It should be properly decoded from form multi-type encoding. This is the last bug that stops us from using this library, fixes would be appreciated.

**Comment by spulec** [comment]
Thanks; setting this as a feature request to work in either way.

**Comment by bblommers** [comment]
@ignaloidas I'm unable to reproduce this on master, so I'm wondering if this has been fixed in the meantime.
Are you able to reproduce this with the latest dev-release? (1.3.17.dev245)

**Comment by ignaloidas** [comment]
@bblommers looks like this has been fixed as I can no longer reproduce.

**Comment by bblommers** [comment]
Thanks for letting us know @ignaloidas!
