### ISSUE TITLE
Batch.Client.describe_jobs(...) fails for not-yet-started jobs

### ISSUE THREAD

**Issue by mztechins** [spulec/moto#2201]
## How to reproduce

Pseudocode:
```python
boto3.client('batch', region_name=...)
resp = batch_client.submit_job(...)
job_id = resp['jobId']
resp = batch_client.describe_jobs(jobs=[job_id])
```
or just un the [tests.test_batch.test_batch.test_submit_job](https://github.com/spulec/moto/blob/8cb4db1896521af99ff295b028f604c6ab599401/tests/test_batch/test_batch.py#L652) test.
OS Name:	Microsoft Windows 10 Pro

## Expected behavior

resp holds a valid job jescription for given job_id.

## Actual results

It crashes with:
```
Error
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Program Files\Python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "E:\opensource\moto\venv\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "E:\opensource\moto\moto\core\models.py", line 80, in wrapper
    result = func(*args, **kwargs)
  File "E:\opensource\moto\moto\core\models.py", line 80, in wrapper
    result = func(*args, **kwargs)
  File "E:\opensource\moto\moto\core\models.py", line 80, in wrapper
    result = func(*args, **kwargs)
  [Previous line repeated 2 more times]
  File "E:\opensource\moto\tests\test_batch\test_batch.py", line 700, in test_submit_job
    resp = batch_client.describe_jobs(jobs=[job_id])
  File "E:\opensource\moto\venv\lib\site-packages\botocore\client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "E:\opensource\moto\venv\lib\site-packages\botocore\client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "E:\opensource\moto\venv\lib\site-packages\botocore\client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "E:\opensource\moto\venv\lib\site-packages\botocore\endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "E:\opensource\moto\venv\lib\site-packages\botocore\endpoint.py", line 137, in _send_request
    success_response, exception):
  File "E:\opensource\moto\venv\lib\site-packages\botocore\endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "E:\opensource\moto\venv\lib\site-packages\botocore\hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "E:\opensource\moto\venv\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "E:\opensource\moto\venv\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "E:\opensource\moto\venv\lib\site-packages\botocore\retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "E:\opensource\moto\venv\lib\site-packages\botocore\retryhandler.py", line 251, in __call__
    caught_exception)
  File "E:\opensource\moto\venv\lib\site-packages\botocore\retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "E:\opensource\moto\venv\lib\site-packages\botocore\retryhandler.py", line 317, in __call__
    caught_exception)
  File "E:\opensource\moto\venv\lib\site-packages\botocore\retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "E:\opensource\moto\venv\lib\site-packages\botocore\retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "E:\opensource\moto\venv\lib\site-packages\botocore\endpoint.py", line 197, in _do_get_response
    responses = self._event_emitter.emit(event_name, request=request)
  File "E:\opensource\moto\venv\lib\site-packages\botocore\hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "E:\opensource\moto\venv\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "E:\opensource\moto\venv\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "E:\opensource\moto\moto\core\models.py", line 298, in __call__
    status, headers, body = response_callback(request, request.url, request.headers)
  File "E:\opensource\moto\moto\core\responses.py", line 117, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "E:\opensource\moto\moto\core\responses.py", line 200, in _dispatch
    return self.call_action()
  File "E:\opensource\moto\moto\core\responses.py", line 274, in call_action
    response = method()
  File "E:\opensource\moto\moto\batch\responses.py", line 263, in describejobs
    return json.dumps({'jobs': self.batch_backend.describe_jobs(jobs)})
  File "E:\opensource\moto\moto\batch\models.py", line 1015, in describe_jobs
    result.append(job.describe())
  File "E:\opensource\moto\moto\batch\models.py", line 292, in describe
    'startedAt': datetime2int(self.job_started_at),
  File "E:\opensource\moto\moto\batch\models.py", line 35, in datetime2int
    return int(time.mktime(date.timetuple()))
Exception: mktime argument out of range
```

## Software configuration
moto: master branch at 8cb4db1896521af99ff295b028f604c6ab599401, cloned from github
boto 2.49.0
boto3 1.9.148
botocore 1.12.148

**Comment by mztechins** [comment]
I'm working on it myself...
