### ISSUE TITLE
Error with Nat Gateway AllocationId and Cloudformation

### ISSUE THREAD

**Issue by lobsterdore** [spulec/moto#2217]
# The problem

I've encountered an issue testing NAT Gateways via Cloudformation and Moto server, I am trying to test this CF template here, however it seems that Moto does not recognise the AllocationId property of the NAT Gateway:

```YAML
---

Description: NAT Gateway setup
AWSTemplateFormatVersion: 2010-09-09

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'false'
      EnableDnsHostnames: 'false'
      InstanceTenancy:
        Ref: AWS::NoValue

  SubnetPublic:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs:
              Ref: AWS::Region
      CidrBlock: 10.1.0.0/16
      MapPublicIpOnLaunch: true

  NatEip:
    Type: AWS::EC2::EIP

  Nat:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - NatEip
          - AllocationId
      SubnetId:
        Ref: SubnetPublic
```
## Expected result

A successfully created CF stack with a NAT Gateway.

## Actual result

```
127.0.0.1 - - [23/May/2019 08:18:03] "POST / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File ".venv/lib/python2.7/site-packages/werkzeug/serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File ".venv/lib/python2.7/site-packages/werkzeug/serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File ".venv/lib/python2.7/site-packages/moto/server.py", line 104, in __call__
    return backend_app(environ, start_response)
  File ".venv/lib/python2.7/site-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File ".venv/lib/python2.7/site-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File ".venv/lib/python2.7/site-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File ".venv/lib/python2.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File ".venv/lib/python2.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File ".venv/lib/python2.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File ".venv/lib/python2.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File ".venv/lib/python2.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File ".venv/lib/python2.7/site-packages/moto/core/utils.py", line 140, in __call__
    result = self.callback(request, request.url, {})
  File ".venv/lib/python2.7/site-packages/moto/core/responses.py", line 117, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File ".venv/lib/python2.7/site-packages/moto/core/responses.py", line 200, in _dispatch
    return self.call_action()
  File ".venv/lib/python2.7/site-packages/moto/core/responses.py", line 274, in call_action
    response = method()
  File ".venv/lib/python2.7/site-packages/moto/cloudformation/responses.py", line 68, in create_stack
    role_arn=role_arn,
  File ".venv/lib/python2.7/site-packages/moto/cloudformation/models.py", line 414, in create_stack
    create_change_set=create_change_set,
  File ".venv/lib/python2.7/site-packages/moto/cloudformation/models.py", line 187, in __init__
    self.resource_map = self._create_resource_map()
  File ".venv/lib/python2.7/site-packages/moto/cloudformation/models.py", line 195, in _create_resource_map
    resource_map.create()
  File ".venv/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 463, in create
    if isinstance(self[resource], ec2_models.TaggedEC2Resource):
  File ".venv/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 403, in __getitem__
    resource_logical_id, resource_json, self, self._region_name)
  File ".venv/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 299, in parse_and_create_resource
    resource_name, resource_json, region_name)
  File ".venv/lib/python2.7/site-packages/moto/ec2/models.py", line 3892, in create_from_cloudformation_json
    cloudformation_json['Properties']['AllocationId'],
KeyError: u'AllocationId'
```

## To reproduce this issue

* Install Moto server into a virtualenv - ```virtualenv .venv && .venv/bin/pip install "moto[server]"```
* Run Moto cloudformation server on the command line with the default port - ```.venv/bin/moto_server cloudformation```
* Create a stack using the template above - ```AWS_ACCESS_KEY_ID=foobar AWS_DEFAULT_REGION=foobar AWS_SECRET_ACCESS_KEY=foobar aws --endpoint-url http://localhost:5000 cloudformation create-stack --stack-name myteststack --template-body file://vpc.yml --region eu-west-1```

## Moto version

1.3.8.

**Comment by lobsterdore** [comment]
Additionally it seems that there is an issue with getting AllocationId's from EIPs as well via Cloudformation and Moto Server:

```YAML
---

Description: NAT EIP setup
AWSTemplateFormatVersion: 2010-09-09

Resources:

  NatEip:
    Type: AWS::EC2::EIP

Outputs:
  NatEipAllocationId:
    Description: Nat EIP Allocation Id
    Value:
      Fn::GetAtt:
        - NatEip
        - AllocationId
```

Applied using the steps above like so - ```AWS_ACCESS_KEY_ID=foobar AWS_DEFAULT_REGION=foobar AWS_SECRET_ACCESS_KEY=foobar aws --endpoint-url http://localhost:5000 cloudformation create-stack --stack-name myeipstack --template-body file://eip.yml --region eu-west-1```

Error output:

```
127.0.0.1 - - [23/May/2019 08:40:05] "POST / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/werkzeug/serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/werkzeug/serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/moto/server.py", line 104, in __call__
    return backend_app(environ, start_response)
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/moto/core/utils.py", line 140, in __call__
    result = self.callback(request, request.url, {})
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/moto/core/responses.py", line 117, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/moto/core/responses.py", line 200, in _dispatch
    return self.call_action()
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/moto/core/responses.py", line 274, in call_action
    response = method()
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/moto/cloudformation/responses.py", line 68, in create_stack
    role_arn=role_arn,
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/moto/cloudformation/models.py", line 414, in create_stack
    create_change_set=create_change_set,
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/moto/cloudformation/models.py", line 188, in __init__
    self.output_map = self._create_output_map()
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/moto/cloudformation/models.py", line 200, in _create_output_map
    output_map.create()
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 613, in create
    self[output]
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 586, in __getitem__
    output_logical_id, output_json, self._resource_map)
  File "/Users/david.reedfrancis/workspace/sansible/moto_server_venv/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 361, in parse_output
    output.value = clean_json(output_json['Value'], resources_map)
KeyError: u'Value'
```

**Comment by lobsterdore** [comment]
Ah so actually it seems that allocation ID is required, and the actual error here is that ```Fn::GetAtt: - NatEip - AllocationId``` seems to return None.

**Comment by spulec** [comment]
It looks like we haven't implemented `get_cfn_attribute` for the `NatGateway` model yet. I'm going to set this as a feature request. Thanks!

**Comment by lobsterdore** [comment]
@spulec thanks for the response, this will allow me to have some tests for a chunk code that is currently untested.

**Comment by lobsterdore** [comment]
@spulec just digging a bit further, the actual error is with the EIP resource, it's the output bit where I try to grab the AllocationID that fails in this template:

```YAML
---

Description: NAT EIP setup
AWSTemplateFormatVersion: 2010-09-09

Resources:

  NatEip:
    Type: AWS::EC2::EIP

Outputs:
  NatEipAllocationId:
    Description: Nat EIP Allocation Id
    Value:
      Fn::GetAtt:
        - NatEip
        - AllocationId
```

It looks like ```get_cfn_attribute``` has been defined for the ```ElasticAddress``` model so I am not sure why it's not working - https://github.com/spulec/moto/blob/2a5f7e15a7bc748c1148dae922cb1a9f8672dcbe/moto/ec2/models.py#L3247

**Comment by lobsterdore** [comment]
@spulec OK turns out this actually isn't a bug with Moto at all, turns out that I need to specify a domain of VPC for the EIP, then I get an allocation ID:

```YAML
---

Description: NAT EIP setup
AWSTemplateFormatVersion: 2010-09-09

Resources:

  NatEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: "vpc"

Outputs:
  NatEipAllocationId:
    Description: Nat EIP Allocation Id
    Value:
      Fn::GetAtt:
        - NatEip
        - AllocationId
```

The Cloudformation docs state this as being the case so Moto is correct here.

**Comment by spulec** [comment]
Ah, great to hear. Thanks for following up!
