### ISSUE TITLE
AWS Lambdas not updating from cloudformation properly

### ISSUE THREAD

**Issue by mikesarfaty** [spulec/moto#2317]
## Reporting Bugs

# Issue
I'm deploying lambdas with serverless, and localstack, and the issue we are running into is that the old lambdas are not being deleted which I believe is leading to the newly created lambdas not being able to be created.

Example: I have a serverless application called my-app, I deploy to localstack and the first time it works perfectly. I make changes, and deploy again, and the function is still only the function from the first deploy.

There is some traceback, but from what I've read it may not be an issue. 

# Traceback
```
2019-07-16T11:51:46:ERROR:werkzeug: Error on request:
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 303, in run_wsgi
execute(self.server.app)
File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 291, in execute
application_iter = app(environ, start_response)
File "/usr/local/lib/python2.7/site-packages/moto/server.py", line 104, in __call__
return backend_app(environ, start_response)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python2.7/site-packages/moto/core/utils.py", line 140, in __call__
result = self.callback(request, request.url, {})
File "/usr/local/lib/python2.7/site-packages/moto/core/responses.py", line 117, in dispatch
return cls()._dispatch(*args, **kwargs)
File "/usr/local/lib/python2.7/site-packages/moto/core/responses.py", line 200, in _dispatch
return self.call_action()
File "/usr/local/lib/python2.7/site-packages/moto/core/responses.py", line 274, in call_action
response = method()
File "/usr/local/lib/python2.7/site-packages/moto/cloudformation/responses.py", line 294, in update_stack
tags=tags,
File "/usr/local/lib/python2.7/site-packages/moto/cloudformation/models.py", line 330, in update_stack
stack.update(template, role_arn, parameters=parameters, tags=tags)
File "/usr/local/lib/python2.7/site-packages/moto/cloudformation/models.py", line 112, in update
self.resource_map.update(self.template_dict, parameters)
File "/usr/local/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 526, in update
resource_name, resource_json, self, self._region_name)
File "/usr/local/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 323, in parse_and_delete_resource
resource_class.delete_from_cloudformation_json(
AttributeError: type object 'LambdaVersion' has no attribute 'delete_from_cloudformation_json'
```

I added in a temporary dummy method, to fix that, and then I got almost the same error with a similar traceback, with the error 
```
...
File "/usr/local/lib/python2.7/site-packages/moto/cloudformation/models.py", line 330, in update_stack
stack.update(template, role_arn, parameters=parameters, tags=tags)
File "/usr/local/lib/python2.7/site-packages/moto/cloudformation/models.py", line 112, in update
self.resource_map.update(self.template_dict, parameters)
File "/usr/local/lib/python2.7/site-packages/moto/cloudformation/parsing.py", line 545, in update
raise last_exception
AttributeError: type object 'LambdaFunction' has no attribute 'update_from_cloudformation_json'
```

**Comment by spulec** [comment]
Thanks for opening; setting this as a feature request.

**Comment by chrisandrews7** [comment]
https://github.com/spulec/moto/issues/793
