### ISSUE TITLE
@mock_dynamodb2 update_item with AttributeUpdates doesn't work for list items

### ISSUE THREAD

**Issue by swen128** [spulec/moto#2328]
Similar to https://github.com/spulec/moto/issues/1823

When I try to update a mocked DynamoDB item using the `update_item` method with the `Attribute Updates` argument, it fails with `TypeError: unhashable type: 'dict'`.

## Minimal code to reproduce the problem

```python
import boto3
from moto import mock_dynamodb2


@mock_dynamodb2
def test_update_item_with_list():
    dynamodb = boto3.resource('dynamodb', region_name='us-east-1')

    dynamodb.create_table(
        TableName='Table',
        KeySchema=[
            {
                'AttributeName': 'key',
                'KeyType': 'HASH'
            }
        ],
        AttributeDefinitions=[
            {
                'AttributeName': 'key',
                'AttributeType': 'S'
            },
        ],
        ProvisionedThroughput={
            'ReadCapacityUnits': 1,
            'WriteCapacityUnits': 1
        }
    )
    table = dynamodb.Table('Table')
    table.update_item(
        Key={'key': 'the-key'},
        AttributeUpdates={
            'list': {'Value': [1, 2], 'Action': 'PUT'}
        }
    )


if __name__ == '__main__':
    test_update_item_with_list()
```

## Traceback

```
Traceback (most recent call last):
  File "tests/test_moto.py", line 41, in <module>
    test_update_item_with_list()
  File "{my_project}/venv/lib/python3.7/site-packages/moto/core/models.py", line 80, in wrapper
    result = func(*args, **kwargs)
  File "tests/test_moto.py", line 37, in test_update_item_with_list
    return table.get_item(Key={'key': 'the-key'})
  File "{my_project}/venv/lib/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "{my_project}/venv/lib/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "{my_project}/venv/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "{my_project}/venv/lib/python3.7/site-packages/botocore/client.py", line 655, in _make_api_call
    model=operation_model, context=request_context
  File "{my_project}/venv/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "{my_project}/venv/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "{my_project}/venv/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "{my_project}/venv/lib/python3.7/site-packages/boto3/dynamodb/transform.py", line 204, in inject_attribute_value_output
    'AttributeValue'
  File "{my_project}/venv/lib/python3.7/site-packages/boto3/dynamodb/transform.py", line 254, in transform
    model, params, transformation, target_shape)
  File "{my_project}/venv/lib/python3.7/site-packages/boto3/dynamodb/transform.py", line 261, in _transform_parameters
    model, params, transformation, target_shape)
  File "{my_project}/venv/lib/python3.7/site-packages/boto3/dynamodb/transform.py", line 276, in _transform_structure
    target_shape)
  File "{my_project}/venv/lib/python3.7/site-packages/boto3/dynamodb/transform.py", line 261, in _transform_parameters
    model, params, transformation, target_shape)
  File "{my_project}/venv/lib/python3.7/site-packages/boto3/dynamodb/transform.py", line 285, in _transform_map
    params[key] = transformation(value)
  File "{my_project}/venv/lib/python3.7/site-packages/boto3/dynamodb/types.py", line 268, in deserialize
    return deserializer(value[dynamodb_type])
  File "{my_project}/venv/lib/python3.7/site-packages/boto3/dynamodb/types.py", line 289, in _deserialize_ss
    return set(map(self._deserialize_s, value))
TypeError: unhashable type: 'dict'
```

## Package versions

```
boto==2.49.0
boto3==1.9.189
botocore==1.12.189
moto==1.3.13
```

**Comment by spulec** [comment]
Closed with https://github.com/spulec/moto/pull/2329
