### ISSUE TITLE
AttributeError: module 'responses' has no attribute 'GET'

### ISSUE THREAD

**Issue by gtalarico** [spulec/moto#2348]
Couldn't find dup on issues, apologies if I missed it.

```
# repro.py
import moto

# moto==1.3.13
# boto3==1.9.199
# Python 3.7.3

with moto.mock_s3():
    import boto3

    s3 = boto3.client("s3")
    s3.put_object(Bucket="xxx", Key="xxx", Body="xxx".encode())
```

```
$ python repro.py
Traceback (most recent call last):
  File "repro.py", line 1, in <module>
    import moto
  File "/Users/repos/test/.venv/lib/python3.7/site-packages/moto/__init__.py", line 8, in <module>
    from .acm import mock_acm  # flake8: noqa
  File "/Users/repos/test/.venv/lib/python3.7/site-packages/moto/acm/__init__.py", line 2, in <module>
    from .models import acm_backends
  File "/Users/repos/test/.venv/lib/python3.7/site-packages/moto/acm/models.py", line 6, in <module>
    from moto.core import BaseBackend, BaseModel
  File "/Users/repos/test/.venv/lib/python3.7/site-packages/moto/core/__init__.py", line 2, in <module>
    from .models import BaseModel, BaseBackend, moto_api_backend  # flake8: noqa
  File "/Users/repos/test/.venv/lib/python3.7/site-packages/moto/core/models.py", line 143, in <module>
    RESPONSES_METHODS = [responses.GET, responses.DELETE, responses.HEAD,
AttributeError: module 'responses' has no attribute 'GET'
```

Also tested on:
```
boto==1.9.159
moto-1.3.14.dev61
```

**Comment by spulec** [comment]
Can you check which version of `responses` library you have installed?

**Comment by gtalarico** [comment]
Newbie mistake. 
I had file called in my project `reponses.py`
