### ISSUE TITLE
Feature: Implement 'update_item' for mock_dynamodb (v1)

### ISSUE THREAD

**Issue by darshan-ghumare** [spulec/moto#2822]
I am running as standalone/server mode,
`# moto_server dynamodb -H 0.0.0.0`

I'm getting following traceback when I try to update item,
`Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/moto/server.py", line 135, in __call__
    return backend_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/moto/core/utils.py", line 144, in __call__
    result = self.callback(request, request.url, {})
  File "/usr/local/lib/python2.7/dist-packages/moto/core/responses.py", line 197, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/moto/core/responses.py", line 295, in _dispatch
    return self.call_action()
  File "/usr/local/lib/python2.7/dist-packages/moto/dynamodb/responses.py", line 30, in call_action
    response = getattr(self, endpoint)()
AttributeError: 'DynamoHandler' object has no attribute 'update_item'
`

I have following questions as well,
1. Does moto only support Dynamodb 2011 API version, does this support 2012 API version?
2. moto::dynamodb update_item does not support update_item.

**Comment by bblommers** [comment]
Hi @darshan-ghumare, moto.dynamodb supports the 2011 API - moto.dynamodb2 supports the 2012 API version.

You're right that moto.dynamodb does not support update_item, but moto.dynamodb2 does support it. Is it possible to upgrade for you?

**Comment by darshan-ghumare** [comment]
@bblommers It would be difficult to upgrade the App to 2012 version.
Is there any branch/implementation that added update_item in moto for API 2011 version?

**Comment by bblommers** [comment]
Not yet, but I'll mark this as an enhancement if people want to pick this up
