### ISSUE TITLE
After loading a mocked dynamodb into an object I can no longer access it

### ISSUE THREAD

**Issue by MichealGoldman** [spulec/moto#2874]
I am writing tests for a python library we are developing, this library acts as a wrapper for dynamodb  interactions. The library consists of two objects, one of which is just the dynamodb connection. When I mock the db in my test, all is fine, I can use put_item(), scan(), etc. Once I instantiate my object with the db as input, I can no longer access ANY ddb functionality. I have tried this with both unittest and pytest with the same results. Here is my traceback.

Traceback (most recent call last):
  File "C:\Python\Python38-32\lib\site-packages\moto\core\models.py", line 88, in wrapper
    result = func(*args, **kwargs)
  File "activity_status_handler\python\tests\UnitTesting\test_activity_status.py", line 255, in test_find
    response = self.fake_aso.find(self.fake_asddb)
  File "activity_status_handler\python\tests\UnitTesting\../..\activity_status_handler\activity_status.py", line 560, in find
    response = ddb.DDB_ACTIVITY_STATUS.query(
  File "C:\Python\Python38-32\lib\site-packages\boto3\resources\factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "C:\Python\Python38-32\lib\site-packages\boto3\resources\action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "C:\Python\Python38-32\lib\site-packages\botocore\client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Python\Python38-32\lib\site-packages\botocore\client.py", line 598, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "C:\Python\Python38-32\lib\site-packages\botocore\client.py", line 644, in _convert_to_request_dict
    api_params = self._emit_api_params(
  File "C:\Python\Python38-32\lib\site-packages\botocore\client.py", line 664, in _emit_api_params
    responses = self.meta.events.emit(
  File "C:\Python\Python38-32\lib\site-packages\botocore\hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "C:\Python\Python38-32\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "C:\Python\Python38-32\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "C:\Python\Python38-32\lib\site-packages\boto3\dynamodb\transform.py", line 27, in copy_dynamodb_params
    return copy.deepcopy(params)
  File "C:\Python\Python38-32\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Python\Python38-32\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Python\Python38-32\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Python\Python38-32\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Python\Python38-32\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Python\Python38-32\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Python\Python38-32\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Python\Python38-32\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Python\Python38-32\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Python\Python38-32\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Python\Python38-32\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Python\Python38-32\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Python\Python38-32\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Python\Python38-32\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Python\Python38-32\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Python\Python38-32\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Python\Python38-32\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "C:\Python\Python38-32\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Python\Python38-32\lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_thread.lock' object

Python 3.8, windows 10, installed via "pip install moto'.  

boto==2.49.0
boto3==1.12.18
botocore==1.15.18
moto==1.3.14

My test code 

    @mock_dynamodb2
    def fake_ddb(self):

        # setup dynamodb object
        self.fake_ddb_resource = boto3.resource(
            'dynamodb', region_name="us-east-1")

        _ = self.fake_ddb_resource.create_table(
            TableName='test_ana_activity_status_TEST',
            KeySchema=[
                {
                    'KeyType': 'HASH',  # Partition key
                    'AttributeName': 'corltn_id',
                },
                {
                    'AttributeName': 'strt_utc_ts',
                    'KeyType': 'RANGE'  # Sort key
                }
            ],
            AttributeDefinitions=[
                {
                    'AttributeName': 'corltn_id',
                    'AttributeType': 'S'
                },
                {
                    'AttributeName': 'strt_utc_ts',
                    'AttributeType': 'S'
                }
            ],
            ProvisionedThroughput={
                'ReadCapacityUnits': 10,
                'WriteCapacityUnits': 10
            }
        )

        self.client = boto3.client('dynamodb', region_name="us-east-1")

        # data = self.client.scan(TableName='test_ana_activity_status_TEST')
        # print(data)
 
        self.table_name = 'test_ana_activity_status_TEST'
        
        self.fake_asddb = ActivityStatusDDB(table=self.fake_ddb_resource.Table(
            "test_ana_activity_status_TEST"), component_type=ComponentType.Lambda)
        self.fake_aso = ActivityStatus(self.fake_asddb)

        self.uid_keys = [
            "9c8f3443-a742-4594-a64e-14e235926384",
            "8c8f3443-a742-4594-a64e-14e235926384",
            "7c8f3443-a742-4594-a64e-14e235926384",
            "6c8f3443-a742-4594-a64e-14e235926384"
        ]
        self.uid = "9c8f3443-a742-4594-a64e-14e235926384"
        self.metrics_list = [{"mtrc_nm": "name1", "valu_nr": "value1"}, {
            "mtrc_nm": "name2", "valu_nr": "value2"}]

   @mock_dynamodb2
    def test_find(self):
        # self.skipTest("moto write issues")
        
        moto = mock_dynamodb2()
        moto.start()
        self.fake_ddb()

        for item in self.uid_keys:

            data = {
                'corltn_id': {'S':item},
                'strt_utc_ts': {'S':item},
                }

            # HERE i have no issues writing to the mocked db
            self.client.put_item(
                TableName='test_ana_activity_status_TEST',
                Item=data
            )

        

        data = self.client.scan(TableName='test_ana_activity_status_TEST')
        print("")
        for item in data['Items']:
            print(item)

        for key in self.uid_keys:
            temp = self.fake_aso.new(
                self.fake_asddb, State.invoke, "pending", "action", "processor", uid=key)
            assert temp.uid() == key
            temp.store()     # Everything works fine until this point (the .store is calling boto3 put_item)

        response = self.fake_aso.find(self.fake_asddb)
        assert response == "not working"
        moto.stop()

Any help is appreciated, if you would like more of the source code please let me know.

**Comment by bblommers** [comment]
Hi @mikerah13, you don't need to explicitly start/stop the mock if you already have the decorators. What happens if you remove these lines?
```
moto = mock_dynamodb2()
moto.start()
...
mock.stop()
```

**Comment by bblommers** [comment]
Going to close this due to a lack of response, but feel free to let me know if this is still an issue.

**Comment by davidhessler** [comment]
Having exact same issue.

**Comment by neil-greenwood** [comment]
I just had the same problem, @bblommers, and it was caused by passing in a dynamodb Table object instead of the table's name.
