### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd1 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by darshan-ghumare** [spulec/moto#2881]
Getting following error after putting object(2 MB size) on s3

```
172.16.102.254 - - [08/Apr/2020 13:11:44] "GET /moto-api HTTP/1.1" 200 -
172.16.102.254 - - [08/Apr/2020 13:11:48] "GET /moto-api/data.json HTTP/1.1" 200 -

172.17.0.31 - - [08/Apr/2020 13:12:15] "PUT http://s3.amazonaws.com/dummys3base/ HTTP/1.1" 200 -
172.17.0.31 - - [08/Apr/2020 13:12:17] "PUT http://s3.amazonaws.com/dummys3base/base-1/988558570881511441 HTTP/1.1" 200 -
172.16.102.254 - - [08/Apr/2020 13:12:20] "GET /moto-api HTTP/1.1" 200 -
172.16.102.254 - - [08/Apr/2020 13:12:23] "GET /moto-api/data.json HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/moto/server.py", line 135, in __call__
    return backend_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/moto/core/utils.py", line 144, in __call__
    result = self.callback(request, request.url, {})
  File "/usr/local/lib/python2.7/dist-packages/moto/core/responses.py", line 723, in model_data
    json.dumps(getattr(instance, attr))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 201, in encode
    return encode_basestring_ascii(o)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd1 in position 0: invalid continuation byte

```

**Comment by bblommers** [comment]
Hi @darshan-ghumare, Can you share your test case, ideally with an similar object where you can reproduce this?

**Comment by bblommers** [comment]
Going to close this due to a lack of response, but feel free to let me know if this is still an issue.
