### ISSUE TITLE
Unsubscribe of in-existent SNS subscription does not throw NotFoundException

### ISSUE THREAD

**Issue by tomers** [spulec/moto#2992]
The SNS model's unsubscribe fails on KeyError when trying to unsubscribe an SNS subscription that does not exists.

Instead, the code should be:
```
def unsubscribe(self, subscription_arn):
        try:
            self.subscriptions.pop(subscription_arn, None)
        except KeyError:
            raise SNSNotFoundError("Topic with arn {0} not found".format(subscription_arn))
```

Reference: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sns.html#SNS.Client.unsubscribe

**Comment by tomers** [comment]
In `test_unsubscribe_from_deleted_topic` I notice:
```
    # Now delete hanging subscription
    client.unsubscribe(SubscriptionArn=subscription_arn)

    subscriptions = client.list_subscriptions()["Subscriptions"]
    subscriptions.should.have.length_of(0)

    # Deleting it again should not result in any error
    client.unsubscribe(SubscriptionArn=subscription_arn)
```

However in my code I get an exception...
My moto version: Docker taken from https://github.com/spulec/moto.git tags/1.3.14
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3.6/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/moto/server.py", line 135, in __call__
    return backend_app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/moto/core/utils.py", line 144, in __call__
    result = self.callback(request, request.url, {})
  File "/usr/lib/python3.6/site-packages/moto/core/responses.py", line 197, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/moto/core/responses.py", line 295, in _dispatch
    return self.call_action()
  File "/usr/lib/python3.6/site-packages/moto/core/responses.py", line 380, in call_action
    response = method()
  File "/usr/lib/python3.6/site-packages/moto/sns/responses.py", line 239, in unsubscribe
    self.backend.unsubscribe(subscription_arn)
  File "/usr/lib/python3.6/site-packages/moto/sns/models.py", line 455, in unsubscribe
    self.subscriptions.pop(subscription_arn)
KeyError: 'arn:aws:sns:eu-central-1:123456789012:fake_nsof_sns_topic:a8f8e434-5dda-4090-9250-b02c24f9c710'
```

**Comment by tomers** [comment]
Found out this issue is fixed by https://github.com/spulec/moto/commit/2fb5004dc2147925b512fa9706061cbb39486a62

Unfortunately I use the latest release, tags/1.3.14 from Nov 14, 2019 so this commit is not included in it. It's been exactly 6 month since your last release - would you be kind enough to deploy a new one soon?

Please close this ticket.

Thanks

**Comment by spulec** [comment]
We do continuous releases on every commit to master so you should be able to use this today: https://pypi.org/project/moto/#history

Let me know if any issues.

**Comment by tomers** [comment]
I use the docker file, not pip, so CI releases in pypi does not help me much
