### ISSUE TITLE
ImportError: cannot import name 'ItemSizeToUpdateTooLarge'

### ISSUE THREAD

**Issue by ronnoceel** [spulec/moto#3014]
Steps to reproduce:
```$ moto_server```

Expected: Server begins running
Actual: 
```
Traceback (most recent call last):
  File "/home/vagrant/.local/bin/moto_server", line 5, in <module>
    from moto.server import main
  File "/home/vagrant/.local/lib/python3.6/site-packages/moto/__init__.py", line 7, in <module>
    from .awslambda import mock_lambda, mock_lambda_deprecated  # noqa
  File "/home/vagrant/.local/lib/python3.6/site-packages/moto/awslambda/__init__.py", line 2, in <module>
    from .models import lambda_backends
  File "/home/vagrant/.local/lib/python3.6/site-packages/moto/awslambda/models.py", line 36, in <module>
    from moto.dynamodb2 import dynamodb_backends2
  File "/home/vagrant/.local/lib/python3.6/site-packages/moto/dynamodb2/__init__.py", line 2, in <module>
    from .models import dynamodb_backends as dynamodb_backends2
  File "/home/vagrant/.local/lib/python3.6/site-packages/moto/dynamodb2/models/__init__.py", line 17, in <module>
    from moto.dynamodb2.exceptions import (
ImportError: cannot import name 'ItemSizeToUpdateTooLarge'
```

This happens every time I try and run moto server. I have tried importing the name manually, but `ItemSizeToUpdateTooLarge` does no appear to exist (neither does google return any results).

System:
`Linux ubuntu-xenial 4.4.0-178-generic #208-Ubuntu SMP Sun Apr 5 23:45:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Installed with pip. I have tried uninstalling an reinstalling.
```
$pip -V
pip 20.1 from /home/vagrant/.local/lib/python3.6/site-packages/pip (python 3.6)
```
```
$ python -V
Python 3.6.10
```

Moto versions:
moto                    1.3.14
moto-ext                1.3.15.15

Boto versions:
boto                    2.49.0
boto3                   1.13.6
botocore                1.16.6

**Comment by bblommers** [comment]
Hi @ronnoceel, `moto-ext` uses a more uptodate version of moto under the hood. This error doesn't exist in moto 1.3.14 yet, though. What happens if you upgrade to the latest release, `1.3.15.dev866`?

**Comment by ronnoceel** [comment]
Thank you! That solved my problem.

`pip install moto==1.3.15.dev866`

**Comment by bblommers** [comment]
Good to hear!
I'll close this - feel free to open a new issue if you run into any other problems.
