### ISSUE TITLE
Error: Cant create DynamoDB table

### ISSUE THREAD

**Issue by benkeil** [spulec/moto#3066]
Version: I used the actual master.

The terraform code:

```
resource "aws_dynamodb_table" "grades" {
  name         = "${var.service_name}.grades"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "id"
  range_key    = "reference"

  attribute {
    name = "id"
    type = "S"
  }

  attribute {
    name = "reference"
    type = "S"
  }

  global_secondary_index {
    name            = "byReference"
    hash_key        = "reference"
    projection_type = "ALL"
  }

  lifecycle {
    prevent_destroy = true
  }

  tags = local.tags
}
```

The debug output of terraform:

```
2020-06-12T14:48:02.175+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 2020/06/12 14:48:02 [DEBUG] [aws-sdk-go] {"Table": {"AttributeDefinitions": [{"AttributeName": "reference", "AttributeType": "S"}, {"AttributeName": "id", "AttributeType": "S"}], "ProvisionedThroughput": {"WriteCapacityUnits": 10, "ReadCapacityUnits": 10, "NumberOfDecreasesToday": 0}, "TableSizeBytes": 0, "TableName": "componenttest-widget-service.grades", "TableStatus": "ACTIVE", "TableArn": "arn:aws:dynamodb:us-east-1:123456789011:table/componenttest-widget-service.grades", "KeySchema": [{"AttributeName": "id", "KeyType": "HASH"}, {"AttributeName": "reference", "KeyType": "RANGE"}], "ItemCount": 0, "CreationDateTime": 1591966082.035368, "GlobalSecondaryIndexes": [{"IndexName": "byReference", "KeySchema": [{"AttributeName": "reference", "KeyType": "HASH"}], "Projection": {"ProjectionType": "ALL"}, "IndexStatus": "ACTIVE"}], "LocalSecondaryIndexes": []}}
```

```
 runtime error: invalid memory address or nil pointer dereference
2020-06-12T15:26:43.227+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4ea19ab]
2020-06-12T15:26:43.227+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4:
2020-06-12T15:26:43.227+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: goroutine 134 [running]:
2020-06-12T15:26:43.227+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.flattenAwsDynamoDbTableResource(0xc001406b60, 0xc0012eec00, 0xc000652270, 0x0)
2020-06-12T15:26:43.227+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/structure.go:4149 +0x105b
2020-06-12T15:26:43.227+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsDynamoDbTableRead(0xc001406b60, 0x5b37620, 0xc000301900, 0x64b2400, 0xc000e7fd20)
2020-06-12T15:26:43.227+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_dynamodb_table.go:665 +0x330
2020-06-12T15:26:43.227+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsDynamoDbTableCreate(0xc001406b60, 0x5b37620, 0xc000301900, 0x2, 0xa406520)
2020-06-12T15:26:43.227+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_dynamodb_table.go:439 +0x1548
2020-06-12T15:26:43.227+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000566000, 0xc000a346e0, 0xc0010007e0, 0x5b37620, 0xc000301900, 0xc0008c0701, 0xc000d52990, 0xc0008c0790)
2020-06-12T15:26:43.227+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:310 +0x365
2020-06-12T15:26:43.228+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000152180, 0xc000df59c8, 0xc000a346e0, 0xc0010007e0, 0xc000881828, 0xc0011aa2e0, 0x5946b60)
2020-06-12T15:26:43.228+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294 +0x99
2020-06-12T15:26:43.228+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000595138, 0x702f440, 0xc000b0df80, 0xc001406540, 0xc000595138, 0xc000b0df80, 0xc000e17b30)
2020-06-12T15:26:43.228+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885 +0x8b4
2020-06-12T15:26:43.228+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x64da560, 0xc000595138, 0x702f440, 0xc000b0df80, 0xc001178ba0, 0x0, 0x702f440, 0xc000b0df80, 0xc001366b00, 0x562)
2020-06-12T15:26:43.228+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3305 +0x217
2020-06-12T15:26:43.228+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0008a9680, 0x7051c00, 0xc000e0e480, 0xc0012ee100, 0xc000958cc0, 0xa3d9780, 0x0, 0x0, 0x0)
2020-06-12T15:26:43.228+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:1024 +0x4f4
2020-06-12T15:26:43.228+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: google.golang.org/grpc.(*Server).handleStream(0xc0008a9680, 0x7051c00, 0xc000e0e480, 0xc0012ee100, 0x0)
2020-06-12T15:26:43.228+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:1313 +0xd97
2020-06-12T15:26:43.228+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00013a0e0, 0xc0008a9680, 0x7051c00, 0xc000e0e480, 0xc0012ee100)
2020-06-12T15:26:43.228+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:722 +0xbb
2020-06-12T15:26:43.228+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-06-12T15:26:43.228+0200 [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:720 +0xa1
```

The problem seems to be the global secondary index.

**Comment by bblommers** [comment]
This is now fixed as of moto >= 1.3.15.dev906
