### ISSUE TITLE
test_streaming_upload_from_file_to_presigned_url fails

### ISSUE THREAD

**Issue by dawngerpony** [spulec/moto#3080]
# Steps to reproduce

`make test` on a fresh copy of `master`.

# Expected result

All tests pass.

# Actual result

One S3 test (`test_streaming_upload_from_file_to_presigned_url`) produces an error:

```
ERROR: tests.test_s3.test_s3.test_streaming_upload_from_file_to_presigned_url
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dawn.james/dev/github.com/dawngerpony/moto/.venv/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/dawn.james/dev/github.com/dawngerpony/moto/moto/core/models.py", line 98, in wrapper
    result = func(*args, **kwargs)
  File "/Users/dawn.james/dev/github.com/dawngerpony/moto/tests/test_s3/test_s3.py", line 1048, in test_streaming_upload_from_file_to_presigned_url
    bucket.create()
  File "/Users/dawn.james/dev/github.com/dawngerpony/moto/.venv/lib/python3.7/site-packages/boto3-1.14.6-py3.7.egg/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/dawn.james/dev/github.com/dawngerpony/moto/.venv/lib/python3.7/site-packages/boto3-1.14.6-py3.7.egg/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/Users/dawn.james/dev/github.com/dawngerpony/moto/.venv/lib/python3.7/site-packages/botocore-1.17.6-py3.7.egg/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/dawn.james/dev/github.com/dawngerpony/moto/.venv/lib/python3.7/site-packages/botocore-1.17.6-py3.7.egg/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.
```

# Notes

* The fix appears to be simple, I have included it in #3079, but I thought I should raise a separate issue anyway.
* I'm not sure why this is happening today, I'm pretty sure it wasn't happening yesterday, but the fix seems harmless so I see no problem in making it.

**Comment by bblommers** [comment]
All tests should have the region specified. Locally, boto3 might pick up the region from the AWS config, but as Travis doesn't have any AWS config, our build should always fail with a missing region.
Not sure why it didn't.. but your PR definitely fixes it. Thanks :)
