### ISSUE TITLE
failure to import moto with boto version 2.9.6

### ISSUE THREAD

**Issue by jetlag11235** [spulec/moto#315]
I used pip to install moto on an old develop machine and ran into problems trying to import the library due to missing features in an older boto version:

```python
>>> import moto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/moto/__init__.py", line 14, in <module>
    from .kinesis import mock_kinesis  # flake8: noqa
  File "/usr/local/lib/python2.7/dist-packages/moto/kinesis/__init__.py", line 2, in <module>
    from .models import kinesis_backends
  File "/usr/local/lib/python2.7/dist-packages/moto/kinesis/models.py", line 3, in <module>
    import boto.kinesis
ImportError: No module named kinesis

>>> import boto.kinesis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named kinesis

>>> import boto
>>> boto.__version__
'2.9.6'
```

upgrading to the most recent release of boto solved my issues.  kinesis was introduced in boto version 2.20.0, so I thought the laziest solution would be to make this a minimum requirement to installation of moto.  I did *not* verify that this version is sufficient.

**Comment by spulec** [comment]
Closed with #314
