### ISSUE TITLE
`describe_maintenance_windows` action has not been implemented

### ISSUE THREAD

**Issue by raffienficiaud** [spulec/moto#3157]
## Reporting Bugs

`moto` version `1.3.14` installed with `pip` in a virtualenv on `python3` / ubuntu. Using `python3` mocks.

The following simple test fails 

```
from moto import mock_autoscaling, mock_ec2, mock_ssm
import unittest


class EC2HelperTests(unittest.TestCase):

    def setUp(self):
        for vv in ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_SECURITY_TOKEN', 'AWS_SESSION_TOKEN']:
            os.environ[vv] = 'testing'

    def tearDown(self):
        for vv in ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_SECURITY_TOKEN', 'AWS_SESSION_TOKEN']:
            os.environ.pop(vv)

    @mock_ssm
    def test_get_maintenance_window(self):
        region = 'us-east-1'

        patch_region.return_value = region
        patch_instance_id.return_value = 'fake-instance'

        ssm_client = boto3.client('ssm', region_name=region)

        response = ssm_client.describe_maintenance_windows(
            Filters=[
                {
                    'Key': 'Name',
                    'Values': [
                        "fake-maintenance-window-name",
                    ]
                },
            ],
        )
```

with the following exception

```
Traceback (most recent call last):
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/moto/core/models.py", line 88, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/mock.py", line 1183, in patched
    return func(*args, **keywargs)
  File "/data/code/pix4d/berlin-infra/fields_cloud_data_sync/couchbase-ami/pix4d-scripts/couchbase_tools/pix4d_couchbase_tools/tests/test_cb_node.py", line 102, in test_get_maintenance_window
    "fake-maintenance-window-name",
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/client.py", line 622, in _make_api_call
    operation_model, request_dict, request_context)
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/client.py", line 641, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/endpoint.py", line 256, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/endpoint.py", line 197, in _do_get_response
    responses = self._event_emitter.emit(event_name, request=request)
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/moto/core/models.py", line 272, in __call__
    request, request.url, request.headers
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/moto/core/responses.py", line 197, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/moto/core/responses.py", line 295, in _dispatch
    return self.call_action()
  File "/data/code/pix4d/sandbox/venv_enterprise/lib/python3.6/site-packages/moto/core/responses.py", line 393, in call_action
    "The {0} action has not been implemented".format(action)
NotImplementedError: The describe_maintenance_windows action has not been implemented

```

## Actual result

Exception raised with a `NotImplementedError` message.

## Expected result

1. successful call to `ssm_client.describe_maintenance_windows` without exception raised
1. filter working on the set of maintenance windows: 
    1. first call returns an empty set of maintenance windows
    1. second call (after having manually created the maintenance windows) has an active filter with a behaviour close to the one of aws-cli/boto

**Comment by bblommers** [comment]
Thanks for raising this @raffienficiaud - marking this as an enhancement
