### ISSUE TITLE
NotImplementedError: The update_policy action has not been implemented

### ISSUE THREAD

**Issue by harvester843** [spulec/moto#3238]
Good afternoon,

I came across this error while using the organizations update_policy API call:
```python
Error
Traceback (most recent call last):
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\moto\core\models.py", line 88, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\unittest\mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "C:\Users\redacted\Desktop\redacted\redacted\tests\unit\test_organizations.py", line 319, in test_update_scp
    Content=str(updated_scp)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\client.py", line 622, in _make_api_call
    operation_model, request_dict, request_context)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\client.py", line 641, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\endpoint.py", line 137, in _send_request
    success_response, exception):
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\endpoint.py", line 256, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\retryhandler.py", line 251, in __call__
    caught_exception)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\retryhandler.py", line 317, in __call__
    caught_exception)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\endpoint.py", line 197, in _do_get_response
    responses = self._event_emitter.emit(event_name, request=request)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\moto\core\models.py", line 272, in __call__
    request, request.url, request.headers
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\moto\core\responses.py", line 197, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\moto\core\responses.py", line 295, in _dispatch
    return self.call_action()
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python36\lib\site-packages\moto\core\responses.py", line 393, in call_action
    "The {0} action has not been implemented".format(action)
NotImplementedError: The update_policy action has not been implemented
```
I am calling it by creating a session, with that session I create the organizations client and call it:
 
```python
                updated_policy = self.orgs_client.update_policy(
                    PolicyId=policy_id,
                    Name=policy_name,
                    Description=policy_description,
                    Content=str(updated_scp)
                )
````
I am expecting the API call to succeed, but it is giving me the aforementioned error

Currently installed:
moto version 1.3.14
boto3 version 1.10.34
botocore version 1.17.28
installed all libraries using pip

**Comment by bblommers** [comment]
Thanks for raising this @harvester843. The `update_policy` endpoint was only introduced recently, and is available as of moto >= moto >= 1.3.15.dev999.
Can you verify whether your test case works after upgrading?

**Comment by harvester843** [comment]
Hello @bblommers ,

Yes I have confirmed my update_policy test case now works using moto version 1.3.15.dev999. Is there a target date for the release of 1.3.15? 

Also, thanks for addressing this issue quickly!

**Comment by bblommers** [comment]
There's nothing planned in terms of a release, as far as I know. Using the dev-releases is recommended though, because of the infrequent nature of official releases - and the only difference is really the naming.
