### ISSUE TITLE
Can't get secrets which are added from aws cli

### ISSUE THREAD

**Issue by gudata** [spulec/moto#3258]
Hello, 
I have added a secret from a file 
```
aws --endpoint-url http://localhost:5000 --region us-east-1 secretsmanager put-secret-value --secret-id rds-space_util --secret-string file://rds.json
```
rds.json content is
```
{
    "ARN": "arn:aws:secretsmanager:us-east-1:361255764607:secret:rds-space_util-3jLvFd",
    "Name": "rds-space_util",
    "VersionId": "5EEFFAED-7CFE-4DEE-8436-83D97C4AA190",
    "SecretString": "{\n  \"engine\": \"MySQL\",\n  \"username\": \"essential\",\n  \"password\": \"somepassword\",\n  \"host\": \"data-mysql-rds.some-domain.com\",\n  \"port\": \"3306\",\n  \"dbname\": \"space_util\"\n}\n",
    "VersionStages": [
        "AWSCURRENT"
    ],
    "CreatedDate": "2019-07-10T17:45:55.995000+03:00"
}

```
and I am able to see the secret with those two commands

```
aws --endpoint-url http://localhost:5000 --region us-east-1 secretsmanager list-secrets
aws --endpoint-url http://localhost:5000 --region us-east-1 secretsmanager get-secret-value --secret-id rds-space_util 
```

When I try to get the secret from the python2.7 it says that It couldn't find it.

```
import boto3
from moto import mock_secretsmanager


@mock_secretsmanager
def test():
    conn = boto3.client("secretsmanager", region_name="us-east-1")

    secret_value = "test_get_secret_value_by_arn"
    result = conn.create_secret(
        Name="java-util-test-password", SecretString=secret_value
    )
    # It works!
    result = conn.get_secret_value(SecretId="java-util-test-password")

    # With hardcoded endpoint it also works.
    client = boto3.client("secretsmanager", region_name='us-east-1', endpoint_url='http://localhost:5000')
    secret_string = client.get_secret_value(SecretId="rds-space_util")
    print("ok")

    # This one from aws cli is not visible here.
    result = conn.get_secret_value(SecretId="rds-space_util")
    print(result)

test()

```

Here is the output
```
python test-secretsmanager.py 
/home/guda/.local/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.10) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/home/guda/.pyenv/versions/2.7.18/lib/python2.7/site-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,
ok
Traceback (most recent call last):
  File "test-secretsmanager.py", line 25, in <module>
    test()
  File "/home/guda/.pyenv/versions/2.7.18/lib/python2.7/site-packages/moto/core/models.py", line 88, in wrapper
    result = func(*args, **kwargs)
  File "test-secretsmanager.py", line 22, in test
    result = conn.get_secret_value(SecretId="rds-space_util")
  File "/home/guda/.pyenv/versions/2.7.18/lib/python2.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/guda/.pyenv/versions/2.7.18/lib/python2.7/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: <exception str() failed>
```

**Comment by kam193** [comment]
Hi, I think it's because you use new-style mock which doesn't redirect calls to server but makes true mocking in the same process. As I see in the code base, `_deprecated` mocks work as you assumed (if I understand it good), but there is no this mock for secretmanager. 

You can try to create it, probably in the way like:

```
from moto.core.models import deprecated_base_decorator
from moto.secretsmanager import secretsmanager_backends

moto_secretmanager_deprecated = deprecated_base_decorator(secretsmanager_backends)
```
but I was unable to check if it works.

**Comment by bblommers** [comment]
Hi @gudata, the MotoServer app can't be used in conjunction with the decorators. They each live in their own process and have their own internal data store. Any CLI commands will only talk to the MotoServer, and store secrets there.
When using the decorators, it will initialize a completely  new process + empty data store.


`boto3.client("secretsmanager", region_name='us-east-1', endpoint_url='http://localhost:5000')`
This works because it specifically talks to the same MotoServer.

Note that you don't need the decorators at all when using the MotoServer/specify endpoint_urls in the boto3-clients.

@kam193 Not sure whether that would work actually, but using the `_deprecated` is never recommended. Those decorators will lose support at some point in the future.

**Comment by kam193** [comment]
@bblommers I know, I think this is why there is no `_deprecated` for secretmanager. I guess gudata could expect this behavior because of previous use of old decorators in other cases.

Anyway, this never should work with the current moto design and try to manually create deprecated decorator should only act as  a temporary workaround.

**Comment by gudata** [comment]
Got my mistake, thank you!
