### ISSUE TITLE
`mock_ecs.describe_container_instances` missing value `registeredAt`

### ISSUE THREAD

**Issue by Ellynas** [spulec/moto#3352]
The [official ECS documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html#ECS.Client.describe_container_instances) states that the response of `client.describe_container_instances()` contains :
>registeredAt (datetime) --
The Unix timestamp for when the container instance was registered.

But as far as I know, moto mock of that call doesn't.

### to Reproduce:
Inspired from [`test_run_task()`](https://github.com/spulec/moto/blob/a668349a70ffce571c74c77074e6270f3cb59dd7/tests/test_ecs/test_ecs_boto3.py#L1087)

```python 
@mock_ec2
@mock_ecs
def test():
    client = boto3.client("ecs", region_name="us-east-1")
    ec2 = boto3.resource("ec2", region_name="us-east-1")

    test_cluster_name = "test_ecs_cluster"

    _ = client.create_cluster(clusterName=test_cluster_name)

    test_instance = ec2.create_instances(
        ImageId="ami-1234abcd", MinCount=1, MaxCount=1
    )[0]

    instance_id_document = json.dumps(
        ec2_utils.generate_instance_identity_document(test_instance)
    )

    response = client.register_container_instance(
        cluster=test_cluster_name, instanceIdentityDocument=instance_id_document
    )

    _ = client.register_task_definition(
        family="test_ecs_task",
        containerDefinitions=[
            {
                "name": "hello_world",
                "image": "docker/hello-world:latest",
                "cpu": 1024,
                "memory": 400,
                "essential": True,
                "environment": [
                    {"name": "AWS_ACCESS_KEY_ID", "value": "SOME_ACCESS_KEY"}
                ],
                "logConfiguration": {"logDriver": "json-file"},
            }
        ],
    )
    response = client.run_task(
        cluster="test_ecs_cluster",
        overrides={},
        taskDefinition="test_ecs_task",
        count=2,
        startedBy="moto",
    )
    node = self.ecs.describe_container_instances(
        cluster="test_ecs_cluster",
        containerInstances=self.ecs.list_container_instances(cluster="test_ecs_cluster", status="ACTIVE")["containerInstanceArns"],
    )
    print(node["containerInstances"][0]["registeredAt"]) #KeyError: 'registeredAt'
```
Logs : 
```
Traceback (most recent call last):
  File "/path/to/python3.6/site-packages/moto/core/models.py", line 100, in wrapper
    result = func(*args, **kwargs)
  File "/path/to/python3.6/site-packages/moto/core/models.py", line 100, in wrapper
    result = func(*args, **kwargs)
  File "/path/topython3.6/site-packages/moto/core/models.py", line 100, in wrapper
    result = func(*args, **kwargs)
  File "/path/to/my/file.py", line 147, in test_test
    print(node["containerInstances"][0]["registeredAt"])
KeyError: 'registeredAt'
```

moto version : 1.3.16

This attribute is quite important to us, because we want to have a script that shuts down instances if they are "too old" or something like that, and properly testing that script is key.

**Comment by bblommers** [comment]
Thanks for raising this @Ellynas - marking it as an enhancement.

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.16.dev51

**Comment by Ellynas** [comment]
You've been really helpful, I really appreciate that.

If I may, I have one subsequent question : In my tests, how can i access directly `EC2ContainerServiceBackend.container_instances` property so i can alter it to create my tests ?

So far I've tried : 
```python
@mock_ecs
def test_private():
    ecs = boto3.client(
        "ecs",
        region_name=settings.AWS_REGION,
        aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
        aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
    )

    ecs.create_cluster(clusterName="myCluster")
    # I'm certain that this uses EC2ContainerServiceBackend.create_cluster()
    # because I put a pprint in it to verify it's propremy called

    print(type(ecs))  # outputs <class 'botocore.client.ECS'>

    print(self.ecs.container_instances) 
    # AttributeError: 'ECS' object has no attribute 'container_instances'
```
