### ISSUE TITLE
Attempts to use awscli with HTTP_PROXY and HTTPS_PROXY pointing at moto_server results in KeyError

### ISSUE THREAD

**Issue by major0** [spulec/moto#3390]
## Reporting Bugs
Moto server throws `KeyError: 'HTTP_HOST'` when attempting to use moto_server as an http/https proxy with the AWS CLI.

See: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-proxy.html

Docker container built from the following `Dockerfile`:
```
FROM alpine:3.11.6

RUN set -e \
        && ln -sf /usr/share/zoneinfo/Etc/UTC /etc/localtime \
        && mkdir -p /docker-entrypoint.d \
        && apk --update add --no-cache --virtual .build-deps \
        && apk add --no-cache \
                python3 \
                git \
                jq \
                curl \
                groff \
                libffi \
                openssl \
                build-base \
                py3-pip \
                python3-dev \
                libffi-dev \
                openssl-dev \
        && pip3 install --upgrade \
                awscli==1.18.49 \
                s3cmd==2.1.0 \
                "moto[server]" \
        && apk --purge -v del \
                build-base \
                py3-pip \
                python3-dev \
                libffi-dev \
                openssl-dev \
        && rm -f /var/cache/apk/*

COPY docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]
```
The `docker-entrypoint.sh` allows launching a shell in the container via: `docker run -it moto /bin/sh`

From inside the Docker container:
```
moto_server &
HTTP_PROXY="http://127.0.0.1:5000" HTTPS_PROXY="http://127.0.0.1:5000" aws ec2 describe-vpcs
```
_Note: Same results when launching moto_server and specify a service. E.g. `moto_server ec2`._

Output:
```
/ # moto_server &
/ #  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

/ # HTTP_PROXY="http://127.0.0.1:5000" HTTPS_PROXY="http://127.0.0.1:5000" aws ec2 describe-vpcs
127.0.0.1 - - [15/Oct/2020 14:25:48] "CONNECT ec2.us-east-2.amazonaws.com:443 HTTP/1.0" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3.8/site-packages/moto/server.py", line 166, in __call__
    backend_app = self.get_application(environ)
  File "/usr/lib/python3.8/site-packages/moto/server.py", line 130, in get_application
    host = environ["HTTP_HOST"].split(":")[0]
KeyError: 'HTTP_HOST'
127.0.0.1 - - [15/Oct/2020 14:25:48] "CONNECT ec2.us-east-2.amazonaws.com:443 HTTP/1.0" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3.8/site-packages/moto/server.py", line 166, in __call__
    backend_app = self.get_application(environ)
  File "/usr/lib/python3.8/site-packages/moto/server.py", line 130, in get_application
    host = environ["HTTP_HOST"].split(":")[0]
KeyError: 'HTTP_HOST'
127.0.0.1 - - [15/Oct/2020 14:25:48] "CONNECT ec2.us-east-2.amazonaws.com:443 HTTP/1.0" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3.8/site-packages/moto/server.py", line 166, in __call__
    backend_app = self.get_application(environ)
  File "/usr/lib/python3.8/site-packages/moto/server.py", line 130, in get_application
    host = environ["HTTP_HOST"].split(":")[0]
KeyError: 'HTTP_HOST'
127.0.0.1 - - [15/Oct/2020 14:25:51] "CONNECT ec2.us-east-2.amazonaws.com:443 HTTP/1.0" 500 -
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3.8/site-packages/moto/server.py", line 166, in __call__
    backend_app = self.get_application(environ)
  File "/usr/lib/python3.8/site-packages/moto/server.py", line 130, in get_application
    host = environ["HTTP_HOST"].split(":")[0]
KeyError: 'HTTP_HOST'
127.0.0.1 - - [15/Oct/2020 14:25:56] "CONNECT ec2.us-east-2.amazonaws.com:443 HTTP/1.0" 500 -

Failed to connect to proxy URL: "http://127.0.0.1:5000"
Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3.8/site-packages/moto/server.py", line 166, in __call__
    backend_app = self.get_application(environ)
  File "/usr/lib/python3.8/site-packages/moto/server.py", line 130, in get_application
    host = environ["HTTP_HOST"].split(":")[0]
KeyError: 'HTTP_HOST'
```

**Comment by smulikHakipod** [comment]
this solved it to me `aws --endpoint-url http://localhost:5000 sts get-caller-identity`

**Comment by bblommers** [comment]
That sounds like the right solution @smulikHakipod. 

The idea of moto_server is not to use it as a proxy, but to act as a offline/onprem AWS server. So all it takes is to add the endpoint_url parameter to the CLI/SDK - there's no need to use a proxy to get moto_server working.

**Comment by bblommers** [comment]
Going to close this due to a lack of response, but feel free to let me know if this is still an issue.
