### ISSUE TITLE
UnrecognizedClientException when using Application Autoscaling

### ISSUE THREAD

**Issue by aneri-masi** [spulec/moto#3407]
I have a lambda for collecting ECS service task metrics - and for this purpose, I am calling the [DescribeScalableTargets](https://docs.aws.amazon.com/autoscaling/application/APIReference/API_DescribeScalableTargets.html) API.

The lambda itself works fine, but my unit tests using moto are failing.

I am using the following:
boto3=1.10.36
moto=1.3.16

Unit test approach:
```
        ecs = boto3.client('ecs', region_name='us-east-1')
        """:type : pyboto3.ecs """

        ecs.create_cluster(clusterName='mock_cluster')

        ecs.register_task_definition(family = 'mock_task_def', containerDefinitions=[])
        ecs.create_service(cluster = 'mock_cluster',
                           serviceName='mock_service',
                           taskDefinition='mock_task_def:1',
                           desiredCount=3)

        autoscaler = boto3.client('application-autoscaling', region_name='us-east-1')

        autoscaler.register_scalable_target(
            MaxCapacity=10,
            MinCapacity=1,
            ResourceId='service/mock_cluster/mock_service',
            ScalableDimension='ecs:service:DesiredCount',
            ServiceNamespace='ecs')
```

I get the following error when I run this:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moto/core/models.py", line 100, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moto/core/models.py", line 100, in wrapper
    result = func(*args, **kwargs)
  File "/Users/kpatel/CloudPlatform/ecs_task/test/test_main.py", line 53, in test_healthy_service
    autoscaler.register_scalable_target(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/botocore/client.py", line 276, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/botocore/client.py", line 586, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the RegisterScalableTarget operation: The security token included in the request is invalid.

----------------------------------------------------------------------
Ran 1 test in 0.977s
```

Any ideas on how to get around this?

**Comment by aneri-masi** [comment]
Ah, I was using `mock_autoscaling` instead of `mock_applicationautoscaling` - all good now!
