### ISSUE TITLE
Travis CI jobs failing intermittently

### ISSUE THREAD

**Issue by bpandola** [spulec/moto#3475]
`test_batch.test_submit_job` fails intermittently across all Python versions and regardless of whether `TEST_SERVER_MODE=false` or `TEST_SERVER_MODE=true`.

<details>
<summary>Nose Failure</summary>
<p>

```
======================================================================
FAIL: test_batch.test_submit_job
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/spulec/moto/moto/core/models.py", line 99, in wrapper
    result = func(*args, **kwargs)
  File "/home/travis/build/spulec/moto/moto/core/models.py", line 99, in wrapper
    result = func(*args, **kwargs)
  File "/home/travis/build/spulec/moto/moto/core/models.py", line 99, in wrapper
    result = func(*args, **kwargs)
  [Previous line repeated 2 more times]
  File "/home/travis/build/spulec/moto/tests/test_batch/test_batch.py", line 750, in test_submit_job
    [event["message"] for event in resp["events"]].should.equal(["hello"])
  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/sure/__init__.py", line 387, in wrapper
    raise AssertionError(e)
AssertionError: given
X = []
    and
Y = ['hello']
Y has 1 items whereas X has only 0
>>  raise AssertionError(e)
```

</p>
</details>  

The test is still failing occasionally after the recent switch from nose to pytest.

<details>
<summary>Pytest Failure</summary>
<p>

```
=================================== FAILURES ===================================
_______________________________ test_submit_job ________________________________

self = <sure.AssertionBuilder object at 0x7fd94262df60>, args = (['hello'],)
kw = {}

    @wraps(func)
    def wrapper(self, *args, **kw):
        try:
>           value = func(self, *args, **kw)

../../../virtualenv/python3.6.10/lib/python3.6/site-packages/sure/__init__.py:385: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sure.AssertionBuilder object at 0x7fd94262df60>, what = ['hello']
epsilon = None

    @assertionmethod
    def equal(self, what, epsilon=None):
        """compares given object ``X``  with an expected ``Y`` object.
    
        It primarily assures that the compared objects are absolute equal ``==``.
    
        :param what: the expected value
        :param epsilon: a delta to leverage upper-bound floating point permissiveness
        """
    
        try:
            comparison = DeepComparison(self.obj, what, epsilon).compare()
            error = False
        except AssertionError as e:
            error = e
            comparison = None
    
        if isinstance(comparison, DeepExplanation):
            error = comparison.get_assertion(self.obj, what)
    
        if self.negative:
            if error:
                return True
    
            msg = '%s should differ from %s, but is the same thing'
            raise AssertionError(msg % (safe_repr(self.obj), safe_repr(what)))
    
        else:
            if not error:
                return True
>           raise error
E           AssertionError: given
E           X = []
E               and
E           Y = ['hello']
E           Y has 1 items whereas X has only 0

../../../virtualenv/python3.6.10/lib/python3.6/site-packages/sure/__init__.py:673: AssertionError
```

</p>
</details>

This "flipper test" was mentioned and acknowledged as a problem in #3161, but I wasn't able to find an existing issue tracking it.  I will investigate.

**Comment by bblommers** [comment]
Hey @bpandola, just as an FYI: this was my attempt at fixing it: https://github.com/spulec/moto/pull/3146

That obviously wasn't the solution, hopefully you have better luck/investigator skills ;)
