### ISSUE TITLE
The purge_queue action has not been implemented

### ISSUE THREAD

**Issue by Garrett-R** [spulec/moto#349]
I start a moto_server instance using
```
moto_server sqs --host 127.0.0.1 --port 5555
```

I then execute this script

    import boto.sqs

    region = boto.sqs.regioninfo.RegionInfo(name='LOCAL', endpoint='localhost')
    sqs_conn = boto.connect_sqs('access-key', 'secret-key', is_secure=False, region=region, port=5555)

    new_queue = sqs_conn.create_queue('new-queue')
    new_queue.purge()

And moto_server gives me this error:
```
127.0.0.1 - - [20/May/2015 01:13:10] "GET /123456789012/new-queue?Action=PurgeQueue&Version=2012-11-05 HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/garrett/Desktop/del/lib/python2.7/site-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/home/garrett/Desktop/del/lib/python2.7/site-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/home/garrett/Desktop/del/lib/python2.7/site-packages/moto/server.py", line 53, in __call__
    return backend_app(environ, start_response)
  File "/home/garrett/Desktop/del/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/garrett/Desktop/del/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/garrett/Desktop/del/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/garrett/Desktop/del/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/garrett/Desktop/del/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/garrett/Desktop/del/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/garrett/Desktop/del/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/garrett/Desktop/del/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/garrett/Desktop/del/lib/python2.7/site-packages/moto/core/utils.py", line 77, in __call__
    result = self.callback(request, request.url, {})
  File "/home/garrett/Desktop/del/lib/python2.7/site-packages/moto/core/responses.py", line 124, in dispatch
    return self.call_action()
  File "/home/garrett/Desktop/del/lib/python2.7/site-packages/moto/core/responses.py", line 150, in call_action
    raise NotImplementedError("The {0} action has not been implemented".format(action))
NotImplementedError: The purge_queue action has not been implemented

```

This is similar to this closed issue: https://github.com/spulec/moto/issues/71.

I also tried with using `mock_sqs` as a context manager, and same error.

**Comment by spulec** [comment]
Thanks for opening this! It should be fixed in the master branch now.

**Comment by Garrett-R** [comment]
Thanks!!
