### ISSUE TITLE
Validation Exception raised when trying to call .get_item() method on the Dynamodb table object.

### ISSUE THREAD

**Issue by vsuzdaltsev** [spulec/moto#3525]
## Reporting Bugs

The following code fails when trying to call .get_item() method
```
import boto3
from moto import mock_dynamodb2

TABLE = 'test_table'
TEST_ROLES = [
    {
        "Role": "000000000001-role",
        'Account': "000000000001",
        "Str": 'My string 1',
        "Doc": "Some doc 1"
    },
    {
        "Role": "000000000002-role",
        'Account': "000000000002",
        "Str": 'My string 2',
        "Doc": "Some doc 2"
    },
]


def setup_mock_dynamodb():
    with mock_dynamodb2():
        dynamodb = boto3.resource('dynamodb', 'us-east-2')
        table = dynamodb.create_table(
            TableName=TABLE,
            KeySchema=[
                {'AttributeName': 'Role', 'KeyType': 'HASH'}

            ],
            AttributeDefinitions=[
                {'AttributeName': 'Role', 'AttributeType': 'S'}
            ],
            ProvisionedThroughput={'ReadCapacityUnits': 5, 'WriteCapacityUnits': 5}
        )

        table.meta.client.get_waiter('table_exists').wait(TableName=TABLE)
        list(map(lambda role: table.put_item(Item=role), TEST_ROLES))

        # Scan works !!!
        print(f">> SCAN: {table.scan()}")
        
        # But get_item fails !!!
        print(f">> GET_ITEM: {table.get_item(Key={'Role': '000000000001-role'}, AttributesToGet=['Str'])}")


if __name__ == "__main__":
    setup_mock_dynamodb()
```

**Comment by vsuzdaltsev** [comment]
Results the following:
```
>> SCAN: {'Items': [{'Role': '000000000001-role', 'Account': '000000000001', 'Str': 'My string 1', 'Doc': 'Some doc 1'}, {'Role': '000000000002-role', 'Account': '000000000002', 'Str': 'My string 2', 'Doc': 'Some doc 2'}], 'Count': 2, 'ScannedCount': 2, 'ConsumedCapacity': {'TableName': 'test_table', 'CapacityUnits': 1}, 'ResponseMetadata': {'RequestId': 'FK7LFQYUL9XXLA3CX86UVY1V61E3U4JK606E0PKG54112AIHXIXJ', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com', 'x-amzn-requestid': 'FK7LFQYUL9XXLA3CX86UVY1V61E3U4JK606E0PKG54112AIHXIXJ'}, 'RetryAttempts': 0}}
(WK-Core-Shared-Library) yaa@mac$ py3 python3/packages/wk_automation/tests/wk_automation/aws/dynamodb/bug.py                                                                                                              [test_long_run] /opt/wk/WK-Core-Shared-Library
>> SCAN: {'Items': [{'Role': '000000000001-role', 'Account': '000000000001', 'Str': 'My string 1', 'Doc': 'Some doc 1'}, {'Role': '000000000002-role', 'Account': '000000000002', 'Str': 'My string 2', 'Doc': 'Some doc 2'}], 'Count': 2, 'ScannedCount': 2, 'ConsumedCapacity': {'TableName': 'test_table', 'CapacityUnits': 1}, 'ResponseMetadata': {'RequestId': 'AW35CVZS1PVJJT97MAPEWJOOH20W6LHSX1Q8MKU88UGLH77032GK', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com', 'x-amzn-requestid': 'AW35CVZS1PVJJT97MAPEWJOOH20W6LHSX1Q8MKU88UGLH77032GK'}, 'RetryAttempts': 0}}
Traceback (most recent call last):
  File "python3/packages/wk_automation/tests/wk_automation/aws/dynamodb/bug.py", line 51, in <module>
    setup_mock_dynamodb()
  File "python3/packages/wk_automation/tests/wk_automation/aws/dynamodb/bug.py", line 47, in setup_mock_dynamodb
    print(f">> GET_ITEM: {table.get_item(Key={'Role': '000000000001-role'}, AttributesToGet=['Str'])}")
  File "/Users/yaa/.local/share/virtualenvs/WK-Core-Shared-Library-QoIpL0iR/lib/python3.8/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/yaa/.local/share/virtualenvs/WK-Core-Shared-Library-QoIpL0iR/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/Users/yaa/.local/share/virtualenvs/WK-Core-Shared-Library-QoIpL0iR/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/yaa/.local/share/virtualenvs/WK-Core-Shared-Library-QoIpL0iR/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the GetItem operation: Validation Exception
zsh: exit 1     python3.8 
```

**Comment by vsuzdaltsev** [comment]
environment:
```
boto==2.49.0
boto3==1.16.29
botocore==1.19.30
moto==1.3.16
```

**Comment by rkisliak** [comment]
The same problem :-/

**Comment by kickman2l** [comment]
+ 1

**Comment by vsuzdaltsev** [comment]
The problem was in the incorrect schema definition.
