### ISSUE TITLE
Empty S3 Lifecycle returns empty array instead of S3ResponseError

### ISSUE THREAD

**Issue by echiu64** [spulec/moto#356]
When the S3 Lifecycle is empty, it should return an exception vs an empty array.

e.g. in real life:
```
>>> b.get_lifecycle_config()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/echiu/anaconda/lib/python2.7/site-packages/boto/s3/bucket.py", line 1387, in get_lifecycle_config
    response.status, response.reason, body)
boto.exception.S3ResponseError: S3ResponseError: 404 Not Found
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchLifecycleConfiguration</Code><Message>The lifecycle configuration does not exist</Message><BucketName>myfirst-bucket</BucketName><RequestId>...</RequestId><HostId>...</HostId></Error>
```

In moto:
```
>>> @mock_s3
... def test():
...     conn = boto.connect_s3()
...     bucket = conn.create_bucket("moto-bucket")
...     bucket.get_lifecycle_config()
...
>>> test()
>>>
```
When you inspect "bucket" it's an empty array

**Comment by spulec** [comment]
Thanks for opening! Fixed with https://github.com/spulec/moto/commit/91fffbb83bfb2315635633f956d3b02c183a3165
