### ISSUE TITLE
stop ec2 instance failed with golang sdk: Unable to create moto backend app for empty service: "None"

### ISSUE THREAD

**Issue by WangXiangUSTC** [spulec/moto#3624]
## Reporting Bugs

1. Start localstack

```bash
SERVISCES=kinesis,s3 IMAGE_NAME=localstack/localstack:0.12.5 TMPDIR=/private$TMPDIR localstack -d start --docker
``` 

2. Create ec2 instance with aws client

```bash
aws --endpoint-url=http://127.0.0.1:4566 ec2 run-instances --image-id ami --count 1 --instance-type t2.micro --key-name test      
```

and can see the instance is created:

```bash
aws --endpoint-url=http://127.0.0.1:4566 ec2  describe-instances
```

3. Use golang code to stop this instance

```go
package main

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	awscfg "github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/credentials"
	"github.com/aws/aws-sdk-go-v2/service/ec2"
)

func main() {
	ctx := context.Background()
	opts := []func(*awscfg.LoadOptions) error{
		awscfg.WithRegion("us-east-1a"),

		awscfg.WithEndpointResolver(aws.EndpointResolverFunc(func(service, region string) (aws.Endpoint, error) {
			return aws.Endpoint{URL: "http://127.0.0.1:4566"}, nil
		})),
		awscfg.WithSharedConfigProfile("localstack"),
	}

	opts = append(opts, awscfg.WithCredentialsProvider(credentials.NewStaticCredentialsProvider(
		"test",
		"test",
		"",
	)))

	cfg, err := awscfg.LoadDefaultConfig(ctx, opts...)
	if err != nil {
		fmt.Println(err)
		return
	}
	ec2client := ec2.NewFromConfig(cfg)

	_, err = ec2client.StopInstances(context.TODO(), &ec2.StopInstancesInput{
		InstanceIds: []string{"i-07ad55738134bc40c"},
	})
	if err != nil {
		fmt.Println(err)
		return
	}
}
```

and the localstack print error:

```log
2021-01-28T13:34:48:WARNING:localstack.multiserver: Unable to create moto backend app for empty service: "None"
2021-01-28 13:34:48,369:API: Error on request:
Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/moto/server.py", line 173, in __call__
    return backend_app(environ, start_response)
TypeError: 'NoneType' object is not callable
```

**Comment by bpandola** [comment]
First of all, `us-east-1a` is not a valid region.  Second of all, you need to make sure that your custom endpoint resolver is properly configured with a region: `return aws.Endpoint{URL: "http://127.0.0.1:4566", SigningRegion: region}, nil`

Using your example code and changing the region to `us-east-1` and making the needed endpoint change resulted in a successful call to the moto server for me.

**Comment by WangXiangUSTC** [comment]
> First of all, `us-east-1a` is not a valid region. Second of all, you need to make sure that your custom endpoint resolver is properly configured with a region: `return aws.Endpoint{URL: "http://127.0.0.1:4566", SigningRegion: region}, nil`
> 
> Using your example code and changing the region to `us-east-1` and making the needed endpoint change resulted in a successful call to the moto server for me.

Thanks! It works for me!

But I have a question, I use aws client to describe ec2 instance, the result is as follow:
```json
{
    "Reservations": [
        {
            "Groups": [],
            "Instances": [
                {
                    "AmiLaunchIndex": 0,
                    "ImageId": "ami",
                    "InstanceId": "i-5424c5fcbf4cba60a",
                    "InstanceType": "t2.micro",
                    "KernelId": "None",
                    "KeyName": "test",
                    "LaunchTime": "2021-02-01T02:44:20+00:00",
                    "Monitoring": {
                        "State": "disabled"
                    },
                    "Placement": {
                        "AvailabilityZone": "us-east-1a",
                        "GroupName": "",
                        "Tenancy": "default"
                    },
                    "PrivateDnsName": "ip-10-32-158-103.ec2.internal",
                    "PrivateIpAddress": "10.32.158.103",
                    "ProductCodes": [],
                    "PublicDnsName": "ec2-54-214-42-115.compute-1.amazonaws.com",
                    "PublicIpAddress": "54.214.42.115",
                    "State": {
                        "Code": 16,
                        "Name": "running"
                    },
                    "StateTransitionReason": "",
                    "SubnetId": "subnet-7c21d116",
                    "VpcId": "vpc-7f39ff91",
                    "Architecture": "x86_64",
                    "BlockDeviceMappings": [
                        {
                            "DeviceName": "/dev/sda1",
                            "Ebs": {
                                "AttachTime": "2021-02-01T02:44:20+00:00",
                                "DeleteOnTermination": true,
                                "Status": "in-use",
                                "VolumeId": "vol-38aa5b98"
                            }
                        }
                    ],
                    "ClientToken": "ABCDE0000000000003",
                    "EbsOptimized": false,
                    "Hypervisor": "xen",
                    "NetworkInterfaces": [
                        {
                            "Association": {
                                "IpOwnerId": "000000000000",
                                "PublicIp": "54.214.42.115"
                            },
                            "Attachment": {
                                "AttachTime": "2015-01-01T00:00:00+00:00",
                                "AttachmentId": "eni-attach-3a2e9f7c",
                                "DeleteOnTermination": true,
                                "DeviceIndex": 0,
                                "Status": "attached"
                            },
                            "Description": "Primary network interface",
                            "Groups": [],
                            "MacAddress": "1b:2b:3c:4d:5e:6f",
                            "NetworkInterfaceId": "eni-a32e6b37",
                            "OwnerId": "000000000000",
                            "PrivateIpAddress": "10.32.158.103",
                            "PrivateIpAddresses": [
                                {
                                    "Association": {
                                        "IpOwnerId": "000000000000",
                                        "PublicIp": "54.214.42.115"
                                    },
                                    "Primary": true,
                                    "PrivateIpAddress": "10.32.158.103"
                                }
                            ],
                            "SourceDestCheck": true,
                            "Status": "in-use",
                            "SubnetId": "subnet-7c21d116",
                            "VpcId": "vpc-7f39ff91"
                        }
                    ],
                    "RootDeviceName": "/dev/sda1",
                    "RootDeviceType": "ebs",
                    "SecurityGroups": [],
                    "SourceDestCheck": true,
                    "StateReason": {
                        "Code": "",
                        "Message": ""
                    },
                    "VirtualizationType": "paravirtual"
                }
            ],
            "OwnerId": "000000000000",
            "ReservationId": "r-da1139ef"
        }
    ]
}
```
why the `AvailabilityZone` is `us-east-1a` but I need to update it to `us-east-1` in the code?

**Comment by bpandola** [comment]
Each region has multiple availability zones: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html

**Comment by WangXiangUSTC** [comment]
> Each region has multiple availability zones: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html

thanks！

**Comment by bblommers** [comment]
Thanks for the solution @bpandola! Happy to hear his is resolved.
