### ISSUE TITLE
IoT "create_topic_rule" operation fails on moto standalone server

### ISSUE THREAD

**Issue by pedro-dlfa** [spulec/moto#3676]
### how to reproduce the issue
* Start moto server: `moto_server`
* Then execute the following code in a python console
```python
        iot_client = boto3.client("iot", region_name="eu-west-1", endpoint_url="http://localhost:5000")
        iot_client.create_topic_rule(
            ruleName="TEST",
            topicRulePayload={
                'sql': "Select *",
                'ruleDisabled': False,
                'actions': [
                    {
                        'republish': {
                            'roleArn': 'arn:aws:iam::123456789012:role/iot_rule',
                            'topic': 'string',
                            'qos': 1
                        }
                    }
                ],
                'awsIotSqlVersion': '2016-03-23'
            }
        )
```

### what you expected to happen
The request succeeds and the IoT rule is created

### what actually happens
* `create_topic_rule` invocation returns the following error:
```
    def test_failure(self):
        iot_client = boto3.client("iot", region_name="eu-west-1", endpoint_url="http://localhost:5000")
>       iot_client.create_topic_rule(
            ruleName="TEST",
            topicRulePayload={
                'sql': "Select *",
                'ruleDisabled': False,
                'actions': [
                    {
                        'republish': {
                            'roleArn': 'arn:aws:iam::123456789012:role/iot_rule',
                            'topic': 'string',
                            'qos': 1
                        }
                    }
                ],
                'awsIotSqlVersion': '2016-03-23'
            }
        )

iot_client = <botocore.client.IoT object at 0x110c46400>
self       = <test_things_groups_event_processor.TestThingsGroupEventProcessor object at 0x10d4eed60>

test_things_groups_event_processor.py:140: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../venv/lib/python3.8/site-packages/botocore/client.py:316: in _api_call
    return self._make_api_call(operation_name, kwargs)
        args       = ()
        kwargs     = {'ruleName': 'TEST',
 'topicRulePayload': {'actions': [{'republish': {'qos': 1,
                                                 'roleArn': 'arn:aws:iam::123456789012:role/iot_rule',
                                                 'topic': 'string'}}],
                      'awsIotSqlVersion': '2016-03-23',
                      'ruleDisabled': False,
                      'sql': 'Select *'}}
        operation_name = 'CreateTopicRule'
        py_operation_name = 'create_topic_rule'
        self       = <botocore.client.IoT object at 0x110c46400>
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <botocore.client.IoT object at 0x110c46400>
operation_name = 'CreateTopicRule'
api_params = {'ruleName': 'TEST', 'topicRulePayload': {'actions': [{'republish': {'qos': 1, 'roleArn': 'arn:aws:iam::123456789012:role/iot_rule', 'topic': 'string'}}], 'awsIotSqlVersion': '2016-03-23', 'ruleDisabled': False, 'sql': 'Select *'}}

    def _make_api_call(self, operation_name, api_params):
        operation_model = self._service_model.operation_model(operation_name)
        service_name = self._service_model.service_name
        history_recorder.record('API_CALL', {
            'service': service_name,
            'operation': operation_name,
            'params': api_params,
        })
        if operation_model.deprecated:
            logger.debug('Warning: %s.%s() is deprecated',
                         service_name, operation_name)
        request_context = {
            'client_region': self.meta.region_name,
            'client_config': self.meta.config,
            'has_streaming_input': operation_model.has_streaming_input,
            'auth_type': operation_model.auth_type,
        }
        request_dict = self._convert_to_request_dict(
            api_params, operation_model, context=request_context)
    
        service_id = self._service_model.service_id.hyphenize()
        handler, event_response = self.meta.events.emit_until_response(
            'before-call.{service_id}.{operation_name}'.format(
                service_id=service_id,
                operation_name=operation_name),
            model=operation_model, params=request_dict,
            request_signer=self._request_signer, context=request_context)
    
        if event_response is not None:
            http, parsed_response = event_response
        else:
            http, parsed_response = self._make_request(
                operation_model, request_dict, request_context)
    
        self.meta.events.emit(
            'after-call.{service_id}.{operation_name}'.format(
                service_id=service_id,
                operation_name=operation_name),
            http_response=http, parsed=parsed_response,
            model=operation_model, context=request_context
        )
    
        if http.status_code >= 300:
            error_code = parsed_response.get("Error", {}).get("Code")
            error_class = self.exceptions.from_code(error_code)
>           raise error_class(parsed_response, operation_name)
E           botocore.exceptions.ClientError: An error occurred (500) when calling the CreateTopicRule operation (reached max retries: 4): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
E           <title>500 Internal Server Error</title>
E           <h1>Internal Server Error</h1>
E           <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

api_params = {'ruleName': 'TEST',
 'topicRulePayload': {'actions': [{'republish': {'qos': 1,
                                                 'roleArn': 'arn:aws:iam::123456789012:role/iot_rule',
                                                 'topic': 'string'}}],
                      'awsIotSqlVersion': '2016-03-23',
                      'ruleDisabled': False,
                      'sql': 'Select *'}}
error_class = <class 'botocore.exceptions.ClientError'>
error_code = '500'
event_response = None
handler    = <function inject_api_version_header_if_needed at 0x10c3fb040>
http       = <botocore.awsrequest.AWSResponse object at 0x110c665e0>
operation_model = OperationModel(name=CreateTopicRule)
operation_name = 'CreateTopicRule'
parsed_response = {'Error': {'Code': '500',
           'Message': '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 '
                      'Final//EN">\n'
                      '<title>500 Internal Server Error</title>\n'
                      '<h1>Internal Server Error</h1>\n'
                      '<p>The server encountered an internal error and was '
                      'unable to complete your request. Either the server is '
                      'overloaded or there is an error in the '
                      'application.</p>\n'},
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '290',
                                      'content-type': 'text/html; '
                                                      'charset=utf-8',
                                      'date': 'Thu, 11 Feb 2021 16:30:02 GMT',
                                      'server': 'Werkzeug/1.0.1 Python/3.8.2'},
                      'HTTPStatusCode': 500,
                      'MaxAttemptsReached': True,
                      'RetryAttempts': 4}}
request_context = {'auth_type': None,
 'client_config': <botocore.config.Config object at 0x110c465b0>,
 'client_region': 'eu-west-1',
 'has_streaming_input': False,
 'timestamp': '20210211T163002Z'}
request_dict = {'body': b'{"sql": "Select *", "ruleDisabled": false, "actions": [{"republish":'
         b' {"roleArn": "arn:aws:iam::123456789012:role/iot_rule", "topic": "st'
         b'ring", "qos": 1}}], "awsIotSqlVersion": "2016-03-23"}',
 'context': {'auth_type': None,
             'client_config': <botocore.config.Config object at 0x110c465b0>,
             'client_region': 'eu-west-1',
             'has_streaming_input': False,
             'timestamp': '20210211T163002Z'},
 'headers': {'User-Agent': 'Boto3/1.14.40 Python/3.8.2 Darwin/18.7.0 '
                           'Botocore/1.17.40'},
 'method': 'POST',
 'query_string': {},
 'url': 'http://localhost:5000/rules/TEST',
 'url_path': '/rules/TEST'}
self       = <botocore.client.IoT object at 0x110c46400>
service_id = 'iot'
service_name = 'iot'

../../../venv/lib/python3.8/site-packages/botocore/client.py:635: ClientError

```

* `moto_server` reports the following stacktrace:
```
127.0.0.1 - - [11/Feb/2021 17:30:02] "POST /rules/TEST HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/opt/airbus/src/iot_platform/ssib/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/opt/airbus/src/iot_platform/ssib/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/opt/airbus/src/iot_platform/ssib/venv/lib/python3.8/site-packages/moto/server.py", line 166, in __call__
    backend_app = self.get_application(environ)
  File "/opt/airbus/src/iot_platform/ssib/venv/lib/python3.8/site-packages/moto/server.py", line 141, in get_application
    app = self.create_app(backend)
  File "/opt/airbus/src/iot_platform/ssib/venv/lib/python3.8/site-packages/moto/server.py", line 213, in create_backend_app
    backend = list(backends.get_backend(service).values())[0]
  File "/opt/airbus/src/iot_platform/ssib/venv/lib/python3.8/site-packages/moto/backends.py", line 96, in get_backend
    module_name, backends_name = BACKENDS[name]
KeyError: None
```

**what version of Moto you're using**
Version: 1.3.16, with standalone server

**Comment by bpandola** [comment]
Try with the [latest dev version](https://pypi.org/project/moto/1.3.17.dev256/).  Should work.

**Comment by pedro-dlfa** [comment]
It works 🎉 
Thanks for the quick feedback!

**Comment by pedro-dlfa** [comment]
Hi there,
Just a question: do you know or have an estimation of when will be officially released the new version that fixes the issue?
