### ISSUE TITLE
Enhancement: Implement instance filtering by subnet-id

### ISSUE THREAD

**Issue by tony-dot-sh** [spulec/moto#3693]
When attempting `aws --endpoint-url=http://localhost:5000 --region eu-west-1 ec2 describe-instances --filters Name=subnet-id,Values=subnet-db124fe0` moto spits out:

`NotImplementedError: Filter dicts have not been implemented in Moto for 'subnet-id' yet.` is the error returned when attempting to filter instances by `subnet-id`:

Per [AWS API Docs](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html) `subnet-id` is a valid resource-type to filter by.

Environment:
OS: Ubuntu 20.10
Python: 3.8.6
Go: 1.15.6
Moto: pulled d8097b24dc25c5435e99802cc41921ae5947f778

Full Stacktrace:
```python
Error on request:
Traceback (most recent call last):
  File "venv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "venv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "moto/server.py", line 177, in __call__
    self.killReceived = True
  File "venv/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "venv/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "venv/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "venv/lib/python3.8/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "moto/core/utils.py", line 151, in __call__
    result = self.callback(request, request.url, {})
  File "moto/core/responses.py", line 202, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "moto/core/responses.py", line 312, in _dispatch
    return self.call_action()
  File "moto/core/responses.py", line 402, in call_action
    response = method()
  File "moto/ec2/responses/instances.py", line 28, in describe_instances
    reservations = self.ec2_backend.all_reservations(filters=filter_dict)
  File "moto/ec2/models.py", line 1152, in all_reservations
    reservations = filter_reservations(reservations, filters)
  File "moto/ec2/utils.py", line 418, in filter_reservations
    if passes_filter_dict(instance, filter_dict):
  File "moto/ec2/utils.py", line 397, in passes_filter_dict
    raise NotImplementedError(
NotImplementedError: Filter dicts have not been implemented in Moto for 'subnet-id' yet. Feel free to open an issue at https://github.com/issues
```

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.17.dev268
