### ISSUE TITLE
Mocked DynamoDB throws wrong error when table doesn't exist

### ISSUE THREAD

**Issue by max-reify** [spulec/moto#3695]
## Impact

I am unable to use moto to accurately test code that detects when a DynamoDB table is not replicated in the current region

## Reproduce

```python
from moto import mock_dynamodb2
import boto3

@mock_dynamodb2
def repro():
  client = boto3.client('dynamodb', 'us-east-1')
  result = client.get_item(TableName='foo', Key={'site-id': {'S': 'foo'}})
```

## Expected result

`ResourceNotFound` raised. Here's the stack trace from boto3 for a live API request:

```
  File "test.py", line 3, in <module>
    client.get_item(TableName='foo', Key={'site-id': {'S': 'foo'}})
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetItem operation: Requested resource not found
```

## Actual result

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv/lib/python3.9/site-packages/moto/core/models.py", line 100, in wrapper
    result = func(*args, **kwargs)
  File "<stdin>", line 4, in test_my_model_save
  File "venv/lib/python3.9/site-packages/botocore/client.py", line 337, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "venv/lib/python3.9/site-packages/botocore/client.py", line 656, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the GetItem operation: Validation Exception
```

## Versions
- Python 3.9.0
- Moto 1.3.16
- botocore 1.18.0

**Comment by bblommers** [comment]
Thanks for raising this @max-reify. Doesn't look like we're explicitly checking for this scenario yet, so marking it as an enhancement

**Comment by bblommers** [comment]
This is now part of moto >= 1.3.17.dev274
