### ISSUE TITLE
mock_dynamodb2 fails to update field that is used in a Global Secondary Index

### ISSUE THREAD

**Issue by h0wser** [spulec/moto#3760]
In the newest version of moto 2.0.1, when calling update_item on a field that is used as a key in a GSI, the operation triggers a ValidationException saying that an AttributeValue may not contain an empty string.

**how to reproduce the issue**

Save the following code to .py file and run.

``` python
from moto import mock_dynamodb2
import boto3

with mock_dynamodb2():
    name = "TestTable"
    conn = boto3.client("dynamodb", region_name="eu-west-2", aws_access_key_id="ak", aws_secret_access_key="sk")
    conn.create_table(
        TableName=name,
        KeySchema=[{"AttributeName": "main_key", "KeyType": "HASH"}],
        AttributeDefinitions=[{"AttributeName": "main_key", "AttributeType": "S"},
            {"AttributeName": "index_key", "AttributeType": "S"}],
        ProvisionedThroughput={"ReadCapacityUnits": 5, "WriteCapacityUnits": 5},
        GlobalSecondaryIndexes=[
            {
                "IndexName": "test_index",
                "KeySchema": [
                    {
                        "AttributeName": "index_key",
                        "KeyType": "HASH"
                    }
                ],
                "Projection": {
                    "ProjectionType": "ALL",
                },
                "ProvisionedThroughput": {"ReadCapacityUnits": 1, "WriteCapacityUnits": 1}
            }
        ]
    )

    conn.put_item(
        TableName=name,
        Item={
            "main_key": {"S": "testkey1"},
            "extra_data": {"S": "testdata"},
            "index_key": {"S": "indexkey1"}
        },
    )

    resp = conn.update_item(
        TableName=name,
        Key={"main_key": {"S": "testkey1"}},
        UpdateExpression="set index_key=:new_index_key",
        ExpressionAttributeValues={":new_index_key": {"S": "new_value"}}
    )

    print(resp)
```

**what you expected to happen**
That the attribute index_key updates successfully.

I have validated that this code runs correctly against dynamodb proper without issues. It also works under the 1.3.6 version of moto.

**what actually happens**
```
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    resp = conn.update_item(
  File "/home/h0wser/.local/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/h0wser/.local/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the UpdateItem operation: One or more parameter values were invalid: An AttributeValue may not contain an empty string
```

**what version of Moto you're using**
```
boto==2.49.0
boto3==1.17.22
botocore==1.20.22
moto==2.0.1
```
Installed via pip.

**Comment by bblommers** [comment]
Thanks for raising this @h0wser - looks like a bug indeed.

**Comment by mm-zhe** [comment]
I am seeing the same bug,  any workaround?

**Comment by JamesBelchamber** [comment]
Urgh! Spent an hour on this today :upside_down_face: awesome to see a fix already written - @bblommers is there any chance it'll make it into the next release?

**Comment by bblommers** [comment]
That will depend on when another maintainer approves the fix @JamesBelchamber - I have no control over that timeline I'm afraid

**Comment by JamesBelchamber** [comment]
I was hoping the response would be something I could muck in and help with :sweat_smile: okay, understood, thanks for getting it in so quickly :)

**Comment by mfogel** [comment]
This bug appears to be still happening in v2.0.5. @spulec is there anything I can do to help @bblommers 's PR move along? Thanks.

**Comment by bblommers** [comment]
This is now part of moto >= 2.0.10 @JamesBelchamber
