### ISSUE TITLE
Route53: creating a health check with type of CALCULATED fails

### ISSUE THREAD

**Issue by newtondev** [spulec/moto#3787]
When trying to create a CALCULATED health check for aggregating health check alarms, the response from the moto library fails to parse. However when executing the same request to an AWS account it succeeds with the creation.

Versions:
- Python @ 3.8
- Moto @ 2.0.2
- Botocore @ 1.20.30

Example test code:
```
@mock_route53
def test_create_calculated_health_check(self):
    client = boto3.client('route53')

    response = client.create_health_check(
        CallerReference='test-route53-health-HealthCheck-ZHV123',
        HealthCheckConfig={
            'Type':             'CALCULATED',
            'Inverted':         False,
            'Disabled':         False,
            'HealthThreshold':  1,
            'ChildHealthChecks': [
                '96f93979-70e9-4d55-b299-fab4db2931e6'
            ]
        },
    )

    self.assertIsNotNone(response)
```

Stacktrace:
```
======================================================================
ERROR: test_create_calculated_health_check (__main__.HealthChecksTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/moto/core/models.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "test_health_checks.py", line 43, in test_create_calculated_health_check
    response = client.create_health_check(
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/client.py", line 662, in _make_api_call
    http, parsed_response = self._make_request(
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/client.py", line 682, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/endpoint.py", line 134, in _send_request
    success_response, exception = self._get_response(
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/endpoint.py", line 166, in _get_response
    success_response, exception = self._do_get_response(
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/endpoint.py", line 217, in _do_get_response
    parsed_response = parser.parse(
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/parsers.py", line 245, in parse
    parsed = self._do_parse(response, shape)
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/parsers.py", line 809, in _do_parse
    self._add_modeled_parse(response, shape, final_parsed)
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/parsers.py", line 818, in _add_modeled_parse
    self._parse_payload(response, shape, member_shapes, final_parsed)
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/parsers.py", line 859, in _parse_payload
    body_parsed = self._parse_shape(shape, original_parsed)
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/parsers.py", line 312, in _parse_shape
    return handler(shape, node)
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/parsers.py", line 388, in _handle_structure
    parsed[member_name] = self._parse_shape(
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/parsers.py", line 312, in _parse_shape
    return handler(shape, node)
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/parsers.py", line 388, in _handle_structure
    parsed[member_name] = self._parse_shape(
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/parsers.py", line 312, in _parse_shape
    return handler(shape, node)
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/parsers.py", line 388, in _handle_structure
    parsed[member_name] = self._parse_shape(
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/parsers.py", line 312, in _parse_shape
    return handler(shape, node)
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/parsers.py", line 174, in _get_text_content
    return func(self, shape, text)
  File "/Users/craignewton/insided/ops-10/insided/community-setup/venv/lib/python3.8/site-packages/botocore/parsers.py", line 486, in _handle_integer
    return int(text)
ValueError: invalid literal for int() with base 10: 'None'
```

**Comment by bblommers** [comment]
Looks like there are two issues (at least..) with the calculated health-check:
 - It returns IPAddress and Port in the response, when it shouldn't
 - It has port as 'None', with throws the above error.

Are you able to share an example response for the test case you provided, @newtondev? Just want to make sure I haven't missed anything else

**Comment by newtondev** [comment]
@bblommers thanks for picking this up. The only other issue I had was with the CallerReference as mentioned in this ticket: https://github.com/spulec/moto/issues/3786
