### ISSUE TITLE
Security Group revoke ingress rule fails if not revoking all IPs within an IpPermission object

### ISSUE THREAD

**Issue by will-schneble** [spulec/moto#3970]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request

### Python and moto versions

* Python 3.8.3
* moto==2.0.8

### Affected Resource(s)

* ec2.revoke_security_group_ingress
* ec2.SecurityRule

### Expected Behavior

Trying to authorize IP ingress rules for a security group and then revoke some of the applied rules. Expected moto to remove the ingress IP rule for 10.0.0.0/32 for port 22 and protocol tcp.

### Actual Behavior

An exception is thrown for `InvalidPermission.NotFound` because moto [SecurityRule comparison compares the entire IpRanges collection](https://github.com/spulec/moto/blob/7947b1e00133985775add3dd62b20d4fe9b2e652/moto/ec2/models.py#L2005) and not if each IP in the `ec2.revoke_security_group_ingress` request's IpPermission object is in the SG's IpPermission objects. This means when using moto a user can only revoke entire IpPermission objects in the SG (and not a single IP within an object) which is not the same behavior as boto3.

### Steps to Reproduce

```python
import boto3
import moto

isMocking = True
ips = [
  '10.0.0.0/32',
  '10.0.0.1/32',
  '10.0.0.2/32',
]

if isMocking:
  mock = moto.mock_ec2()
  mock.start()
print('isMocking=%s' % isMocking)

s = boto3.Session(profile_name='default')
c = s.client('ec2')

groupId = c.create_security_group(
  Description="TEST",
  GroupName="TEST"
)['GroupId']
print('Created Security Group with ID: %s' % groupId)
try:
  c.authorize_security_group_ingress(
    GroupId=groupId,
    IpPermissions=[
      {
        'FromPort': 22,
        'ToPort': 22,
        'IpProtocol': 'tcp',
        'IpRanges': [
          {
            'CidrIp': x
          } for x in ips
        ]
      }
    ]
  )

  sg = c.describe_security_groups(GroupIds=[groupId])['SecurityGroups'][0]
  tmp = [x['CidrIp'] for y in sg['IpPermissions'] for x in y['IpRanges'] if y['ToPort'] == 22 and y['FromPort'] == 22 and y['IpProtocol'] == 'tcp']
  assert set(ips) == set(tmp), "Expected permission set tcp:22 to contain %s but got %s" % (ips, tmp)
  print('Security Group rules added')

  c.revoke_security_group_ingress(
    GroupId=groupId,
    IpPermissions=[
      {
        'FromPort': 22,
        'ToPort': 22,
        'IpProtocol': 'tcp',
        'IpRanges': [
          {
            'CidrIp': x
          } for x in ips[:1]
        ]
      }
    ]
  )

  sg = c.describe_security_groups(GroupIds=[groupId])['SecurityGroups'][0]
  tmp = [x['CidrIp'] for y in sg['IpPermissions'] for x in y['IpRanges'] if y['ToPort'] == 22 and y['FromPort'] == 22 and y['IpProtocol'] == 'tcp']
  assert set(ips[1:]) == set(tmp), "Expected permission set tcp:22 to contain %s but got %s" % (ips[1:], tmp)
  print('Security Group rule revoked')
finally:
  c.delete_security_group(GroupId=groupId)
  print('Security Group deleted')
  if isMocking:
    mock.stop()
```

1. Run the above script with `isMocking=True`.
2. Get an authenticated session in ~/.aws/credentials for the default profile (or if you have long term creds in the default profile then skip this step).
3. Run the above script with `isMocking=False`

### Debug Output

```
runfile('C:/Users/will/Downloads/moto_sg_example.py', wdir='C:/Users/will/Downloads')
isMocking=True
Created Security Group with ID: sg-81d77cdb
Security Group rules added
Security Group deleted
Traceback (most recent call last):

  File "C:\Users\will\Downloads\moto_sg_example.py", line 52, in <module>
    c.revoke_security_group_ingress(

  File "C:\Users\will\Anaconda3\lib\site-packages\botocore\client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)

  File "C:\Users\will\Anaconda3\lib\site-packages\botocore\client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)

ClientError: An error occurred (InvalidPermission.NotFound) when calling the RevokeSecurityGroupIngress operation: The specified rule does not exist in this security group

# New python run with isMocking=False
runfile('C:/Users/will/Downloads/moto_sg_example.py', wdir='C:/Users/will/Downloads')
isMocking=False
Created Security Group with ID: sg-0501bd1cc0854929f
Security Group rules added
Security Group rule revoked
Security Group deleted
```

### Important Factoids

Additionally, moto stores SecurityRules with the same protocol, fromPort, and toPort in different IpPermission objects which is not the behavior of AWS boto3 where AWS will merge similar IpPermission objects together. For example, moto will have
```json
{
  "IpPermissions": [
    {
      "FromPort": 22,
      "ToPort": 22,
      "Protocol": "tcp",
      "IpRanges": [
        {
          "CidrIp": "10.0.0.0/32"
        }
      ]
    },
    {
      "FromPort": 22,
      "ToPort": 22,
      "Protocol": "tcp",
      "IpRanges": [
        {
          "CidrIp": "10.0.0.1/32"
        }
      ]
    }
  ]
}
```
if each IP was added in a different ec2.authorize_security_group_ingress request. Here is some code to reproduce this:
```python
import boto3
import moto

mock = moto.mock_ec2()
mock.start()

c = boto3.client('ec2')
groupId = c.create_security_group(
  Description="TEST",
  GroupName="TEST"
)['GroupId']
for x in ['10.0.0.0/32', '10.0.0.1/32']:
  c.authorize_security_group_ingress(
    GroupId=groupId,
    IpPermissions=[
      {
        'FromPort': 22,
        'ToPort': 22,
        'IpProtocol': 'tcp',
        'IpRanges': [
          {
            'CidrIp': x
          }
        ]
      }
    ]
  )
print(c.describe_security_groups(GroupIds=[groupId])['SecurityGroups'][0]['IpPermissions'])
c.delete_security_group(GroupId=groupId)
mock.stop()
```

**Comment by bblommers** [comment]
Thanks for raising this and providing the scripts/tests to verify this @will-schneble - very helpful!
