### ISSUE TITLE
AWS Lambda error response is mixed up with docker container logs

### ISSUE THREAD

**Issue by dazza-codes** [spulec/moto#3992]
Lambda function:

```python
def lambda_handler(event, context):
    raise RuntimeError("Oops")
```

The moto response is like:

```python
{'FunctionError': 'Handled',
 'Payload': <StreamingBody at 0x7f2e5c60cd20 for ClientResponseContentProxy at 0x7f2e5c57adc0>,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '748',
                                      'content-type': 'text/html; '
                                                      'charset=utf-8',
                                      'date': 'Mon, 07 Jun 2021 01:07:15 GMT',
                                      'server': 'Werkzeug/2.0.1 Python/3.7.10',
                                      'x-amz-crc32': '1107850810',
                                      'x-amz-function-error': 'Handled',
                                      'x-amzn-requestid': 'W2G2JRHZK5PB3NC151UWZFBCV27KHMZDMR6BILHQEPDCY6BGLBSY'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'W2G2JRHZK5PB3NC151UWZFBCV27KHMZDMR6BILHQEPDCY6BGLBSY',
                      'RetryAttempts': 0},
 'StatusCode': 200}
```

That looks correct (i.e. a 200 response with a  'FunctionError').  But the data is a mixture of logging and the error:

```
('error running lambda: lambda invoke failed output: \x1b[32mSTART RequestId: '
 'a62e5f44-8555-1644-d467-365ce24ec49e Version: 1\x1b[0m\n'
 "event: {'action': 'runtime-error'}\n"
 '[ERROR] RuntimeError: runtime-error\n'
 'Traceback (most recent call last):\n'
 '\xa0\xa0File "/var/task/lambda_function.py", line 12, in lambda_handler\n'
 '\xa0\xa0\xa0\xa0raise RuntimeError(action)\n'
 '\x1b[32mEND RequestId: a62e5f44-8555-1644-d467-365ce24ec49e\x1b[0m\n'
 '\x1b[32mREPORT RequestId: a62e5f44-8555-1644-d467-365ce24ec49e\tInit '
 'Duration: 160.93 ms\tDuration: 3.14 ms\tBilled Duration: 4 ms\tMemory Size: '
 '128 MB\tMax Memory Used: 23 MB\t\x1b[0m\n'
 '\n'
 '{"errorType":"RuntimeError","errorMessage":"runtime-error","stackTrace":["  '
 'File \\"/var/task/lambda_function.py\\", line 12, in lambda_handler\\n    '
 'raise RuntimeError(action)\\n"]}\n')
```

The moto error response is a string that cannot be parsed as JSON.

The actual AWS Lambda response for something like this is:

```python
{'ExecutedVersion': '$LATEST',
 'FunctionError': 'Unhandled',
 'Payload': <StreamingBody at 0x7faa8b9985f0 for ClientResponseContentProxy at 0x7faa8b9985a0>,
 'ResponseMetadata': {'HTTPHeaders': {'connection': 'keep-alive',
                                      'content-length': '178',
                                      'content-type': 'application/json',
                                      'date': 'Mon, 07 Jun 2021 01:00:50 GMT',
                                      'x-amz-executed-version': '$LATEST',
                                      'x-amz-function-error': 'Unhandled',
                                      'x-amzn-remapped-content-length': '0',
                                      'x-amzn-requestid': 'xxx-snipped',
                                      'x-amzn-trace-id': 'xxx-snipped'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'xxx-snipped',
                      'RetryAttempts': 0},
 'StatusCode': 200}
```

The AWS Lambda response has `application/json` content type and the error in the response body is like:

```python
{'errorMessage': 'Oops',
 'errorType': 'RuntimeError',
 'stackTrace': ['  File "/var/task/lambda_function.py", line 23, in '
                'lambda_handler\n'
                '    raise RuntimeError("Oops")\n']}
```

## versions

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

$ docker --version
Docker version 20.10.7, build f0df350

$ python --version
Python 3.7.10

$ poetry show moto
name         : moto
version      : 1.3.16
description  : A library that allows your python tests to easily mock out the boto library

dependencies
 - aws-xray-sdk >=0.93,<0.96 || >0.96
 - boto >=2.36.0
 - boto3 >=1.9.201
 - botocore >=1.12.201
 - cfn-lint >=0.4.0
 - cryptography >=2.3.0
 - docker >=2.5.1
 - ecdsa <0.15
 - flask *
 - idna >=2.5,<3
 - Jinja2 >=2.10.1
 - jsondiff >=1.1.2
 - MarkupSafe <2.0
 - mock *
 - more-itertools *
 - python-dateutil >=2.1,<3.0.0
 - python-jose >=3.1.0,<4.0.0
 - pytz *
 - PyYAML >=5.1
 - requests >=2.5
 - responses >=0.9.0
 - six >1.9
 - sshpubkeys >=3.1.0
 - werkzeug *
 - xmltodict *
 - zipp *

```

**Comment by bblommers** [comment]
Hi @dazza-codes, I'm pretty sure this has been improved/fixed since 1.3.16.
Are you able to upgrade to 2.x and verify this?

(Keep in mind that the installation method has changed since 2.x: https://github.com/spulec/moto/issues/3722)

**Comment by dazza-codes** [comment]
That's good to hear.  Sorry, I try to avoid major.0.0 releases until they get to something like >= major.1.0 - I don't have a lot of time just now to check the change logs and try it out.  Congrats on the 2.x release.

**Comment by bblommers** [comment]
> I try to avoid major.0.0 releases until they get to something like >= major.1.0

Understandable!

Just tested this out, actually, and this is still an issue. The PR I was thinking about only fixed the success response, which had the same issue. Marking this as a bug. 👍

**Comment by dazza-codes** [comment]
If it helps, a branch off master of https://github.com/dazza-codes/aio-aws could test a new release for moto - that repo has some useful moto mocks for lambda tests.

- https://github.com/dazza-codes/aio-aws/blob/master/tests/test_aio_aws_lambda.py

Some skips or comments point to issues here on moto.
