### ISSUE TITLE
Unable to create StepScaling policies with mock_applicationautoscaling

### ISSUE THREAD

**Issue by rkstrickland** [spulec/moto#4053]
Sample code to re-produce:

```
from moto import mock_applicationautoscaling
import boto3

def show_problem_with_step_scaling():
    with mock_applicationautoscaling():
        conn = boto3.client("application-autoscaling", region_name ="us-east-1")
        conn.put_scaling_policy(**{
            "ServiceNamespace": "ecs",
            "ScalableDimension": "ecs:DesiredCount",
            "ResourceId": "service/clustername/servicename",
            "StepScalingPolicyConfiguration": {
                "AdjustmentType": "ChangeInCapacity",
                "MetricAggregationType": "Maximum",
                "StepAdjustments": [
                    {
                        "ScalingAdjustment": 85,
                    }
                ],
                "Cooldown": 8605,
                "MinAdjustmentMagnitude": 1
            },
            "PolicyType": "StepScaling",
            "PolicyName": "film_fund_green"
        })

show_problem_with_step_scaling()
```

Output from code:

```
Traceback (most recent call last):
  File "/Users/rossstrickland/repos/isc/problem.py", line 26, in <module>
    show_problem_with_step_scaling()
  File "/Users/rossstrickland/repos/isc/problem.py", line 7, in show_problem_with_step_scaling
    conn.put_scaling_policy(**{
  File "/Users/rossstrickland/repos/isc/isc.venv/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/rossstrickland/repos/isc/isc.venv/lib/python3.9/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the PutScalingPolicy operation: Unknown policy type StepScaling specified.
```

Using v2.0.9, but looks like issue is still present in newer code.

I've tracked the issue down to this line of code:

https://github.com/spulec/moto/blob/2.0.10/moto/applicationautoscaling/models.py#L314

`"policy_type"` should be `policy_type`

**Comment by bblommers** [comment]
This is now part of moto >= 2.0.11.dev27
