### ISSUE TITLE
S3 IAM: Head object for objects without permissions raises wrong error.

### ISSUE THREAD

**Issue by thesketh** [spulec/moto#4059]
Hi there! Thanks for writing this library, it's been exceptionally useful for testing error handling of boto code under simulated real life conditions! I've been writing some tests which mock IAM perms for S3 and one of my fake accounts with zero permissions receives a 404 every time it tries to HEAD an object in S3. Against the live AWS endpoint these are 403 errors, regardless of whether or not the file exists.

Here's a minimum working example:

```python
import boto3
from botocore.exceptions import ClientError
from moto import mock_s3, mock_iam
from moto.core import set_initial_no_auth_action_count


def head_fake_object():
    """Head an S3 object we should have no access to."""
    resource = boto3.resource(
        "s3",
        aws_access_key_id="fake_key",
        aws_secret_access_key="fake_pass"
    )

    obj = resource.Object("myfakebucket", "myfakekey")
    try:
        obj.load()
    except ClientError as err:
        response = err.response
        status_code = response["ResponseMetadata"]["HTTPStatusCode"]
        assert status_code == 403


if __name__ == "__main__":
    # Using AWS.
    print("Trying to head object with no perms (against live AWS).")
    head_fake_object()
    print("Successfully returns 403.")

    # Using moto.
    print("Trying to head object with no perms (against moto endpoint).")
    mock_s3().start()
    mock_iam().start()
    decorator = set_initial_no_auth_action_count(0)
    decorator(head_fake_object)()
    # Assertion error here.
    print("Successfully returns 403.")
```

This code outputs the following:

```
Trying to head object with no perms (against live AWS).
Successfully returns 403.
Trying to head object with no perms (against moto endpoint).
Traceback (most recent call last):
  File "example.py", line 17, in head_fake_object
    obj.load()
  File "/home/thesketh/.anaconda/envs/blobject/lib/python3.8/site-packages/boto3/resources/factory.py", line 505, in do_action
    response = action(self, *args, **kwargs)
  File "/home/thesketh/.anaconda/envs/blobject/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/thesketh/.anaconda/envs/blobject/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/thesketh/.anaconda/envs/blobject/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the HeadObject operation: The specified bucket does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 35, in <module>
    decorator(head_fake_object)()
  File "/home/thesketh/.anaconda/envs/blobject/lib/python3.8/site-packages/moto/core/responses.py", line 165, in wrapper
    result = function(*args, **kwargs)
  File "example.py", line 21, in head_fake_object
    assert status_code == 403
AssertionError
```

**Comment by bblommers** [comment]
Thanks for raising this @thesketh. Looks like we're authenticating for all other HTTP methods (GET/PUT/POST/DELETE), but not for HEAD requests. Marking it as a bug.
