### ISSUE TITLE
The describe_instance_types action has not been implemented

### ISSUE THREAD

**Issue by ZuluPro** [spulec/moto#421]
As describe in boto's issue (https://github.com/boto/boto/issues/3137), function for describe all instance has not been implemented at AWS. However it is implemented on other systems like Eucalyptus.

```
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/serving.py", line 180, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/serving.py", line 168, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/moto/server.py", line 57, in __call__
    return backend_app(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.4/dist-packages/moto/core/utils.py", line 77, in __call__
    result = self.callback(request, request.url, {})
  File "/usr/local/lib/python3.4/dist-packages/moto/core/responses.py", line 87, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/moto/core/responses.py", line 128, in _dispatch
    return self.call_action()
  File "/usr/local/lib/python3.4/dist-packages/moto/core/responses.py", line 154, in call_action
    raise NotImplementedError("The {0} action has not been implemented".format(action))
NotImplementedError: The describe_instance_types action has not been implemented
```

**Comment by ZuluPro** [comment]
I've began to implement that here: https://github.com/spulec/moto/compare/master...ZuluPro:instancetypes?expand=1

What do you think about ?

**Comment by spulec** [comment]
That looks good. You should open a PR
