### ISSUE TITLE
boto3 and EMR not working -- JSON responses

### ISSUE THREAD

**Issue by alexdebrie** [spulec/moto#427]
When I try to test `run_job_flow` with `boto3`, I get the following error:

```
Traceback (most recent call last):
  File "/Users/alex.debrie/Envs/findapp-test/lib/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "/Users/alex.debrie/emr/test_schemas.py", line 51, in test_can_launch_cluster
    r = client.run_job_flow(**config)
  File "/Users/alex.debrie/Envs/findapp-test/lib/python2.7/site-packages/botocore/client.py", line 269, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/alex.debrie/Envs/findapp-test/lib/python2.7/site-packages/botocore/client.py", line 324, in _make_api_call
    operation_model, request_dict)
  File "/Users/alex.debrie/Envs/findapp-test/lib/python2.7/site-packages/botocore/endpoint.py", line 111, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/alex.debrie/Envs/findapp-test/lib/python2.7/site-packages/botocore/endpoint.py", line 138, in _send_request
    request, operation_model, attempts)
  File "/Users/alex.debrie/Envs/findapp-test/lib/python2.7/site-packages/botocore/endpoint.py", line 191, in _get_response
    operation_model.output_shape)),
  File "/Users/alex.debrie/Envs/findapp-test/lib/python2.7/site-packages/botocore/parsers.py", line 208, in parse
    parsed = self._do_parse(response, shape)
  File "/Users/alex.debrie/Envs/findapp-test/lib/python2.7/site-packages/botocore/parsers.py", line 534, in _do_parse
    original_parsed = json.loads(body)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

From what I can tell, `moto` returns XML responses for EMR ([see here](https://github.com/spulec/moto/blob/master/moto/emr/responses.py#L106)). You can only use EMR with the `client` interface (rather than the `resources` interface), which means it relies on the data files in `botocore`. The [EMR data file](https://github.com/boto/botocore/blob/develop/botocore/data/emr/2009-03-31/service-2.json#L12) says it returns JSON, rather than XML, so it's choking when it gets XML from moto. The [EMR Api Reference](http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_RunJobFlow.html) also indicates it returns JSON (scroll to the very bottom).

I'm happy to implement the JSON responses, but I could use a little guidance. Any tips on how to check whether JSON or XML should be returned? I see a similar issue happened with SNS in #402. My request has a `Content-Type` of `u'application/x-amz-json-1.1'`, so maybe I'll just check for that?

**Comment by spulec** [comment]
Yes, that is the route we need to go. If you get some time, that would be great!

Checking the `Content-Type` is the correct approach. Doing something very similar to #404 is what we want here.

**Comment by achiku** [comment]
This repro script might help a bit.

```python
# -*- coding: utf-8 -*-
import logging

import boto3
from moto import mock_emr


if __name__ == '__main__':
    mock = mock_emr()
    mock.start()

    boto3.set_stream_logger('boto3.resources', logging.DEBUG)
    client = boto3.client('emr', region_name='us-east-1')
    cluster = client.run_job_flow(
        Name='cluster',
        AmiVersion='3.8.0',
        Instances={
            'MasterInstanceType': 'c3.xlarge',
            'SlaveInstanceType': 'c3.xlarge',
            'InstanceCount': 3,
            'Placement': {'AvailabilityZone': 'us-east-1a'},
            'KeepJobFlowAliveWhenNoSteps': True,
        },
        VisibleToAllUsers=True,
    )
    print(cluster)
    mock.stop()
```

**Comment by spulec** [comment]
This was fixed with https://github.com/spulec/moto/commit/7cd404808b9fd60e2529ce4b65ada15071f0ee1e

Feel free to reopen if it still doesn't work.
