### ISSUE TITLE
Failure to mock creating a DynamoDB table

### ISSUE THREAD

**Issue by malcolmpurvis** [spulec/moto#428]
I've been trying to use moto (version 0.4.14) with the dymamodb example in the boto3 (version 1.1.3) docs (http://boto3.readthedocs.org/en/latest/guide/dynamodb.html) under Python 3.5, but it fails deep in the bowels of moto.  This is the script I'm using:

```
#!/usr/bin/env python35

from boto3.session import Session

from moto import mock_dynamodb


def main():
    with mock_dynamodb():
        session = Session(aws_access_key_id='<YOUR ACCESS KEY ID>',
                          aws_secret_access_key='<YOUR SECRET KEY>',
                          region_name= 'us-east-1')
        # Get the service resource
        dynamodb = session.resource('dynamodb')

        # Create the DynamoDB table.
        table = dynamodb.create_table(
            TableName='users',
            KeySchema=[
                {
                    'AttributeName': 'username',
                    'KeyType': 'HASH'
                },
                {
                    'AttributeName': 'last_name',
                    'KeyType': 'RANGE'
                }
            ],
            AttributeDefinitions=[
                {
                    'AttributeName': 'username',
                    'AttributeType': 'S'
                },
                {
                    'AttributeName': 'last_name',
                    'AttributeType': 'S'
                },
            ],
            ProvisionedThroughput={
                'ReadCapacityUnits': 5,
                'WriteCapacityUnits': 5
            }
        )

        # Wait until the table exists.
        table.meta.client.get_waiter('table_exists').wait(TableName='users')

        # Print out some data about the table.
        print(table.item_count)

if __name__ == '__main__':
    main()
```

This fails with the stack trace:

```
Traceback (most recent call last):
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mockdb.py", line 52, in <module>
    main()
  File "mockdb.py", line 41, in main
    'WriteCapacityUnits': 5
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/boto3/resources/factory.py", line 344, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/boto3/resources/action.py", line 77, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/client.py", line 268, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/client.py", line 322, in _make_api_call
    operation_model, request_dict)
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/endpoint.py", line 111, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/endpoint.py", line 140, in _send_request
    success_response, exception):
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/endpoint.py", line 204, in _needs_retry
    caught_exception=caught_exception)
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/retryhandler.py", line 250, in __call__
    caught_exception)
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/retryhandler.py", line 265, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/endpoint.py", line 168, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1170, in getresponse
    response = self.response_class(self.sock, method=self._method)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 220, in __init__
    self.fp = sock.makefile("rb")
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/httpretty/core.py", line 332, in makefile
    self._entry.fill_filekind(self.fd)
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/httpretty/core.py", line 591, in fill_filekind
    status, headers, self.body = self.callable_body(self.request, self.info.full_url(), headers)
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/moto/core/responses.py", line 87, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/moto/core/responses.py", line 128, in _dispatch
    return self.call_action()
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/moto/dynamodb/responses.py", line 62, in call_action
    response = getattr(self, endpoint)()
  File "/Users/mpurvis/.virtualenvs/monarch-ve/lib/python3.5/site-packages/moto/dynamodb/responses.py", line 96, in create_table
    hash_hey = key_schema['HashKeyElement']
TypeError: list indices must be integers or slices, not str

```

**Comment by spulec** [comment]
Can you try using the `mock_dynamodb2` decorator instead?

**Comment by blueyed** [comment]
It's the same/similar with `mock_dynamodb2`:

Traceback (most recent call last):
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "…/app/tests/test_moto.py", line 198, in test_moto_1
    assert get_distance_for_org_today(org) == 0.0
  File "…/app/stats.py", line 84, in get_distance_for_org_today
    int(today.strftime('%Y%m%d')))
  File "…/app/stats.py", line 41, in get_from_dynamodb
    Key('organization').eq(str(org.uuid))
  File "…/pyenv/project/lib/python3.5/site-packages/boto3/resources/factory.py", line 455, in do_action
    response = action(self, *args, **kwargs)
  File "…/pyenv/project/lib/python3.5/site-packages/boto3/resources/action.py", line 79, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/client.py", line 396, in _make_api_call
    operation_model, request_dict)
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/endpoint.py", line 111, in make_request
    return self._send_request(request_dict, operation_model)
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/endpoint.py", line 140, in _send_request
    success_response, exception):
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/endpoint.py", line 213, in _needs_retry
    caught_exception=caught_exception)
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/retryhandler.py", line 250, in __call__
    caught_exception)
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/retryhandler.py", line 265, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/endpoint.py", line 168, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "…/pyenv/project/lib/python3.5/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.5/http/client.py", line 1170, in getresponse
    response = self.response_class(self.sock, method=self._method)
  File "/usr/lib64/python3.5/http/client.py", line 220, in __init__
    self.fp = sock.makefile("rb")
  File "…/pyenv/project/lib/python3.5/site-packages/httpretty/core.py", line 332, in makefile
    self._entry.fill_filekind(self.fd)
  File "…/pyenv/project/lib/python3.5/site-packages/httpretty/core.py", line 591, in fill_filekind
    status, headers, self.body = self.callable_body(self.request, self.info.full_url(), headers)
  File "…/moto/moto/core/responses.py", line 95, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "…/moto/moto/core/responses.py", line 136, in _dispatch
    return self.call_action()
  File "…/moto/moto/dynamodb2/responses.py", line 62, in call_action
    response = getattr(self, endpoint)()
  File "…/moto/moto/dynamodb2/responses.py", line 259, in query
    index = table.schema
AttributeError: 'NoneType' object has no attribute 'schema'

**Comment by blueyed** [comment]
Actually the error above is something different, and using `dynamodb2` should work for the `create_table` from this issue.

**Comment by spulec** [comment]
Going to close. Feel free to reopen if this didn't solve it.

**Comment by RAMESHGP** [comment]
Hi Spulec,
On the above code reference i can able to create and put the items in DB mock.
But when I am trying to get the table items with the help of get_item(). As it throws 
 **botocore.exceptions.ClientError: An error occurred (ValidationException)** 
Please help to get out of this issue

Below packages i used in my script
import os, json, sys, boto3, time
from boto3.session import Session
from moto import mock_dynamodb2
from boto3.dynamodb.conditions import Key, Attr

**Code Snippet**


            # Print out some data about the table.
            filters = event_data['filters']
            key = {'deviceID': filters['device_id']}
            print (key)
            try:
                response = table.get_item(Key=key)
                print("this is response",response) 
            except Exception as e:
                logger.exception(e)

(Pdb) key
{'deviceID': '2304'}

(Pdb) response = table.get_item(Key=key)
INFO:boto3.resources.action:Calling dynamodb:get_item with {'TableName': 'intelli_temp_mon_assets_dev', 'Key': {'deviceID': '2304'}}
*** botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the GetItem operation:

####Complete Code below:

import os, json, sys, boto3, time
from boto3.session import Session
import logging
from moto import mock_dynamodb2
from MyDynamodbClass import *

from boto3.dynamodb.conditions import Key, Attr 
logging.basicConfig()
logger = logging.getLogger()
logger.setLevel(logging.INFO)

logger.info("SUCCESS: Connection to DATABASE and SNS instance succeeded")

class Post_Lambda(object):
    #Test Class. All your test functonality
    def main():
        fileDir = os.path.dirname(os.path.realpath('__file__'))
        event_file = os.path.join(fileDir, 'mock_event.json')
        with open(event_file) as json_data:
            event_data = json.load(json_data)

        with mock_dynamodb2():
            session = Session(aws_access_key_id='<YOUR ACCESS KEY ID>',
                              aws_secret_access_key='<YOUR SECRET KEY>',
                              region_name= 'us-east-1')
            # Get the service resource
            dynamodb = session.resource('dynamodb')

            # Create the DynamoDB table.
            table = dynamodb.create_table(
                TableName='intelli_temp_mon_assets_dev',
                KeySchema=[
                    {
                        'AttributeName': 'device_id',
                        'KeyType': 'HASH'
                    }
                ],
                AttributeDefinitions=[
                    {
                        'AttributeName': 'device_id',
                        'AttributeType': 'S'
                    }
                ],
                ProvisionedThroughput={
                    'ReadCapacityUnits': 5,
                    'WriteCapacityUnits': 5
                }
            )
            # Wait until the table exists.
            table.meta.client.get_waiter('table_exists').wait(TableName='intelli_temp_mon_assets_dev')
            table.put_item(
                   Item={
                        'device_id': '2004',
                        'alarm_level': 'low',
                        'alarms': '100',
                        'category': 'Fridge',
                        'device-status': 'false',
                        'current_temp': '28.50',
                        "measure_unit":  'C',
                        "siteID": '712',
                        "locationID": 'location2',
                        "model_type": 'Eskimo1890'
                    }
            )
            table.put_item(
                Item={
                        'device_id': '2304',
                        'alarm_level': 'high',
                        'alarms': '200',
                        'category': 'Fridge',
                        'device-status': 'true', 
                        'current_temp': '38.50',
                        "measure_unit":  'C',
                        "siteID": '863',
                        "locationID": 'location1',
                        "model_type": 'Eskimo1990'
                    }
            )
            # Print out some data about the table.
            filters = event_data['filters']
            key = {'deviceID': filters['device_id']}
            print (key)
            try:
                response = table.get_item(Key=key)
                print("this is response",response) 
            except Exception as e:
                logger.exception(e)

            logger.info("Your code logic")
            data={}
            import pdb; pdb.set_trace()
            print(table.item_count)
            # foo = Feature.myfun()
            foo = lambda_handler(None, None)
            print("You have to assert this response %s " %(foo))
    if __name__ == '__main__':
        main()



Fails with Stack trace

$ python mock_device_details.py
INFO:root:SUCCESS: Connection to DATABASE and SNS instance succeeded
INFO:boto3.resources.action:Calling dynamodb:create_table with {'TableName': 'intelli_temp_mon_assets_dev', 'AttributeDefinitions': [{'AttributeName': 'device_id', 'AttributeType': 'S'}], 'KeySchema': [{'AttributeName': 'device_id', 'KeyType': 'HASH'}], 'ProvisionedThroughput': {'ReadCapacityUnits': 5, 'WriteCapacityUnits': 5}}
INFO:boto3.resources.action:Calling dynamodb:put_item with {'TableName': 'intelli_temp_mon_assets_dev', 'Item': {'locationID': 'location2', 'alarm_level': 'low', 'alarms': '100', 'measure_unit': 'C', 'current_temp': '28.50', 'model_type': 'Eskimo1890', 'siteID': '712', 'category': 'Fridge', 'device_id': '2004', 'device-status': 'false'}}
INFO:boto3.resources.action:Calling dynamodb:put_item with {'TableName': 'intelli_temp_mon_assets_dev', 'Item': {'locationID': 'location1', 'alarm_level': 'high', 'alarms': '200', 'measure_unit': 'C', 'current_temp': '38.50', 'model_type': 'Eskimo1990', 'siteID': '863', 'category': 'Fridge', 'device_id': '2304', 'device-status': 'true'}}
INFO:boto3.resources.action:Calling dynamodb:get_item with {'TableName': 'intelli_temp_mon_assets_dev', 'Key': {'deviceID': '2304'}}
**ERROR:root:An error occurred (ValidationException) when calling the GetItem operation:**
Traceback (most recent call last):
  File "mock_device_details.py", line 93, in main
    response = table.get_item(Key=key)
  File "C:\Python33\lib\site-packages\boto3\resources\factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "C:\Python33\lib\site-packages\boto3\resources\action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "C:\Python33\lib\site-packages\botocore\client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Python33\lib\site-packages\botocore\client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the GetItem operation:
INFO:root:Your code logic
{'deviceID': '2304'}
> c:\python33\scripts\dynamodb\mock_device_details.py(117)main()
-> print(table.item_count)

**Comment by karthikvadla** [comment]
@spulec Can you please help me what's going wrong here, I'm strugging on using moto since a day.
My test file looks as this

```
from db_utils import DynamoDbOperations
from moto import mock_dynamodb2
import pytest
import boto3
import os
import datetime
import json

TEST_DYNAMO_TABLE_NAME = 'test'
JSON_ITEM = {
    'id': '123',
    'name': 'karthik'
}
TEST_DATE_TIME = str(datetime.datetime.now())


@pytest.fixture
def aws_credentials():
    """Mocked AWS Credentials for moto."""
    os.environ['AWS_ACCESS_KEY_ID'] = 'testing'
    os.environ['AWS_SECRET_ACCESS_KEY'] = 'testing'
    os.environ['AWS_SECURITY_TOKEN'] = 'testing'
    os.environ['AWS_SESSION_TOKEN'] = 'testing'
    os.environ['AWS_DEFAULT_REGION'] = 'us-west-2'


@pytest.fixture
def dynamo_db_table(aws_credentials):
    print("Stetup....")

    def _dynamo_db_table(table_name, json_item):
        with mock_dynamodb2():
            boto3.client('dynamodb').create_table(
                AttributeDefinitions=[
                    {'AttributeName': 'id', 'AttributeType': 'S'}
                ],
                TableName=table_name,
                KeySchema=[{'AttributeName': 'id', 'KeyType': 'HASH'}],
                ProvisionedThroughput={
                    'ReadCapacityUnits': 5,
                    'WriteCapacityUnits': 5,
                },
            )
            table = boto3.resource('dynamodb').Table(table_name)
            table.put_item(Item=json_item)
            yield table
    yield _dynamo_db_table

    print("Tear down ....")


def test_item(dynamo_db_table):
    table = dynamo_db_table(TEST_DYNAMO_TABLE_NAME, JSON_ITEM)
    response = table.get_item(Key={'id': '123'})
    print(response['Item'])


@mock_dynamodb2
def test_dynamo_db_utils_init(dynamo_db_table):
    # DynamoDbOperations(TEST_DYNAMO_TABLE_NAME)
    # print("Finished")
    # print("***********fixture***********")
    # print(dynamo_db_table)
    # print('**********************************')
    # print(db)
    # print('**********************************')
    pass


# def test_dynamo_db_utils_insert_item(dynamo_db_table):
#     json_item = {
#         'id': '123',
#         'name': 'karthik'
#     }
#     dynamo_db_table(TEST_DYNAMO_TABLE_NAME)
#     db = DynamoDbOperations(TEST_DYNAMO_TABLE_NAME)
#     response = db.insert_item(json_item)
#     assert 200 in response

```
i have this error
```
_____________________________________________________________________________________________ test_item _____________________________________________________________________________________________

dynamo_db_table = <function dynamo_db_table.<locals>._dynamo_db_table at 0x1146788c0>

    def test_item(dynamo_db_table):
        table = dynamo_db_table(TEST_DYNAMO_TABLE_NAME, JSON_ITEM)
>       response = table.get_item(Key={'id': '123'})
E       AttributeError: 'generator' object has no attribute 'get_item'

test_dynamo_db_utils.py:54: AttributeError

```.
It means its not mocking table?
