### ISSUE TITLE
describe_network_interfaces after run_instances fails with InvalidAddress.NotFound

### ISSUE THREAD

**Issue by sblask** [spulec/moto#4376]
The following code will raise an exception for the second describe_network_interfaces call:

```
#!/usr/bin/env python3
import boto3
import moto


@moto.mock_ec2
def main():
    client = boto3.client("ec2", region_name="ap-southeast-2")

    print(client.describe_network_interfaces())

    client.run_instances(
        ImageId=client.describe_images()["Images"][0]["ImageId"],
        MinCount=1,
        MaxCount=1,
    )

    print(client.describe_network_interfaces())


if __name__ == "__main__":
    main()

```

```
$ python test.py
{'NetworkInterfaces': [], 'ResponseMetadata': {'RequestId': 'ddb0aaf1-8b65-4f0a-94fa-654b18b8a204', 'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com'}, 'RetryAttempts': 0}}
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    main()
  File "/Users/sebastian/Clones/packer-cleanup/.venv/lib/python3.8/site-packages/moto/core/models.py", line 114, in wrapper
    result = func(*args, **kwargs)
  File "test.py", line 18, in main
    print(client.describe_network_interfaces())
  File "/Users/sebastian/Clones/packer-cleanup/.venv/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/sebastian/Clones/packer-cleanup/.venv/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAddress.NotFound) when calling the DescribeNetworkInterfaces operation: Address '['54.214.49.42']' not found.
```

I'd expect the call to just succeed or if Moto can't handle it a Moto exception with a possible workaround.

**Comment by sblask** [comment]
Manually creating the network interface works:

```
#!/usr/bin/env python3
import boto3
import moto


@moto.mock_ec2
def main():
    client = boto3.client("ec2", region_name="ap-southeast-2")

    print(client.describe_network_interfaces())

    resource = boto3.resource("ec2", region_name="ap-southeast-2")

    vpc = resource.create_vpc(CidrBlock="10.0.0.0/16")
    subnet = resource.create_subnet(VpcId=vpc.id, CidrBlock="10.0.0.0/18")
    eni = subnet.create_network_interface()

    client.run_instances(
        ImageId=client.describe_images()["Images"][0]["ImageId"],
        MinCount=1,
        MaxCount=1,
        NetworkInterfaces=[
            {
                "DeviceIndex": 0,
                "NetworkInterfaceId": eni.id,
                "SubnetId": subnet.id,
            }
        ],
    )

    print(client.describe_network_interfaces())


if __name__ == "__main__":
    main()
```

**Comment by bblommers** [comment]
Hi @sblask, which version of Moto are you using? I can't reproduce this at all, I'm afraid

**Comment by bblommers** [comment]
I was able to narrow it down a bit more: https://github.com/bblommers/moto/actions/runs/1322070387

Are you able to try the latest dev-release (2.2.9.dev27), @sblask? It looks like it was fixed (again) quite recently.
