### ISSUE TITLE
S3 copy_object() doesn't handle missing object properly

### ISSUE THREAD

**Issue by movestill** [spulec/moto#4524]
* boto 2.48.0
* boto3 1.16.63
* botocore 1.19.63
* python 3.7.9
* moto 1.3.7 (pip installed) but also saw the issue with the latest version when I tried it briefly

I expected to see the `NoSuchKey` exception but got this instead:

```
Traceback (most recent call last):
  File "test_s3_exception.py", line 30, in <module>
    run()
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/moto/core/models.py", line 74, in wrapper
    result = func(*args, **kwargs)
  File "test_s3_exception.py", line 22, in run
    s3_client.copy_object(Bucket=target, CopySource={'Bucket': src, 'Key': 'foofoofoo'}, Key='newkey')
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/client.py", line 663, in _make_api_call
    operation_model, request_dict, request_context)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/client.py", line 682, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/endpoint.py", line 256, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/endpoint.py", line 197, in _do_get_response
    responses = self._event_emitter.emit(event_name, request=request)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/moto/core/models.py", line 292, in __call__
    status, headers, body = response_callback(request, request.url, request.headers)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/moto/s3/responses.py", line 569, in key_response
    response = self._key_response(request, full_url, headers)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/moto/s3/responses.py", line 622, in _key_response
    return self._key_response_put(request, body, bucket_name, query, key_name, headers)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/moto/s3/responses.py", line 721, in _key_response_put
    storage=storage_class, acl=acl, src_version_id=src_version_id)
  File "/Users/user/.virtualenvs/microns/lib/python3.7/site-packages/moto/s3/models.py", line 919, in copy_key
    key = key.copy(dest_key_name)
AttributeError: 'NoneType' object has no attribute 'copy'
```

## Reproduction Steps

```python
from moto import mock_s3

@mock_s3
def run():
    s3 = boto3.resource('s3')
    src = 'foo.bar'
    target = 'target.bar'
    s3.create_bucket(Bucket=src)
    s3.create_bucket(Bucket=target)
     
    s3_client = boto3.client('s3')
    s3_client.copy_object(Bucket=target, CopySource={'Bucket': src, 'Key': 'foofoofoo'}, Key='newkey')

run()
```

**Comment by bblommers** [comment]
Hi @movestill, thanks for raising this and for providing the reproducible test case! 
Will mark it as an enhancement to implement this validation.
