### ISSUE TITLE
No module named 'yaml' in tags 2.2.15 and 2.2.16.dev5 (moto/ssm) 

### ISSUE THREAD

**Issue by MihaiBogdanEugen** [spulec/moto#4579]
Possible duplicate of #4570 , but it's for a different AWS service (SSM, and not CloudFormation)

I'm running into this error: `ModuleNotFoundError: No module named 'yaml'` when trying to run a unit test with moto mocking SSM.

The full stacktrace: 
```
Error
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_ssm
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/MyProject/test/test_ssm.py", line 11, in <module>
    class SSMTest(unittest.TestCase):
  File "/MyProject/test/test_ssm.py", line 20, in SSMTest
    def test_authentication(self):
  File "/MyProject/venv/lib/python3.9/site-packages/moto/__init__.py", line 16, in f
    module = importlib.import_module(module_name, "moto")
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/MyProject/venv/lib/python3.9/site-packages/moto/ssm/__init__.py", line 1, in <module>
    from .models import ssm_backends
  File "/MyProject/venv/lib/python3.9/site-packages/moto/ssm/models.py", line 16, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

I'm using Python 3.9.7 and I've tried both moto 2.2.15 and the very latest version 2.2.16.dev5, to no avail.

What am I doing wrong?

**Comment by MihaiBogdanEugen** [comment]
I'm manually installing moto by running:
```
 pip install moto==2.2.15
```

And I'm using pip 21.1.2.

**Comment by MihaiBogdanEugen** [comment]
I managed to solve this by installing "all":
```
pip install moto[all]=2.2.15
```

Feel free to close this if you don't plan to fix it.

**Comment by bblommers** [comment]
Hi @MihaiBogdanEugen, that is the fix! From moto 2.x, you should install dependencies for the specific services that you intend to use:
`pip install moto[ssm,s3,whatever-other-service-you-use]`

Just `pip install moto` will only install generic dependencies, but no dependencies that are only used for specific services.
By specifying which services are used, people only need to download dependencies that they need for their project, but can skip others.

If there are too many services to list, then `pip install moto[all]` is a good workaround, as it will install all dependencies for all services.

I'll close it, but feel free to reply if you do have any other questions/issues!
