### ISSUE TITLE
respond_decision_task_completed API call not functionally complete, despite implementation_coverage claim

### ISSUE THREAD

**Issue by JimNero009** [spulec/moto#4708]
I believe I have stumbled across an issue with the SWF implementation you provide -- at least, in terms of the documented support.

The implementation docs suggest that the 'respond_decision_task_completed' API call is supported. However, if you call it with a decision that is not implemented (see https://github.com/spulec/moto/blob/master/moto/swf/models/workflow_execution.py#L410-L419), then that call will fail and it will raise a NotImplementedError.

Sample code to reproduce:
```
import boto3
from moto import mock_swf

@mock_swf
def test_moto_directly():
    client = boto3.client("swf")
    client.register_domain(name="testdomain", workflowExecutionRetentionPeriodInDays="1")
    client.register_workflow_type(domain="testdomain", name="test", version="1", defaultTaskStartToCloseTimeout="60", defaultExecutionStartToCloseTimeout="60")
    client.start_workflow_execution(domain="testdomain", workflowId="foobar", workflowType={"name": "test", "version": "1"}, taskList={"name": "testtasklist"}, childPolicy="TERMINATE")
    task_token = client.poll_for_decision_task(domain="testdomain", taskList={"name": "testtasklist"})["taskToken"]
    decisions = [{'decisionType': 'RecordMarker', 'recordMarkerDecisionAttributes': {'details': '{"timestamp":sometime}', 'markerName': '_workflow_event_workflowExecutionStarted'}}]
    client.respond_decision_task_completed(taskToken=task_token, decisions=decisions)
```

Produces a stack trace like:
```
Traceback (most recent call last):
  File "recreate_swf_issue.py", line 30, in <module>
    test_moto_directly()
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/moto/core/models.py", line 100, in wrapper
    result = func(*args, **kwargs)
  File "recreate_swf_issue.py", line 27, in test_moto_directly
    client.respond_decision_task_completed(taskToken=task_token, decisions=decisions)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/endpoint.py", line 197, in _do_get_response
    responses = self._event_emitter.emit(event_name, request=request)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/moto/core/models.py", line 323, in __call__
    request, request.url, request.headers
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/moto/core/responses.py", line 202, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/moto/core/responses.py", line 312, in _dispatch
    return self.call_action()
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/moto/core/responses.py", line 397, in call_action
    response = method()
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/moto/swf/responses.py", line 468, in respond_decision_task_completed
    task_token, decisions=decisions, execution_context=execution_context
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/moto/swf/models/__init__.py", line 294, in respond_decision_task_completed
    execution_context=execution_context,
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/moto/swf/models/workflow_execution.py", line 320, in complete_decision_task
    self.handle_decisions(evt.event_id, decisions)
  File "/Users/jimcockburn/<redacted>/<redacted>/.venv/lib/python3.5/site-packages/moto/swf/models/workflow_execution.py", line 422, in handle_decisions
    "Cannot handle decision: {0}".format(decision_type)
NotImplementedError: Cannot handle decision: RecordMarker
```

I am interested in the implementation of these decision tasks. Do you have a timeline on completing them? In the meantime, would it be prudent to re-evaluate your implementation completion checklist so that others don't fall into the same problem?

Cheers!

**Comment by bblommers** [comment]
Hi @JimNero009, thanks for raising this. As far as I know, this is not on anyone's radar, so if you want to help out, a PR would be very welcome!

The coverage document indicates that the feature is supported, but there is no guarantee that it supports every possible parameter combination. Will mark it as an enhancement to also add docstrings to give some indication of what is/is not supported.

**Comment by JimNero009** [comment]
Hi Bert, thanks for the response and the info. I may be able to have a go at implementing at least a part of the functionality over the next few weeks. If you have any general documentation on how to get started with a contribution, I'd be more than happy to read it!

**Comment by bblommers** [comment]
There is some general documentation/development tips here: http://docs.getmoto.org/en/latest/docs/contributing/index.html

The only hard and fast rule is that there should be a separation between model (in models.py) and view (responses.py), but other than that, the various services are so different that it's difficult to have strict rules on what the implementation should look like. 
SWF has already quite an in-depth implementation, though, so as long as you don't deviate too much from that 'style' it should be OK.
