### ISSUE TITLE
Launch template support for spot fleet requests

### ISSUE THREAD

**Issue by cheshirex** [spulec/moto#4746]
Is there currently any way to support requesting a spot fleet with a launch template? I've been trying to do this (with code that works against AWS) and getting:
```Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/server.py", line 183, in __call__
    return backend_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/utils.py", line 148, in __call__
    result = self.callback(request, request.url, {})
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 205, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 315, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/core/responses.py", line 405, in call_action
    response = method()
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/ec2/responses/spot_fleets.py", line 61, in request_spot_fleet
    launch_specs=launch_specs,
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/ec2/models.py", line 5937, in request_spot_fleet
    launch_specs,
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/ec2/models.py", line 5747, in __init__
    self.create_spot_requests(self.target_capacity)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/ec2/models.py", line 5825, in create_spot_requests
    weight_map, added_weight = self.get_launch_spec_counts(weight_to_add)
  File "/opt/code/localstack/.venv/lib/python3.7/site-packages/moto/ec2/models.py", line 5814, in get_launch_spec_counts
    )[0]
IndexError: list index out of range
```

I note that https://github.com/spulec/moto/blob/a688c0032596a7dfef122b69a08f2bec3be2e481/moto/ec2/responses/spot_fleets.py#L51 only seems to look for the LaunchSpecifications field, not LaunchTemplateConfigs.

Thanks!

**Comment by bblommers** [comment]
Thanks for raising this, @cheshirex. Do you use the `LaunchTemplateConfigs.Overrides` parameter at all, or would just support for `LaunchTemplateConfigs.LaunchTemplateSpecification` be sufficient for your use case?

**Comment by cheshirex** [comment]
I do use the overrides.

Thanks!

**Comment by facundoolano** [comment]
I found the same problem, also with using `LaunchTemplateConfigs.Overrides`.
