### ISSUE TITLE
DynamoDb2 create_table not validate ProvisionedThroughput parameter

### ISSUE THREAD

**Issue by lucianomarqueto** [spulec/moto#4781]
Hello,
When I call create_table from dynamodb client, if a pass `BillingMode='PROVISIONED'` the parameter `ProvisionedThroughput ` is required, as you can see in boto3 documentation: [Boto3 DynamoDB create_table](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb.html#DynamoDB.Client.create_table)

> If you set BillingMode as PROVISIONED , you must specify this property. If you set BillingMode as PAY_PER_REQUEST , you cannot specify this property.

if you run the code below using `@mock_dynamodb2`, it does not raise an error. 

```
@mock_dynamodb2
    def test_dynamodb_create_table(self):
        dynamodb_client = boto3.client("dynamodb", region_name='us-east-1')

        res = dynamodb_client.create_table(TableName='my-table',
                                     AttributeDefinitions=[
                                         {
                                             'AttributeName': 'some_field',
                                             'AttributeType': 'S'
                                         }
                                     ],
                                     KeySchema=[
                                         {
                                             'AttributeName': 'some_field',
                                             'KeyType': 'HASH'
                                         }
                                     ],
                                     BillingMode='PROVISIONED',
                                     StreamSpecification={
                                         'StreamEnabled': False,
                                         'StreamViewType': 'NEW_IMAGE'
                                     })
        print(res)
```

But if you remove `@mock_dynamodb2`, boto3 will raise the error below

```
Error
Traceback (most recent call last):
  File ".../test_dynamodb_utils.py", line 11, in test_dynamodb_create_table
    res = dynamodb_client.create_table(TableName='my-table',
  File ".../venv/lib/python3.9/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File ".../venv/lib/python3.9/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreateTable operation: One or more parameter values were invalid: ReadCapacityUnits and WriteCapacityUnits must both be specified when BillingMode is PROVISIONED
```

moto version 2.3.1

Thanks a lot ahead,

**Comment by bblommers** [comment]
Hi @lucianomarqueto, thanks for raising this! Marking it as an enhancement to implement this validation
