### ISSUE TITLE
DynamoDB2 state seems to be kept across unit tests

### ISSUE THREAD

**Issue by facundoolano** [spulec/moto#4784]
I'm running a basic test with mocked dynamodb (which I based off of the [s3 example in the documentation](http://docs.getmoto.org/en/latest/docs/getting_started.html#class-decorator)). I'm using the class decorator and creating a table on the test setUp, and, if I have more than on test in my class, it fails with `ResourceInUseException`, as if the state was shared across the different tests.

If I use S3 instead of dynamo, I don't have this issue.

sample code:
```python
import unittest

import boto3
from moto import mock_dynamodb2


@mock_dynamodb2
class TestMockClassLevel(unittest.TestCase):
    def setUp(self):
        dynamodb = boto3.client('dynamodb', region_name='us-west-2')
        dynamodb.create_table(
            TableName='TestTable',
            AttributeDefinitions=[{"AttributeName": "name", "AttributeType": "S"}],
            KeySchema=[{"AttributeName": "name", "KeyType": "HASH"}]
        )

    def test_1(self):
        pass

    def test_2(self):
        pass
```

Output:
```
python -m unittest test2.py
.E
======================================================================
ERROR: test_2 (test2.TestMockClassLevel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/facundo/dev/adroll/boodah/smoove/venv/lib/python3.6/site-packages/moto/core/models.py", line 119, in wrapper
    result = func(*args, **kwargs)
  File "/Users/facundo/dev/adroll/boodah/smoove/test2.py", line 14, in setUp
    KeySchema=[{"AttributeName": "name", "KeyType": "HASH"}]
  File "/Users/facundo/dev/adroll/boodah/smoove/venv/lib/python3.6/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/facundo/dev/adroll/boodah/smoove/venv/lib/python3.6/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceInUseException: An error occurred (ResourceInUseException) when calling the CreateTable operation: Resource in use

----------------------------------------------------------------------
Ran 2 tests in 0.171s

FAILED (errors=1)
```

Package versions:
```
boto3==1.20.21
moto[s3,ec2,autoscaling,iam,dynamodb,cloudwatch,applicationautoscaling]==2.3.2
```

**Comment by bblommers** [comment]
Hi @facundoolano, that was the behavior in Moto 2.x, yes. 
In Moto 3.x it was changed to reset the state before every test-method, as that is much more intuitive.

Are you able to upgrade to 3.x?

https://github.com/spulec/moto/issues/4774

**Comment by facundoolano** [comment]
Thanks @bblommers that seems to do the trick. I installed the latest version a few days ago and got 2.3.2, but apprently I've been looking at 3.x documentation instead.
