### ISSUE TITLE
multi part upload with empty part list should be rejected

### ISSUE THREAD

**Issue by mdavis-xyz** [spulec/moto#4825]
# Steps to reproduce

```
from moto import mock_s3
import boto3

bucket = 'mybucket'
key = 'test-multi-empty'

if True:
    mock_s3().start()
    
    client = boto3.client('s3')
    client.create_bucket(
        Bucket=bucket,
        CreateBucketConfiguration={
            'LocationConstraint': 'ap-southeast-2'
        },
    )

response = boto3.client('s3').create_multipart_upload(
    Bucket=bucket,
    Key=key,
)
id = response['UploadId']

upload = boto3.resource('s3').MultipartUpload(bucket, key, id)
print("Completing")
upload.complete(
    MultipartUpload={
        'Parts': []
    }
)
print("Done")
```

Try this with `if True` and with `if False`.

# Expected behavior

Same result with or without moto.
i.e. without moto, the empty parts list is rejected.

```
Traceback (most recent call last):
  File "multi.py", line 25, in <module>
    upload.complete(
  File "/home/ec2-user/.pyenv/versions/3.8.11/lib/python3.8/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/ec2-user/.pyenv/versions/3.8.11/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/ec2-user/.pyenv/versions/3.8.11/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/.pyenv/versions/3.8.11/lib/python3.8/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (MalformedXML) when calling the CompleteMultipartUpload operation: The XML you provided was not well-formed or did not validate against our published schema
```

# Actual behavior

With moto, this script will successfully create an empty object, instead of rejecting it.

# Versions:

moto: 2.2.16
boto3: 1.20.14
botocore: 1.23.37

**Comment by bblommers** [comment]
Interesting - looks like boto3 doesn't quite know how to handle the response, if the XML coming from AWS is invalid. It'd be interesting to see how other SDK's/the CLI handle this.
I'll mark it as an enhancement to copy this behaviour.

**Comment by mdavis-xyz** [comment]
I suspect this is a bug in the API spec itself. The docs don't mention a minimum list length, and I can't see one [here](https://github.com/boto/boto3/blob/367f8f87194684bcd66903c8baae1ca2cbed87f2/boto3/data/s3/2006-03-01/resources-1.json#L782) either.
