### ISSUE TITLE
table.update_item raises ValueError instead of expected ResourceNotFoundException

### ISSUE THREAD

**Issue by jrobbins-LiveData** [spulec/moto#4880]
Using `moto` v3.0.4 on Windows 10.

Issue https://github.com/spulec/moto/issues/4344 (Closed) reported something similar with `batch_get_item`, but this report is for `update_item`.   My code is expecting `ResourceNotFoundException` in the case of a non-existent table (which is the observed behavior on AWS.)  But with `moto`, `ValueError` is raised instead.

Reproduction available at https://github.com/LiveData-Inc/moto_dynamodb2_issue.

```python
    with mock_dynamodb2():
        client = boto3.client("dynamodb")
        resource_client = boto3.resource("dynamodb")

        test_table = resource_client.Table("test")

        try:
            result = test_table.update_item(
                Key={"Index": "something"},
                UpdateExpression="SET owner = :owner",
                ExpressionAttributeValues={":owner": "some_owner"},
                ConditionExpression=Attr("owner").eq("UNOWNED") | Attr("owner").not_exists(),
                ReturnValues="ALL_NEW",
                ReturnConsumedCapacity="TOTAL",
            )

            print(f"{result=}")

        # NOTE I expected this exception
        except client.exceptions.ResourceNotFoundException as error:
            print(f"{error=}")

        # NOTE but instead got this exception
        except ValueError as error:
            print(f"{error=}")
```

Full Traceback

```
Traceback (most recent call last):
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\test.py", line 41, in <module>
    main()
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\test.py", line 20, in main
    result = test_table.update_item(
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\boto3\resources\factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\boto3\resources\action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\client.py", line 705, in _make_api_call
    http, parsed_response = self._make_request(
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\client.py", line 725, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\endpoint.py", line 106, in make_request
    return self._send_request(request_dict, operation_model)
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\endpoint.py", line 182, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\endpoint.py", line 301, in _needs_retry
    responses = self._event_emitter.emit(
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\retryhandler.py", line 192, in __call__
    if self._checker(**checker_kwargs):
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\retryhandler.py", line 265, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\retryhandler.py", line 284, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\retryhandler.py", line 331, in __call__
    checker_response = checker(attempt_number, response,
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\retryhandler.py", line 231, in __call__
    return self._check_caught_exception(
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\retryhandler.py", line 374, in _check_caught_exception
    raise caught_exception
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\endpoint.py", line 245, in _do_get_response
    responses = self._event_emitter.emit(event_name, request=request)
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\moto\core\models.py", line 289, in __call__
    status, headers, body = response_callback(
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\moto\core\responses.py", line 205, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\moto\core\responses.py", line 315, in _dispatch
    return self.call_action()
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\moto\core\utils.py", line 229, in _wrapper
    response = f(*args, **kwargs)
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\moto\core\utils.py", line 261, in _wrapper
    response = f(*args, **kwargs)
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\moto\dynamodb2\responses.py", line 136, in call_action
    response = getattr(self, endpoint)()
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\moto\dynamodb2\responses.py", line 950, in update_item
    existing_item = copy.deepcopy(self.dynamodb_backend.get_item(name, key))
  File "C:\Users\jeff1\Documents\projects\git\moto_dynamodb2_issue\.venv\lib\site-packages\moto\dynamodb2\models\__init__.py", line 1397, in get_item
    raise ValueError("No table found")
ValueError: No table found
```

**Comment by bblommers** [comment]
Hi @jrobbins-LiveData , welcome to Moto! Thanks for raising this, will mark it as a bug.

**Comment by jrobbins-LiveData** [comment]
Amazingly fast turnaround!  Thank you!!
