### ISSUE TITLE
Getting exception when trying to use secrets manager: TypeError: s3_key_response_put() missing 1 required positional argument: 'headers'

### ISSUE THREAD

**Issue by toshetah** [spulec/moto#4939]
I am trying to run localstack. I am installing on a docker the following packages:

```
RUN pip3 install 'moto[all]' flask-cors h11 hypercorn quart readerwriterlock cbor2 cachetools crontab localstack jsonpatch boto
RUN \
  (SERVICES=s3,secretsmanager,sqs,sns localstack start --host 2>&1 | tee /tmp/log &) ; \
  for waitForDone in `seq 1 300`; do \
  sleep 1; \
  (tail /tmp/log | grep '^Ready\.$') && exit 0; \
  done; \
  if [ $waitForDone -eq 300 ]; then echo "TIMEOUT waiting for localstack"; exit 1; fi; \
  rm /tmp/log ; \
  killall localstack ; \
  exit 0
```

It installs currently `moto[all]` version 3.1.0
Then, when running in golang the following code:

```
_, _ := ds.s3Client.PutObject(
	context.TODO(),
	&s3.PutObjectInput{
		Key:    "key",
		Bucket: "bucket",
		Body:   Body:   bytes.NewReader([]byte("{}")),
	})
```

Throws the following excpetion:

```
2022-03-15 07:48:47,110:API: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/serving.py", line 324, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/serving.py", line 313, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.9/dist-packages/moto/moto_server/werkzeug_app.py", line 240, in __call__
    return backend_app(environ, start_response)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/localstack/utils/patch.py", line 35, in proxy
    return new(target, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/localstack/utils/aws/request_context.py", line 163, in convert_to_flask_response_call
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/moto/core/utils.py", line 127, in __call__
    result = self.callback(request, request.url, dict(request.headers))
  File "/usr/local/lib/python3.9/dist-packages/moto/core/utils.py", line 261, in _wrapper
    response = f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/moto/s3/responses.py", line 1082, in key_response
    response = self._key_response(request, full_url, self.headers)
  File "/usr/local/lib/python3.9/dist-packages/moto/s3/responses.py", line 1170, in _key_response
    return self._key_response_put(request, body, bucket_name, query, key_name)
  File "/usr/local/lib/python3.9/dist-packages/localstack/utils/patch.py", line 35, in proxy
    return new(target, *args, **kwargs)
TypeError: s3_key_response_put() missing 1 required positional argument: 'headers'
2022-03-15 07:48:47,110:API: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/serving.py", line 324, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.9/dist-packages/werkzeug/serving.py", line 313, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.9/dist-packages/moto/moto_server/werkzeug_app.py", line 240, in __call__
    return backend_app(environ, start_response)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/localstack/utils/patch.py", line 35, in proxy
    return new(target, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/localstack/utils/aws/request_context.py", line 163, in convert_to_flask_response_call
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/moto/core/utils.py", line 127, in __call__
    result = self.callback(request, request.url, dict(request.headers))
  File "/usr/local/lib/python3.9/dist-packages/moto/core/utils.py", line 261, in _wrapper
    response = f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/moto/s3/responses.py", line 1082, in key_response
    response = self._key_response(request, full_url, self.headers)
  File "/usr/local/lib/python3.9/dist-packages/moto/s3/responses.py", line 1170, in _key_response
    return self._key_response_put(request, body, bucket_name, query, key_name)
  File "/usr/local/lib/python3.9/dist-packages/localstack/utils/patch.py", line 35, in proxy
    return new(target, *args, **kwargs)
TypeError: s3_key_response_put() missing 1 required positional argument: 'headers'
```

I mitigated the issue by reverting `moto[all]` to version `3.0.7`.
I am pretty sure that the commit that caused this issue was https://github.com/spulec/moto/pull/4929/files#diff-a14f7ca014b23638947c5f417dacb9a4d59eef3aee9a8041e2c855e8587643cdL1176

I'd be happy to contribute a fix if that is welcome by you :)

**Comment by bblommers** [comment]
Hi @toshetah, it's probably better to raise this with Localstack. That commit is definitely the reason it fails now, but the root cause is the fact that Localstack calls Moto's internal methods with the wrong variables.

See this file: https://github.com/localstack/localstack/blob/5e6162ff4c0880634d4fceacc525a4249f038fb5/localstack/services/s3/s3_starter.py
All these `@patch`-ed methods would need updating, not just the `s3_key_response_put`-method.

**Comment by bblommers** [comment]
Looks like LocalStack are already on this, judging from this PR: https://github.com/localstack/localstack/pull/5706

They are using a fork of Moto behind the scenes, so it may be worth using that instead to ensure full compatibility with Moto: https://pypi.org/project/moto-ext/
