### ISSUE TITLE
Unable to find appropriate backend for test.bucket.amazonaws.com.Remember

### ISSUE THREAD

**Issue by jroose** [spulec/moto#4963]
Hello,

I'm using moto_server on moto versions 3.1.0 and 3.1.1 to mock S3 for testing an S3 backed PyPI server that I'm building.  I'm creating a test_bucket with the following code:
```
        self.moto_portnum = random.randint(9000, 9999)
        self.bucket_name = 'test_bucket'
        self.moto_endpoint = f'http://localhost:{int(self.moto_portnum)}'
       
        ...

        moto = sh.command('moto_server')
        job = sh(
            moto('-p', str(self.moto_portnum)),
            wait = False
        )

        ...

        s3 = boto3.resource(
            's3',
            endpoint_url=self.moto_endpoint,
            aws_access_key_id='testing',
            aws_secret_access_key='testing',
            aws_session_token='testing',
            region_name='us-east-1'
        )
        s3.create_bucket(Bucket=self.bucket_name, ACL='public-read')
```

Then I'm attempting to download a file from it using pip, with a flask server as an intermediary facilitating package listing, uploads, and downloads:
```
        sh = self.sh
        pip = self.pip
        python = sh.command('python')

        # The following call to boto3 works
        s3 = boto3.resource(
            's3',
            endpoint_url=self.moto_endpoint,
            aws_access_key_id='testing',
            aws_secret_access_key='testing',
            aws_session_token='testing',
            region_name='us-east-1'
        )
        key = "repo/axle-test-a/axle_test_a-0.0.0-py2.py3-none-any.whl"
        x = s3.Object(self.bucket_name, key).get()

        # But the pip install fails, after my Flask engine that lives at self.endpoint redirects the download to self.moto_endpoint
        sh(pip('install', '--verbose', '--index-url', self.endpoint, '--retries', '1', 'axle_test_a'))
        result = sh.evaluate(python('-m', 'axle_test_a'))

        self.assertEqual(result, "axle_test_a\n")
```

The call to `s3.Object().get()` works great:
```
127.0.0.1 - - [22/Mar/2022 15:06:00] "GET /test_bucket/repo/axle-test-a/axle_test_a-0.0.0-py2.py3-none-any.whl HTTP/1.1" 200 -
```

But the call to pip fails when it tries to download the wheel from moto_server's mock S3 directly:
```
Unable to find appropriate backend for test.bucket.amazonaws.com.Remember to add the URL to urls.py, and run scripts/update_backend_index.py to index it.
127.0.0.1 - - [22/Mar/2022 15:06:01] "GET /test_bucket/repo/axle-test-a/axle_test_a-0.0.0-py2.py3-none-any.whl HTTP/1.1" 500 -
  http://localhost:9205 "GET /test_bucket/repo/axle-test-a/axle_test_a-0.0.0-py2.py3-none-any.whl HTTP/1.1" 500 290
Error on request:
Traceback (most recent call last):
  File "/home/alaric/projects/src/axle/venv/lib/python3.9/site-packages/werkzeug/serving.py", line 324, in run_wsgi
    execute(self.server.app)
  File "/home/alaric/projects/src/axle/venv/lib/python3.9/site-packages/werkzeug/serving.py", line 313, in execute
    application_iter = app(environ, start_response)
  File "/home/alaric/projects/src/axle/venv/lib/python3.9/site-packages/moto/moto_server/werkzeug_app.py", line 239, in __call__
    backend_app = self.get_application(environ)
  File "/home/alaric/projects/src/axle/venv/lib/python3.9/site-packages/moto/moto_server/werkzeug_app.py", line 181, in get_application
    app = self.create_app(backend)
  File "/home/alaric/projects/src/axle/venv/lib/python3.9/site-packages/moto/moto_server/werkzeug_app.py", line 261, in create_backend_app
    backend_dict = backends.get_backend(service)
  File "/home/alaric/projects/src/axle/venv/lib/python3.9/site-packages/moto/backends.py", line 48, in get_backend
    module_name, backends_name = BACKENDS[name]
KeyError: None
```

This appears to be a bug in moto_server's handling of unauthenticated custom S3 buckets' urls.  Please advise.

**Comment by bblommers** [comment]
Hi @jroose, welcome to Moto!

Where is this URL, `test.bucket.amazonaws.com`, coming from?
Looking at the error message, it looks like the full URL that PyPi tries to connect to is:
`test.bucket.amazonaws.com/test_bucket/repo/axle-test-a/axle_test_a-0.0.0-py2.py3-none-any.whl`

Which looks wrong - IIRC, it should be either `s3.amazonaws.com/bucket`, or `bucket.amazonaws.com/file`

**Comment by jroose** [comment]
I'm honestly not sure where the test.bucket.amazonaws.com is coming from -- I assumed it was something within moto.  The output of `pip --verbose` (omtited for brevity) shows that pip isn't/shouldn't be trrying to connect to it:
```
http://localhost:8868 "GET /simple/axle-test-a/ HTTP/1.1" 200 496
  Found link http://localhost:9161/test_bucket/repo/axle-test-a/axle-test-a-0.0.0.tar.gz (from http://localhost:8868/simple/axle-test-a/), version: 0.0.0
  Found link http://localhost:9161/test_bucket/repo/axle-test-a/axle-test-a-0.0.0.zip (from http://localhost:8868/simple/axle-test-a/), version: 0.0.0
  Found link http://localhost:9161/test_bucket/repo/axle-test-a/axle_test_a-0.0.0-py2.py3-none-any.whl (from http://localhost:8868/simple/axle-test-a/), version: 0.0.0
Given no hashes to check 3 links for project 'axle-test-a': discarding no candidates
Collecting axle_test_a
  Created temporary directory: /tmp/pip-unpack-ddgqgy1b
  Starting new HTTP connection (1): localhost:9161
```

The logs prefixed with 127.0.0.1 appear to come from moto_server, so I'm pretty confident pip is connecting to it appropriately, otherwise moto_server wouldn't have caught the "GET" request.

**Comment by jroose** [comment]
I think I've figured this out.  It appears that underscores are invalid in bucket names because AWS normally translates them into DNS names.  As a result, I think moto_server was converting "test_bucket" to "test.bocket".  I replaced "test_bucket" with "testbucket" and now the unit test is passing.  

Thanks for your help!
