### ISSUE TITLE
mock_logs delete_metric_filter raises unexpected InvalidParameterException

### ISSUE THREAD

**Issue by guimorg** [spulec/moto#4968]
#### Issue description

When using the `moto.mock_logs`, `boto3` fails to delete a metric_filter arguing that the `logGroupName` parameter is invalid, even if the log group already exists and that the metric_filter was already created using the same `logGroupName`.

#### Steps to reproduce the issue

Here is a code snippet:

```python
>>> from moto import mock_logs
>>> import boto3
>>> mock_logs().start()
>>> client = boto3.client("logs")
>>> client.create_log_group(logGroupName="/hello-world/my-cool-endpoint")
{'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com'}, 'RetryAttempts': 0}}
>>> client.put_metric_filter(
...     logGroupName="/hello-world/my-cool-endpoint",
...     filterName="my-cool-filter",
...     filterPattern="{ $.val = * }",
...     metricTransformations=[{
...         "metricName": "my-metric",
...         "metricNamespace": "my-namespace",
...         "metricValue": "$.value",
...     }]
... )
{'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com'}, 'RetryAttempts': 0}}
>>> client.delete_metric_filter(logGroupName="/hello-world/my-cool-endpoint", filterName="my-cool-filter")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/e/venv/lib/python3.8/site-packages/botocore/client.py", line 401, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/tmp/e/venv/lib/python3.8/site-packages/botocore/client.py", line 731, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the DeleteMetricFilter operation: 1 validation error detected: Value '/hello-world/my-cool-endpoint' at 'logGroupName' failed to satisfy constraint: Must match pattern: [.-_/#A-Za-z0-9]+$
```

My environment:

- Python: 3.7.12
- boto3 version: '1.21.26'
- moto version: '3.1.1'

#### What's the expected result?

The created filter_metric on the already specified and validated log_group was deleted.

Here is the behavior running boto3 **without moto**:

```python
>>> import boto3
>>> client = boto3.client("logs")
>>> client.create_log_group(logGroupName="/hello-world/my-cool-endpoint")
{'ResponseMetadata': {'RequestId': 'xxx', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'xxx', 'content-type': 'application/x-amz-json-1.1', 'content-length': '0', 'date': 'xxx'}, 'RetryAttempts': 0}}
>>> client.put_metric_filter(
...      logGroupName="/hello-world/my-cool-endpoint",
...      filterName="my-cool-filter",
...      filterPattern="{ $.val = * }",
...      metricTransformations=[{
...          "metricName": "my-metric",
...          "metricNamespace": "my-namespace",
...          "metricValue": "$.value",
...      }]
... )
{'ResponseMetadata': {'RequestId': 'xxx', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'xxx', 'content-type': 'application/x-amz-json-1.1', 'content-length': '0', 'date': 'xxx'}, 'RetryAttempts': 0}}
>>> client.delete_metric_filter(logGroupName="/hello-world/my-cool-endpoint", filterName="my-cool-filter")
{'ResponseMetadata': {'RequestId': 'xxx', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'xxx', 'content-type': 'application/x-amz-json-1.1', 'content-length': '0', 'date': 'xxx'}, 'RetryAttempts': 0}}
```

#### What's the actual result?

The method fails somehow due to a parameter exception validation.

**Comment by bblommers** [comment]
Hi @guimorg, thanks for raising this! Marking it as a bug. Looks like our regex is a bit too strict when validating the name.
