### ISSUE TITLE
Issue with six - ImportError: No module named urlllib.parse

### ISSUE THREAD

**Issue by amitsaha** [spulec/moto#501]
Here is a simple reproducer:

```
# t.py
from raven.handlers.logging import SentryHandler                                                                                                                                                                                     
from moto import mock_s3   
```
Run this using  ``python t.py`` and you will see:

```
Traceback (most recent call last):
  File "test_six_raven.py", line 3, in <module>
    from moto import mock_s3
  File "/usr/local/lib/python2.7/dist-packages/moto/__init__.py", line 8, in <module>
    from .autoscaling import mock_autoscaling  # flake8: noqa
  File "/usr/local/lib/python2.7/dist-packages/moto/autoscaling/__init__.py", line 2, in <module>
    from .models import autoscaling_backends
  File "/usr/local/lib/python2.7/dist-packages/moto/autoscaling/models.py", line 3, in <module>
    from moto.core import BaseBackend
  File "/usr/local/lib/python2.7/dist-packages/moto/core/__init__.py", line 2, in <module>
    from .models import BaseBackend  # flake8: noqa
  File "/usr/local/lib/python2.7/dist-packages/moto/core/models.py", line 8, in <module>
    from .responses import metadata_response
  File "/usr/local/lib/python2.7/dist-packages/moto/core/responses.py", line 9, in <module>
    from six.moves.urllib.parse import parse_qs, urlparse
```

[raven-python](https://github.com/getsentry/raven-python/blob/master/raven/utils/six.py) ships with it's own version of ``six`` which is definitely causing this. 

Now, here is something which I don't yet understand. If I just add a line to the above script:

```
import six.moves.urllib
from raven.handlers.logging import SentryHandler
from moto import mock_s3
```
it all works.

**Comment by amitsaha** [comment]
There seems to be something else going on. So will close the issue.
