### ISSUE TITLE
mock_s3 on inherited classes doesn't work

### ISSUE THREAD

**Issue by saichander17** [spulec/moto#5017]
What I've observed is that if I added the decorator mock_s3 to a parent class and not add the decorator to the child class, the child class s3 instances won't be mocked. Is this expected? Couldn't find anything related to this. So, posting it here. 

Below is the code snippet I used. 

```
import boto3
from moto import mock_s3

@mock_s3
class Parent:
    def create(self):
        print("Parent Create started")
        conn = boto3.resource("s3", region_name="us-east-1")
        print(list(conn.buckets.all()))
        conn.create_bucket(Bucket="asd")
        print(list(conn.buckets.all()))
        print("Parent Create ended")

class Child(Parent):
    def create(self):
        super().create()
        print("Child Create started")
        conn = boto3.resource("s3", region_name="us-east-1")
        print(list(conn.buckets.all()))
        conn.create_bucket(Bucket="pqr")
        print(list(conn.buckets.all()))

Child().create()
```

This is the following console log I get in the response 

```
Parent Create started
[]
[s3.Bucket(name='asd')]
Parent Create ended
Child Create started
[s3.Bucket(name='api-v2-zappa-dev')]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/saichander/sixsense/repos/sixsense-api-v2/moto_test.py", line 20, in create
    conn.create_bucket(Bucket="pqr")
  File "/Users/saichander/.pyenv/versions/3.8.9/envs/sixsense-api-v2/lib/python3.8/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/saichander/.pyenv/versions/3.8.9/envs/sixsense-api-v2/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/Users/saichander/.pyenv/versions/3.8.9/envs/sixsense-api-v2/lib/python3.8/site-packages/botocore/client.py", line 337, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/saichander/.pyenv/versions/3.8.9/envs/sixsense-api-v2/lib/python3.8/site-packages/botocore/client.py", line 656, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IllegalLocationConstraintException) when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.
```

As you can see above, after the line Child Create started, it is actually using my original access key and secret key and fetching the actual buckets.

I'm wondering if this is the expected behaviour and it's mandatory to add mock_s3 decorator to both parent and child class?

**Comment by bblommers** [comment]
Hi @saichander17, the decorator adds the mock-behaviour at compile-time. At compile-time we only know about `Parent::create`, so the mock will be started before this method executes, and ends after this method has finished.
Any code executed afterwards is no longer mocked.

In your example, the mock only needs to be added to the `Child`-class, to ensure that the mock is active around the `Child::create`-method. 
(It is possible to add it to the Parent-class as well, but if the mock is already active for the Child-class, the mock for the Parent-class is ignored.)

Does that solve your problem?

**Comment by saichander17** [comment]
Yes, Thanks for the detailed answer. I think this info should be available somewhere in the documentation to avoid the confusion.
