### ISSUE TITLE
[dynamodb2] `put_item` with an empty set as an attribute does not throw ValidationException

### ISSUE THREAD

**Issue by schatten** [spulec/moto#5116]
Hey! Thanks for a great library. It makes unit tests really easy to write!

This is similar to #1129 and #1744. Tested on moto version `==2.3.2`

DynamoDB [does not allow](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes.SetTypes) empty sets as values for items. We've had to write some custom wrappers for this, and I suspect heavy users would do the same.

When writing a unit test though, moto's dynamodb does not error out.

How to reproduce:
Try the following [gist](https://gist.github.com/schatten/ecbae774b296b24afbc63e934d554d6e) 50 lines including whitespace.

Key snippets from the gist:
```python

item = {
    "Key": "some-irrelevant_key",
    "SetTypeAttribute": {"SS": set([])},
}

# The table can be a dynamodb table or a moto mocked dynamodb table.
table.put_item(Item=item)
```

The output I get is:
```
Writing to real dynamodb
Failed writing to real dynamodb
Traceback (most recent call last):
  File "moto-fail.py", line 42, in <module>
    write_via_boto()
  File "moto-fail.py", line 19, in write_via_boto
    write_item(table=table)
  File "moto-fail.py", line 11, in write_item
    table.put_item(Item=item)
  File "/home/dipanjanm/.local/lib/python3.8/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/home/dipanjanm/.local/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/dipanjanm/.local/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/dipanjanm/.local/lib/python3.8/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the PutItem operation: One or more parameter values were invalid: An number set  may not be empty


Writing to mock dynamodb
Succeeded writing to mock dynamodb
```

## Expectation
Calling `put_item` on mock dynamodb2 with an empty set as an attribute should fail with a `ValidationException`.

Cheers!

**Comment by bblommers** [comment]
Thanks for raising this @schatten!
