### ISSUE TITLE
Using moto with KCL apps locally

### ISSUE THREAD

**Issue by smnkrt** [spulec/moto#5130]
I've searched through issues and PRs and i have not found the answer.
I'm trying to set up a local development environment for a KCL app using moto (on OSX) and i've been getting into errors seemingly pointing to the lack of HTTP/2.0 support by moto:

<details><summary>KCL stacktraces</summary>

```
^[2022-05-13 14:17:36,784 [aws-java-sdk-NettyEventLoop-1-9] WARN  i.n.channel.DefaultChannelPipeline [NONE] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 3c21444f43
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:103)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:338)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:239)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-05-13 14:17:36,785 [multi-lang-daemon-0000] ERROR s.a.kinesis.leases.ShardSyncTask [NONE] - Caught exception while sync'ing Kinesis shards and leases
java.lang.RuntimeException: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: First received frame was not SETTINGS. Hex dump for first 5 bytes: 3c21444f43
	at software.amazon.kinesis.retrieval.AWSExceptionManager.apply(AWSExceptionManager.java:65)
	at software.amazon.kinesis.leases.KinesisShardDetector.listShards(KinesisShardDetector.java:210)
	at software.amazon.kinesis.leases.KinesisShardDetector.listShardsWithFilter(KinesisShardDetector.java:170)
	at software.amazon.kinesis.leases.HierarchicalShardSyncer.getShardListAtInitialPosition(HierarchicalShardSyncer.java:291)
	at software.amazon.kinesis.leases.HierarchicalShardSyncer.checkAndCreateLeaseForNewShards(HierarchicalShardSyncer.java:118)
	at software.amazon.kinesis.leases.ShardSyncTask.call(ShardSyncTask.java:70)
	at software.amazon.kinesis.metrics.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:53)
	at software.amazon.kinesis.leases.ShardSyncTaskManager.callShardSyncTask(ShardSyncTaskManager.java:144)
	at software.amazon.kinesis.coordinator.PeriodicShardSyncManager.syncShardsOnce(PeriodicShardSyncManager.java:155)
	at software.amazon.kinesis.coordinator.Scheduler.initialize(Scheduler.java:350)
	at software.amazon.kinesis.coordinator.Scheduler.run(Scheduler.java:317)
	at software.amazon.kinesis.multilang.MultiLangDaemon$MultiLangRunner.call(MultiLangDaemon.java:95)
	at software.amazon.kinesis.multilang.MultiLangDaemon$MultiLangRunner.call(MultiLangDaemon.java:86)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: First received frame was not SETTINGS. Hex dump for first 5 bytes: 3c21444f43
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98)
	at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:43)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:205)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:201)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:143)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:125)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:74)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:104)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$WrappedErrorForwardingResponseHandler.onError(MakeAsyncHttpRequestStage.java:158)
	at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.handleFailure(NettyRequestExecutor.java:299)
	at software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor.makeRequestListener(NettyRequestExecutor.java:171)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:501)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 1 common frames omitted
```

</details>

Moto logs
```
127.0.0.1 - - [13/May/2022 14:17:27] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [13/May/2022 14:17:30] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [13/May/2022 14:17:33] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [13/May/2022 14:17:36] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [13/May/2022 14:17:36] code 505, message Invalid HTTP version (2.0)
127.0.0.1 - - [13/May/2022 14:17:36] "PRI * HTTP/2.0" HTTPStatus.HTTP_VERSION_NOT_SUPPORTED -
127.0.0.1 - - [13/May/2022 14:17:37] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [13/May/2022 14:17:37] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [13/May/2022 14:17:37] "POST / HTTP/1.1" 200 -
```

As i am new to moto I'd like to confirm with you, that ATM due to lack of `subscribe_to_shard` implementation (http://docs.getmoto.org/en/latest/docs/services/kinesis.html?highlight=kinesis) it is impossible to use KCL with Moto, is that correct? I was looking for some configuration to force KCL to use  HTTP/1.1 or tweaking moto configuration, but with not luck so far.

**Comment by bblommers** [comment]
Hi @smnkrt! I'm not familiar enough with KCL to say how much it uses the `subscribe_to_shard`-functionality.

It sounds like the HTTP2-requirement is the more immediate issue. Have you looked into running Nginx as a reverse proxy? Nginx should be capable of listening/serving HTTP/2 requests, while retrieving the actual content from a regular HTTP1.1 server.

`MotoServer on port 5000` <--> `Nginx, translating HTTP/2:5001 to HTTP/1.1:5000` <--> `KCL configured to talk to port 5001`

**Comment by smnkrt** [comment]
Hi, thanks for a quick response! I have not tried it and it's a good idea - I'll look into, thanks! :)

**Comment by bblommers** [comment]
Hi @smnkrt, were you able to get this working? Or is there anything on Moto's side that needs to be done to make this work?

**Comment by smnkrt** [comment]
Hey @bblommers i was not able to try suggested approach unfortunately. Regarding MOTO's side Ideally if at some point MOTO would support `subscribe_to_shard` via HTTP/2.0 out of the box it would be awesome for KCL development/testing.
I also won't be able to try it for some time so we can close the issue. If at some point I'll try NGINX proxy i'll post a comment here.
