### ISSUE TITLE
elb doesn't work in region ap-northeast-2

### ISSUE THREAD

**Issue by beeva-antonioirizar** [spulec/moto#523]
Hello,
First of all say thank you for this library.
I use boto3 and I can't create an elb in region ap-northeast-2. I suppose it is a small bug, because I can do it in other regions.

I have the following code:

``` python
import boto3
from moto import mock_elb


@mock_elb
def test():
    client = boto3.client('elb', region_name='ap-northeast-2')
    client.create_load_balancer(LoadBalancerName='elb1', Listeners=[{
        'Protocol': 'HTTP',
        'LoadBalancerPort': 80,
        'InstancePort': 80}])


test()
```

I get the next trace:

``` console
Traceback (most recent call last):
  File "motoTest.py", line 14, in <module>
    test()
  File "/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "motoTest.py", line 11, in test
    'InstancePort': 80}])
  File "/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/botocore/client.py", line 385, in _make_api_call
    operation_model, request_dict)
  File "/botocore/endpoint.py", line 111, in make_request
    return self._send_request(request_dict, operation_model)
  File "/botocore/endpoint.py", line 140, in _send_request
    success_response, exception):
  File "/botocore/endpoint.py", line 213, in _needs_retry
    caught_exception=caught_exception)
  File "/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/botocore/retryhandler.py", line 250, in __call__
    caught_exception)
  File "/botocore/retryhandler.py", line 265, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/botocore/retryhandler.py", line 313, in __call__
    caught_exception)
  File "/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(attempt_number, caught_exception)
  File "/botocore/retryhandler.py", line 355, in _check_caught_exception
    raise caught_exception
KeyError: u'ap-northeast-2'
```

Regards.

**Comment by spulec** [comment]
Can you upgrade your version of `botocore`? My first guess is an outdated endpoint config file.

**Comment by beeva-antonioirizar** [comment]
I'm update botocore to version 1.3.26 (last version) and I get the same error.

Regards.

**Comment by spulec** [comment]
Oops, I was wrong. Can you try upgrading your version of `boto`?

**Comment by spulec** [comment]
Going to close. Feel free to reopen if the issues is still happening.
