### ISSUE TITLE
Tagging count in S3 response breaks requests

### ISSUE THREAD

**Issue by Kostia-K** [spulec/moto#5256]
I'm using `requests` to download a file from S3 using a presigned link. Here's example code where I expect it to print `b"abc"` but it throws an exception when calling `requests.get`.

```python
import boto3
import requests
from moto import mock_s3

with mock_s3():
    s3 = boto3.client("s3")
    s3.create_bucket(Bucket="my-bucket")
    s3.put_object(
        Bucket="my-bucket", Key="test.txt", Body=b"abc", Tagging="MyTag=value"
    )
    url = s3.generate_presigned_url(
        "get_object", Params={"Bucket": "my-bucket", "Key": "test.txt"}
    )
    response = requests.get(url)
    print(response.content)
```

Installation `pip install moto boto3 requests` using all latest versions.
```
boto3==1.24.15
botocore==1.27.15
moto==3.1.14
requests==2.28.0
urllib3==1.26.9
```

Traceback

```
Traceback (most recent call last):
  File "test_mock_s3.py", line 14, in <module>
    response = requests.get(url)
  File "/home/konstantin/test/moto/venv/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/konstantin/test/moto/venv/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/konstantin/test/moto/venv/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/konstantin/test/moto/venv/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/konstantin/test/moto/venv/lib/python3.8/site-packages/responses/__init__.py", line 1042, in unbound_on_send
    return self._on_request(adapter, request, *a, **kwargs)
  File "/home/konstantin/test/moto/venv/lib/python3.8/site-packages/responses/__init__.py", line 1000, in _on_request
    response = adapter.build_response(  # type: ignore[no-untyped-call]
  File "/home/konstantin/test/moto/venv/lib/python3.8/site-packages/requests/adapters.py", line 312, in build_response
    response.headers = CaseInsensitiveDict(getattr(resp, "headers", {}))
  File "/home/konstantin/test/moto/venv/lib/python3.8/site-packages/requests/structures.py", line 44, in __init__
    self.update(data, **kwargs)
  File "/usr/lib/python3.8/_collections_abc.py", line 832, in update
    self[key] = other[key]
  File "/home/konstantin/test/moto/venv/lib/python3.8/site-packages/urllib3/_collections.py", line 158, in __getitem__
    return ", ".join(val[1:])
TypeError: sequence item 0: expected str instance, int found
```

If you remove the `Tagging` parameter, it works as expected.

Seems like it's expecting header values to be strings but the S3 mock returns an int. The culprit is this line in the `moto` code https://github.com/spulec/moto/blob/master/moto/s3/models.py#L294. If I change it to
```python
res["x-amz-tagging-count"] = str(len(tags.keys()))
```
the above code works as expected.

**Comment by bblommers** [comment]
Thanks for raising this and providing the fix @Kostia-K!
