### ISSUE TITLE
Autoscaling with missing availabilityZones and launchTemplate results in broken dashboard

### ISSUE THREAD

**Issue by hans-d** [spulec/moto#5326]
## Reporting Bugs

fresh install of moto, run via `moto_server`

terraform json fragments (generated)
```
   "aws_autoscaling_group": {
      "ec2_auto_16C147B8": {
        "//": {
          "metadata": {
            "path": "proj1/ec2/auto",
            "uniqueId": "ec2_auto_16C147B8"
          }
        },
        "launch_template": {
          "id": "${aws_launch_template.ec2_tmpl_7F4E28E6.id}",
          "version": "$Default"
        },
        "max_size": 10,
        "min_size": 1
      }
 
   "aws_launch_template": {
      "ec2_tmpl_7F4E28E6": {
        "//": {
          "metadata": {
            "path": "proj1/ec2/tmpl",
            "uniqueId": "ec2_tmpl_7F4E28E6"
          }
        },
        "image_id": "${data.aws_ami.ec2_ami_086DC4ED.id}",
        "instance_type": "t2.micro"
      }
    }

```

terraform output:
```
[2022-07-24T14:16:26.667] [ERROR] default - ╷
│ Error: creating Auto Scaling Group (terraform-20220724121556627800000004): :
│ 	status code: 400, request id: 7a62c49f-347e-4fc4-9331-6e8eEXAMPLE
│
│   with aws_autoscaling_group.ec2_auto_16C147B8,
│   on cdk.tf.json line 115, in resource.aws_autoscaling_group.ec2_auto_16C147B8:
│  115:       }
```
logging output moto server:
```
127.0.0.1 - - [24/Jul/2022 14:15:56] "POST / HTTP/1.1" 400 -
```
when going to `http://127.0.0.1:5000/moto-api/#`
- screen remains blank (only black header visible)
logging output moto server:
```
127.0.0.1 - - [24/Jul/2022 14:16:46] "GET /moto-api/data.json HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Users/hansdonner/.local/share/virtualenvs/proj1-LvnwPjOk/lib/python3.9/site-packages/werkzeug/serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "/Users/hansdonner/.local/share/virtualenvs/proj1-LvnwPjOk/lib/python3.9/site-packages/werkzeug/serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "/Users/hansdonner/.local/share/virtualenvs/proj1-LvnwPjOk/lib/python3.9/site-packages/moto/moto_server/werkzeug_app.py", line 240, in __call__
    return backend_app(environ, start_response)
  File "/Users/hansdonner/.local/share/virtualenvs/proj1-LvnwPjOk/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/hansdonner/.local/share/virtualenvs/proj1-LvnwPjOk/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/hansdonner/.local/share/virtualenvs/proj1-LvnwPjOk/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/hansdonner/.local/share/virtualenvs/proj1-LvnwPjOk/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hansdonner/.local/share/virtualenvs/proj1-LvnwPjOk/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hansdonner/.local/share/virtualenvs/proj1-LvnwPjOk/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/hansdonner/.local/share/virtualenvs/proj1-LvnwPjOk/lib/python3.9/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hansdonner/.local/share/virtualenvs/proj1-LvnwPjOk/lib/python3.9/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hansdonner/.local/share/virtualenvs/proj1-LvnwPjOk/lib/python3.9/site-packages/moto/core/utils.py", line 128, in __call__
    result = self.callback(request, request.url, dict(request.headers))
  File "/Users/hansdonner/.local/share/virtualenvs/proj1-LvnwPjOk/lib/python3.9/site-packages/moto/moto_api/_internal/responses.py", line 56, in model_data
    json.dumps(getattr(instance, attr))
  File "/Users/hansdonner/.local/share/virtualenvs/proj1-LvnwPjOk/lib/python3.9/site-packages/moto/autoscaling/models.py", line 511, in image_id
    if self.launch_template:
AttributeError: 'FakeAutoScalingGroup' object has no attribute 'launch_template'
```

Expecting:
- more verbose logging on moto why requests are returning errors
- autoscaling group to be created without error
- dashboard to be functioning

**Comment by hans-d** [comment]
ok, caused by not having `availability_zones` as parameter.
Still, having some more info on the moto_server stdout and the failing dashboard is still an issue

**Comment by bblommers** [comment]
Thanks for raising this @hans-d - we should indeed have some validation before exploding.
