### ISSUE TITLE
Default ACL not set for multipart upload

### ISSUE THREAD

**Issue by ColdrickSotK** [spulec/moto#5408]
## Context

When using moto's implementation of S3's multipart upload to upload an object, the ACL seems like it is not set on the object unless it is specified explicitly by the uploader. This causes problems with subsequent requests to access the object, eg. `HeadObject`.

For some reason that I've not got to the bottom of, this issue only seems to occur when using presigned URLs to send the `HeadObject` request, using boto's client methods directly works as expected.

### Expected behaviour

- Upload a large object using multipart upload
- Send a HeadObject request using a presigned URL
- Get a successful response

### Actual behaviour

- Upload a large object using multipart upload
- Send a HeadObject request using a presigned URL
- An `AttributeError` is raised in the `mock_s3` context manager

## Traceback

```
Traceback (most recent call last):
  File "/home/adam/Projects/buildstream/buildgrid/.tox/venv/lib/python3.10/site-packages/werkzeug/serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "/home/adam/Projects/buildstream/buildgrid/.tox/venv/lib/python3.10/site-packages/werkzeug/serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "/home/adam/Projects/buildstream/buildgrid/.tox/venv/lib/python3.10/site-packages/moto/moto_server/werkzeug_app.py", line 240, in __call__
    return backend_app(environ, start_response)
  File "/home/adam/Projects/buildstream/buildgrid/.tox/venv/lib/python3.10/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/adam/Projects/buildstream/buildgrid/.tox/venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/home/adam/Projects/buildstream/buildgrid/.tox/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/adam/Projects/buildstream/buildgrid/.tox/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/adam/Projects/buildstream/buildgrid/.tox/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/adam/Projects/buildstream/buildgrid/.tox/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/adam/Projects/buildstream/buildgrid/.tox/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adam/Projects/buildstream/buildgrid/.tox/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/adam/Projects/buildstream/buildgrid/.tox/venv/lib/python3.10/site-packages/moto/core/utils.py", line 128, in __call__
    result = self.callback(request, request.url, dict(request.headers))
  File "/home/adam/Projects/buildstream/buildgrid/.tox/venv/lib/python3.10/site-packages/moto/core/utils.py", line 262, in _wrapper
    response = f(*args, **kwargs)
  File "/home/adam/Projects/buildstream/buildgrid/.tox/venv/lib/python3.10/site-packages/moto/s3/responses.py", line 1087, in key_response
    response = self._key_response(request, full_url, self.headers)
  File "/home/adam/Projects/buildstream/buildgrid/.tox/venv/lib/python3.10/site-packages/moto/s3/responses.py", line 1132, in _key_response
    if not key.acl.public_read and not signed_url:
AttributeError: 'NoneType' object has no attribute 'public_read'
```

## Reproduction

This snippet demonstrates the issue for me. In my actual codebase I'm using presigned URLs for the upload steps too, but the problem is also present when using boto3 directly as in this example.

``` python
import boto3
from moto import mock_s3
import requests

with mock_s3():
    auth_args = {
        "aws_access_key_id": "access_key",
        "aws_secret_access_key": "secret_key"
    }
    client = boto3.client('s3', **auth_args)

    bucket_name = 'testing'
    client.create_bucket(Bucket=bucket_name)

    object_key = 'test_multipart_object'
    content = b'some large thing' + b'.' * 200 * 1024 * 1024

    multipart_response = client.create_multipart_upload(
        # ACL='private',  # Uncomment to "fix" the issue, but this parameter is optional
        Bucket=bucket_name,
        Key=object_key
    )
    upload_id = multipart_response['UploadId']

    chunk_size = 100 * 1024 * 1024
    offset = 0
    part_number = 1
    parts = {}
    while offset < len(content):
        part = client.upload_part(
            Bucket=bucket_name,
            Key=object_key,
            UploadId=upload_id,
            PartNumber=part_number,
            Body=content[offset:offset+chunk_size]
        )
        parts[part_number] = part['ETag']
        part_number += 1
        offset += chunk_size

    client.complete_multipart_upload(
        Bucket=bucket_name,
        Key=object_key,
        UploadId=upload_id,
        MultipartUpload={
            'Parts': [
                {
                    'ETag': tag,
                    'PartNumber': number
                }
                for number, tag in parts.items()
            ]
        }
    )

    # Works fine
    client.head_object(Bucket=bucket_name, Key=object_key)

    # Raises an AttributeError in moto
    url = client.generate_presigned_url(
        'head_object',
        Params={'Bucket': bucket_name, 'Key': object_key}
    )
    requests.get(url)
```

## Version info

Using the moto python mocks. Dependencies installed with pip into a virtualenv managed by tox.

moto==3.1.16
boto3==1.24.49
botocore==1.27.49

**Comment by bblommers** [comment]
Thank you for raising this and providing the repro @ColdrickSotK! Marking it as a bug.
