### ISSUE TITLE
Incompatible with openapi-spec-validator >= 0.5

### ISSUE THREAD

**Issue by yan12125** [spulec/moto#5457]
## Reporting Bugs

In a virtual environment,
```
$ pip install moto==4.0.2 openapi-spec-validator==0.5.1
$ cat test-moto.py
from moto import mock_apigateway

@mock_apigateway
def foo():
    pass
$ python test-moto.py 
Traceback (most recent call last):
  File "/home/yen/tmp/test-moto.py", line 4, in <module>
    def foo():
  File "/home/yen/tmp/venv/lib/python3.10/site-packages/moto/__init__.py", line 8, in f
    module = importlib.import_module(module_name, "moto")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/yen/tmp/venv/lib/python3.10/site-packages/moto/apigateway/__init__.py", line 1, in <module>
    from .models import apigateway_backends
  File "/home/yen/tmp/venv/lib/python3.10/site-packages/moto/apigateway/models.py", line 15, in <module>
    from openapi_spec_validator.exceptions import OpenAPIValidationError
ImportError: cannot import name 'OpenAPIValidationError' from 'openapi_spec_validator.exceptions' (/home/yen/tmp/venv/lib/python3.10/site-packages/openapi_spec_validator/exceptions.py)
```

There is no error with `openapi-spec-validator==0.4.0`.

**Comment by yan12125** [comment]
Many thanks for the fast fix!
