### ISSUE TITLE
file descriptor cannot be a negative integer (-1)

### ISSUE THREAD

**Issue by japo32** [spulec/moto#548]
This may be related to another issue since I'm getting a similar error: https://github.com/spulec/moto/issues/440

```
File "/usr/share/stuff-site-adcontrol/.test-venv/lib/python3.4/site-packages/botocore/awsrequest.py", line 162, in _send_output
    read, write, exc = select.select([self.sock], [], [self.sock], 1)
ValueError: file descriptor cannot be a negative integer (-1)
```

Here's my test case:

```
    @mock_s3
    def test_boto3_bucket_create(self):
        s3 = boto3.resource('s3')
        s3.create_bucket(Bucket="blah")

        self.test_file = open('/tmp/foo.txt', 'w+');
        self.test_file.write('This is a test file!')
        self.test_file.close()
        self.test_file = open("/tmp/foo.txt", "r+")
        pp.pprint('------=====')
        pp.pprint(self.test_file.read())
        s3.Object('blah', 'hello.txt').upload_file('/tmp/foo.txt')
        self.test_file.close()
```

I'm on Python 3.4.3 with:

```
amqp==1.4.9
anyjson==0.3.3
billiard==3.3.0.22
boto==2.39.0
boto3==1.2.3
botocore==1.3.28
cached-property==1.2.0
celery==3.1.18
Django==1.8.9
django-cors-headers==1.1.0
django-filter==0.11.0
djangorestframework==3.2.2
docutils==0.12
Flask==0.10.1
Flask-SQLAlchemy==2.0
httpretty==0.8.14
itsdangerous==0.24
Jinja2==2.8
jmespath==0.9.0
kombu==3.0.33
MarkupSafe==0.23
moto==0.4.22
nose2==0.6.0
pep8==1.7.0
phpserialize==1.3
psycopg2==2.6.1
python-dateutil==2.4.2
pytz==2015.7
redis==2.10.5
requests==2.2.1
six==1.10.0
SQLAlchemy==1.0.8
urllib3==1.14
-e git+git+ssh://gerrit.dmz.wgtn.cat-it.co.nz:29418/fairfax-adfliction.git@7d8f718aefb958f0cd2eb60eec6f9b4c1429a791#egg=vizeng&subdirectory=submodules/viz_engine
Werkzeug==0.11.4
wheel==0.26.0
xmltodict==0.9.2

```

As you can see I have moto==0.4.22 and httpretty==0.8.14

**Comment by spulec** [comment]
Does downgrading to `httpretty==0.8.0` work as suggested in that issue?

**Comment by japo32** [comment]
Hi @spulec, when I downgrade httpretty to 0.8.0 I get this. This is with everything else the same.

```
    HTTPResponse.__init__(self, *args, **kwargs)
  File "/usr/lib/python3.4/http/client.py", line 290, in __init__
    self.fp = sock.makefile("rb")
  File "/usr/share/stuff-site-adcontrol/.test-venv/lib/python3.4/site-packages/httpretty/core.py", line 312, in makefile
    self._entry.fill_filekind(self.fd)
  File "/usr/share/stuff-site-adcontrol/.test-venv/lib/python3.4/site-packages/httpretty/core.py", line 592, in fill_filekind
    fk.write(utf8(item) + b'\n')
ValueError: I/O operation on closed file.
```

**Comment by wrr** [comment]
I experience the same issues that @japo32 (I use Python 3.5.1). Doing:

    s3.Object('foo', 'bar').put(Body=b'hello')

results in `file descriptor cannot be a negative integer` error with `httpretty` newer than `0.8.10`, and `I/O operation on closed file` with older versions of `httpretty`

**Comment by spulec** [comment]
Can you try this again with the latest version of moto and let me know if it is still happening?

**Comment by japo32** [comment]
Thanks @spulec, the file descriptor error is gone.

I changed the versions to:
```
moto==0.4.23
httpretty==0.8.14
```

But I'm getting a new error with one of my other tests:
```
 def test_get_create_object(self):
        s3 = boto3.resource('s3')
        s3.create_bucket(Bucket="blah")
        self.test_file = open('/tmp/foo.txt', 'w+')
        self.test_file.write('This is a test file!')
        self.test_file.close()
        self.test_file = open("/tmp/foo.txt", "r+")
        s3.Object('blah', 'hello.txt').upload_file('/tmp/foo.txt')
        object_in_bucket = s3.meta.client.get_object(Bucket="blah", Key='hello.txt')
        self.assertEqual(
            self.content,
            object_in_bucket['Body'].read().decode("utf-8"))
```

```
Traceback (most recent call last):
  File "/usr/share/stuff-site-adcontrol/.test-venv/lib/python3.4/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "/usr/share/stuff-site-adcontrol/submodules/cron/test/test_utils_s3.py", line 50, in test_get_create_object
    object_in_bucket = s3.meta.client.get_object(Bucket="blah", Key='hello.txt')
  File "/usr/share/stuff-site-adcontrol/.test-venv/lib/python3.4/site-packages/botocore/client.py", line 301, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/share/stuff-site-adcontrol/.test-venv/lib/python3.4/site-packages/botocore/client.py", line 375, in _make_api_call
    operation_model, request_dict)
  File "/usr/share/stuff-site-adcontrol/.test-venv/lib/python3.4/site-packages/botocore/endpoint.py", line 111, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/share/stuff-site-adcontrol/.test-venv/lib/python3.4/site-packages/botocore/endpoint.py", line 138, in _send_request
    request, operation_model, attempts)
  File "/usr/share/stuff-site-adcontrol/.test-venv/lib/python3.4/site-packages/botocore/endpoint.py", line 193, in _get_response
    operation_model.output_shape)),
  File "/usr/share/stuff-site-adcontrol/.test-venv/lib/python3.4/site-packages/botocore/parsers.py", line 208, in parse
    parsed = self._do_parse(response, shape)
  File "/usr/share/stuff-site-adcontrol/.test-venv/lib/python3.4/site-packages/botocore/parsers.py", line 555, in _do_parse
    member_shapes, final_parsed)
  File "/usr/share/stuff-site-adcontrol/.test-venv/lib/python3.4/site-packages/botocore/parsers.py", line 611, in _parse_non_payload_attrs
    member_shape, headers[header_name])
  File "/usr/share/stuff-site-adcontrol/.test-venv/lib/python3.4/site-packages/botocore/parsers.py", line 226, in _parse_shape
    return handler(shape, node)
  File "/usr/share/stuff-site-adcontrol/.test-venv/lib/python3.4/site-packages/botocore/parsers.py", line 149, in _get_text_content
    return func(self, shape, text)
  File "/usr/share/stuff-site-adcontrol/.test-venv/lib/python3.4/site-packages/botocore/parsers.py", line 375, in _handle_integer
    return int(text)
ValueError: invalid literal for int() with base 10: "b'\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00'"

```

**Comment by johanneskoester** [comment]
I am getting the same error. Does not happen with httpretty 0.8.10.

**Comment by jtprince** [comment]
I had this problem with moto 0.4.19 ("file descriptor cannot be a negative integer").  I then upgraded to 0.4.27 and things worked (i.e., the error went away).  Perhaps this issue has been properly addressed now and should be closed?

**Comment by spulec** [comment]
Thanks for the update. Is anyone seeing this with the moto 0.4.27?

**Comment by adamtheturtle** [comment]
> Thanks for the update. Is anyone seeing this with the moto 0.4.27?

@spulec I am, but I'm not in a position right now to make a small reproducible case. I get the `invalid literal for int() with base 10` and it works when I use httpretty 0.8.10.

Thanks for the software 😄

**Comment by spulec** [comment]
We've replaced HTTPretty with Responses in `master`. I'm optimistic this will fix this issue. Can someone give it a test?

**Comment by spulec** [comment]
Going to close this out. Feel free to reopen if it is still happening.

**Comment by muppetjones** [comment]
@spulec I'm suddenly getting this with `moto==0.4.30` and `httpretty==0.8.14`. I've been using these versions for some time, so I don't know where this came from.

Upgrading to `moto==0.4.31` fixes the issue.

**Comment by spulec** [comment]
Got it; thanks for letting me know
