### ISSUE TITLE
Create EC2 instance with nonexistent security group raises exception instead of giving an appropriate error

### ISSUE THREAD

**Issue by cheshirex** [spulec/moto#5484]
My team encountered this when moving from an old version of localstack to a newer one. Apparently in an older version, we could just pass in a non-existent security group as part of the configuration for an EC2 instance request, but in the newer version moto actually looks up the security group.

This line:
https://github.com/spulec/moto/blob/9fc64ad93b40ad179a828be19e6da940e7256e02/moto/ec2/models/security_groups.py#L572
will return the security group found _or None_ if nothing was found. But this line:
https://github.com/spulec/moto/blob/9fc64ad93b40ad179a828be19e6da940e7256e02/moto/ec2/models/instances.py#L482
will try to access the security group ID from the security group object, without realizing the possibility that the security group may not exist, and instead we have a None object in the list.

The call stack we got (from localstack 0.14.5 (which seems to be using moto 3.1.12 if I'm reading that right), but I checked and the relevant lines in moto's master branch don't seem to have changed) is:
```
2022-09-19T06:47:22.130:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST http://diamond-localstack:4566/: 'NoneType' object has no attribute 'id' Traceback (most recent call last):
  File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 185, in index
    result = await run_sync(handler, request, data)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 85, in run_sync
    return await loop.run_in_executor(thread_pool, copy_context().run, func_wrapped)
  File "/opt/code/localstack/localstack/utils/threads.py", line 39, in run
    result = self.func(self.params, **kwargs)
  File "/opt/code/localstack/localstack/utils/asyncio.py", line 30, in _run
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 993, in handler
    return modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/services/edge.py", line 170, in forward_request
    result = do_forward_request(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 534, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 614, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/http/adapters.py", line 51, in forward_request
    response = self.request(request)
  File "/opt/code/localstack/localstack/aws/proxy.py", line 43, in request
    return self.skeleton.invoke(context)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/localstack/aws/forwarder.py", line 61, in _call
    return fallthrough_handler(context, req)
  File "/opt/code/localstack/localstack/services/moto.py", line 109, in proxy_moto
    status, headers, content = dispatch_to_moto(context)
  File "/opt/code/localstack/localstack/services/moto.py", line 139, in dispatch_to_moto
    return dispatch(request, request.url, request.headers)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/responses.py", line 205, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/responses.py", line 315, in _dispatch
    return self.call_action()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/core/responses.py", line 405, in call_action
    response = method()
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/ec2/responses/instances.py", line 83, in run_instances
    new_reservation = self.ec2_backend.add_instances(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/ec2/models/instances.py", line 607, in add_instances
    new_instance = Instance(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/ec2/models/instances.py", line 160, in __init__
    self.prep_nics(
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/ec2/models/instances.py", line 468, in prep_nics
    group_ids.extend([group.id for group in security_groups])
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/moto/ec2/models/instances.py", line 468, in <listcomp>
    group_ids.extend([group.id for group in security_groups])
AttributeError: 'NoneType' object has no attribute 'id'
```

I'm going to apologize here because normally I would try to dig into more information, compare the actual behaviour of AWS in this specific instance and such, but I'm under some time pressure at the moment and can't get into that right now -- but I didn't want to leave this without at least opening the issue here for your awareness. We have a workaround (basically, deferring upgrading the localstack version for now) so I can't stay on this at the moment.

Thanks!

**Comment by bblommers** [comment]
Thanks for raising this @cheshirex!

**Comment by bblommers** [comment]
Looks like AWS returns this error:
`{'Code': 'InvalidGroup.NotFound', 'Message': "The security group 'sg-bbfe0e' does not exist in VPC 'vpc-...'"}`
