### ISSUE TITLE
Dynamodb mock, missing validation for transactions (transact_write_items)

### ISSUE THREAD

**Issue by LukaK** [spulec/moto#5496]
Hello,
creating transaction with conflicting operations seem to pass locally with dynamodb_mock. For example creating Add and Delete operation of the same item will fail on the stack but pass locally.

Code to reproduce.
```
#!/usr/bin/env python
import boto3
import pytest
from moto import mock_dynamodb



@pytest.fixture()
def mock_table():
    with mock_dynamodb():

        dynamodb = boto3.resource("dynamodb", region_name="eu-west-1")

        # Create the table
        dynamodb.create_table(
            TableName="test_table",
            KeySchema=[
                {"AttributeName": "pk", "KeyType": "HASH"},
                {"AttributeName": "sk", "KeyType": "RANGE"},
            ],
            AttributeDefinitions=[
                {"AttributeName": "pk", "AttributeType": "S"},
                {"AttributeName": "sk", "AttributeType": "S"},
            ],
            BillingMode="PAY_PER_REQUEST",
        )
        yield dynamodb

def main():
    dc = boto3.client("dynamodb")
    dc.transact_write_items(
        TransactItems = [
            {
                "Put": {
                    "Item": {"pk": {"S": 'test'}, "sk": {"S": 'test'}},
                    "TableName": "test_table",
                },
                "Delete": {
                    "Key": {"pk": {"S": 'test'}, "sk": {"S": 'test'}},
                    "TableName": "test_table",
                }
            }
        ]
    )

def test__main(mock_table):
    main()

if __name__ == "__main__":
    main()

```

If you run `pytest` locally it will pass, but if you run it on real dynamodb table you will get
```
Traceback (most recent call last):
  File "./test.py", line 50, in <module>
    main()
  File "./test.py", line 40, in main
    "TableName": "test_table",
  File "/home/luka/.virtualenvs/tg-scheduler/lib/python3.7/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/luka/.virtualenvs/tg-scheduler/lib/python3.7/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the TransactWriteItems operation: TransactItems can only contain one of Check, Put
, Update or Delete
```
Moto version: `moto==4.0.2 and boto3==1.24.54` but the same happens on `moto==3.0.7`.

**Comment by bblommers** [comment]
Thanks for raising this @LukaK - marking it as an enhancement to add this validation.
If you want to implement this yourself, PR's are always welcome!
