### ISSUE TITLE
How to create a mock AWS::ApiGateway::Resource ?

### ISSUE THREAD

**Issue by jhw** [spulec/moto#5766]
I am trying to create a mock HTTP GET endpoint for a Lambda funcion, and along the way need to create an instance of `AWS::ApiGateway::Resource` -

```
import unittest

from moto import mock_apigateway

import boto3

@mock_apigateway
class HelloTest(unittest.TestCase):

    def setUp(self):
        apigw=boto3.client('apigateway')
        restapi=apigw.create_rest_api(name="my-rest-api")
        resource=apigw.create_resource(restApiId=restapi["id"],
                                       parentId=restapi["id"], # <-- what goes here?
                                       pathPart="whatevs")
        print (resource)
    
    def test_hello(self):
        self.assertEqual(2, 2)

if __name__=="__main__":
    unittest.main()
```

But this fails with -

```
======================================================================
ERROR: test_hello (__main__.HelloTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jhw/work/deployer/env/lib/python3.8/site-packages/moto/core/models.py", line 110, in wrapper
    result = func(*args, **kwargs)
  File "dev/test_mock_apigw.py", line 13, in setUp
    resource=apigw.create_resource(restApiId=restapi["id"],
  File "/Users/jhw/work/deployer/env/lib/python3.8/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/jhw/work/deployer/env/lib/python3.8/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NotFoundException: An error occurred (NotFoundException) when calling the CreateResource operation: Invalid resource identifier specified

----------------------------------------------------------------------
Ran 1 test in 0.181s

FAILED (errors=1)
```

The problem seems to be the `parentId` parameter being passed to `create_resource`.

Looking at the docs for `AWS::ApiGateway::Resource` for a moment - 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-resource.html

```
[ParentId] If you want to create a child resource, the ID of the parent resource. For resources without a parent, specify the RestApi root resource ID, such as { "Fn::GetAtt": ["MyRestApi", "RootResourceId"] }.
```

That's fine if using Cloudformation, but how to do the equivalent in boto/moto?

**Comment by bblommers** [comment]
Hi @jhw! When a REST API is created, Moto/AWS automatically create a root resource (`/`). This is the resource that should be used as a parent for immediate child resources.

You can retrieve the ID of the root resource like so:
```
resources = client.get_resources(restApiId=api_id)
root_id = [resource for resource in resources["items"] if resource["path"] == "/"][0]["id"]
```
It's a bit cumbersome, but this is the official/AWS way of retrieving this value, as far as I'm aware.

**Comment by jhw** [comment]
Excellent! Thank you. Closed.
