### ISSUE TITLE
GetQueueUrlAsync() throws invalid security token exception.

### ISSUE THREAD

**Issue by rita005** [spulec/moto#5819]
Hello.

I'm trying to run some integrations tests on azure release pipelines. I was able to run tests successfully on my local machine using moto docker image, but when I try to connect to connect to SQS the following error is thrown:

```
2023-01-05T11:54:36.0558026Z       The security token included in the request is invalid.
2023-01-05T11:54:36.0558402Z       Amazon.SQS.AmazonSQSException: The security token included in the request is invalid.
2023-01-05T11:54:36.0559066Z        ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
2023-01-05T11:54:36.0559606Z          at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
2023-01-05T11:54:36.0560059Z          at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
2023-01-05T11:54:36.0560512Z          at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
2023-01-05T11:54:36.0560965Z          at Amazon.SQS.Internal.ValidationResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
2023-01-05T11:54:36.0561426Z          at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
2023-01-05T11:54:36.0561857Z          --- End of inner exception stack trace ---
2023-01-05T11:54:36.0562401Z          at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
2023-01-05T11:54:36.0563412Z          at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
2023-01-05T11:54:36.0563995Z          at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
2023-01-05T11:54:36.0564513Z          at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
2023-01-05T11:54:36.0564999Z          at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
2023-01-05T11:54:36.0565448Z          at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
2023-01-05T11:54:36.0565878Z          at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
2023-01-05T11:54:36.0566339Z          at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
2023-01-05T11:54:36.0566812Z          at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
2023-01-05T11:54:36.0567290Z          at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
2023-01-05T11:54:36.0567739Z          at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
2023-01-05T11:54:36.0568181Z          at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
2023-01-05T11:54:36.0568629Z          at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
2023-01-05T11:54:36.0569071Z          at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
2023-01-05T11:54:36.0569523Z          at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
2023-01-05T11:54:36.0570068Z          at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
2023-01-05T11:54:36.0570589Z          at SqsDummyProject.MessageProxy.GetQueueUrlAsync() in 
```

The environment variables used on my local machine are the same as the ones used on the pipeline. Also, when trying to connect to S3 no problems were found.

I've created a dummy project to replicate this odd behavior: [SQS Test Project](https://dev.azure.com/1181183/sqs-test-project/_release?definitionId=1&view=mine&_a=releases
)

Thanks in advance!

**Comment by bblommers** [comment]
Hi @rita005, I'm not a C# developer myself, so I can't offer a lot of help here I'm afraid.

The only thing that stands out to  me are the [environment variables](https://dev.azure.com/1181183/sqs-test-project/_releaseProgress?releaseId=10&_a=release-variables). They configure `localhost:8090` as the proxy - shouldn't this value be used as the EndpointURL, instead of a proxy?

**Comment by rita005** [comment]
Thanks for your reply!
I've already tried with the env variable ServiceUrl but the output is the same,

If the token is invalid shouldn't the behaviour be coherent in all aws mocked services? For example, in S3 everything works as expected but for SQS it doesn't.

**Comment by bblommers** [comment]
> If the token is invalid shouldn't the behaviour be coherent in all aws mocked services? For example, in S3 everything works as expected but for SQS it doesn't.
>

Yes, it should be coherent - I don't know why it isn't. Can you show the behaviour of S3 in the same project, i.e. with the same env vars/setup?

**Comment by rita005** [comment]
I'm sorry for the late response.

I was not able to mimic the behavior that I have on the original project, where only sqs fails. You can check the results [here](https://dev.azure.com/1181183/sqs-test-project/_releaseProgress?releaseId=29&_a=release-pipeline-progress).

I've tried multiple configurations with no luck. Locally everything works as intended.

**Comment by bblommers** [comment]
The pipeline variables are only set for 'Release' - no variables are set for `SQS try connect`. Could that be the issue?

![Screenshot from 2023-02-07 21-00-32](https://user-images.githubusercontent.com/6058517/217376832-394d509b-f037-44ab-82b5-0d08f1e6bb15.png)

**Comment by rita005** [comment]
Release variables are set for all the stages on a release pipeline. On the logs, you can check on the "Initialize Job" step all the environment variables available for the current job.

Do you think it's possible to be some kind of issue related to docker's time/timezone?

**Comment by bblommers** [comment]
The `aws cli` commands do succeed against Moto, that's why I'm assuming this is a configuration problem - not an issue with MotoServer/the docker container.

There is [this issue](https://github.com/aws/aws-sdk-net/issues/1977), which indicates that the `AWS:PROXYHOST` variable isn't taken into account at all. That could be another avenue to check; see whether it does work with the proxy config specified as part of the config files.

**Comment by bblommers** [comment]
I don't think there's anything else Moto can do here, so I'm going to close this.

We have some dotnet tests now to verify that the MotoServer itself works, with hardcoded credentials. How to get it working with config files/environment variables is more a question for the AWS SDK as far as I'm concerned.
https://github.com/getmoto/moto/blob/master/other_langs/tests_dotnet/ExampleTestProject/UnitTest.cs
