### ISSUE TITLE
utf-8 character in url fails to match mock_s3 urls

### ISSUE THREAD

**Issue by bchatelard** [spulec/moto#598]
Url matching is broken on latest release, this sample is not working anymore.

```
# -*- coding: utf-8 -*-

import boto
from boto.s3.key import Key
from moto import mock_s3

@mock_s3
def test_my_model_save():
    conn = boto.connect_s3()
    bucket = conn.create_bucket('mybucket')

    key = Key(bucket, '/working/test')
    key.set_contents_from_string("test")

    key = Key(bucket, '/nonworkîng/test')
    key.set_contents_from_string("test")
```

I have the following traceback:

```
Traceback (most recent call last):
  File "test_moto.py", line 19, in <module>
    test_my_model_save()
  File "/.virtualenvs/test/lib/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "test_moto.py", line 16, in test_my_model_save
    key.set_contents_from_string("test")
  File "/.virtualenvs/test/lib/python2.7/site-packages/boto/s3/key.py", line 1426, in set_contents_from_string
    encrypt_key=encrypt_key)
  File "/.virtualenvs/test/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/.virtualenvs/test/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/.virtualenvs/test/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/.virtualenvs/test/lib/python2.7/site-packages/boto/s3/connection.py", line 670, in make_request
    retry_handler=retry_handler
  File "/.virtualenvs/test/lib/python2.7/site-packages/boto/connection.py", line 1077, in make_request
    retry_handler=retry_handler)
  File "/.virtualenvs/test/lib/python2.7/site-packages/boto/connection.py", line 941, in _mexe
    request.body, request.headers)
  File "/.virtualenvs/test/lib/python2.7/site-packages/boto/s3/key.py", line 844, in sender
    http_conn.send(chunk)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 869, in send
    self.sock.sendall(data)
  File "/.virtualenvs/test/lib/python2.7/site-packages/httpretty/core.py", line 385, in sendall
    return self.real_sendall(data, *args, **kw)
  File "/.virtualenvs/test/lib/python2.7/site-packages/httpretty/core.py", line 353, in real_sendall
    self.truesock.connect(self._address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 22] Invalid argument
```

This sample is working on release 0.4.20, i think this was introduced by a7938ed9ec814fa9cf53272ceb65e84d11d50dc1

**Comment by spulec** [comment]
This is fixed now. Please feel free to reopen if there are still issues.
