### ISSUE TITLE
After running update_auto_scaling_group calls to describe_auto_scaling_groups fails

### ISSUE THREAD

**Issue by boynux** [spulec/moto#603]
After running `update_auto_scaling_group` trying to retrieve the same auto scaling group with `describe_auto_scaling_groups` fails.

How to produce: 

1. Create an auto scaling group with name 'test-asg'
2. change `MinSize` to 0 with `update_auto_scaling_group` method
3. call `describe_auto_scaling_group` with `name=['test-asg']`

Expected result: an array with that auto scaling group defintion
Actual result: Exception `ValueError: invalid literal for int() with base 10: 'None'`

Here is the full stack trace:

```
======================================================================
ERROR: test_retrieve_autoscaling_groups_in_vpc (tests.helpers.aws.test_asg_descale.AsgDescaleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "/home/mamad/Working/secret-ops-scripts/tests/helpers/aws/test_asg_descale.py", line 45, in test_retrieve_autoscaling_groups_in_vpc
    asg_result = self.get_asg('test-asg-group')
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "/home/mamad/Working/secret-ops-scripts/tests/helpers/aws/test_asg_descale.py", line 37, in get_asg
    AutoScalingGroupNames=[asg_name]
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/botocore/client.py", line 252, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/botocore/client.py", line 531, in _make_api_call
    operation_model, request_dict)
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/botocore/endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/botocore/endpoint.py", line 144, in _send_request
    request, operation_model, attempts)
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/botocore/endpoint.py", line 203, in _get_response
    parser.parse(response_dict, operation_model.output_shape)),
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/botocore/parsers.py", line 211, in parse
    parsed = self._do_parse(response, shape)
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/botocore/parsers.py", line 458, in _do_parse
    parsed = self._parse_shape(shape, start)
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/botocore/parsers.py", line 257, in _parse_shape
    return handler(shape, node)
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/botocore/parsers.py", line 326, in _handle_structure
    member_shape, member_node)
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/botocore/parsers.py", line 257, in _parse_shape
    return handler(shape, node)
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/botocore/parsers.py", line 310, in _handle_list
    return super(BaseXMLResponseParser, self)._handle_list(shape, node)
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/botocore/parsers.py", line 265, in _handle_list
    parsed.append(self._parse_shape(member_shape, item))
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/botocore/parsers.py", line 257, in _parse_shape
    return handler(shape, node)
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/botocore/parsers.py", line 326, in _handle_structure
    member_shape, member_node)
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/botocore/parsers.py", line 257, in _parse_shape
    return handler(shape, node)
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/botocore/parsers.py", line 149, in _get_text_content
    return func(self, shape, text)
  File "/home/mamad/Working/secret-ops-scripts/.env/local/lib/python2.7/site-packages/botocore/parsers.py", line 415, in _handle_integer
    return int(text)
ValueError: invalid literal for int() with base 10: 'None'

----------------------------------------------------------------------
```

**Comment by spulec** [comment]
Thanks for opening!
