### ISSUE TITLE
redshift boto3 failure

### ISSUE THREAD

**Issue by kapilt** [spulec/moto#607]
``` python
import boto3
from moto import mock_redshift
import unittest

class RedshiftTest(unittest.TestCase):

    @mock_redshift
    def test_redshift(self):
        client = boto3.client('redshift')
        self.assertEqual(
            client.describe_clusters(), [])
```

results in 

```
nosetests -s -v tests/test_redshift.py
test_redshift (tests.test_redshift.RedshiftTest) ... ERROR

======================================================================
ERROR: test_redshift (tests.test_redshift.RedshiftTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ylv522/projects/pypy-c7n/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "/Users/ylv522/projects/custodian/tests/test_redshift.py", line 15, in test_redshift
    client.describe_clusters(), [])
  File "/Users/ylv522/projects/pypy-c7n/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/ylv522/projects/pypy-c7n/site-packages/botocore/client.py", line 396, in _make_api_call
    operation_model, request_dict)
  File "/Users/ylv522/projects/pypy-c7n/site-packages/botocore/endpoint.py", line 111, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/ylv522/projects/pypy-c7n/site-packages/botocore/endpoint.py", line 138, in _send_request
    request, operation_model, attempts)
  File "/Users/ylv522/projects/pypy-c7n/site-packages/botocore/endpoint.py", line 197, in _get_response
    operation_model.output_shape)),
  File "/Users/ylv522/projects/pypy-c7n/site-packages/botocore/parsers.py", line 208, in parse
    parsed = self._do_parse(response, shape)
  File "/Users/ylv522/projects/pypy-c7n/site-packages/botocore/parsers.py", line 410, in _do_parse
    root = self._parse_xml_string_to_dom(xml_contents)
  File "/Users/ylv522/projects/pypy-c7n/site-packages/botocore/parsers.py", line 346, in _parse_xml_string_to_dom
    "invalid XML received:\n%s" % (e, xml_string))
ResponseParserError: Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received:
{"DescribeClustersResponse": {"DescribeClustersResult": {"Clusters": []}, "ResponseMetadata": {"RequestId": "384ac68d-3775-11df-8963-01868b7c937a"}}}
-------------------- >> begin captured logging << --------------------
botocore.credentials: DEBUG: Skipping environment variable credential check because profile name was explicitly set.
botocore.credentials: DEBUG: Looking for credentials via: env
botocore.credentials: DEBUG: Looking for credentials via: assume-role
botocore.credentials: DEBUG: Looking for credentials via: shared-credentials-file
botocore.credentials: DEBUG: Looking for credentials via: config-file
botocore.credentials: DEBUG: Looking for credentials via: ec2-credentials-file
botocore.credentials: DEBUG: Looking for credentials via: boto-config
botocore.credentials: DEBUG: Looking for credentials via: iam-role
botocore.vendored.requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): 169.254.169.254
botocore.vendored.requests.packages.urllib3.connectionpool: DEBUG: "GET /latest/meta-data/iam/security-credentials/ HTTP/1.1" 200 12
botocore.vendored.requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): 169.254.169.254
botocore.vendored.requests.packages.urllib3.connectionpool: DEBUG: "GET /latest/meta-data/iam/security-credentials/default-role HTTP/1.1" 200 134
botocore.credentials: INFO: Found credentials from IAM Role: default-role
botocore.client: DEBUG: Registering retry handlers for service: redshift
botocore.hooks: DEBUG: Event creating-client-class.redshift: calling handler <function add_generate_presigned_url at 0x0000000105cc91f0>
botocore.endpoint: DEBUG: Setting redshift timeout as (60, 60)
botocore.endpoint: DEBUG: Making request for <botocore.model.OperationModel object at 0x0000000108089670> (verify_ssl=True) with params: {'url_path': '/', 'query_string': '', 'method': u'POST', 'headers': {'User-Agent': 'Boto3/1.2.3 Pyth\
on/2.7.10 Darwin/14.5.0 Botocore/1.3.22'}, 'body': {'Action': u'DescribeClusters', 'Version': u'2012-12-01'}, 'url': u'https://redshift.us-east-1.amazonaws.com/'}
botocore.hooks: DEBUG: Event request-created.redshift.DescribeClusters: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x00000001080896a8>>
botocore.auth: DEBUG: Calculating signature using v4 auth.
botocore.auth: DEBUG: CanonicalRequest:
POST
/

host:redshift.us-east-1.amazonaws.com
user-agent:Boto3/1.2.3 Python/2.7.10 Darwin/14.5.0 Botocore/1.3.22
x-amz-date:20160507T190541Z
x-amz-security-token:test-session-token

host;user-agent;x-amz-date;x-amz-security-token
481bf18470de185c687e64aab34b0a61a0f51bd0a4f2b2aeeae9a243747a6b18
botocore.auth: DEBUG: StringToSign:
AWS4-HMAC-SHA256
20160507T190541Z
20160507/us-east-1/redshift/aws4_request
77ff3a553beb4d0f3d36c609660aaea29be33142e196d2c6d791c4dc31b8e95b
botocore.auth: DEBUG: Signature:
ed30cf4df4665820363e1227e2fbad093c09b1b01ebd0b88cf0bdcadb39a13b7
botocore.endpoint: DEBUG: Sending http request: <PreparedRequest [POST]>
botocore.vendored.requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): redshift.us-east-1.amazonaws.com
botocore.vendored.requests.packages.urllib3.connectionpool: DEBUG: "POST / HTTP/1.1" 200 149
botocore.parsers: DEBUG: Response headers: {'date': 'Sat, 07 May 2016 19:05:41 GMT', 'content-type': 'text/plain; charset=utf-8', 'content-length': '149', 'server': 'Python/HTTPretty', 'status': '200', 'connection': 'close'}
botocore.parsers: DEBUG: Response body:
{"DescribeClustersResponse": {"DescribeClustersResult": {"Clusters": []}, "ResponseMetadata": {"RequestId": "384ac68d-3775-11df-8963-01868b7c937a"}}}
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.170s

FAILED (errors=1)
```

**Comment by spulec** [comment]
It looks like boto3 uses the XML interface for Redshift, while boto used the JSON interface. We will need to implement the XML interface for Redshift in order for this to work. We have done this with [some other services](https://github.com/spulec/moto/blob/6928501973dff823540a3cfe8b4b0880722e8e9c/moto/cloudformation/responses.py#L51-L61) in the past.

**Comment by spulec** [comment]
A basic version of this was added with https://github.com/spulec/moto/commit/3cdb4afad0f6a42c790c39c56e2b6f0680d54ff7

Please feel free to reopen if it still doesn't work.
