### ISSUE TITLE
Cannot upload images to a bucket

### ISSUE THREAD

**Issue by rahuldeve** [spulec/moto#609]
I have a function which uploads a .PNG file to a bucket. Unfortunately moto tries to decode the file using utf-8 and an error pops up. Here is the error log:

> Traceback (most recent call last):
  File "/srv/zulip/zerver/lib/test_runner.py", line 97, in run_test
    test_method()
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "/srv/zulip/zerver/tests/test_upload.py", line 284, in test_upload_avatar_image_s3
    upload_avatar_image_s3(fp, user_profile, sender_email)
  File "/srv/zulip/zerver/lib/upload.py", line 179, in upload_avatar_image_s3
    image_data,
  File "/srv/zulip/zerver/lib/upload.py", line 111, in upload_image_to_s3
    key.set_contents_from_string(contents, headers=headers)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1426, in set_contents_from_string
    encrypt_key=encrypt_key)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/boto/s3/key.py", line 879, in sender
    response = http_conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1049, in getresponse
    response = self.response_class(*args, **kwds)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/boto/connection.py", line 390, in __init__
    http_client.HTTPResponse.__init__(self, *args, **kwargs)
  File "/usr/lib/python2.7/httplib.py", line 352, in __init__
    self.fp = sock.makefile('rb', 0)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/httpretty/core.py", line 332, in makefile
    self._entry.fill_filekind(self.fd)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/httpretty/core.py", line 591, in fill_filekind
    status, headers, self.body = self.callable_body(self.request, self.info.full_url(), headers)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/moto/s3/responses.py", line 79, in ambiguous_response
    return self.bucket_response(request, full_url, headers)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/moto/s3/responses.py", line 83, in bucket_response
    response = self._bucket_response(request, full_url, headers)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/moto/s3/responses.py", line 113, in _bucket_response
    body = body.decode('utf-8')
  File "/srv/zulip-venv/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by spulec** [comment]
Hmm, can you confirm which version of boto you are using? It looks like boto [is encoding](https://github.com/boto/boto/blob/dd5f87c7d5c55b69aa23bb4c21010897eb0deb42/boto/s3/key.py#L1421-L1422) everything as utf-8 so I'm not sure what the problem would be.

**Comment by rahuldeve** [comment]
Im using version 2.38.0

**Comment by spulec** [comment]
Can you paste some example code or data so I can try to reproduce?

**Comment by rahuldeve** [comment]
@spulec I looked into this and it seems to be a problem when the variable gets passed to another function, it messes with the encoding. Anyway I can confirm that this is not a moto bug so I'll close this.
