### ISSUE TITLE
Another issue with boto and proxy -> Enviroment variables

### ISSUE THREAD

**Issue by justinsr20** [spulec/moto#637]
Hi mate,

first off kudos to writing such a sweet library you have saved a lot of devs a lot of pain. Unfortunately the diablo known to all developers as the proxy is still causing headaches.

I have found that when the enviroment variables:

```
D:\dev\git_repos\platform-health>set | find "PROXY"
HTTPS_PROXY=http://localhost:3128
HTTP_PROXY=http://localhost:3128
NO_PROXY=169.254.169.254
```

are set the below error is outputted:

```
D:\dev\git_repos\platform-health>nosetests
E
======================================================================
ERROR: test_when_no_instances_attached_to_elb_and_no_elbs (test_orphan_elb_finder.test_elb_tools.TestElbTools)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\apps\python\python27\lib\site-packages\moto\core\models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "D:\dev\git_repos\platform-health\tests\unit_tests\test_orphan_elb_finder\test_elb_tools.py", line 26, in test_when_no_instances_attached_to_elb_and_no_elbs
    no_elbs_exist = elb_client.describe_load_balancers()
  File "d:\apps\python\python27\lib\site-packages\botocore\client.py", line 262, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "d:\apps\python\python27\lib\site-packages\botocore\client.py", line 541, in _make_api_call
    operation_model, request_dict)
  File "d:\apps\python\python27\lib\site-packages\botocore\endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "d:\apps\python\python27\lib\site-packages\botocore\endpoint.py", line 146, in _send_request
    success_response, exception):
  File "d:\apps\python\python27\lib\site-packages\botocore\endpoint.py", line 219, in _needs_retry
    caught_exception=caught_exception)
  File "d:\apps\python\python27\lib\site-packages\botocore\hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "d:\apps\python\python27\lib\site-packages\botocore\hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "d:\apps\python\python27\lib\site-packages\botocore\retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "d:\apps\python\python27\lib\site-packages\botocore\retryhandler.py", line 251, in __call__
    caught_exception)
  File "d:\apps\python\python27\lib\site-packages\botocore\retryhandler.py", line 266, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "d:\apps\python\python27\lib\site-packages\botocore\retryhandler.py", line 314, in __call__
    caught_exception)
  File "d:\apps\python\python27\lib\site-packages\botocore\retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "d:\apps\python\python27\lib\site-packages\botocore\retryhandler.py", line 356, in _check_caught_exception
    raise caught_exception
ValueError: need more than 1 value to unpack
-------------------- >> begin captured logging << --------------------
botocore.credentials: DEBUG: Skipping environment variable credential check because profile name was explicitly set.
botocore.credentials: DEBUG: Looking for credentials via: env
botocore.credentials: DEBUG: Looking for credentials via: assume-role
botocore.credentials: DEBUG: Looking for credentials via: shared-credentials-file
botocore.credentials: DEBUG: Looking for credentials via: config-file
botocore.credentials: DEBUG: Looking for credentials via: ec2-credentials-file
botocore.credentials: DEBUG: Looking for credentials via: boto-config
botocore.credentials: DEBUG: Looking for credentials via: iam-role
botocore.vendored.requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): 169.254.169.254
botocore.vendored.requests.packages.urllib3.connectionpool: DEBUG: "GET /latest/meta-data/iam/security-credentials/ HTTP/1.1" 200 12
botocore.vendored.requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): 169.254.169.254
botocore.vendored.requests.packages.urllib3.connectionpool: DEBUG: "GET /latest/meta-data/iam/security-credentials/default-role HTTP/1.1" 200 134
botocore.credentials: INFO: Found credentials from IAM Role: default-role
botocore.loaders: DEBUG: Loading JSON file: d:\apps\python\python27\lib\site-packages\botocore\data\endpoints.json
botocore.loaders: DEBUG: Loading JSON file: d:\apps\python\python27\lib\site-packages\botocore\data\elb\2012-06-01\service-2.json
botocore.loaders: DEBUG: Loading JSON file: d:\apps\python\python27\lib\site-packages\botocore\data\_retry.json
botocore.client: DEBUG: Registering retry handlers for service: elb
botocore.hooks: DEBUG: Event creating-client-class.elb: calling handler <function add_generate_presigned_url at 0x0000000003B48F98>
botocore.client: DEBUG: The s3 config key is not a dictionary type, ignoring its value of: None
botocore.endpoint: DEBUG: Setting elasticloadbalancing timeout as (60, 60)
botocore.endpoint: DEBUG: Making request for OperationModel(name=DescribeLoadBalancers) (verify_ssl=True) with params: {'body': {'Action': u'DescribeLoadBalancers', 'Version': u'2012-06-01'}, 'url': u'https://elasticloadbalancing.ap-southeast-2.amazonaws.com/', 'headers': {'User-Agent': 'Boto3/1.3.1 Python/2.7.11 Windows/7 Botocore/1.4.27'}, 'query_string':
'', 'url_path': '/', 'method': u'POST'}
botocore.hooks: DEBUG: Event request-created.elasticloadbalancing.DescribeLoadBalancers: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x0000000004EB45C0>>
botocore.auth: DEBUG: Calculating signature using v4 auth.
botocore.auth: DEBUG: CanonicalRequest:
POST
/

host:elasticloadbalancing.ap-southeast-2.amazonaws.com
x-amz-date:20160617T042726Z
x-amz-security-token:test-session-token

host;x-amz-date;x-amz-security-token
236069f72bf74f0c7ddff0a34b0defa8a21d1d6a897e588764e1b2ff6319f94a
botocore.auth: DEBUG: StringToSign:
AWS4-HMAC-SHA256
20160617T042726Z
20160617/ap-southeast-2/elasticloadbalancing/aws4_request
ab6db0f6de31f42ec75d62be14c0bf219ef6f4269e880ff85784183b81b9d459
botocore.auth: DEBUG: Signature:
5fa48e8a622518f3f90884ebc5a4084d1105b7999b843e8d2c95ccb3b909ece9
botocore.endpoint: DEBUG: Sending http request: <PreparedRequest [POST]>
botocore.vendored.requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): elasticloadbalancing.ap-southeast-2.amazonaws.com
botocore.endpoint: DEBUG: Exception received when sending HTTP request.
Traceback (most recent call last):
  File "d:\apps\python\python27\lib\site-packages\botocore\endpoint.py", line 174, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "d:\apps\python\python27\lib\site-packages\botocore\vendored\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "d:\apps\python\python27\lib\site-packages\botocore\vendored\requests\adapters.py", line 370, in send
    timeout=timeout
  File "d:\apps\python\python27\lib\site-packages\botocore\vendored\requests\packages\urllib3\connectionpool.py", line 539, in urlopen
    self._prepare_proxy(conn)
  File "d:\apps\python\python27\lib\site-packages\botocore\vendored\requests\packages\urllib3\connectionpool.py", line 727, in _prepare_proxy
    conn.connect()
  File "d:\apps\python\python27\lib\site-packages\botocore\vendored\requests\packages\urllib3\connection.py", line 217,
in connect
    self._tunnel()
  File "d:\apps\python\python27\lib\httplib.py", line 805, in _tunnel
    self._tunnel_port))
  File "d:\apps\python\python27\lib\httplib.py", line 873, in send
    self.sock.sendall(data)
  File "d:\apps\python\python27\lib\site-packages\httpretty\core.py", line 405, in sendall
    headers, body = list(map(utf8, data.split(b'\r\n\r\n', 1)))
ValueError: need more than 1 value to unpack
botocore.hooks: DEBUG: Event needs-retry.elasticloadbalancing.DescribeLoadBalancers: calling handler <botocore.retryhandler.RetryHandler object at 0x0000000004E496D8>
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.660s

FAILED (errors=1)
```

Below is my test class:

```
# # -*- coding: utf-8 -*-

from .context import elb_tools
import boto3

import unittest
from moto.elb import mock_elb
import os

#from nose.tools import set_trace;


class TestElbTools(unittest.TestCase):
    """Basic test cases."""

    def setUp(self):
        self.region = 'ap-southeast-2'

    #describe method: check_elb_has_attached_instances

    @mock_elb
    def test_when_no_instances_attached_to_elb_and_no_elbs(self):
        elb_client = boto3.client('elb', region_name=self.region)
        no_elbs_exist = elb_client.describe_load_balancers()
        orphan_elbs = elb_tools.check_elb_has_attached_instances \
                                (no_elbs_exist)

        self.assertIsNone(orphan_elbs)
```

Cannot for the life of my figure out whats going on. When I completely remove the HTTP_PROXY & HTTPS_PROXY env variables it behaves as normal:

```
D:\dev\git_repos\platform-health>set NO_PROXY=

D:\dev\git_repos\platform-health>set | find "PROXY"

D:\dev\git_repos\platform-health>nosetests
.
----------------------------------------------------------------------
Ran 1 test in 1.576s

OK
```

**Comment by spulec** [comment]
It looks like the request gets split different with proxies:

```
(Pdb) p list(map(utf8, data.split(b'\r\n\r\n', 1)))
['CONNECT elasticloadbalancing.ap-southeast-2.amazonaws.com:443 HTTP/1.0\r\n']
```

Seems like HTTPretty needs to have different behavior for CONNECTs.

**Comment by xsmaster** [comment]
There is an open bug with HTTPretty and the proxy. [Setting http_proxy breaks HTTPretty #122](https://github.com/gabrielfalcao/HTTPretty/issues/122)

**Comment by spulec** [comment]
Can you test if this work on the `master` branch now?

**Comment by MaCaki** [comment]
I was running into the same issue as @justinsr20 recently while trying to run the following test within a dev VM for a service that uses a https proxy.   After updating both `moto` and `boto3` from the latest versions available on pypi as well as trying to manually `unset` all https proxy env variables I was still getting the error
```
ValueError: need more than 1 value to unpack
botocore.hooks: DEBUG: Event needs-retry.s3.CreateBucket: calling handler <botocore.retryhandler.RetryHandler object at 0x7f3c29cbadd0>

```

However after pulling `boto3` master I was able to run these tests successfully.   


[truncated test func]
```python
    @mock_s3
    def test_move_model_to_archive(self):
        """Should move the model to the archive key space."""

        test_bucket = 'test.model.bucket'
        test_source_key = 'test_model/latest/cat_braynz_923.json'
        test_target_key = 'test_model/latest/cat_braynz_923.json'
        test_contents = 'if haz -> no brain == buy NAO'
        client = boto3.client('s3')

        client.create_bucket(Bucket=test_bucket)

        bucket = client.head_bucket(Bucket=test_bucket)
       
        # upload test key.
        client.upload_fileobj(
            cStringIO.StringIO(test_contents),
            test_bucket,
            test_source_key
        )

```

**Comment by spulec** [comment]
Great, thanks for testing. I'm going to close this out.

Someone please yell if it still seems to be happening on master.
