### ISSUE TITLE
S3 multipart upload not working

### ISSUE THREAD

**Issue by ghego** [spulec/moto#677]
I'm using moto to write tests.

the following code works and the call is correctly mocked:

``` python
s3 = boto3.client('s3')
s3.upload_file(Bucket='bucket', Key='out_name', Filename=SMALL_FILE)
```

while if I try with a large file, it fails because of timeout error:

``` python
s3 = boto3.client('s3')
s3.upload_file(Bucket='bucket', Key='out_name', Filename=LARGE_FILE)
```

``` python
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/my_test.py", line 51, in test_my_function
    my_module.my_function(event, None)
  File "my_module.py", line 49, in my_function
    s3.upload_file(Bucket='bucket', Key='out_name', Filename=LARGE_FILE)
  File "anaconda/lib/python2.7/site-packages/boto3/s3/inject.py", line 84, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File "anaconda/lib/python2.7/site-packages/boto3/s3/transfer.py", line 639, in upload_file
    self._multipart_upload(filename, bucket, key, callback, extra_args)
  File "anaconda/lib/python2.7/site-packages/boto3/s3/transfer.py", line 733, in _multipart_upload
    uploader.upload_file(filename, bucket, key, callback, extra_args)
  File "anaconda/lib/python2.7/site-packages/boto3/s3/transfer.py", line 390, in upload_file
    MultipartUpload={'Parts': parts})
  File "anaconda/lib/python2.7/site-packages/botocore/client.py", line 278, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "anaconda/lib/python2.7/site-packages/botocore/client.py", line 572, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred () when calling the CompleteMultipartUpload operation: 
-------------------- >> begin captured logging << --------------------
botocore.credentials: DEBUG: Skipping environment variable credential check because profile name was explicitly set.
botocore.credentials: DEBUG: Looking for credentials via: env
botocore.credentials: DEBUG: Looking for credentials via: assume-role
botocore.credentials: DEBUG: Looking for credentials via: shared-credentials-file
botocore.credentials: DEBUG: Looking for credentials via: config-file
botocore.credentials: DEBUG: Looking for credentials via: ec2-credentials-file
botocore.credentials: DEBUG: Looking for credentials via: boto-config
botocore.credentials: DEBUG: Looking for credentials via: container-role
botocore.credentials: DEBUG: Looking for credentials via: iam-role
botocore.vendored.requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): 169.254.169.254
botocore.utils: DEBUG: Caught exception while trying to retrieve credentials: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/iam/security-credentials/ (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x110f29150>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))
Traceback (most recent call last):
  File "anaconda/lib/python2.7/site-packages/botocore/utils.py", line 159, in _get_request
    response = requests.get(url, timeout=timeout)
  File "anaconda/lib/python2.7/site-packages/botocore/vendored/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "anaconda/lib/python2.7/site-packages/botocore/vendored/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "anaconda/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "anaconda/lib/python2.7/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "anaconda/lib/python2.7/site-packages/botocore/vendored/requests/adapters.py", line 419, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/meta-data/iam/security-credentials/ (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPConnection object at 0x110f29150>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))
botocore.utils: DEBUG: Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
botocore.loaders: DEBUG: Loading JSON file: anaconda/lib/python2.7/site-packages/botocore/data/endpoints.json
botocore.loaders: DEBUG: Loading JSON file: anaconda/lib/python2.7/site-packages/botocore/data/s3/2006-03-01/service-2.json
botocore.loaders: DEBUG: Loading JSON file: anaconda/lib/python2.7/site-packages/botocore/data/_retry.json
botocore.client: DEBUG: Registering retry handlers for service: s3
botocore.hooks: DEBUG: Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x110e63050>
botocore.hooks: DEBUG: Event creating-client-class.s3: calling handler <function _handler at 0x110c0c578>
botocore.hooks: DEBUG: Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x110e63e60>
botocore.client: DEBUG: The s3 config key is not a dictionary type, ignoring its value of: None
botocore.endpoint: DEBUG: Setting s3 timeout as (60, 60)
An error occurred () when calling the CompleteMultipartUpload operation: 
--------------------- >> end captured logging << ---------------------
```

any idea why?

**Comment by spulec** [comment]
By default, boto3 is going to try to use multiple threads to upload large files.

The following should work:

```python
from boto3.s3.transfer import TransferConfig

s3.upload_file(Bucket='bucket', Key='out_name', Filename=LARGE_FILE, Config=TransferConfig(use_threads=False))
```

Please reopen if it doesn't.
