### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'lstrip_blocks'

### ISSUE THREAD

**Issue by anentropic** [spulec/moto#728]
I have decorated my tests with `@mock_s3`

I get the following error when running:

```
Traceback (most recent call last):
  File "/Users/me/.pyenv/versions/2.7.11/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/myproject/VENV/lib/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "/myproject/proj/../proj/tests/integration/engine/management/commands/test_archive_deleted_chat_messages.py", line 95, in test_archive_exception_log_and_continue
    self.cmd.handle(write=True, noinput=True)
  File "/myproject/proj/engine/management/commands/__init__.py", line 335, in handle
    super(LiveUpdateCommand, self).handle(*args, **kwargs)
  File "/myproject/proj/engine/management/commands/__init__.py", line 165, in handle
    self._prepare_args(*args, **kwargs)
  File "/myproject/proj/engine/management/commands/archive_deleted_chat_messages.py", line 219, in _prepare_args
    self.bucket = conn.create_bucket(self.bucket_name)
  File "/myproject/VENV/lib/python2.7/site-packages/boto/s3/connection.py", line 616, in create_bucket
    data=data)
  File "/myproject/VENV/lib/python2.7/site-packages/boto/s3/connection.py", line 668, in make_request
    retry_handler=retry_handler
  File "/myproject/VENV/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/myproject/VENV/lib/python2.7/site-packages/boto/connection.py", line 944, in _mexe
    response = connection.getresponse()
  File "/Users/me/.pyenv/versions/2.7.11/lib/python2.7/httplib.py", line 1133, in getresponse
    response = self.response_class(*args, **kwds)
  File "/myproject/VENV/lib/python2.7/site-packages/boto/connection.py", line 390, in __init__
    http_client.HTTPResponse.__init__(self, *args, **kwargs)
  File "/Users/me/.pyenv/versions/2.7.11/lib/python2.7/httplib.py", line 390, in __init__
    self.fp = sock.makefile('rb', 0)
  File "/myproject/VENV/lib/python2.7/site-packages/httpretty/core.py", line 332, in makefile
    self._entry.fill_filekind(self.fd)
  File "/myproject/VENV/lib/python2.7/site-packages/httpretty/core.py", line 591, in fill_filekind
    status, headers, self.body = self.callable_body(self.request, self.info.full_url(), headers)
  File "/myproject/VENV/lib/python2.7/site-packages/moto/s3/responses.py", line 83, in bucket_response
    response = self._bucket_response(request, full_url, headers)
  File "/myproject/VENV/lib/python2.7/site-packages/moto/s3/responses.py", line 120, in _bucket_response
    return self._bucket_response_put(request, body, region_name, bucket_name, querystring, headers)
  File "/myproject/VENV/lib/python2.7/site-packages/moto/s3/responses.py", line 248, in _bucket_response_put
    template = self.response_template(S3_BUCKET_CREATE_RESPONSE)
  File "/myproject/VENV/lib/python2.7/site-packages/moto/core/responses.py", line 85, in response_template
    lstrip_blocks=True)
TypeError: __init__() got an unexpected keyword argument 'lstrip_blocks'
```

fresh install from pip `moto==0.4.27`

**Comment by anentropic** [comment]
Ah, it seems it's not compatible with `Jinja2==2.6`

upgrading to `Jinja2==2.8` has fixed it for me

currently no version is specified for Jinja2 in your `setup.py`

**Comment by spulec** [comment]
Thanks for opening, I've changed the code to require a higher version.
