### ISSUE TITLE
docker API is broken inside a test with @mock_something annotation

### ISSUE THREAD

**Issue by dtenenba** [spulec/moto#749]
Here's a test function (requires that you `pip install docker-py` and have Docker installed):

```python
def test_example():
    import docker
    cli = docker.Client(base_url="unix://var/run/docker.sock")
    im = cli.images()
```
It works just fine. However if I add a `@mock` annotation such as `@mock_s3` or `@mock_ec2` above the `def`, I get a long stack trace (see below).

I can work around this, by testing the docker-related functionality in a separate test.
But thought you might want to know.

**EDIT**: Actually, it won't be that easy to work around this. The function under test uses S3 and EC2 and also the docker API, so it would be good to solve this. 

**EDIT2**: This seems similar to #330 but the solution there (to upgrade httpretty) did not fix it for me. 

I suppose this might be expected behavior, since I know `moto` is intercepting calls to the `socket` package.

```
======================================================================
ERROR: test_example (__main__.MyAppTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "test.py", line 116, in test_example
    im = cli.images()
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/docker/api/image.py", line 40, in images
    res = self._result(self._get(self._url("/images/json"), params=params),
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/docker/client.py", line 132, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 362, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1093, in _send_request
    self.endheaders(body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 869, in send
    self.sock.sendall(data)
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/httpretty/core.py", line 409, in sendall
    info = URIInfo(hostname=self._host, port=self._port,
  File "/Users/dtenenba/envs/gemstrigger/lib/python2.7/site-packages/httpretty/core.py", line 464, in __getattr__
    return getattr(self.truesock, name)
AttributeError: '_socketobject' object has no attribute '_host'

----------------------------------------------------------------------
Ran 8 tests in 0.677s

FAILED (errors=1)
```

**Comment by dtenenba** [comment]
I was able to reproduce this with HTTPretty alone (without moto) so I filed an [issue](https://github.com/gabrielfalcao/HTTPretty/issues/311) there. I guess this can be closed but I'll leave it open in case anyone wants to say or do anything further.

**Comment by dtenenba** [comment]
I have a [workaround](https://github.com/gabrielfalcao/HTTPretty/issues/311#issuecomment-257660604) for this now so I am closing this (plus it doesn't really belong here).
