### ISSUE TITLE
using moto and HTTPretty in the same test function

### ISSUE THREAD

**Issue by dtenenba** [spulec/moto#750]
I want to test a function that calls S3 (using boto3) and also calls a different REST API that I developed.

I was hoping that I could do this, using moto to mock S3 and HTTPretty to mock the other service. The fact that moto is built on HTTPretty was encouraging.

But I tried a short example and it failed:

```python
import requests
from sure import expect
import httpretty
import moto
import boto3

def function_to_test():
    client = boto3.client("s3")
    client.create_bucket(Bucket="foobart")
    return(requests.get('http://api.yipit.com/v1/deals/'))

@moto.mock_s3
@httpretty.activate
def test_it():
    httpretty.register_uri(httpretty.GET, "http://api.yipit.com/v1/deals/",
                           body='[{"title": "Test Deal"}]',
                           content_type="application/json")
    response = function_to_test()
    expect(response.json()).to.equal([{"title": "Test Deal"}])

test_it()
```

Here's the result of running this:

```
Traceback (most recent call last):
  File "t.py", line 21, in <module>
    test_it()
  File "/Users/dtenenba/dev/github/gems-lambda-trigger/env/lib/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "/Users/dtenenba/dev/github/gems-lambda-trigger/env/lib/python2.7/site-packages/httpretty/core.py", line 1146, in wrapper
    return test(*args, **kw)
  File "t.py", line 18, in test_it
    response = function_to_test()
  File "t.py", line 9, in function_to_test
    client.create_bucket(Bucket="foobart")
  File "/Users/dtenenba/dev/github/gems-lambda-trigger/env/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/dtenenba/dev/github/gems-lambda-trigger/env/lib/python2.7/site-packages/botocore/client.py", line 483, in _make_api_call
    operation_model, request_dict)
  File "/Users/dtenenba/dev/github/gems-lambda-trigger/env/lib/python2.7/site-packages/botocore/endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/dtenenba/dev/github/gems-lambda-trigger/env/lib/python2.7/site-packages/botocore/endpoint.py", line 146, in _send_request
    success_response, exception):
  File "/Users/dtenenba/dev/github/gems-lambda-trigger/env/lib/python2.7/site-packages/botocore/endpoint.py", line 219, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/dtenenba/dev/github/gems-lambda-trigger/env/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/dtenenba/dev/github/gems-lambda-trigger/env/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/dtenenba/dev/github/gems-lambda-trigger/env/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/dtenenba/dev/github/gems-lambda-trigger/env/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/dtenenba/dev/github/gems-lambda-trigger/env/lib/python2.7/site-packages/botocore/retryhandler.py", line 274, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/dtenenba/dev/github/gems-lambda-trigger/env/lib/python2.7/site-packages/botocore/retryhandler.py", line 314, in __call__
    caught_exception)
  File "/Users/dtenenba/dev/github/gems-lambda-trigger/env/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/dtenenba/dev/github/gems-lambda-trigger/env/lib/python2.7/site-packages/botocore/retryhandler.py", line 356, in _check_caught_exception
    raise caught_exception
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://foobart.s3.amazonaws.com/".
```

I realize that if I move the AWS/S3 calls to another function that I can write separate test functions, one with the `@httpretty.activate` decorator and the other with the `@moto.s3` decorator.
But I am not sure that there is a valid path through the code that does not call both AWS and the other service. 

I guess I have to make my 'units' smaller (since this is unit testing), but I was wondering if there is another way to make moto and HTTPretty coexist?

**Comment by spulec** [comment]
Given how HTTPretty is setup, I don't know that there is a way to do this. You could create a PR to HTTPretty so that successive activate()s are additive instead of replacive, but I don't know if they will merge.

**Comment by spulec** [comment]
Let me know if you come up with any other ideas.

**Comment by alanoe** [comment]
Does the decorators order make any difference (i.e. if moto.mock_s3 decorator is put *after* httpretty.activate one) ? I found a test in my code base which does that and it works for mocking non (S3) AWS URLs. However, when I start to access AWS URLs, it strangely works twice and in the third time the response status code is 400. Debugging a little, I noticed that the first two times the callback returned is and in the third is "not_implemented_callback". This worked on moto 0.3.1 and I got the error when I updated to 1.3.14, surely related to https://github.com/spulec/moto/pull/2294/commits/c7147b06b119f68483a532daa6fe8a248bc3feb0 . Anyway, I have no idea why it works twice before failing.

I need to mock S3 AWS access and HTTP access in the same function. Could you recommend a solution, given that httppretty won't work? Another requests mock library such as responses would work?
