### ISSUE TITLE
SQS change_message_visibility

### ISSUE THREAD

**Issue by hevy-CC4477** [spulec/moto#753]
Hi,

I wrote a test where I change multiple times the message visibility. It works fine with aws, here is my error with moto (the error happen on the second call of change_message_visibility):

```
Traceback (most recent call last):
  File "/home/centos/project/tests/functional_tests/test_sqs_queue.py", line 244, in test_change_message_visibility
    q.change_message_visibility(handle, timedelta(minutes=1))
  File "/home/centos/project/decorators.py", line 29, in call
    return func(*args, **kwargs)
  File "/home/centos/project/sqs_queue.py", line 192, in change_message_visibility
    VisibilityTimeout=timeout.seconds)
  File "/home/centos/env/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/centos/env/lib/python2.7/site-packages/botocore/client.py", line 483, in _make_api_call
    operation_model, request_dict)
  File "/home/centos/env/lib/python2.7/site-packages/botocore/endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/centos/env/lib/python2.7/site-packages/botocore/endpoint.py", line 144, in _send_request
    request, operation_model, attempts)
  File "/home/centos/env/lib/python2.7/site-packages/botocore/endpoint.py", line 209, in _get_response
    response_dict, operation_model.output_shape)
  File "/home/centos/env/lib/python2.7/site-packages/botocore/parsers.py", line 209, in parse
    parsed = self._do_error_parse(response, shape)
  File "/home/centos/env/lib/python2.7/site-packages/botocore/parsers.py", line 435, in _do_error_parse
    root = self._parse_xml_string_to_dom(xml_contents)
  File "/home/centos/env/lib/python2.7/site-packages/botocore/parsers.py", line 387, in _parse_xml_string_to_dom
    "invalid XML received:\n%s" % (e, xml_string))
ResponseParserError: Unable to parse response (syntax error: line 1, column 0), invalid XML received:
Invalid request: The receipt handle provided is not valid.
```

Any idea why ?

**Comment by hevy-CC4477** [comment]
I found the issue, the ReceiptHandle changed. Here is my test:

does not work:
```
@mock_sqs
def test_boto3_change_visibility():
    queue_name = "blah"
    res_sqs = boto3.resource('sqs', region_name='us-east-1')
    client_sqs = boto3.client('sqs', region_name='us-east-1')
    queue = res_sqs.create_queue(QueueName=queue_name)
    queue.send_message(MessageBody="derp")

    response = client_sqs.receive_message(QueueUrl=queue.url)
    messages = response.get("Messages", None)
    message = messages[0]
    handle = message["ReceiptHandle"]

    client_sqs.change_message_visibility(QueueUrl=queue.url, ReceiptHandle=handle, VisibilityTimeout=0)
    time.sleep(60)
    client_sqs.change_message_visibility(QueueUrl=queue.url, ReceiptHandle=handle, VisibilityTimeout=60)
```

work fine:
```
@mock_sqs
def test_boto3_change_visibility():
    queue_name = "blah"
    res_sqs = boto3.resource('sqs', region_name='us-east-1')
    client_sqs = boto3.client('sqs', region_name='us-east-1')
    queue = res_sqs.create_queue(QueueName=queue_name)
    queue.send_message(MessageBody="derp")

    response = client_sqs.receive_message(QueueUrl=queue.url)
    messages = response.get("Messages", None)
    message = messages[0]
    handle = message["ReceiptHandle"]

    client_sqs.change_message_visibility(QueueUrl=queue.url, ReceiptHandle=handle, VisibilityTimeout=0)
    time.sleep(60)
    response = client_sqs.receive_message(QueueUrl=queue.url)
    messages = response.get("Messages", None)
    message = messages[0]
    client_sqs.change_message_visibility(QueueUrl=queue.url, ReceiptHandle=handle, VisibilityTimeout=60)
```

Is it normal that the ReceiptHandle changed ?

**Comment by spulec** [comment]
My understanding is that this is the correct behavior.

http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-queue-message-identifiers.html

```If you receive a message more than once, each time you receive it, you get a different receipt handle. ```

Feel free to reopen if I am misunderstanding
