### ISSUE TITLE
SSL Error running tests python3.5

### ISSUE THREAD

**Issue by smarlowucf** [spulec/moto#771]
When running the test suite against python3.5 two SSL errors are generated.

ERROR: test_decorator_calls.test_context_manager
ERROR: test_decorator_calls.test_decorator_start_and_stop
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/smarlow/projects/venvs/moto/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/smarlow/projects/moto/tests/test_core/test_decorator_calls.py", line 45, in test_decorator_start_and_stop
    conn.get_all_instances()
  File "/home/smarlow/projects/venvs/moto/lib/python3.5/site-packages/boto/ec2/connection.py", line 585, in get_all_instances
    max_results=max_results)
  File "/home/smarlow/projects/venvs/moto/lib/python3.5/site-packages/boto/ec2/connection.py", line 681, in get_all_reservations
    [('item', Reservation)], verb='POST')
  File "/home/smarlow/projects/venvs/moto/lib/python3.5/site-packages/boto/connection.py", line 1170, in get_list
    response = self.make_request(action, params, path, verb)
  File "/home/smarlow/projects/venvs/moto/lib/python3.5/site-packages/boto/connection.py", line 1116, in make_request
    return self._mexe(http_request)
  File "/home/smarlow/projects/venvs/moto/lib/python3.5/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
  File "/home/smarlow/projects/venvs/moto/lib/python3.5/site-packages/boto/connection.py", line 943, in _mexe
    request.body, request.headers)
  File "/usr/lib64/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/home/smarlow/projects/venvs/moto/lib/python3.5/site-packages/boto/https_connection.py", line 131, in connect
    ca_certs=self.ca_certs)
  File "/usr/lib64/python3.5/ssl.py", line 1064, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib64/python3.5/ssl.py", line 747, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.5/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.5/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

----------------------------------------------------------------------
Ran 1198 tests in 170.603s

FAILED (SKIP=49, errors=2)

**Comment by spulec** [comment]
Thanks, we don't officially support python 3.5 right now, but happy to add support if someone has time to submit some PRs.

**Comment by smarlowucf** [comment]
I think the best bet for Python 3 support is migrating to Responses as you mentioned https://github.com/spulec/moto/issues/514. If I find some time I will investigate this.

**Comment by spulec** [comment]
Agreed.

My guess is that we will need to drop support for boto entirely and only allow boto3 though. I'm not completely against this and definitely see it as the way of the future, but not sure how long we still want boto support.

**Comment by smarlowucf** [comment]
I needed some iam mocking in Python3 so I went that route of just boto3 support. To limit dependencies I mocked the function rather than the request. Do you know of any consequences to doing so? I would consider taking time to migrate over all of the moto endpoints/responses etc if you were interested in doing so and agreed with the architecture changes. (I'm guessing this would break the stand-alone server...)

The project is https://github.com/smarlowucf/mockboto3 but could be moved/renamed. And it's still a work in progress.

**Comment by spulec** [comment]
I think the main consequences are lack of a standalone server and relying on boto3 to behave in a particular way (certain function call to mock). As moto moves to only support boto3, I think we will be able to move it in a similar direction.

**Comment by smarlowucf** [comment]
This can be closed for now. The build is passing on Jenkins for 3.6. The build passes locally against 2.7 but still fails on 3.6. I think it's a problem with my environment.

**Comment by Lacrymology** [comment]
I'm having this issue on 3.6.8
