### ISSUE TITLE
S3 upload failure in boto3

### ISSUE THREAD

**Issue by dtenenba** [spulec/moto#786]
This is related to #703 in that it gives the same error, but it might be different because this error still happens for me even though #703 has apparently been fixed. 

Note that I am using the latest moto (0.4.30, master branch, pulled today).

The following code downloads a 28MB file from S3 and then tries to upload it to a mock bucket, and fails with:

```
Traceback (most recent call last):
  File "t2.py", line 50, in <module>
    doit()
  File "t2.py", line 41, in doit
    Key="thefile")
  File "/envs/wenv/local/lib/python2.7/site-packages/boto3/s3/inject.py", line 105, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File "/envs/wenv/local/lib/python2.7/site-packages/boto3/s3/transfer.py", line 253, in upload_file
    filename, '/'.join([bucket, key]), e))
boto3.exceptions.S3UploadFailedError: Failed to upload PT-861-6RXN_S177_L001_R2_001.fastq.gz to mytemptestbucket201611291413/thefile: An error occurred (InvalidPart) when calling the CompleteMultipartUpload operation: One or more of the specified parts could not be found. The part might not have been uploaded, or the specified entity tag might not have matched the part's entity tag.
```

```python
import moto
import boto3
import os
import requests
import shutil

import hashlib

def md5(fname):
    hash_md5 = hashlib.md5()
    with open(fname, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            hash_md5.update(chunk)
    return hash_md5.hexdigest()

url = "https://s3-us-west-2.amazonaws.com/moto-problem-demo/PT-861-6RXN_S177_L001_R2_001.fastq.gz"
inputfile = "PT-861-6RXN_S177_L001_R2_001.fastq.gz"


def download_file(url):
    local_filename = url.split('/')[-1]
    r = requests.get(url, stream=True)
    with open(local_filename, 'wb') as f:
        shutil.copyfileobj(r.raw, f)

    return local_filename

def doit():
    outputfile = "/tmp/outfile"

    if os.path.exists(outputfile):
        os.remove(outputfile)

    bucketname = 'mytemptestbucket201611291413'

    client = boto3.client("s3")
    client.create_bucket(Bucket=bucketname)
    client.upload_file(
        Filename=inputfile,
        Bucket=bucketname,
        Key="thefile")

if not os.path.exists(inputfile):
    print("Test file does not exist locally, downloading....")
    download_file(url)
    assert md5(inputfile) == "1c2004717053f755acd7c9d350ef6fca"

print("With moto")
with moto.mock_s3():
    doit()

```

**Comment by spulec** [comment]
Thanks for opening.

Does the same issue occur if you manually create the multipart upload instead of using `upload_file`?

**Comment by dtenenba** [comment]
I changed the script to the below which should make it a multipart upload, but I'm not sure if this is what you were asking for, I haven't done multipart uploads before. This fails with the same error.
Suggestions welcome as to how to manually create the multipart upload.

```python
import moto
import boto3
import os
import requests
import shutil

import hashlib

def md5(fname):
    hash_md5 = hashlib.md5()
    with open(fname, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            hash_md5.update(chunk)
    return hash_md5.hexdigest()

url = "https://s3-us-west-2.amazonaws.com/moto-problem-demo/PT-861-6RXN_S177_L001_R2_001.fastq.gz"
inputfile = "PT-861-6RXN_S177_L001_R2_001.fastq.gz"


def download_file(url):
    local_filename = url.split('/')[-1]
    r = requests.get(url, stream=True)
    with open(local_filename, 'wb') as f:
        shutil.copyfileobj(r.raw, f)

    return local_filename

def doit():
    outputfile = "/tmp/outfile"

    if os.path.exists(outputfile):
        os.remove(outputfile)

    bucketname = 'mytemptestbucket201611291413'

    client = boto3.client("s3")
    s3 = boto3.resource('s3')
    client.create_bucket(Bucket=bucketname)
    config = boto3.s3.transfer.TransferConfig(
        multipart_threshold=4*1024, # number of bytes
        max_concurrency=10,
        num_download_attempts=10,
    )
    transfer = boto3.s3.transfer.S3Transfer(client, config)
    transfer.upload_file(inputfile, bucketname, 'thefile')

if not os.path.exists(inputfile):
    print("Test file does not exist locally, downloading....")
    download_file(url)
    assert md5(inputfile) == "1c2004717053f755acd7c9d350ef6fca"

print("With moto")
with moto.mock_s3():
    doit()

```

**Comment by spulec** [comment]
Hmmmm, I changed the file I'm using, but the script is hanging for me right now instead of erroring. Not sure why yet.

**Comment by spulec** [comment]
The following script works for me on boto3==1.4.4

```python
import boto3
from moto import *

LARGE_FILE = "[REMOVED]"
from boto3.s3.transfer import TransferConfig

@mock_s3
def test_hanging_moto():
    s3 = boto3.client('s3')
    s3.create_bucket(Bucket="bucket")
    s3.upload_file(Bucket='bucket', Key='out_name', Filename=LARGE_FILE, Config=TransferConfig(use_threads=False))
```

It looks like we need to disable threads since HTTPretty is not thread-safe. Going to close this out for now. At some point we are looking to replace HTTPretty with something else that will hopefully be threadsafe.

Let me know if that doesn't solve the issue.
