### ISSUE TITLE
Moto not able to list ELB's.

### ISSUE THREAD

**Issue by AkhterAli** [spulec/moto#825]
It looks like describe_load_balancers() using boto3 isn't quite working when using moto.

```python
╰─λ python2                                                                                                                                                                                     0 < 15:13:56
Python 2.7.13 (default, Dec 18 2016, 07:03:39)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3, moto
>>>
>>> @moto.mock_route53
... def test_test():
...     session = boto3.Session()
...     elb_client = session.client('elb', region_name='us-east-1')
...     load_balancers = elb_client.describe_load_balancers()
...
>>> test_test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "<stdin>", line 5, in test_test
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 526, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 170, in _send_request
    success_response, exception):
  File "/usr/local/lib/python2.7/site-packages/botocore/endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://elasticloadbalancing.us-east-1.amazonaws.com/".
```

**Comment by spulec** [comment]
Hmmm, I'm having trouble reproducing this. Can you list the version of boto3, botocore, httpretty you have installed?

**Comment by AkhterAli** [comment]
@spulec 
```shell
╭─mo.ali at pm-10423 in /Users/mo.ali
╰─λ pip list                                                                                                                                                                                    0 < 12:45:37
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
appnope (0.1.0)
awscli (1.11.36)
backports.shutil-get-terminal-size (1.0.0)
blessings (1.6)
boto (2.45.0)
boto3 (1.4.3)
botocore (1.4.93)
bpython (0.16)
colorama (0.3.7)
curtsies (0.2.11)
decorator (4.0.11)
deepdiff (2.5.3)
dnspython (1.15.0)
docutils (0.13.1)
enum34 (1.1.6)
funcsigs (1.0.2)
futures (3.0.5)
greenlet (0.4.11)
httpretty (0.8.10)
idna (2.2)
ipdb (0.10.2)
ipython (5.2.2)
ipython-genutils (0.1.0)
Jinja2 (2.9.5)
jmespath (0.9.0)
MarkupSafe (0.23)
mock (2.0.0)
moto (0.4.31)
nose (1.3.7)
pathlib2 (2.2.1)
pbr (1.10.0)
pdb (0.1)
pexpect (4.2.1)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.13)
ptyprocess (0.5.1)
py (1.4.32)
pyaml (16.12.2)
pyasn1 (0.1.9)
Pygments (2.1.3)
pytest (3.0.5)
python-dateutil (2.6.0)
python-gnupg (0.3.9)
pytz (2016.10)
PyYAML (3.12)
requests (2.13.0)
rsa (3.4.2)
s3transfer (0.1.10)
scandir (1.4)
setuptools (32.1.0)
simdns (0.1.0, /Users/mo.ali/Documents/phishme/code/sim_dns_verify_fix)
simplegeneric (0.8.1)
six (1.10.0)
stevedore (1.19.1)
sure (1.4.0)
traitlets (4.3.1)
troposphere (1.9.1)
virtualenv (15.1.0)
virtualenv-clone (0.2.6)
virtualenvwrapper (4.7.2)
wcwidth (0.1.7)
Werkzeug (0.11.15)
wheel (0.29.0)
xmltodict (0.10.2)
╭─mo.ali at pm-10423 in /Users/mo.ali
╰─λ pip3 list                                                                                                                                                                                   0 < 12:45:43
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
appnope (0.1.0)
awscli (1.11.36)
Babel (2.3.4)
blessings (1.6)
boto (2.45.0)
boto3 (1.4.4)
botocore (1.5.4)
bpython (0.16)
colorama (0.3.7)
curtsies (0.2.11)
decorator (4.0.11)
deepdiff (2.5.3)
Delorean (0.6.0)
dnspython (1.15.0)
docopt (0.6.2)
docutils (0.13.1)
greenlet (0.4.11)
httpretty (0.8.10)
humanize (0.5.1)
idna (2.2)
ipdb (0.10.2)
ipython (5.2.2)
ipython-genutils (0.1.0)
jedi (0.9.0)
Jinja2 (2.9.4)
jmespath (0.9.0)
MarkupSafe (0.23)
mock (2.0.0)
moto (0.4.30)
nose (1.3.7)
pbr (1.10.0)
pdb (0.1)
pexpect (4.2.1)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.9)
ptpython (0.36)
ptyprocess (0.5.1)
py (1.4.32)
pyaml (16.12.2)
pyasn1 (0.1.9)
Pygments (2.1.3)
pynamodb (2.0.3)
pytest (3.0.5)
python-dateutil (2.6.0)
python-gnupg (0.3.9)
pytz (2016.10)
PyYAML (3.12)
requests (2.12.5)
rsa (3.4.2)
s3transfer (0.1.10)
setuptools (32.2.0)
simdns (0.1.0, /Users/mo.ali/Documents/phishme/code/sim_dns_verify_fix)
simplegeneric (0.8.1)
six (1.10.0)
stevedore (1.19.1)
sure (1.4.0)
traitlets (4.3.1)
troposphere (1.9.1)
tzlocal (1.3)
virtualenv (15.1.0)
virtualenv-clone (0.2.6)
virtualenvwrapper (4.7.2)
wcwidth (0.1.7)
Werkzeug (0.11.15)
wheel (0.29.0)
xmltodict (0.10.2)
xonsh (0.5.2)
╭─mo.ali at pm-10423 in /Users/mo.ali
╰─λ
```

**Comment by spulec** [comment]
It looks like you are using `mock_route53` instead of `mock_elb`. We have a different decorator for each service to mock.

**Comment by AkhterAli** [comment]
@spulec Thanks, now I feel dumb for making such an obvious error.  I will work with this.  Quick question though, can I use multiple decorators with moto?

**Comment by spulec** [comment]
No problem. Thanks for using moto!
