### ISSUE TITLE
mock_s3 interfering SQLAlchemy calls to local MySQL databases

### ISSUE THREAD

**Issue by varadharajan** [spulec/moto#834]
Please consider the below code snippet.
```python
#!/usr/bin/env python

from sqlalchemy import create_engine
from sqlalchemy_utils import database_exists
from moto import mock_s3



@mock_s3
def test_foob():
    database_exists("mysql+pymysql://user:password@127.0.0.1")
```

If we run this with pytests, it will fail with the below error. 

```
 sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
```

However, if we remove the `@mock_s3` decorator, it passes. Any idea why this is happening?

**Comment by varadharajan** [comment]
Looks like this only happens with PyMySQL driver.

**Comment by kennydo** [comment]
I believe this issue is related to HTTPretty's lack of Python3 support (I hit this issue with `mock_sqs`, but I suspect it affects all the `mock_*` context managers/decorators). Just curious, what version of python are you running?

Steps to reproduce:
1. Run mysql locally (say, with a `foo_test` database)

1. Verify it works on python2.7:
    1. Create virtualenv for python2.7: `virtualenv --python /usr/bin/python2.7 venv27`
    1. `source venv27/bin/activate; pip install pymysql httpretty`
    1. Then run the following via python repl:
        ```
        Python 2.7.10 (default, Jul 30 2016, 19:40:32)
        [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
        Type "help", "copyright", "credits" or "license" for more information.
        >>> import httpretty
        >>> httpretty.enable()
        >>> import pymysql
        >>> pycon = pymysql.connect(host='127.0.0.1', user='root', db='foo_test')
        >>>
        ```
    1. pymysql + httpretty working fine together in python2.7

1. Verify it fails on python3.4:
    1. Create virtualenv for python3.4: `python3 -m venv venv34`
    1. `source venv34/bin/activate; pip install pymysql httpretty`
    1. Then run the following via repl:
        ```
        $ python
        Python 3.4.4 (default, Nov  6 2016, 19:13:18)
        [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
        Type "help", "copyright", "credits" or "license" for more information.
        >>> import httpretty
        >>> httpretty.enable()
        >>> import pymysql
        >>> pycon = pymysql.connect(host='127.0.0.1', user='root', db='foo_test')
        Traceback (most recent call last):
          File "<stdin>", line 1, in <module>
          File "/Users/kedo/Desktop/venv34/lib/python3.4/site-packages/pymysql/__init__.py", line 90, in Connect
            return Connection(*args, **kwargs)
          File "/Users/kedo/Desktop/venv34/lib/python3.4/site-packages/pymysql/connections.py", line 699, in __init__
            self.connect()
          File "/Users/kedo/Desktop/venv34/lib/python3.4/site-packages/pymysql/connections.py", line 927, in connect
            self._get_server_information()
          File "/Users/kedo/Desktop/venv34/lib/python3.4/site-packages/pymysql/connections.py", line 1241, in _get_server_information
            packet = self._read_packet()
          File "/Users/kedo/Desktop/venv34/lib/python3.4/site-packages/pymysql/connections.py", line 983, in _read_packet
            packet_header = self._read_bytes(4)
          File "/Users/kedo/Desktop/venv34/lib/python3.4/site-packages/pymysql/connections.py", line 1029, in _read_bytes
            CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
        pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')
        ```
    1. Uh oh!

**Comment by varadharajan** [comment]
@kennydo  Yeah.. You are right. I'm using Python 3.5. Sorry i should've mentioned it before :(

**Comment by spulec** [comment]
Can you try this against the `master` branch? I don't think it should be the case anymore.

**Comment by kennydo** [comment]
It looks good to me!

(in python3.4)
```
>>> with moto.mock_s3():
...     pymysql.connect(host='127.0.0.1', user='root', db='foo_test')
...
<pymysql.connections.Connection object at 0x102cc9da0>
```

**Comment by spulec** [comment]
Great, thanks for opening the issue!
