### ISSUE TITLE
Can't access https URLs when mocking s3

### ISSUE THREAD

**Issue by lsemel** [spulec/moto#859]
With moto 0.4.31, boto 2.46.1, requests 2.13.0, the following generates an error.
```
import moto
import boto
import requests

with moto.mock_s3():
    response = requests.get('https://google.com')
    print response.status_code
````

```
Traceback (most recent call last):
  File "mt.py", line 6, in <module>
    response = requests.get('https://google.com', verify=False)
  File "/Users/lsemel/www/virtualenvs/venv/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/lsemel/www/virtualenvs/venv/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/lsemel/www/virtualenvs/venv/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/lsemel/www/virtualenvs/venv/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/lsemel/www/virtualenvs/venv/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ('bad handshake: WantWriteError()',)
```

**Comment by spulec** [comment]
This should be fixed with version `1.0.0`. Let me know if you still see issues.

**Comment by marcelchastain** [comment]
@spulec request we reopen this. 
I'm observing this behavior with `mock_s3()` and `mock_s3_deprecated()` in v1.0.1

```
>>> with moto.mock_s3_deprecated():
...     response = requests.get('https://google.com')
...     print response.status_code
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/mchastain/.virtualenvs/frame/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/mchastain/.virtualenvs/frame/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/mchastain/.virtualenvs/frame/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/mchastain/.virtualenvs/frame/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/Users/mchastain/.virtualenvs/frame/lib/python2.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='google.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError('bad handshake: WantWriteError()',),))
```


and


```
>>> with moto.mock_s3():
...     response = requests.get('https://google.com')
...     print response.status_code
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/mchastain/.virtualenvs/frame/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/mchastain/.virtualenvs/frame/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/mchastain/.virtualenvs/frame/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/mchastain/.virtualenvs/frame/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/Users/mchastain/.virtualenvs/frame/lib/python2.7/site-packages/moto/packages/responses/responses.py", line 302, in unbound_on_send
    return self._on_request(adapter, request, *a, **kwargs)
  File "/Users/mchastain/.virtualenvs/frame/lib/python2.7/site-packages/moto/packages/responses/responses.py", line 244, in _on_request
    raise response
requests.exceptions.ConnectionError: Connection refused: GET https://google.com/
```

**Comment by spulec** [comment]
Feel free to follow along https://github.com/spulec/moto/issues/1567 for more info
