### ISSUE TITLE
"KeyError: 'Prefix'" when trying to put a lifecycle configuration without 'Prefix' key

### ISSUE THREAD

**Issue by Prior99** [spulec/moto#930]
Moto raises an `KeyError: 'Prefix'` when trying to put a lifecycle configuration without `Prefix` key.

[The `Prefix` key is deprecated](http://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.put_bucket_lifecycle_configuration) and no longer supported on S3 EU Central, resulting in a `MalformedXML` error when provided.

## Minimal Example to reproduce

```python
import boto3
import moto
from datetime import datetime

moto.mock_s3().start()
s3 = boto3.client('s3')
s3.create_bucket(Bucket='test')
s3.put_bucket_lifecycle_configuration(
    Bucket='test',
    LifecycleConfiguration={'Rules': [{
        'Expiration': {
            'Date': datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0),
        },
        'Status': 'Enabled',
        'Filter': {
            'Prefix': 'some_key',
        },
    }]},
)
moto.mock_s3().stop()
```

## Invocation

```
$ python -m venv venv
$ source venv/bin/activate
$ pip install boto3 moto
$ python reproduce.py
```

## Full stacktrace

```
Traceback (most recent call last):
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "reproduce.py", line 16, in <module>
    'Prefix': 'some_key',
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/client.py", line 544, in _make_api_call
    operation_model, request_dict)
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/endpoint.py", line 170, in _send_request
    success_response, exception):
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/endpoint.py", line 204, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/tmp/moto/venv/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1327, in getresponse
    response = self.response_class(self.sock, method=self._method)
  File "/usr/lib/python3.6/http/client.py", line 235, in __init__
    self.fp = sock.makefile("rb")
  File "/tmp/moto/venv/lib/python3.6/site-packages/httpretty/core.py", line 332, in makefile
    self._entry.fill_filekind(self.fd)
  File "/tmp/moto/venv/lib/python3.6/site-packages/httpretty/core.py", line 591, in fill_filekind
    status, headers, self.body = self.callable_body(self.request, self.info.full_url(), headers)
  File "/tmp/moto/venv/lib/python3.6/site-packages/moto/s3/responses.py", line 103, in bucket_response
    response = self._bucket_response(request, full_url, headers)
  File "/tmp/moto/venv/lib/python3.6/site-packages/moto/s3/responses.py", line 140, in _bucket_response
    return self._bucket_response_put(request, body, region_name, bucket_name, querystring, headers)
  File "/tmp/moto/venv/lib/python3.6/site-packages/moto/s3/responses.py", line 246, in _bucket_response_put
    self.backend.set_bucket_lifecycle(bucket_name, rules)
  File "/tmp/moto/venv/lib/python3.6/site-packages/moto/s3/models.py", line 364, in set_bucket_lifecycle
    bucket.set_lifecycle(rules)
  File "/tmp/moto/venv/lib/python3.6/site-packages/moto/s3/models.py", line 267, in set_lifecycle
    prefix=rule['Prefix'],
KeyError: 'Prefix'
```

## Versions
```
$ python --version
Python 3.6.1
$ pip freeze
boto==2.46.1
boto3==1.4.4
botocore==1.5.46
docutils==0.13.1
httpretty==0.8.10
Jinja2==2.9.6
jmespath==0.9.2
MarkupSafe==1.0
moto==0.4.31
python-dateutil==2.6.0
pytz==2017.2
requests==2.13.0
s3transfer==0.1.10
six==1.10.0
Werkzeug==0.12.1
xmltodict==0.11.0
```

**Comment by spulec** [comment]
Thanks for opening!

This should be fixed now.
