### ISSUE TITLE
Deprecation Warning with moto 1.0.0

### ISSUE THREAD

**Issue by tardyp** [spulec/moto#942]
Since the release of moto 1.0.0 Buildbot Ci is impacted.
Buildbot Ci is configured to forbid any warning raise by the code
https://nine.buildbot.net/#/builders/11/builds/231/steps/5/logs/stdio

but moto 1.0.0 raise a new warning:
```
 File "/buildbot/buildbot-job/build/sandbox/local/lib/python2.7/site-packages/moto/__init__.py", line 9, in <module>
    from .autoscaling import mock_autoscaling, mock_autoscaling_deprecated  # flake8: noqa
  File "/buildbot/buildbot-job/build/sandbox/local/lib/python2.7/site-packages/moto/autoscaling/__init__.py", line 2, in <module>
    from .models import autoscaling_backends
  File "/buildbot/buildbot-job/build/sandbox/local/lib/python2.7/site-packages/moto/autoscaling/models.py", line 5, in <module>
    from moto.ec2 import ec2_backends
  File "/buildbot/buildbot-job/build/sandbox/local/lib/python2.7/site-packages/moto/ec2/__init__.py", line 2, in <module>
    from .models import ec2_backends
  File "/buildbot/buildbot-job/build/sandbox/local/lib/python2.7/site-packages/moto/ec2/models.py", line 3703, in <module>
    ec2_backends[region.name] = EC2Backend(region.name)
  File "/buildbot/buildbot-job/build/sandbox/local/lib/python2.7/site-packages/moto/ec2/models.py", line 3614, in __init__
    super(EC2Backend, self).__init__()
  File "/buildbot/buildbot-job/build/sandbox/local/lib/python2.7/site-packages/moto/ec2/models.py", line 627, in __init__
    super(InstanceBackend, self).__init__()
  File "/buildbot/buildbot-job/build/sandbox/local/lib/python2.7/site-packages/moto/ec2/models.py", line 860, in __init__
    super(TagBackend, self).__init__()
  File "/buildbot/buildbot-job/build/sandbox/local/lib/python2.7/site-packages/moto/ec2/models.py", line 1042, in __init__
    super(AmiBackend, self).__init__()
  File "/buildbot/buildbot-job/build/sandbox/local/lib/python2.7/site-packages/moto/ec2/models.py", line 1362, in __init__
    self.create_security_group("default", "default group")
  File "/buildbot/buildbot-job/build/sandbox/local/lib/python2.7/site-packages/moto/ec2/models.py", line 1375, in create_security_group
    group = SecurityGroup(self, group_id, name, description, vpc_id=vpc_id)
  File "/buildbot/buildbot-job/build/sandbox/local/lib/python2.7/site-packages/moto/core/models.py", line 233, in __new__
    instance = super(BaseModel, cls).__new__(cls, *args, **kwargs)
exceptions.DeprecationWarning: object() takes no parameters
```
We will add this warning as a exception, but we would be glad if moto could fix this warning and release a new version.

**Comment by tardyp** [comment]
Another deprecation warning triggered by moto 1.0.0:
```
[ERROR]
Traceback (most recent call last):
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/site-packages/twisted/trial/runner.py", line 508, in loadPackage
    module = modinfo.load()
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/site-packages/twisted/python/modules.py", line 392, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/site-packages/twisted/python/reflect.py", line 301, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/site-packages/twisted/python/reflect.py", line 240, in _importAndCheckStack
    return __import__(importName)
  File "/buildbot/buildbot-job/build/master/buildbot/test/unit/test_worker_ec2.py", line 30, in <module>
    from moto import mock_ec2
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/site-packages/moto/__init__.py", line 8, in <module>
    from .apigateway import mock_apigateway, mock_apigateway_deprecated  # flake8: noqa
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/site-packages/moto/apigateway/__init__.py", line 2, in <module>
    from .models import apigateway_backends
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/site-packages/moto/apigateway/models.py", line 7, in <module>
    from moto.packages.responses import responses
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/site-packages/moto/packages/responses/responses.py", line 12, in <module>
    from cookies import Cookies
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/site-packages/cookies.py", line 110, in <module>
    class Definitions(object):
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/site-packages/cookies.py", line 312, in Definitions
    ATTR_RE = re.compile(ATTR)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/sre_parse.py", line 864, in parse
    p = _parse_sub(source, pattern, True, False)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/sre_parse.py", line 415, in _parse_sub
    itemsappend(_parse(source, state, verbose))
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/sre_parse.py", line 763, in _parse
    p = _parse_sub(source, state, sub_verbose)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/sre_parse.py", line 415, in _parse_sub
    itemsappend(_parse(source, state, verbose))
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/sre_parse.py", line 763, in _parse
    p = _parse_sub(source, state, sub_verbose)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/sre_parse.py", line 415, in _parse_sub
    itemsappend(_parse(source, state, verbose))
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.6/sre_parse.py", line 743, in _parse
    DeprecationWarning, stacklevel=7
builtins.DeprecationWarning: Flags not at the start of the expression (?ix)  # Case-insens (truncated)

```
