### ISSUE TITLE
Moto breaks with other locales than en_US

### ISSUE THREAD

**Issue by b4stien** [spulec/moto#95]
I try to use moto to test my S3 integration with boto, but I need to format my date/time in French, so I have, somewhere in my app, the following:

```
import locale
locale.setlocale(locale.LC_TIME, 'fr_FR')
```

Which happens to break moto, I get the following stacktrace:

```
Traceback (most recent call last):
  File "bla/tests/test_biz_file.py", line 61, in setUp
    self._backup_s3_conn, self.filer._s3_conn = self.filer._s3_conn, boto.connect_s3()
  File "bla/lib/python2.7/site-packages/boto/__init__.py", line 140, in connect_s3
    return S3Connection(aws_access_key_id, aws_secret_access_key, **kwargs)
  File "bla/lib/python2.7/site-packages/boto/s3/connection.py", line 190, in __init__
    validate_certs=validate_certs, profile_name=profile_name)
  File "bla/lib/python2.7/site-packages/boto/connection.py", line 568, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "bla/lib/python2.7/site-packages/boto/auth.py", line 882, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials
```

When I try to run the tests of moto directly, with the locale set to French, I get `UnicodeDecodeError` everywhere. Any idea ?

**Comment by aop** [comment]
I'm still running into this exact same issue with

moto==0.4.25
httpretty==0.8.10

```
Traceback (most recent call last):
  File "/home/oskari/koodaus/myproject/env/local/lib/python2.7/site-packages/mock.py", line 1201, in patched
    return func(*args, **keywargs)
  File "/home/oskari/koodaus/myproject/env/local/lib/python2.7/site-packages/moto/core/models.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "/home/oskari/koodaus/myproject/tests/mytest.py", line 42, in test_mytest
    s3_connection.create_bucket(self.s3_bucket_name)
  File "/home/oskari/koodaus/myproject/env/local/lib/python2.7/site-packages/boto/s3/connection.py", line 612, in create_bucket
    data=data)
  File "/home/oskari/koodaus/myproject/env/local/lib/python2.7/site-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/home/oskari/koodaus/myproject/env/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/home/oskari/koodaus/myproject/env/local/lib/python2.7/site-packages/boto/connection.py", line 944, in _mexe
    response = connection.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1049, in getresponse
    response = self.response_class(*args, **kwds)
  File "/home/oskari/koodaus/myproject/env/local/lib/python2.7/site-packages/boto/connection.py", line 390, in __init__
    http_client.HTTPResponse.__init__(self, *args, **kwargs)
  File "/usr/lib/python2.7/httplib.py", line 352, in __init__
    self.fp = sock.makefile('rb', 0)
  File "/home/oskari/koodaus/myproject/env/local/lib/python2.7/site-packages/httpretty/core.py", line 332, in makefile
    self._entry.fill_filekind(self.fd)
  File "/home/oskari/koodaus/myproject/env/local/lib/python2.7/site-packages/httpretty/core.py", line 601, in fill_filekind
    string_list.append('date: %s' % headers.pop('date'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
```

**Comment by julozi** [comment]
Hi @spulec ,

The issue does still exist with moto==0.4.25 and httpretty==0.8.10

Here is a sample code that recreate the failure : 

    import boto
    import locale
    from moto import mock_s3
    
    locale.setlocale(locale.LC_TIME, "fr_FR")
    
    mock = mock_s3()
    mock.start()
    
    conn = boto.connect_s3()
    conn.create_bucket('test')

**Comment by spulec** [comment]
If you use boto3 against `master`, I think this should no longer be an issue.
