### ISSUE TITLE
get_object on gzip encoded objects fail with moto 1.0.0

### ISSUE THREAD

**Issue by peterbe** [spulec/moto#963]
If I PUT an object in, gzip compress it myself, then try to read it, it fails.
Here's how I put it in:
```python
def test_get_stream_gzipped(s3_client):
    s3_client.create_bucket(Bucket='private')
    buffer_ = BytesIO()
    with GzipFile(fileobj=buffer_, mode='w') as f:
        f.write(payload)
    payload_gz = buffer_.getvalue()
    s3_client.put_object(
        Bucket='bucketname',
        Key='keyname',
        Body=payload_gz,
        ContentEncoding='gzip',
    )
    ....
```
But when I, later in the test, try to read it I get...:
```
Traceback (most recent call last):
  File "/app/tests/test_symboldownloader.py", line 349, in test_get_stream_gzipped
    bucket_name, key = next(stream)
  File "/app/tecken/base/symboldownloader.py", line 285, in _get_stream
    bytestream = BytesIO(response['Body'].read())
  File "/usr/local/lib/python3.5/site-packages/botocore/response.py", line 84, in read
    self._verify_content_length()
  File "/usr/local/lib/python3.5/site-packages/botocore/response.py", line 95, in _verify_content_length
    expected_bytes=int(self._content_length))
botocore.exceptions.IncompleteReadError: 21 read, but total bytes expected is 34.
```
The `IncompleteReadError` check isn't wrong, it's just that it shouldn't happen. 
The relevant code does:
```python
# This is botocore/response.py

class StreamingBody(object):
    ...

    def _verify_content_length(self):
        # See: https://github.com/kennethreitz/requests/issues/1855
        # Basically, our http library doesn't do this for us, so we have
        # to do this ourself.
        if self._content_length is not None and \
                self._amount_read != int(self._content_length):
            raise IncompleteReadError(
                actual_bytes=self._amount_read,
                expected_bytes=int(self._content_length))
```
The size is different because once decompressed the total length of data read is different from the value of the `Content-Length`. 

I put some print statements in where it does the `chunk = self._raw_stream.read()` in botocore and now it's suddenly a plain byte string and not a gzipped byte string. 

Versions:
* Python 3.5.1
* botocore 1.5.48
* boto3 1.4.4
* moto 1.0.0

**Comment by spulec** [comment]
Thanks for opening! This should be fixed now.
