### ISSUE TITLE
Feature Request: Lambda Function with multiple files in a Zip File

### ISSUE THREAD

**Issue by RAbraham** [spulec/moto#981]
Hi,
I have a zip file which contains two files. I can successfully unzip the zip file using `unzip` in the terminal.

```python
code_paths = ['lambda.py', 'handler.dill']
zip_path = '/tmp/' + 'moto-rajiv' + '.zip'
make_local_zipfile(code_paths)
with zipfile.ZipFile(zip_path, "r", zipfile.ZIP_DEFLATED) as f:
        pprint(f.namelist()) #This prints ['lambda.py', 'handler.dill']

with open(zip_path, 'rb') as ziper:
       conn.create_function(
            FunctionName=...,
            ...
            Code={
                'ZipFile': ziper.read()
            },
            ...
        )
```

I get the following error. Note that the files get conjugated into one single line:
```
Traceback (most recent call last):
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/jaya/mock/in_memory_harness.py", line 121, in <module>
    deploy_lambda.deploy_lambda_package_local(print_lambda)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/jaya/deployment/deploy_lambda.py", line 329, in deploy_lambda_package_local
    Publish=True,
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/botocore/client.py", line 544, in _make_api_call
    operation_model, request_dict)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/botocore/endpoint.py", line 170, in _send_request
    success_response, exception):
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/botocore/endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/botocore/endpoint.py", line 204, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/moto/packages/responses/responses.py", line 300, in unbound_on_send
    return self._on_request(adapter, request, *a, **kwargs)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/moto/packages/responses/responses.py", line 255, in _on_request
    status, r_headers, body = match['callback'](request)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/moto/core/utils.py", line 164, in __call__
    result = self.callback(request, request.url, request.headers)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/moto/awslambda/responses.py", line 16, in root
    return self._create_function(request, full_url, headers)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/moto/awslambda/responses.py", line 62, in _create_function
    fn = lambda_backend.create_function(spec)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/moto/awslambda/models.py", line 215, in create_function
    fn = LambdaFunction(spec)
  File "/Users/rabraham/Documents/dev/thescore/analytics/jaya/venv/lib/python3.6/site-packages/moto/awslambda/models.py", line 57, in __init__
    self.code = zip_file.read("".join(zip_file.namelist()))
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py", line 1308, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py", line 1346, in open
    zinfo = self.getinfo(name)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py", line 1275, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'lambda.pyhandler.dill' in the archive"

Process finished with exit code 1

```

Digging through the code, I found the [line](https://github.com/spulec/moto/commit/6c577091da23efe7ccf0b24fdd81a64fbff2dd1f#diff-2df06bdd95e3c78b9335da9f260a3472R45)
```
self.code = zip_file.read("".join(zip_file.namelist()))
```
My understanding is that `zip_file.read` accepts only one file name at a time. This line of code conjugates all the filenames without any space separation and that is why the code fails. 

If I can change the way I pass in the contents, let me know.

**Comment by spulec** [comment]
Yeah, it looks like we don't support that right now. It seems like we'll need to expand beyond just having `self.code` to be able to handle multiple files.

Going to change the title of this and set it as a feature request. Thanks
